df1 <-
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <-
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ActivityDefinition', 'ITU', '', 'DomainResource', 'The definition of a specific activity to be taken, independent of any particular patient or context+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this activity definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the activity definition',
'version', 'Σ', '0..1', 'string', 'Business version of the activity definition',
'name', 'ΣI', '0..1', 'string', 'Name for this activity definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this activity definition (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the activity definition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'Type of individual the activity definition is intended forSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the activity definition',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for activity definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this activity definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the activity definition',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the activity definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the activity definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the activity definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'E.g. Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the activity definition',
'kind', 'Σ', '0..1', 'code', 'Kind of resourceRequestResourceType (Required)',
'profile', '', '0..1', 'canonical(StructureDefinition)', 'What profile the resource needs to conform to',
'code', 'Σ', '0..1', 'CodeableConcept', 'Detail type of activityProcedure Codes (SNOMED CT) (Example)',
'intent', '', '0..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'doNotPerform', '?!Σ', '0..1', 'boolean', 'True if the activity should not be performed',
'timing[x]', '', '0..1', '', 'When activity is to occur',
'timingTiming', '', '', 'Timing', '',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingRange', '', '', 'Range', '',
'timingDuration', '', '', 'Duration', '',
'location', '', '0..1', 'Reference(Location)', 'Where it should happen',
'participant', '', '0..*', 'BackboneElement', 'Who should participate in the action',
'type', '', '1..1', 'code', 'patient | practitioner | related-person | deviceActionParticipantType (Required)',
'role', '', '0..1', 'CodeableConcept', 'E.g. Nurse, Surgeon, Parent, etc.Action participant role (Example)',
'product[x]', '', '0..1', '', 'Whats administered/suppliedSNOMED CT Medication Codes (Example)',
'productReference', '', '', 'Reference(Medication | Substance)', '',
'productCodeableConcept', '', '', 'CodeableConcept', '',
'quantity', '', '0..1', 'SimpleQuantity', 'How much is administered/consumed/supplied',
'dosage', '', '0..*', 'Dosage', 'Detailed dosage instructions',
'bodySite', '', '0..*', 'CodeableConcept', 'What part of body to perform onSNOMED CT Body Structures (Example)',
'specimenRequirement', '', '0..*', 'Reference(SpecimenDefinition)', 'What specimens are required to perform this action',
'observationRequirement', '', '0..*', 'Reference(ObservationDefinition)', 'What observations are required to perform this action',
'observationResultRequirement', '', '0..*', 'Reference(ObservationDefinition)', 'What observations must be produced by this action',
'transform', '', '0..1', 'canonical(StructureMap)', 'Transform to apply the template',
'dynamicValue', '', '0..*', 'BackboneElement', 'Dynamic aspects of the definition',
'path', '', '1..1', 'string', 'The path to the element to be set dynamically',
'expression', '', '1..1', 'Expression', 'An expression that provides the dynamic value for the customization',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <-
tibble::tribble(
~`X1`,~`X2`,
'ActivityDefinition', '',
'ActivityDefinition.subtitle', 'Added Element',
'ActivityDefinition.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'ActivityDefinition.experimental', 'No longer marked as Modifier',
'ActivityDefinition.subject[x]', 'Added Element',
'ActivityDefinition.author', 'Added Element',
'ActivityDefinition.editor', 'Added Element',
'ActivityDefinition.reviewer', 'Added Element',
'ActivityDefinition.endorser', 'Added Element',
'ActivityDefinition.library', 'Type changed from Reference(Library) to canonical(Library)',
'ActivityDefinition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/request-resource-types|4.0.1',
'ActivityDefinition.profile', 'Added Element',
'ActivityDefinition.intent', 'Added Element',
'ActivityDefinition.priority', 'Added Element',
'ActivityDefinition.doNotPerform', 'Added Element',
'ActivityDefinition.timing[x]', 'Add Types Age, Duration',
'ActivityDefinition.participant.type', 'Change value set from http://hl7.org/fhir/ValueSet/action-participant-type to http://hl7.org/fhir/ValueSet/action-participant-type|4.0.1',
'ActivityDefinition.specimenRequirement', 'Added Element',
'ActivityDefinition.observationRequirement', 'Added Element',
'ActivityDefinition.observationResultRequirement', 'Added Element',
'ActivityDefinition.transform', 'Type changed from Reference(StructureMap) to canonical(StructureMap)',
'ActivityDefinition.dynamicValue.path', 'Min Cardinality changed from 0 to 1',
'ActivityDefinition.dynamicValue.expression', 'Min Cardinality changed from 0 to 1
        Type changed from string to Expression',
'ActivityDefinition.contributor', 'deleted',
'ActivityDefinition.dynamicValue.description', 'deleted',
'ActivityDefinition.dynamicValue.language', 'deleted',
)


df4 <-
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ActivityDefinition', 'ITU', '', 'DomainResource', 'The definition of a specific activity to be taken, independent of any particular patient or context+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this activity definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the activity definition',
'version', 'Σ', '0..1', 'string', 'Business version of the activity definition',
'name', 'ΣI', '0..1', 'string', 'Name for this activity definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this activity definition (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the activity definition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'Type of individual the activity definition is intended forSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the activity definition',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for activity definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this activity definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the activity definition',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the activity definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the activity definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the activity definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'E.g. Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the activity definition',
'kind', 'Σ', '0..1', 'code', 'Kind of resourceRequestResourceType (Required)',
'profile', '', '0..1', 'canonical(StructureDefinition)', 'What profile the resource needs to conform to',
'code', 'Σ', '0..1', 'CodeableConcept', 'Detail type of activityProcedure Codes (SNOMED CT) (Example)',
'intent', '', '0..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'doNotPerform', '?!Σ', '0..1', 'boolean', 'True if the activity should not be performed',
'timing[x]', '', '0..1', '', 'When activity is to occur',
'timingTiming', '', '', 'Timing', '',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingRange', '', '', 'Range', '',
'timingDuration', '', '', 'Duration', '',
'location', '', '0..1', 'Reference(Location)', 'Where it should happen',
'participant', '', '0..*', 'BackboneElement', 'Who should participate in the action',
'type', '', '1..1', 'code', 'patient | practitioner | related-person | deviceActionParticipantType (Required)',
'role', '', '0..1', 'CodeableConcept', 'E.g. Nurse, Surgeon, Parent, etc.Action participant role (Example)',
'product[x]', '', '0..1', '', 'Whats administered/suppliedSNOMED CT Medication Codes (Example)',
'productReference', '', '', 'Reference(Medication | Substance)', '',
'productCodeableConcept', '', '', 'CodeableConcept', '',
'quantity', '', '0..1', 'SimpleQuantity', 'How much is administered/consumed/supplied',
'dosage', '', '0..*', 'Dosage', 'Detailed dosage instructions',
'bodySite', '', '0..*', 'CodeableConcept', 'What part of body to perform onSNOMED CT Body Structures (Example)',
'specimenRequirement', '', '0..*', 'Reference(SpecimenDefinition)', 'What specimens are required to perform this action',
'observationRequirement', '', '0..*', 'Reference(ObservationDefinition)', 'What observations are required to perform this action',
'observationResultRequirement', '', '0..*', 'Reference(ObservationDefinition)', 'What observations must be produced by this action',
'transform', '', '0..1', 'canonical(StructureMap)', 'Transform to apply the template',
'dynamicValue', '', '0..*', 'BackboneElement', 'Dynamic aspects of the definition',
'path', '', '1..1', 'string', 'The path to the element to be set dynamically',
'expression', '', '1..1', 'Expression', 'An expression that provides the dynamic value for the customization',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <-
tibble::tribble(
~`X1`,~`X2`,
'ActivityDefinition', '',
'ActivityDefinition.subtitle', 'Added Element',
'ActivityDefinition.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'ActivityDefinition.experimental', 'No longer marked as Modifier',
'ActivityDefinition.subject[x]', 'Added Element',
'ActivityDefinition.author', 'Added Element',
'ActivityDefinition.editor', 'Added Element',
'ActivityDefinition.reviewer', 'Added Element',
'ActivityDefinition.endorser', 'Added Element',
'ActivityDefinition.library', 'Type changed from Reference(Library) to canonical(Library)',
'ActivityDefinition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/request-resource-types|4.0.1',
'ActivityDefinition.profile', 'Added Element',
'ActivityDefinition.intent', 'Added Element',
'ActivityDefinition.priority', 'Added Element',
'ActivityDefinition.doNotPerform', 'Added Element',
'ActivityDefinition.timing[x]', 'Add Types Age, Duration',
'ActivityDefinition.participant.type', 'Change value set from http://hl7.org/fhir/ValueSet/action-participant-type to http://hl7.org/fhir/ValueSet/action-participant-type|4.0.1',
'ActivityDefinition.specimenRequirement', 'Added Element',
'ActivityDefinition.observationRequirement', 'Added Element',
'ActivityDefinition.observationResultRequirement', 'Added Element',
'ActivityDefinition.transform', 'Type changed from Reference(StructureMap) to canonical(StructureMap)',
'ActivityDefinition.dynamicValue.path', 'Min Cardinality changed from 0 to 1',
'ActivityDefinition.dynamicValue.expression', 'Min Cardinality changed from 0 to 1
        Type changed from string to Expression',
'ActivityDefinition.contributor', 'deleted',
'ActivityDefinition.dynamicValue.description', 'deleted',
'ActivityDefinition.dynamicValue.language', 'deleted',
)


df6 <-
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ActivityDefinition.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'ActivityDefinition.subject[x]', 'The possible types of subjects for an activity (E.g. Patient, Practitioner, Organization, Location, etc.).', 'Extensible', 'SubjectType',
'ActivityDefinition.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'ActivityDefinition.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'ActivityDefinition.kind', 'The kind of activity the definition is describing.', 'Required', 'RequestResourceType',
'ActivityDefinition.code', 'Detailed type of the activity; e.g. CBC.', 'Example', 'ProcedureCodes(SNOMEDCT)',
'ActivityDefinition.intent', 'Codes indicating the degree of authority/intentionality associated with a request.', 'Required', 'RequestIntent',
'ActivityDefinition.priority', 'Identifies the level of importance to be assigned to actioning the request.', 'Required', 'RequestPriority',
'ActivityDefinition.participant.type', 'The type of participant in the activity.', 'Required', 'ActionParticipantType',
'ActivityDefinition.participant.role', 'Defines roles played by participants for the action.', 'Example', 'ActionParticipantRole',
'ActivityDefinition.product[x]', 'Code describing the type of substance or medication.', 'Example', 'SNOMEDCTMedicationCodes',
'ActivityDefinition.bodySite', 'A code that identifies the anatomical location.', 'Example', 'SNOMEDCTBodyStructures',
)


df7 <-
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'adf-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches(\"[A-Z]([A-Za-z0-9_]){0,254}\")',
)


df8 <-
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'composed-of', 'reference', 'What resource is being referenced', 'ActivityDefinition.relatedArtifact.where(type=\"composed-of\").resource(Any)', '',
'context', 'token', 'A use context assigned to the activity definition', '(ActivityDefinition.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the activity definition', '(ActivityDefinition.useContext.value as Quantity) | (ActivityDefinition.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the activity definition', 'ActivityDefinition.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the activity definition', 'On ActivityDefinition.useContext:context-type: codecontext-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the activity definition', 'On ActivityDefinition.useContext:context-type: codecontext: value.as(CodeableConcept)', '',
'date', 'date', 'The activity definition publication date', 'ActivityDefinition.date', '',
'depends-on', 'reference', 'What resource is being referenced', 'ActivityDefinition.relatedArtifact.where(type=\"depends-on\").resource | ActivityDefinition.library(Library, Any)', '',
'derived-from', 'reference', 'What resource is being referenced', 'ActivityDefinition.relatedArtifact.where(type=\"derived-from\").resource(Any)', '',
'description', 'string', 'The description of the activity definition', 'ActivityDefinition.description', '',
'effective', 'date', 'The time during which the activity definition is intended to be in use', 'ActivityDefinition.effectivePeriod', '',
'identifier', 'token', 'External identifier for the activity definition', 'ActivityDefinition.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the activity definition', 'ActivityDefinition.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the activity definition', 'ActivityDefinition.name', '',
'predecessor', 'reference', 'What resource is being referenced', 'ActivityDefinition.relatedArtifact.where(type=\"predecessor\").resource(Any)', '',
'publisher', 'string', 'Name of the publisher of the activity definition', 'ActivityDefinition.publisher', '',
'status', 'token', 'The current status of the activity definition', 'ActivityDefinition.status', '',
'successor', 'reference', 'What resource is being referenced', 'ActivityDefinition.relatedArtifact.where(type=\"successor\").resource(Any)', '',
'title', 'string', 'The human-friendly name of the activity definition', 'ActivityDefinition.title', '',
'topic', 'token', 'Topics associated with the module', 'ActivityDefinition.topic', '',
'url', 'uri', 'The uri that identifies the activity definition', 'ActivityDefinition.url', '',
'version', 'token', 'The business version of the activity definition', 'ActivityDefinition.version', '',
)


