df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: N', 'Normative (from v4.0.0)', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`X1`,~`X2`,
NA, 'This page has been approved as part of an ANSI  standard.
   See the Conformance Package for further details.',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Instance', 'implementation must be present and software may be present',
'Capability', 'implementation must be absent, software must be present',
'Requirements', 'implementation and software must be absent',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'CapabilityStatement', 'IN', '', 'DomainResource', 'A statement of system capabilities+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: A Capability Statement SHALL have at least one of REST, messaging or document element.+ Rule: A Capability Statement SHALL have at least one of description, software, or implementation element.+ Rule: Messaging end-point is required (and is only permitted) when a statement is for an implementation.+ Rule: The set of documents must be unique by the combination of profile and mode.+ Rule: If kind = instance, implementation must be present and software may be present+ Rule: If kind = capability, implementation must be absent, software must be present+ Rule: If kind = requirements, implementation and software must be absentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this capability statement, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the capability statement',
'name', 'ΣI', '0..1', 'string', 'Name for this capability statement (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this capability statement (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '1..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'I', '0..1', 'markdown', 'Natural language description of the capability statement',
'useContext', 'ΣTU', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for capability statement (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this capability statement is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'kind', 'ΣI', '1..1', 'code', 'instance | capability | requirementsCapabilityStatementKind (Required)',
'instantiates', 'Σ', '0..*', 'canonical(CapabilityStatement)', 'Canonical URL of another capability statement this implements',
'imports', 'ΣTU', '0..*', 'canonical(CapabilityStatement)', 'Canonical URL of another capability statement this adds to',
'software', 'ΣI', '0..1', 'BackboneElement', 'Software that is covered by this capability statement',
'name', 'Σ', '1..1', 'string', 'A name the software is known by',
'version', 'Σ', '0..1', 'string', 'Version covered by this statement',
'releaseDate', 'Σ', '0..1', 'dateTime', 'Date this version was released',
'implementation', 'ΣI', '0..1', 'BackboneElement', 'If this describes a specific instance',
'description', 'Σ', '1..1', 'string', 'Describes this specific instance',
'url', 'Σ', '0..1', 'url', 'Base URL for the installation',
'custodian', 'ΣTU', '0..1', 'Reference(Organization)', 'Organization that manages the data',
'fhirVersion', 'Σ', '1..1', 'code', 'FHIR Version the system supportsFHIRVersion (Required)',
'format', 'Σ', '1..*', 'code', 'formats supported (xml | json | ttl | mime type)MimeType (Required)',
'patchFormat', 'Σ', '0..*', 'code', 'Patch formats supportedMimeType (Required)',
'implementationGuide', 'Σ', '0..*', 'canonical(ImplementationGuide)', 'Implementation guides supported',
'rest', 'ΣI', '0..*', 'BackboneElement', 'If the endpoint is a RESTful one+ Rule: A given resource can only be described once per RESTful mode.',
'mode', 'Σ', '1..1', 'code', 'client | serverRestfulCapabilityMode (Required)',
'documentation', '', '0..1', 'markdown', 'General description of implementation',
'security', 'ΣTU', '0..1', 'BackboneElement', 'Information about security of implementation',
'cors', 'Σ', '0..1', 'boolean', 'Adds CORS Headers (http://enable-cors.org/)',
'service', 'Σ', '0..*', 'CodeableConcept', 'OAuth | SMART-on-FHIR | NTLM | Basic | Kerberos | CertificatesRestfulSecurityService (Extensible)',
'description', '', '0..1', 'markdown', 'General description of how security works',
'resource', 'ΣI', '0..*', 'BackboneElement', 'Resource served on the REST interface+ Rule: Search parameter names must be unique in the context of a resource.',
'type', 'Σ', '1..1', 'code', 'A resource type that is supportedResourceType (Required)',
'profile', 'Σ', '0..1', 'canonical(StructureDefinition)', 'Base System profile for all uses of resource',
'supportedProfile', 'ΣTU', '0..*', 'canonical(StructureDefinition)', 'Profiles for use cases supported',
'documentation', '', '0..1', 'markdown', 'Additional information about the use of the resource type',
'interaction', '', '0..*', 'BackboneElement', 'What operations are supported?',
'code', '', '1..1', 'code', 'read | vread | update | patch | delete | history-instance | history-type | create | search-typeTypeRestfulInteraction (Required)',
'documentation', '', '0..1', 'markdown', 'Anything special about operation behavior',
'versioning', 'TU', '0..1', 'code', 'no-version | versioned | versioned-updateResourceVersionPolicy (Required)',
'readHistory', 'TU', '0..1', 'boolean', 'Whether vRead can return past versions',
'updateCreate', 'TU', '0..1', 'boolean', 'If update can commit to a new identity',
'conditionalCreate', 'TU', '0..1', 'boolean', 'If allows/uses conditional create',
'conditionalRead', 'TU', '0..1', 'code', 'not-supported | modified-since | not-match | full-supportConditionalReadStatus (Required)',
'conditionalUpdate', 'TU', '0..1', 'boolean', 'If allows/uses conditional update',
'conditionalDelete', 'TU', '0..1', 'code', 'not-supported | single | multiple - how conditional delete is supportedConditionalDeleteStatus (Required)',
'referencePolicy', 'TU', '0..*', 'code', 'literal | logical | resolves | enforced | localReferenceHandlingPolicy (Required)',
'searchInclude', 'TU', '0..*', 'string', '_include values supported by the server',
'searchRevInclude', 'TU', '0..*', 'string', '_revinclude values supported by the server',
'searchParam', '', '0..*', 'BackboneElement', 'Search parameters supported by implementation',
'name', '', '1..1', 'string', 'Name of search parameter',
'definition', '', '0..1', 'canonical(SearchParameter)', 'Source of definition for parameter',
'type', '', '1..1', 'code', 'number | date | string | token | reference | composite | quantity | uri | specialSearchParamType (Required)',
'documentation', '', '0..1', 'markdown', 'Server-specific usage',
'operation', 'Σ', '0..*', 'BackboneElement', 'Definition of a resource operation',
'name', 'Σ', '1..1', 'string', 'Name by which the operation/query is invoked',
'definition', 'Σ', '1..1', 'canonical(OperationDefinition)', 'The defined operation/query',
'documentation', '', '0..1', 'markdown', 'Specific details about operation behavior',
'interaction', '', '0..*', 'BackboneElement', 'What operations are supported?',
'code', '', '1..1', 'code', 'transaction | batch | search-system | history-systemSystemRestfulInteraction (Required)',
'documentation', '', '0..1', 'markdown', 'Anything special about operation behavior',
'searchParam', '', '0..*', 'see searchParam', 'Search parameters for searching all resources',
'operation', 'Σ', '0..*', 'see operation', 'Definition of a system level operation',
'compartment', '', '0..*', 'canonical(CompartmentDefinition)', 'Compartments served/used by system',
'messaging', 'ΣITU', '0..*', 'BackboneElement', 'If messaging is supported',
'endpoint', '', '0..*', 'BackboneElement', 'Where messages should be sent',
'protocol', '', '1..1', 'Coding', 'http | ftp | mllp +MessageTransport (Extensible)',
'address', '', '1..1', 'url', 'Network address or identifier of the end-point',
'reliableCache', '', '0..1', 'unsignedInt', 'Reliable Message Cache Length (min)',
'documentation', '', '0..1', 'markdown', 'Messaging interface behavior details',
'supportedMessage', 'Σ', '0..*', 'BackboneElement', 'Messages supported by this system',
'mode', 'Σ', '1..1', 'code', 'sender | receiverEventCapabilityMode (Required)',
'definition', 'Σ', '1..1', 'canonical(MessageDefinition)', 'Message supported by this system',
'document', 'ΣITU', '0..*', 'BackboneElement', 'Document definition',
'mode', 'Σ', '1..1', 'code', 'producer | consumerDocumentMode (Required)',
'documentation', '', '0..1', 'markdown', 'Description of document support',
'profile', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Constraint on the resources used in the document',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'CapabilityStatement', '',
'CapabilityStatement', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'CapabilityStatement.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'CapabilityStatement.experimental', 'No longer marked as Modifier',
'CapabilityStatement.kind', 'Change value set from http://hl7.org/fhir/ValueSet/capability-statement-kind to http://hl7.org/fhir/ValueSet/capability-statement-kind|4.0.1',
'CapabilityStatement.instantiates', 'Type changed from uri to canonical(CapabilityStatement)',
'CapabilityStatement.imports', 'Added Element',
'CapabilityStatement.implementation.url', 'Type changed from uri to url',
'CapabilityStatement.implementation.custodian', 'Added Element',
'CapabilityStatement.fhirVersion', 'Type changed from id to code
        
Add Binding http://hl7.org/fhir/ValueSet/FHIR-version|4.0.1 (required)',
'CapabilityStatement.format', 'Change value set from http://hl7.org/fhir/ValueSet/mimetypes to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'CapabilityStatement.patchFormat', 'Change value set from http://hl7.org/fhir/ValueSet/mimetypes to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'CapabilityStatement.implementationGuide', 'Type changed from uri to canonical(ImplementationGuide)',
'CapabilityStatement.rest.mode', 'Change value set from http://hl7.org/fhir/ValueSet/restful-capability-mode to http://hl7.org/fhir/ValueSet/restful-capability-mode|4.0.1',
'CapabilityStatement.rest.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.security.service', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/restful-security-service" to "http://terminology.hl7.org/CodeSystem/restful-security-service"',
'CapabilityStatement.rest.security.description', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.type', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'CapabilityStatement.rest.resource.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.rest.resource.supportedProfile', 'Moved from CapabilityStatement.profile to supportedProfile
        Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.rest.resource.interaction', 'Min Cardinality changed from 1 to 0',
'CapabilityStatement.rest.resource.interaction.code', 'Change value set from http://hl7.org/fhir/ValueSet/type-restful-interaction to http://hl7.org/fhir/ValueSet/type-restful-interaction|4.0.1',
'CapabilityStatement.rest.resource.interaction.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.versioning', 'Change value set from http://hl7.org/fhir/ValueSet/versioning-policy to http://hl7.org/fhir/ValueSet/versioning-policy|4.0.1',
'CapabilityStatement.rest.resource.conditionalRead', 'Change value set from http://hl7.org/fhir/ValueSet/conditional-read-status to http://hl7.org/fhir/ValueSet/conditional-read-status|4.0.1',
'CapabilityStatement.rest.resource.conditionalDelete', 'Change value set from http://hl7.org/fhir/ValueSet/conditional-delete-status to http://hl7.org/fhir/ValueSet/conditional-delete-status|4.0.1',
'CapabilityStatement.rest.resource.referencePolicy', 'Change value set from http://hl7.org/fhir/ValueSet/reference-handling-policy to http://hl7.org/fhir/ValueSet/reference-handling-policy|4.0.1',
'CapabilityStatement.rest.resource.searchParam.definition', 'Type changed from uri to canonical(SearchParameter)',
'CapabilityStatement.rest.resource.searchParam.type', 'Change value set from http://hl7.org/fhir/ValueSet/search-param-type to http://hl7.org/fhir/ValueSet/search-param-type|4.0.1',
'CapabilityStatement.rest.resource.searchParam.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.operation', 'Added Element',
'CapabilityStatement.rest.resource.operation.name', 'Added Mandatory Element',
'CapabilityStatement.rest.resource.operation.definition', 'Added Mandatory Element',
'CapabilityStatement.rest.resource.operation.documentation', 'Added Element',
'CapabilityStatement.rest.interaction.code', 'Change value set from http://hl7.org/fhir/ValueSet/system-restful-interaction to http://hl7.org/fhir/ValueSet/system-restful-interaction|4.0.1',
'CapabilityStatement.rest.interaction.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.operation', 'Remove Type BackboneElement',
'CapabilityStatement.rest.compartment', 'Type changed from uri to canonical(CompartmentDefinition)',
'CapabilityStatement.messaging.endpoint.protocol', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/message-transport" to "http://terminology.hl7.org/CodeSystem/message-transport"',
'CapabilityStatement.messaging.endpoint.address', 'Type changed from uri to url',
'CapabilityStatement.messaging.documentation', 'Type changed from string to markdown',
'CapabilityStatement.messaging.supportedMessage.mode', 'Change value set from http://hl7.org/fhir/ValueSet/event-capability-mode to http://hl7.org/fhir/ValueSet/event-capability-mode|4.0.1',
'CapabilityStatement.messaging.supportedMessage.definition', 'Type changed from Reference(MessageDefinition) to canonical(MessageDefinition)',
'CapabilityStatement.document.mode', 'Change value set from http://hl7.org/fhir/ValueSet/document-mode to http://hl7.org/fhir/ValueSet/document-mode|4.0.1',
'CapabilityStatement.document.documentation', 'Type changed from string to markdown',
'CapabilityStatement.document.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.acceptUnknown', 'deleted',
'CapabilityStatement.rest.security.certificate', 'deleted',
'CapabilityStatement.rest.operation.name', 'deleted',
'CapabilityStatement.rest.operation.definition', 'deleted',
'CapabilityStatement.messaging.event', 'deleted',
)


df6 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'CapabilityStatement', 'IN', '', 'DomainResource', 'A statement of system capabilities+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: A Capability Statement SHALL have at least one of REST, messaging or document element.+ Rule: A Capability Statement SHALL have at least one of description, software, or implementation element.+ Rule: Messaging end-point is required (and is only permitted) when a statement is for an implementation.+ Rule: The set of documents must be unique by the combination of profile and mode.+ Rule: If kind = instance, implementation must be present and software may be present+ Rule: If kind = capability, implementation must be absent, software must be present+ Rule: If kind = requirements, implementation and software must be absentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this capability statement, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the capability statement',
'name', 'ΣI', '0..1', 'string', 'Name for this capability statement (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this capability statement (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '1..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'I', '0..1', 'markdown', 'Natural language description of the capability statement',
'useContext', 'ΣTU', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for capability statement (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this capability statement is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'kind', 'ΣI', '1..1', 'code', 'instance | capability | requirementsCapabilityStatementKind (Required)',
'instantiates', 'Σ', '0..*', 'canonical(CapabilityStatement)', 'Canonical URL of another capability statement this implements',
'imports', 'ΣTU', '0..*', 'canonical(CapabilityStatement)', 'Canonical URL of another capability statement this adds to',
'software', 'ΣI', '0..1', 'BackboneElement', 'Software that is covered by this capability statement',
'name', 'Σ', '1..1', 'string', 'A name the software is known by',
'version', 'Σ', '0..1', 'string', 'Version covered by this statement',
'releaseDate', 'Σ', '0..1', 'dateTime', 'Date this version was released',
'implementation', 'ΣI', '0..1', 'BackboneElement', 'If this describes a specific instance',
'description', 'Σ', '1..1', 'string', 'Describes this specific instance',
'url', 'Σ', '0..1', 'url', 'Base URL for the installation',
'custodian', 'ΣTU', '0..1', 'Reference(Organization)', 'Organization that manages the data',
'fhirVersion', 'Σ', '1..1', 'code', 'FHIR Version the system supportsFHIRVersion (Required)',
'format', 'Σ', '1..*', 'code', 'formats supported (xml | json | ttl | mime type)MimeType (Required)',
'patchFormat', 'Σ', '0..*', 'code', 'Patch formats supportedMimeType (Required)',
'implementationGuide', 'Σ', '0..*', 'canonical(ImplementationGuide)', 'Implementation guides supported',
'rest', 'ΣI', '0..*', 'BackboneElement', 'If the endpoint is a RESTful one+ Rule: A given resource can only be described once per RESTful mode.',
'mode', 'Σ', '1..1', 'code', 'client | serverRestfulCapabilityMode (Required)',
'documentation', '', '0..1', 'markdown', 'General description of implementation',
'security', 'ΣTU', '0..1', 'BackboneElement', 'Information about security of implementation',
'cors', 'Σ', '0..1', 'boolean', 'Adds CORS Headers (http://enable-cors.org/)',
'service', 'Σ', '0..*', 'CodeableConcept', 'OAuth | SMART-on-FHIR | NTLM | Basic | Kerberos | CertificatesRestfulSecurityService (Extensible)',
'description', '', '0..1', 'markdown', 'General description of how security works',
'resource', 'ΣI', '0..*', 'BackboneElement', 'Resource served on the REST interface+ Rule: Search parameter names must be unique in the context of a resource.',
'type', 'Σ', '1..1', 'code', 'A resource type that is supportedResourceType (Required)',
'profile', 'Σ', '0..1', 'canonical(StructureDefinition)', 'Base System profile for all uses of resource',
'supportedProfile', 'ΣTU', '0..*', 'canonical(StructureDefinition)', 'Profiles for use cases supported',
'documentation', '', '0..1', 'markdown', 'Additional information about the use of the resource type',
'interaction', '', '0..*', 'BackboneElement', 'What operations are supported?',
'code', '', '1..1', 'code', 'read | vread | update | patch | delete | history-instance | history-type | create | search-typeTypeRestfulInteraction (Required)',
'documentation', '', '0..1', 'markdown', 'Anything special about operation behavior',
'versioning', 'TU', '0..1', 'code', 'no-version | versioned | versioned-updateResourceVersionPolicy (Required)',
'readHistory', 'TU', '0..1', 'boolean', 'Whether vRead can return past versions',
'updateCreate', 'TU', '0..1', 'boolean', 'If update can commit to a new identity',
'conditionalCreate', 'TU', '0..1', 'boolean', 'If allows/uses conditional create',
'conditionalRead', 'TU', '0..1', 'code', 'not-supported | modified-since | not-match | full-supportConditionalReadStatus (Required)',
'conditionalUpdate', 'TU', '0..1', 'boolean', 'If allows/uses conditional update',
'conditionalDelete', 'TU', '0..1', 'code', 'not-supported | single | multiple - how conditional delete is supportedConditionalDeleteStatus (Required)',
'referencePolicy', 'TU', '0..*', 'code', 'literal | logical | resolves | enforced | localReferenceHandlingPolicy (Required)',
'searchInclude', 'TU', '0..*', 'string', '_include values supported by the server',
'searchRevInclude', 'TU', '0..*', 'string', '_revinclude values supported by the server',
'searchParam', '', '0..*', 'BackboneElement', 'Search parameters supported by implementation',
'name', '', '1..1', 'string', 'Name of search parameter',
'definition', '', '0..1', 'canonical(SearchParameter)', 'Source of definition for parameter',
'type', '', '1..1', 'code', 'number | date | string | token | reference | composite | quantity | uri | specialSearchParamType (Required)',
'documentation', '', '0..1', 'markdown', 'Server-specific usage',
'operation', 'Σ', '0..*', 'BackboneElement', 'Definition of a resource operation',
'name', 'Σ', '1..1', 'string', 'Name by which the operation/query is invoked',
'definition', 'Σ', '1..1', 'canonical(OperationDefinition)', 'The defined operation/query',
'documentation', '', '0..1', 'markdown', 'Specific details about operation behavior',
'interaction', '', '0..*', 'BackboneElement', 'What operations are supported?',
'code', '', '1..1', 'code', 'transaction | batch | search-system | history-systemSystemRestfulInteraction (Required)',
'documentation', '', '0..1', 'markdown', 'Anything special about operation behavior',
'searchParam', '', '0..*', 'see searchParam', 'Search parameters for searching all resources',
'operation', 'Σ', '0..*', 'see operation', 'Definition of a system level operation',
'compartment', '', '0..*', 'canonical(CompartmentDefinition)', 'Compartments served/used by system',
'messaging', 'ΣITU', '0..*', 'BackboneElement', 'If messaging is supported',
'endpoint', '', '0..*', 'BackboneElement', 'Where messages should be sent',
'protocol', '', '1..1', 'Coding', 'http | ftp | mllp +MessageTransport (Extensible)',
'address', '', '1..1', 'url', 'Network address or identifier of the end-point',
'reliableCache', '', '0..1', 'unsignedInt', 'Reliable Message Cache Length (min)',
'documentation', '', '0..1', 'markdown', 'Messaging interface behavior details',
'supportedMessage', 'Σ', '0..*', 'BackboneElement', 'Messages supported by this system',
'mode', 'Σ', '1..1', 'code', 'sender | receiverEventCapabilityMode (Required)',
'definition', 'Σ', '1..1', 'canonical(MessageDefinition)', 'Message supported by this system',
'document', 'ΣITU', '0..*', 'BackboneElement', 'Document definition',
'mode', 'Σ', '1..1', 'code', 'producer | consumerDocumentMode (Required)',
'documentation', '', '0..1', 'markdown', 'Description of document support',
'profile', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Constraint on the resources used in the document',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,
'CapabilityStatement', '',
'CapabilityStatement', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'CapabilityStatement.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'CapabilityStatement.experimental', 'No longer marked as Modifier',
'CapabilityStatement.kind', 'Change value set from http://hl7.org/fhir/ValueSet/capability-statement-kind to http://hl7.org/fhir/ValueSet/capability-statement-kind|4.0.1',
'CapabilityStatement.instantiates', 'Type changed from uri to canonical(CapabilityStatement)',
'CapabilityStatement.imports', 'Added Element',
'CapabilityStatement.implementation.url', 'Type changed from uri to url',
'CapabilityStatement.implementation.custodian', 'Added Element',
'CapabilityStatement.fhirVersion', 'Type changed from id to code
        
Add Binding http://hl7.org/fhir/ValueSet/FHIR-version|4.0.1 (required)',
'CapabilityStatement.format', 'Change value set from http://hl7.org/fhir/ValueSet/mimetypes to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'CapabilityStatement.patchFormat', 'Change value set from http://hl7.org/fhir/ValueSet/mimetypes to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'CapabilityStatement.implementationGuide', 'Type changed from uri to canonical(ImplementationGuide)',
'CapabilityStatement.rest.mode', 'Change value set from http://hl7.org/fhir/ValueSet/restful-capability-mode to http://hl7.org/fhir/ValueSet/restful-capability-mode|4.0.1',
'CapabilityStatement.rest.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.security.service', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/restful-security-service" to "http://terminology.hl7.org/CodeSystem/restful-security-service"',
'CapabilityStatement.rest.security.description', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.type', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'CapabilityStatement.rest.resource.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.rest.resource.supportedProfile', 'Moved from CapabilityStatement.profile to supportedProfile
        Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.rest.resource.interaction', 'Min Cardinality changed from 1 to 0',
'CapabilityStatement.rest.resource.interaction.code', 'Change value set from http://hl7.org/fhir/ValueSet/type-restful-interaction to http://hl7.org/fhir/ValueSet/type-restful-interaction|4.0.1',
'CapabilityStatement.rest.resource.interaction.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.versioning', 'Change value set from http://hl7.org/fhir/ValueSet/versioning-policy to http://hl7.org/fhir/ValueSet/versioning-policy|4.0.1',
'CapabilityStatement.rest.resource.conditionalRead', 'Change value set from http://hl7.org/fhir/ValueSet/conditional-read-status to http://hl7.org/fhir/ValueSet/conditional-read-status|4.0.1',
'CapabilityStatement.rest.resource.conditionalDelete', 'Change value set from http://hl7.org/fhir/ValueSet/conditional-delete-status to http://hl7.org/fhir/ValueSet/conditional-delete-status|4.0.1',
'CapabilityStatement.rest.resource.referencePolicy', 'Change value set from http://hl7.org/fhir/ValueSet/reference-handling-policy to http://hl7.org/fhir/ValueSet/reference-handling-policy|4.0.1',
'CapabilityStatement.rest.resource.searchParam.definition', 'Type changed from uri to canonical(SearchParameter)',
'CapabilityStatement.rest.resource.searchParam.type', 'Change value set from http://hl7.org/fhir/ValueSet/search-param-type to http://hl7.org/fhir/ValueSet/search-param-type|4.0.1',
'CapabilityStatement.rest.resource.searchParam.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.resource.operation', 'Added Element',
'CapabilityStatement.rest.resource.operation.name', 'Added Mandatory Element',
'CapabilityStatement.rest.resource.operation.definition', 'Added Mandatory Element',
'CapabilityStatement.rest.resource.operation.documentation', 'Added Element',
'CapabilityStatement.rest.interaction.code', 'Change value set from http://hl7.org/fhir/ValueSet/system-restful-interaction to http://hl7.org/fhir/ValueSet/system-restful-interaction|4.0.1',
'CapabilityStatement.rest.interaction.documentation', 'Type changed from string to markdown',
'CapabilityStatement.rest.operation', 'Remove Type BackboneElement',
'CapabilityStatement.rest.compartment', 'Type changed from uri to canonical(CompartmentDefinition)',
'CapabilityStatement.messaging.endpoint.protocol', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/message-transport" to "http://terminology.hl7.org/CodeSystem/message-transport"',
'CapabilityStatement.messaging.endpoint.address', 'Type changed from uri to url',
'CapabilityStatement.messaging.documentation', 'Type changed from string to markdown',
'CapabilityStatement.messaging.supportedMessage.mode', 'Change value set from http://hl7.org/fhir/ValueSet/event-capability-mode to http://hl7.org/fhir/ValueSet/event-capability-mode|4.0.1',
'CapabilityStatement.messaging.supportedMessage.definition', 'Type changed from Reference(MessageDefinition) to canonical(MessageDefinition)',
'CapabilityStatement.document.mode', 'Change value set from http://hl7.org/fhir/ValueSet/document-mode to http://hl7.org/fhir/ValueSet/document-mode|4.0.1',
'CapabilityStatement.document.documentation', 'Type changed from string to markdown',
'CapabilityStatement.document.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'CapabilityStatement.acceptUnknown', 'deleted',
'CapabilityStatement.rest.security.certificate', 'deleted',
'CapabilityStatement.rest.operation.name', 'deleted',
'CapabilityStatement.rest.operation.definition', 'deleted',
'CapabilityStatement.messaging.event', 'deleted',
)


df8 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'CapabilityStatement.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'CapabilityStatement.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'CapabilityStatement.kind', 'How a capability statement is intended to be used.', 'Required', 'CapabilityStatementKind',
'CapabilityStatement.fhirVersion', 'All published FHIR Versions.', 'Required', 'FHIRVersion',
'CapabilityStatement.formatCapabilityStatement.patchFormat', 'The mime type of an attachment. Any valid mime type is allowed.', 'Required', 'Mime Types',
'CapabilityStatement.rest.mode', 'The mode of a RESTful capability statement.', 'Required', 'RestfulCapabilityMode',
'CapabilityStatement.rest.security.service', 'Types of security services used with FHIR.', 'Extensible', 'RestfulSecurityService',
'CapabilityStatement.rest.resource.type', 'One of the resource types defined as part of this version of FHIR.', 'Required', 'Resource Types',
'CapabilityStatement.rest.resource.interaction.code', 'Operations supported by REST at the type or instance level.', 'Required', 'TypeRestfulInteraction',
'CapabilityStatement.rest.resource.versioning', 'How the system supports versioning for a resource.', 'Required', 'ResourceVersionPolicy',
'CapabilityStatement.rest.resource.conditionalRead', 'A code that indicates how the server supports conditional read.', 'Required', 'ConditionalReadStatus',
'CapabilityStatement.rest.resource.conditionalDelete', 'A code that indicates how the server supports conditional delete.', 'Required', 'ConditionalDeleteStatus',
'CapabilityStatement.rest.resource.referencePolicy', 'A set of flags that defines how references are supported.', 'Required', 'ReferenceHandlingPolicy',
'CapabilityStatement.rest.resource.searchParam.type', 'Data types allowed to be used for search parameters.', 'Required', 'SearchParamType',
'CapabilityStatement.rest.interaction.code', 'Operations supported by REST at the system level.', 'Required', 'SystemRestfulInteraction',
'CapabilityStatement.messaging.endpoint.protocol', 'The protocol used for message transport.', 'Extensible', 'MessageTransport',
'CapabilityStatement.messaging.supportedMessage.mode', 'The mode of a message capability statement.', 'Required', 'EventCapabilityMode',
'CapabilityStatement.document.mode', 'Whether the application produces or consumes documents.', 'Required', 'DocumentMode',
)


df9 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'cpb-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'cpb-1', 'Rule', '(base)', 'A Capability Statement SHALL have at least one of REST, messaging or document element.', 'rest.exists() or messaging.exists() or document.exists()',
'cpb-2', 'Rule', '(base)', 'A Capability Statement SHALL have at least one of description, software, or implementation element.', '(description.count() + software.count() + implementation.count()) > 0',
'cpb-3', 'Rule', '(base)', 'Messaging end-point is required (and is only permitted) when a statement is for an implementation.', 'messaging.endpoint.empty() or kind = 'instance'',
'cpb-7', 'Rule', '(base)', 'The set of documents must be unique by the combination of profile and mode.', 'document.select(profile&mode).isDistinct()',
'cpb-9', 'Rule', 'CapabilityStatement.rest', 'A given resource can only be described once per RESTful mode.', 'resource.select(type).isDistinct()',
'cpb-12', 'Rule', 'CapabilityStatement.rest.resource', 'Search parameter names must be unique in the context of a resource.', 'searchParam.select(name).isDistinct()',
'cpb-14', 'Rule', '(base)', 'If kind = instance, implementation must be present and software may be present', '(kind != 'instance') or implementation.exists()',
'cpb-15', 'Rule', '(base)', 'If kind = capability, implementation must be absent, software must be present', '(kind != 'capability') or (implementation.exists().not() and software.exists())',
'cpb-16', 'Rule', '(base)', 'If kind = requirements, implementation and software must be absent', '(kind!='requirements') or (implementation.exists().not() and software.exists().not())',
)


df10 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context TU', 'token', 'A use context assigned to the capability statement', '(CapabilityStatement.useContext.value as CodeableConcept)', '',
'context-quantity TU', 'quantity', 'A quantity- or range-valued use context assigned to the capability statement', '(CapabilityStatement.useContext.value as Quantity) | (CapabilityStatement.useContext.value as Range)', '',
'context-type TU', 'token', 'A type of use context assigned to the capability statement', 'CapabilityStatement.useContext.code', '',
'context-type-quantity TU', 'composite', 'A use context type and quantity- or range-based value assigned to the capability statement', 'On CapabilityStatement.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value TU', 'composite', 'A use context type and value assigned to the capability statement', 'On CapabilityStatement.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date TU', 'date', 'The capability statement publication date', 'CapabilityStatement.date', '',
'description TU', 'string', 'The description of the capability statement', 'CapabilityStatement.description', '',
'fhirversion TU', 'token', 'The version of FHIR', 'CapabilityStatement.version', '',
'format TU', 'token', 'formats supported (xml | json | ttl | mime type)', 'CapabilityStatement.format', '',
'guide TU', 'reference', 'Implementation guides supported', 'CapabilityStatement.implementationGuide(ImplementationGuide)', '',
'jurisdiction TU', 'token', 'Intended jurisdiction for the capability statement', 'CapabilityStatement.jurisdiction', '',
'mode TU', 'token', 'Mode - restful (server/client) or messaging (sender/receiver)', 'CapabilityStatement.rest.mode', '',
'name TU', 'string', 'Computationally friendly name of the capability statement', 'CapabilityStatement.name', '',
'publisher TU', 'string', 'Name of the publisher of the capability statement', 'CapabilityStatement.publisher', '',
'resource TU', 'token', 'Name of a resource mentioned in a capability statement', 'CapabilityStatement.rest.resource.type', '',
'resource-profile TU', 'reference', 'A profile id invoked in a capability statement', 'CapabilityStatement.rest.resource.profile(StructureDefinition)', '',
'security-service TU', 'token', 'OAuth | SMART-on-FHIR | NTLM | Basic | Kerberos | Certificates', 'CapabilityStatement.rest.security.service', '',
'software TU', 'string', 'Part of the name of a software application', 'CapabilityStatement.software.name', '',
'status TU', 'token', 'The current status of the capability statement', 'CapabilityStatement.status', '',
'supported-profile TU', 'reference', 'Profiles for use cases supported', 'CapabilityStatement.rest.resource.supportedProfile(StructureDefinition)', '',
'title TU', 'string', 'The human-friendly name of the capability statement', 'CapabilityStatement.title', '',
'url TU', 'uri', 'The uri that identifies the capability statement', 'CapabilityStatement.url', '',
'version TU', 'token', 'The business version of the capability statement', 'CapabilityStatement.version', '',
)


