df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Financial Management  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Patient', 'Compartments: Patient, Practitioner',
)


df2 <- 
tibble::tribble(
~`X1`,~`X2`,
'ClaimResponse', 'A payor's adjudication and/or authorization response to the suite of services provided in a Claim. Typically the ClaimResponse references the Claim but does not duplicate
		the clinical or financial information provided in the claim.',
'ExplanationOfBenefit', 'This resource combines the information from the Claim and the ClaimResponse, stripping out any provider or payor proprietary information, into a unified information model 
					suitable for use for: patient reporting; transferring information to a Patient Health Record system; and, supporting complete claim and adjudication information exchange
					with regulatory and analytics organizations and other parts of the provider's organization.',
'Claim', 'A suite of goods and services and insurances coverages under which adjudication or authorization is requested.',
'CoverageEligibilityResponse', 'The response to a request to a payor, a CoverageEligibilityRequest,
				to: ascertain whether a coverage is in-force at the current or at a specified time; list the table of benefits;
				determine whether coverage is provided for specified categories or specific services; and whether preauthorization is required, and if so
				what supporting information would be required.',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ClaimResponse', 'TU', '', 'DomainResource', 'Response to a claim predetermination or preauthorizationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for a claim response',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorFinancial Resource Status Codes (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'More granular claim typeClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'created', 'Σ', '1..1', 'dateTime', 'Response creation date',
'insurer', 'Σ', '1..1', 'Reference(Organization)', 'Party responsible for reimbursement',
'requestor', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'request', 'Σ', '0..1', 'Reference(Claim)', 'Id of resource triggering adjudication',
'outcome', 'Σ', '1..1', 'code', 'queued | complete | error | partialClaim Processing Codes (Required)',
'disposition', '', '0..1', 'string', 'Disposition Message',
'preAuthRef', '', '0..1', 'string', 'Preauthorization reference',
'preAuthPeriod', '', '0..1', 'Period', 'Preauthorization reference effective period',
'payeeType', '', '0..1', 'CodeableConcept', 'Party to be paid any benefits payablePayeeType (Example)',
'item', '', '0..*', 'BackboneElement', 'Adjudication for claim line items',
'itemSequence', '', '1..1', 'positiveInt', 'Claim item instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'BackboneElement', 'Adjudication details',
'category', '', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'reason', '', '0..1', 'CodeableConcept', 'Explanation of adjudication outcomeAdjudication Reason Codes (Example)',
'amount', '', '0..1', 'Money', 'Monetary amount',
'value', '', '0..1', 'decimal', 'Non-monetary value',
'detail', '', '0..*', 'BackboneElement', 'Adjudication for claim details',
'detailSequence', '', '1..1', 'positiveInt', 'Claim detail instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Detail level adjudication details',
'subDetail', '', '0..*', 'BackboneElement', 'Adjudication for claim sub-details',
'subDetailSequence', '', '1..1', 'positiveInt', 'Claim sub-detail instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Subdetail level adjudication details',
'addItem', '', '0..*', 'BackboneElement', 'Insurer added line items',
'itemSequence', '', '0..*', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..*', 'positiveInt', 'Detail sequence number',
'subdetailSequence', '', '0..*', 'positiveInt', 'Subdetail sequence number',
'provider', '', '0..*', 'Reference(Practitioner | PractitionerRole | Organization)', 'Authorized providers',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items adjudication',
'detail', '', '0..*', 'BackboneElement', 'Insurer added line details',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items detail adjudication',
'subDetail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items detail adjudication',
'adjudication', '', '0..*', 'see adjudication', 'Header-level adjudication',
'total', 'Σ', '0..*', 'BackboneElement', 'Adjudication totals',
'category', 'Σ', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'amount', 'Σ', '1..1', 'Money', 'Financial total for the category',
'payment', '', '0..1', 'BackboneElement', 'Payment Details',
'type', '', '1..1', 'CodeableConcept', 'Partial or complete paymentExample Payment Type Codes (Example)',
'adjustment', '', '0..1', 'Money', 'Payment adjustment for non-claim issues',
'adjustmentReason', '', '0..1', 'CodeableConcept', 'Explanation for the adjustmentPayment Adjustment Reason Codes (Example)',
'date', '', '0..1', 'date', 'Expected date of payment',
'amount', '', '1..1', 'Money', 'Payable amount after adjustment',
'identifier', '', '0..1', 'Identifier', 'Business identifier for the payment',
'fundsReserve', '', '0..1', 'CodeableConcept', 'Funds reserved statusFundsReserve (Example)',
'formCode', '', '0..1', 'CodeableConcept', 'Printed form identifierForms (Example)',
'form', '', '0..1', 'Attachment', 'Printed reference or actual form',
'processNote', '', '0..*', 'BackboneElement', 'Note concerning adjudication',
'number', '', '0..1', 'positiveInt', 'Note instance identifier',
'type', '', '0..1', 'code', 'display | print | printoperNoteType (Required)',
'text', '', '1..1', 'string', 'Note explanatory text',
'language', '', '0..1', 'CodeableConcept', 'Language of the textCommon Languages (Preferred but limited to AllLanguages)',
'communicationRequest', '', '0..*', 'Reference(CommunicationRequest)', 'Request for additional information',
'insurance', '', '0..*', 'BackboneElement', 'Patient insurance information',
'sequence', '', '1..1', 'positiveInt', 'Insurance instance identifier',
'focal', '', '1..1', 'boolean', 'Coverage to be used for adjudication',
'coverage', '', '1..1', 'Reference(Coverage)', 'Insurance information',
'businessArrangement', '', '0..1', 'string', 'Additional provider contract number',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Adjudication results',
'error', '', '0..*', 'BackboneElement', 'Processing errors',
'itemSequence', '', '0..1', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..1', 'positiveInt', 'Detail sequence number',
'subDetailSequence', '', '0..1', 'positiveInt', 'Subdetail sequence number',
'code', '', '1..1', 'CodeableConcept', 'Error code detailing processing issuesAdjudicationError (Example)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`X1`,~`X2`,
'ClaimResponse', '',
'ClaimResponse.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/fm-status to http://hl7.org/fhir/ValueSet/fm-status|4.0.1',
'ClaimResponse.type', 'Added Mandatory Element',
'ClaimResponse.subType', 'Added Element',
'ClaimResponse.use', 'Added Mandatory Element',
'ClaimResponse.patient', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.created', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.insurer', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.requestor', 'Renamed from requestProvider to requestor
        Type Reference: Added Target Types PractitionerRole, Organization',
'ClaimResponse.outcome', 'Min Cardinality changed from 0 to 1
        Type changed from CodeableConcept to code
        
Add Binding http://hl7.org/fhir/ValueSet/remittance-outcome|4.0.1 (required)',
'ClaimResponse.preAuthRef', 'Moved from ClaimResponse.insurance to ClaimResponse
        Max Cardinality changed from * to 1',
'ClaimResponse.preAuthPeriod', 'Added Element',
'ClaimResponse.item.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.item.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.item.detail.detailSequence', 'Renamed from sequenceLinkId to detailSequence',
'ClaimResponse.item.detail.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.item.detail.subDetail.subDetailSequence', 'Renamed from sequenceLinkId to subDetailSequence',
'ClaimResponse.addItem.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.addItem.detailSequence', 'Added Element',
'ClaimResponse.addItem.subdetailSequence', 'Added Element',
'ClaimResponse.addItem.provider', 'Added Element',
'ClaimResponse.addItem.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.programCode', 'Added Element',
'ClaimResponse.addItem.serviced[x]', 'Added Element',
'ClaimResponse.addItem.location[x]', 'Added Element',
'ClaimResponse.addItem.quantity', 'Added Element',
'ClaimResponse.addItem.unitPrice', 'Added Element',
'ClaimResponse.addItem.factor', 'Added Element',
'ClaimResponse.addItem.net', 'Added Element',
'ClaimResponse.addItem.bodySite', 'Added Element',
'ClaimResponse.addItem.subSite', 'Added Element',
'ClaimResponse.addItem.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.quantity', 'Added Element',
'ClaimResponse.addItem.detail.unitPrice', 'Added Element',
'ClaimResponse.addItem.detail.factor', 'Added Element',
'ClaimResponse.addItem.detail.net', 'Added Element',
'ClaimResponse.addItem.detail.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.subDetail', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.productOrService', 'Added Mandatory Element',
'ClaimResponse.addItem.detail.subDetail.modifier', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.quantity', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.unitPrice', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.factor', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.net', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.noteNumber', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.adjudication', 'Added Mandatory Element',
'ClaimResponse.adjudication', 'Added Element',
'ClaimResponse.total', 'Added Element',
'ClaimResponse.total.category', 'Added Mandatory Element',
'ClaimResponse.total.amount', 'Added Mandatory Element',
'ClaimResponse.payment.type', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.payment.amount', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.fundsReserve', 'Renamed from reserved to fundsReserve
        Type changed from Coding to CodeableConcept',
'ClaimResponse.formCode', 'Added Element',
'ClaimResponse.form', 'Type changed from CodeableConcept to Attachment',
'ClaimResponse.processNote.type', 'Type changed from CodeableConcept to code
        Change value set from http://hl7.org/fhir/ValueSet/note-type to http://hl7.org/fhir/ValueSet/note-type|4.0.1',
'ClaimResponse.processNote.text', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.processNote.language', 'Change binding strength from extensible to preferred',
'ClaimResponse.error.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.error.detailSequence', 'Renamed from detailSequenceLinkId to detailSequence',
'ClaimResponse.error.subDetailSequence', 'Renamed from subdetailSequenceLinkId to subDetailSequence',
'ClaimResponse.requestOrganization', 'deleted',
'ClaimResponse.addItem.revenue', 'deleted',
'ClaimResponse.addItem.category', 'deleted',
'ClaimResponse.addItem.fee', 'deleted',
'ClaimResponse.addItem.detail.revenue', 'deleted',
'ClaimResponse.addItem.detail.category', 'deleted',
'ClaimResponse.addItem.detail.fee', 'deleted',
'ClaimResponse.totalCost', 'deleted',
'ClaimResponse.unallocDeductable', 'deleted',
'ClaimResponse.totalBenefit', 'deleted',
)


df5 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ClaimResponse', 'TU', '', 'DomainResource', 'Response to a claim predetermination or preauthorizationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for a claim response',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorFinancial Resource Status Codes (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'More granular claim typeClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'created', 'Σ', '1..1', 'dateTime', 'Response creation date',
'insurer', 'Σ', '1..1', 'Reference(Organization)', 'Party responsible for reimbursement',
'requestor', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'request', 'Σ', '0..1', 'Reference(Claim)', 'Id of resource triggering adjudication',
'outcome', 'Σ', '1..1', 'code', 'queued | complete | error | partialClaim Processing Codes (Required)',
'disposition', '', '0..1', 'string', 'Disposition Message',
'preAuthRef', '', '0..1', 'string', 'Preauthorization reference',
'preAuthPeriod', '', '0..1', 'Period', 'Preauthorization reference effective period',
'payeeType', '', '0..1', 'CodeableConcept', 'Party to be paid any benefits payablePayeeType (Example)',
'item', '', '0..*', 'BackboneElement', 'Adjudication for claim line items',
'itemSequence', '', '1..1', 'positiveInt', 'Claim item instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'BackboneElement', 'Adjudication details',
'category', '', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'reason', '', '0..1', 'CodeableConcept', 'Explanation of adjudication outcomeAdjudication Reason Codes (Example)',
'amount', '', '0..1', 'Money', 'Monetary amount',
'value', '', '0..1', 'decimal', 'Non-monetary value',
'detail', '', '0..*', 'BackboneElement', 'Adjudication for claim details',
'detailSequence', '', '1..1', 'positiveInt', 'Claim detail instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Detail level adjudication details',
'subDetail', '', '0..*', 'BackboneElement', 'Adjudication for claim sub-details',
'subDetailSequence', '', '1..1', 'positiveInt', 'Claim sub-detail instance identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Subdetail level adjudication details',
'addItem', '', '0..*', 'BackboneElement', 'Insurer added line items',
'itemSequence', '', '0..*', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..*', 'positiveInt', 'Detail sequence number',
'subdetailSequence', '', '0..*', 'positiveInt', 'Subdetail sequence number',
'provider', '', '0..*', 'Reference(Practitioner | PractitionerRole | Organization)', 'Authorized providers',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items adjudication',
'detail', '', '0..*', 'BackboneElement', 'Insurer added line details',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items detail adjudication',
'subDetail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '1..*', 'see adjudication', 'Added items detail adjudication',
'adjudication', '', '0..*', 'see adjudication', 'Header-level adjudication',
'total', 'Σ', '0..*', 'BackboneElement', 'Adjudication totals',
'category', 'Σ', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'amount', 'Σ', '1..1', 'Money', 'Financial total for the category',
'payment', '', '0..1', 'BackboneElement', 'Payment Details',
'type', '', '1..1', 'CodeableConcept', 'Partial or complete paymentExample Payment Type Codes (Example)',
'adjustment', '', '0..1', 'Money', 'Payment adjustment for non-claim issues',
'adjustmentReason', '', '0..1', 'CodeableConcept', 'Explanation for the adjustmentPayment Adjustment Reason Codes (Example)',
'date', '', '0..1', 'date', 'Expected date of payment',
'amount', '', '1..1', 'Money', 'Payable amount after adjustment',
'identifier', '', '0..1', 'Identifier', 'Business identifier for the payment',
'fundsReserve', '', '0..1', 'CodeableConcept', 'Funds reserved statusFundsReserve (Example)',
'formCode', '', '0..1', 'CodeableConcept', 'Printed form identifierForms (Example)',
'form', '', '0..1', 'Attachment', 'Printed reference or actual form',
'processNote', '', '0..*', 'BackboneElement', 'Note concerning adjudication',
'number', '', '0..1', 'positiveInt', 'Note instance identifier',
'type', '', '0..1', 'code', 'display | print | printoperNoteType (Required)',
'text', '', '1..1', 'string', 'Note explanatory text',
'language', '', '0..1', 'CodeableConcept', 'Language of the textCommon Languages (Preferred but limited to AllLanguages)',
'communicationRequest', '', '0..*', 'Reference(CommunicationRequest)', 'Request for additional information',
'insurance', '', '0..*', 'BackboneElement', 'Patient insurance information',
'sequence', '', '1..1', 'positiveInt', 'Insurance instance identifier',
'focal', '', '1..1', 'boolean', 'Coverage to be used for adjudication',
'coverage', '', '1..1', 'Reference(Coverage)', 'Insurance information',
'businessArrangement', '', '0..1', 'string', 'Additional provider contract number',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Adjudication results',
'error', '', '0..*', 'BackboneElement', 'Processing errors',
'itemSequence', '', '0..1', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..1', 'positiveInt', 'Detail sequence number',
'subDetailSequence', '', '0..1', 'positiveInt', 'Subdetail sequence number',
'code', '', '1..1', 'CodeableConcept', 'Error code detailing processing issuesAdjudicationError (Example)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,
'ClaimResponse', '',
'ClaimResponse.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/fm-status to http://hl7.org/fhir/ValueSet/fm-status|4.0.1',
'ClaimResponse.type', 'Added Mandatory Element',
'ClaimResponse.subType', 'Added Element',
'ClaimResponse.use', 'Added Mandatory Element',
'ClaimResponse.patient', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.created', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.insurer', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.requestor', 'Renamed from requestProvider to requestor
        Type Reference: Added Target Types PractitionerRole, Organization',
'ClaimResponse.outcome', 'Min Cardinality changed from 0 to 1
        Type changed from CodeableConcept to code
        
Add Binding http://hl7.org/fhir/ValueSet/remittance-outcome|4.0.1 (required)',
'ClaimResponse.preAuthRef', 'Moved from ClaimResponse.insurance to ClaimResponse
        Max Cardinality changed from * to 1',
'ClaimResponse.preAuthPeriod', 'Added Element',
'ClaimResponse.item.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.item.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.item.detail.detailSequence', 'Renamed from sequenceLinkId to detailSequence',
'ClaimResponse.item.detail.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.item.detail.subDetail.subDetailSequence', 'Renamed from sequenceLinkId to subDetailSequence',
'ClaimResponse.addItem.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.addItem.detailSequence', 'Added Element',
'ClaimResponse.addItem.subdetailSequence', 'Added Element',
'ClaimResponse.addItem.provider', 'Added Element',
'ClaimResponse.addItem.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.programCode', 'Added Element',
'ClaimResponse.addItem.serviced[x]', 'Added Element',
'ClaimResponse.addItem.location[x]', 'Added Element',
'ClaimResponse.addItem.quantity', 'Added Element',
'ClaimResponse.addItem.unitPrice', 'Added Element',
'ClaimResponse.addItem.factor', 'Added Element',
'ClaimResponse.addItem.net', 'Added Element',
'ClaimResponse.addItem.bodySite', 'Added Element',
'ClaimResponse.addItem.subSite', 'Added Element',
'ClaimResponse.addItem.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.quantity', 'Added Element',
'ClaimResponse.addItem.detail.unitPrice', 'Added Element',
'ClaimResponse.addItem.detail.factor', 'Added Element',
'ClaimResponse.addItem.detail.net', 'Added Element',
'ClaimResponse.addItem.detail.adjudication', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.addItem.detail.subDetail', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.productOrService', 'Added Mandatory Element',
'ClaimResponse.addItem.detail.subDetail.modifier', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.quantity', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.unitPrice', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.factor', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.net', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.noteNumber', 'Added Element',
'ClaimResponse.addItem.detail.subDetail.adjudication', 'Added Mandatory Element',
'ClaimResponse.adjudication', 'Added Element',
'ClaimResponse.total', 'Added Element',
'ClaimResponse.total.category', 'Added Mandatory Element',
'ClaimResponse.total.amount', 'Added Mandatory Element',
'ClaimResponse.payment.type', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.payment.amount', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.fundsReserve', 'Renamed from reserved to fundsReserve
        Type changed from Coding to CodeableConcept',
'ClaimResponse.formCode', 'Added Element',
'ClaimResponse.form', 'Type changed from CodeableConcept to Attachment',
'ClaimResponse.processNote.type', 'Type changed from CodeableConcept to code
        Change value set from http://hl7.org/fhir/ValueSet/note-type to http://hl7.org/fhir/ValueSet/note-type|4.0.1',
'ClaimResponse.processNote.text', 'Min Cardinality changed from 0 to 1',
'ClaimResponse.processNote.language', 'Change binding strength from extensible to preferred',
'ClaimResponse.error.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ClaimResponse.error.detailSequence', 'Renamed from detailSequenceLinkId to detailSequence',
'ClaimResponse.error.subDetailSequence', 'Renamed from subdetailSequenceLinkId to subDetailSequence',
'ClaimResponse.requestOrganization', 'deleted',
'ClaimResponse.addItem.revenue', 'deleted',
'ClaimResponse.addItem.category', 'deleted',
'ClaimResponse.addItem.fee', 'deleted',
'ClaimResponse.addItem.detail.revenue', 'deleted',
'ClaimResponse.addItem.detail.category', 'deleted',
'ClaimResponse.addItem.detail.fee', 'deleted',
'ClaimResponse.totalCost', 'deleted',
'ClaimResponse.unallocDeductable', 'deleted',
'ClaimResponse.totalBenefit', 'deleted',
)


df7 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ClaimResponse.status', 'A code specifying the state of the resource instance.', 'Required', 'FinancialResourceStatusCodes',
'ClaimResponse.type', 'The type or discipline-style of the claim.', 'Extensible', 'ClaimTypeCodes',
'ClaimResponse.subType', 'A more granular claim typecode.', 'Example', 'ExampleClaimSubTypeCodes',
'ClaimResponse.use', 'Claim, preauthorization, predetermination.', 'Required', 'Use',
'ClaimResponse.outcome', 'The result of the claim processing.', 'Required', 'ClaimProcessingCodes',
'ClaimResponse.payeeType', 'A code for the party to be reimbursed.', 'Example', 'Claim Payee Type Codes',
'ClaimResponse.item.adjudication.categoryClaimResponse.total.category', 'The adjudication codes.', 'Example', 'AdjudicationValueCodes',
'ClaimResponse.item.adjudication.reason', 'The adjudication reason codes.', 'Example', 'AdjudicationReasonCodes',
'ClaimResponse.addItem.productOrServiceClaimResponse.addItem.detail.productOrServiceClaimResponse.addItem.detail.subDetail.productOrService', 'Allowable service and product codes.', 'Example', 'USCLSCodes',
'ClaimResponse.addItem.modifierClaimResponse.addItem.detail.modifierClaimResponse.addItem.detail.subDetail.modifier', 'Item type or modifiers codes, eg for Oral whether the treatment is cosmetic or associated with TMJ, or an appliance was lost or stolen.', 'Example', 'ModifierTypeCodes',
'ClaimResponse.addItem.programCode', 'Program specific reason codes.', 'Example', 'ExampleProgramReasonCodes',
'ClaimResponse.addItem.location[x]', 'Place of service: pharmacy, school, prison, etc.', 'Example', 'ExampleServicePlaceCodes',
'ClaimResponse.addItem.bodySite', 'The code for the teeth, quadrant, sextant and arch.', 'Example', 'OralSiteCodes',
'ClaimResponse.addItem.subSite', 'The code for the tooth surface and surface combinations.', 'Example', 'SurfaceCodes',
'ClaimResponse.payment.type', 'The type (partial, complete) of the payment.', 'Example', 'ExamplePaymentTypeCodes',
'ClaimResponse.payment.adjustmentReason', 'Payment Adjustment reason codes.', 'Example', 'PaymentAdjustmentReasonCodes',
'ClaimResponse.fundsReserve', 'For whom funds are to be reserved: (Patient, Provider, None).', 'Example', 'Funds Reservation Codes',
'ClaimResponse.formCode', 'The forms codes.', 'Example', 'Form Codes',
'ClaimResponse.processNote.type', 'The presentation types of notes.', 'Required', 'NoteType',
'ClaimResponse.processNote.language', 'A human language.', 'Preferred, but limited to AllLanguages', 'CommonLanguages',
'ClaimResponse.error.code', 'The adjudication error codes.', 'Example', 'Adjudication Error Codes',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'created', 'date', 'The creation date', 'ClaimResponse.created', '',
'disposition', 'string', 'The contents of the disposition message', 'ClaimResponse.disposition', '',
'identifier', 'token', 'The identity of the ClaimResponse', 'ClaimResponse.identifier', '',
'insurer', 'reference', 'The organization which generated this resource', 'ClaimResponse.insurer(Organization)', '',
'outcome', 'token', 'The processing outcome', 'ClaimResponse.outcome', '',
'patient', 'reference', 'The subject of care', 'ClaimResponse.patient(Patient)', '',
'payment-date', 'date', 'The expected payment date', 'ClaimResponse.payment.date', '',
'request', 'reference', 'The claim reference', 'ClaimResponse.request(Claim)', '',
'requestor', 'reference', 'The Provider of the claim', 'ClaimResponse.requestor(Practitioner, Organization, PractitionerRole)', '',
'status', 'token', 'The status of the ClaimResponse', 'ClaimResponse.status', '',
'use', 'token', 'The type of claim', 'ClaimResponse.use', '',
)


