df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Financial Management  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Patient', 'Compartments: Device, Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <- 
tibble::tribble(
~`X1`,~`X2`,
'Claim', 'A suite of goods and services and insurances coverages under which adjudication or authorization is requested.',
'CoverageEligibilityRequest', 'A request to a payor to: ascertain whether a coverage is in-force at the current or at a specified time; list the table of benefits;
				determine whether coverage is provided for specified categories or specific services; and whether preauthorization is required, and if so
				what supporting information would be required.',
'ClaimResponse', 'A payor's adjudication and/or authorization response to the suite of services provided in a Claim. Typically the ClaimResponse references the Claim but does not duplicate
		the clinical or financial information provided in the claim.',
'ExplanationOfBenefit', 'This resource combines the information from the Claim and the ClaimResponse, stripping out any provider or payor proprietary information, into a unified information model 
		suitable for use for: patient reporting; transferring information to a Patient Health Record system; and, supporting complete claim and adjudication information exchange
 with regulatory and analytics organizations and other parts of the provider's organization.',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Claim', 'TU', '', 'DomainResource', 'Claim, Pre-determination or Pre-authorizationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for claim',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorFinancial Resource Status Codes (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'Category or disciplineClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'billablePeriod', 'Σ', '0..1', 'Period', 'Relevant time frame for the claim',
'created', 'Σ', '1..1', 'dateTime', 'Resource creation date',
'enterer', '', '0..1', 'Reference(Practitioner | PractitionerRole)', 'Author of the claim',
'insurer', 'Σ', '0..1', 'Reference(Organization)', 'Target',
'provider', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'priority', 'Σ', '1..1', 'CodeableConcept', 'Desired processing ugencyProcess Priority Codes (Example)',
'fundsReserve', '', '0..1', 'CodeableConcept', 'For whom to reserve fundsFundsReserve (Example)',
'related', '', '0..*', 'BackboneElement', 'Prior or corollary claims',
'claim', '', '0..1', 'Reference(Claim)', 'Reference to the related claim',
'relationship', '', '0..1', 'CodeableConcept', 'How the reference claim is relatedExample Related Claim Relationship Codes (Example)',
'reference', '', '0..1', 'Identifier', 'File or case reference',
'prescription', '', '0..1', 'Reference(DeviceRequest | MedicationRequest | VisionPrescription)', 'Prescription authorizing services and products',
'originalPrescription', '', '0..1', 'Reference(DeviceRequest | MedicationRequest | VisionPrescription)', 'Original prescription if superseded by fulfiller',
'payee', '', '0..1', 'BackboneElement', 'Recipient of benefits payable',
'type', '', '1..1', 'CodeableConcept', 'Category of recipientPayeeType (Example)',
'party', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson)', 'Recipient reference',
'referral', '', '0..1', 'Reference(ServiceRequest)', 'Treatment referral',
'facility', '', '0..1', 'Reference(Location)', 'Servicing facility',
'careTeam', '', '0..*', 'BackboneElement', 'Members of the care team',
'sequence', '', '1..1', 'positiveInt', 'Order of care team',
'provider', '', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Practitioner or organization',
'responsible', '', '0..1', 'boolean', 'Indicator of the lead practitioner',
'role', '', '0..1', 'CodeableConcept', 'Function within the teamClaim Care Team Role Codes (Example)',
'qualification', '', '0..1', 'CodeableConcept', 'Practitioner credential or specializationExample Provider Qualification Codes (Example)',
'supportingInfo', '', '0..*', 'BackboneElement', 'Supporting information',
'sequence', '', '1..1', 'positiveInt', 'Information instance identifier',
'category', '', '1..1', 'CodeableConcept', 'Classification of the supplied informationClaim Information Category Codes (Example)',
'code', '', '0..1', 'CodeableConcept', 'Type of informationException Codes (Example)',
'timing[x]', '', '0..1', '', 'When it occurred',
'timingDate', '', '', 'date', '',
'timingPeriod', '', '', 'Period', '',
'value[x]', '', '0..1', '', 'Data to be provided',
'valueBoolean', '', '', 'boolean', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'Quantity', '',
'valueAttachment', '', '', 'Attachment', '',
'valueReference', '', '', 'Reference(Any)', '',
'reason', '', '0..1', 'CodeableConcept', 'Explanation for the informationMissing Tooth Reason Codes (Example)',
'diagnosis', '', '0..*', 'BackboneElement', 'Pertinent diagnosis information',
'sequence', '', '1..1', 'positiveInt', 'Diagnosis instance identifier',
'diagnosis[x]', '', '1..1', '', 'Nature of illness or problemICD-10 Codes (Example)',
'diagnosisCodeableConcept', '', '', 'CodeableConcept', '',
'diagnosisReference', '', '', 'Reference(Condition)', '',
'type', '', '0..*', 'CodeableConcept', 'Timing or nature of the diagnosisExample Diagnosis Type Codes (Example)',
'onAdmission', '', '0..1', 'CodeableConcept', 'Present on admissionExample Diagnosis on Admission Codes (Example)',
'packageCode', '', '0..1', 'CodeableConcept', 'Package billing codeExample Diagnosis Related Group Codes (Example)',
'procedure', '', '0..*', 'BackboneElement', 'Clinical procedures performed',
'sequence', '', '1..1', 'positiveInt', 'Procedure instance identifier',
'type', '', '0..*', 'CodeableConcept', 'Category of ProcedureExample Procedure Type Codes (Example)',
'date', '', '0..1', 'dateTime', 'When the procedure was performed',
'procedure[x]', '', '1..1', '', 'Specific clinical procedureICD-10 Procedure Codes (Example)',
'procedureCodeableConcept', '', '', 'CodeableConcept', '',
'procedureReference', '', '', 'Reference(Procedure)', '',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'insurance', 'Σ', '1..*', 'BackboneElement', 'Patient insurance information',
'sequence', 'Σ', '1..1', 'positiveInt', 'Insurance instance identifier',
'focal', 'Σ', '1..1', 'boolean', 'Coverage to be used for adjudication',
'identifier', '', '0..1', 'Identifier', 'Pre-assigned Claim number',
'coverage', 'Σ', '1..1', 'Reference(Coverage)', 'Insurance information',
'businessArrangement', '', '0..1', 'string', 'Additional provider contract number',
'preAuthRef', '', '0..*', 'string', 'Prior authorization reference number',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Adjudication results',
'accident', '', '0..1', 'BackboneElement', 'Details of the event',
'date', '', '1..1', 'date', 'When the incident occurred',
'type', '', '0..1', 'CodeableConcept', 'The nature of the accidentV3 Value SetActIncidentCode (Extensible)',
'location[x]', '', '0..1', '', 'Where the event occurred',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'item', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'careTeamSequence', '', '0..*', 'positiveInt', 'Applicable careTeam members',
'diagnosisSequence', '', '0..*', 'positiveInt', 'Applicable diagnoses',
'procedureSequence', '', '0..*', 'positiveInt', 'Applicable procedures',
'informationSequence', '', '0..*', 'positiveInt', 'Applicable exception and supporting information',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Product or service billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'encounter', '', '0..*', 'Reference(Encounter)', 'Encounters related to this billed item',
'detail', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'subDetail', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'total', '', '0..1', 'Money', 'Total claim cost',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`X1`,~`X2`,
'Claim', '',
'Claim.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/fm-status to http://hl7.org/fhir/ValueSet/fm-status|4.0.1',
'Claim.type', 'Min Cardinality changed from 0 to 1
        Change binding strength from required to extensible',
'Claim.subType', 'Max Cardinality changed from * to 1',
'Claim.use', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/claim-use to http://hl7.org/fhir/ValueSet/claim-use|4.0.1',
'Claim.patient', 'Min Cardinality changed from 0 to 1',
'Claim.created', 'Min Cardinality changed from 0 to 1',
'Claim.enterer', 'Type Reference: Added Target Type PractitionerRole',
'Claim.provider', 'Min Cardinality changed from 0 to 1
        Type Reference: Added Target Types PractitionerRole, Organization',
'Claim.priority', 'Min Cardinality changed from 0 to 1',
'Claim.prescription', 'Type Reference: Added Target Type DeviceRequest',
'Claim.originalPrescription', 'Type Reference: Added Target Types DeviceRequest, VisionPrescription',
'Claim.payee.party', 'Type Reference: Added Target Type PractitionerRole',
'Claim.referral', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'Claim.careTeam.provider', 'Type Reference: Added Target Type PractitionerRole',
'Claim.supportingInfo', 'Renamed from information to supportingInfo',
'Claim.supportingInfo.sequence', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.category', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.code', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.timing[x]', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.value[x]', 'Moved from Claim.information to Claim.supportingInfo
        Add Type boolean',
'Claim.supportingInfo.reason', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.diagnosis.onAdmission', 'Added Element',
'Claim.procedure.type', 'Added Element',
'Claim.procedure.udi', 'Added Element',
'Claim.insurance', 'Min Cardinality changed from 0 to 1',
'Claim.insurance.identifier', 'Added Element',
'Claim.accident.type', 'Change binding strength from required to extensible',
'Claim.item.careTeamSequence', 'Renamed from careTeamLinkId to careTeamSequence',
'Claim.item.diagnosisSequence', 'Renamed from diagnosisLinkId to diagnosisSequence',
'Claim.item.procedureSequence', 'Renamed from procedureLinkId to procedureSequence',
'Claim.item.informationSequence', 'Renamed from informationLinkId to informationSequence',
'Claim.item.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.item.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.item.detail.subDetail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.organization', 'deleted',
'Claim.payee.resourceType', 'deleted',
'Claim.employmentImpacted', 'deleted',
'Claim.hospitalization', 'deleted',
)


df5 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Claim', 'TU', '', 'DomainResource', 'Claim, Pre-determination or Pre-authorizationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for claim',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorFinancial Resource Status Codes (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'Category or disciplineClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'billablePeriod', 'Σ', '0..1', 'Period', 'Relevant time frame for the claim',
'created', 'Σ', '1..1', 'dateTime', 'Resource creation date',
'enterer', '', '0..1', 'Reference(Practitioner | PractitionerRole)', 'Author of the claim',
'insurer', 'Σ', '0..1', 'Reference(Organization)', 'Target',
'provider', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'priority', 'Σ', '1..1', 'CodeableConcept', 'Desired processing ugencyProcess Priority Codes (Example)',
'fundsReserve', '', '0..1', 'CodeableConcept', 'For whom to reserve fundsFundsReserve (Example)',
'related', '', '0..*', 'BackboneElement', 'Prior or corollary claims',
'claim', '', '0..1', 'Reference(Claim)', 'Reference to the related claim',
'relationship', '', '0..1', 'CodeableConcept', 'How the reference claim is relatedExample Related Claim Relationship Codes (Example)',
'reference', '', '0..1', 'Identifier', 'File or case reference',
'prescription', '', '0..1', 'Reference(DeviceRequest | MedicationRequest | VisionPrescription)', 'Prescription authorizing services and products',
'originalPrescription', '', '0..1', 'Reference(DeviceRequest | MedicationRequest | VisionPrescription)', 'Original prescription if superseded by fulfiller',
'payee', '', '0..1', 'BackboneElement', 'Recipient of benefits payable',
'type', '', '1..1', 'CodeableConcept', 'Category of recipientPayeeType (Example)',
'party', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson)', 'Recipient reference',
'referral', '', '0..1', 'Reference(ServiceRequest)', 'Treatment referral',
'facility', '', '0..1', 'Reference(Location)', 'Servicing facility',
'careTeam', '', '0..*', 'BackboneElement', 'Members of the care team',
'sequence', '', '1..1', 'positiveInt', 'Order of care team',
'provider', '', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Practitioner or organization',
'responsible', '', '0..1', 'boolean', 'Indicator of the lead practitioner',
'role', '', '0..1', 'CodeableConcept', 'Function within the teamClaim Care Team Role Codes (Example)',
'qualification', '', '0..1', 'CodeableConcept', 'Practitioner credential or specializationExample Provider Qualification Codes (Example)',
'supportingInfo', '', '0..*', 'BackboneElement', 'Supporting information',
'sequence', '', '1..1', 'positiveInt', 'Information instance identifier',
'category', '', '1..1', 'CodeableConcept', 'Classification of the supplied informationClaim Information Category Codes (Example)',
'code', '', '0..1', 'CodeableConcept', 'Type of informationException Codes (Example)',
'timing[x]', '', '0..1', '', 'When it occurred',
'timingDate', '', '', 'date', '',
'timingPeriod', '', '', 'Period', '',
'value[x]', '', '0..1', '', 'Data to be provided',
'valueBoolean', '', '', 'boolean', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'Quantity', '',
'valueAttachment', '', '', 'Attachment', '',
'valueReference', '', '', 'Reference(Any)', '',
'reason', '', '0..1', 'CodeableConcept', 'Explanation for the informationMissing Tooth Reason Codes (Example)',
'diagnosis', '', '0..*', 'BackboneElement', 'Pertinent diagnosis information',
'sequence', '', '1..1', 'positiveInt', 'Diagnosis instance identifier',
'diagnosis[x]', '', '1..1', '', 'Nature of illness or problemICD-10 Codes (Example)',
'diagnosisCodeableConcept', '', '', 'CodeableConcept', '',
'diagnosisReference', '', '', 'Reference(Condition)', '',
'type', '', '0..*', 'CodeableConcept', 'Timing or nature of the diagnosisExample Diagnosis Type Codes (Example)',
'onAdmission', '', '0..1', 'CodeableConcept', 'Present on admissionExample Diagnosis on Admission Codes (Example)',
'packageCode', '', '0..1', 'CodeableConcept', 'Package billing codeExample Diagnosis Related Group Codes (Example)',
'procedure', '', '0..*', 'BackboneElement', 'Clinical procedures performed',
'sequence', '', '1..1', 'positiveInt', 'Procedure instance identifier',
'type', '', '0..*', 'CodeableConcept', 'Category of ProcedureExample Procedure Type Codes (Example)',
'date', '', '0..1', 'dateTime', 'When the procedure was performed',
'procedure[x]', '', '1..1', '', 'Specific clinical procedureICD-10 Procedure Codes (Example)',
'procedureCodeableConcept', '', '', 'CodeableConcept', '',
'procedureReference', '', '', 'Reference(Procedure)', '',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'insurance', 'Σ', '1..*', 'BackboneElement', 'Patient insurance information',
'sequence', 'Σ', '1..1', 'positiveInt', 'Insurance instance identifier',
'focal', 'Σ', '1..1', 'boolean', 'Coverage to be used for adjudication',
'identifier', '', '0..1', 'Identifier', 'Pre-assigned Claim number',
'coverage', 'Σ', '1..1', 'Reference(Coverage)', 'Insurance information',
'businessArrangement', '', '0..1', 'string', 'Additional provider contract number',
'preAuthRef', '', '0..*', 'string', 'Prior authorization reference number',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Adjudication results',
'accident', '', '0..1', 'BackboneElement', 'Details of the event',
'date', '', '1..1', 'date', 'When the incident occurred',
'type', '', '0..1', 'CodeableConcept', 'The nature of the accidentV3 Value SetActIncidentCode (Extensible)',
'location[x]', '', '0..1', '', 'Where the event occurred',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'item', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'careTeamSequence', '', '0..*', 'positiveInt', 'Applicable careTeam members',
'diagnosisSequence', '', '0..*', 'positiveInt', 'Applicable diagnoses',
'procedureSequence', '', '0..*', 'positiveInt', 'Applicable procedures',
'informationSequence', '', '0..*', 'positiveInt', 'Applicable exception and supporting information',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Product or service billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'encounter', '', '0..*', 'Reference(Encounter)', 'Encounters related to this billed item',
'detail', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'subDetail', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'total', '', '0..1', 'Money', 'Total claim cost',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,
'Claim', '',
'Claim.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/fm-status to http://hl7.org/fhir/ValueSet/fm-status|4.0.1',
'Claim.type', 'Min Cardinality changed from 0 to 1
        Change binding strength from required to extensible',
'Claim.subType', 'Max Cardinality changed from * to 1',
'Claim.use', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/claim-use to http://hl7.org/fhir/ValueSet/claim-use|4.0.1',
'Claim.patient', 'Min Cardinality changed from 0 to 1',
'Claim.created', 'Min Cardinality changed from 0 to 1',
'Claim.enterer', 'Type Reference: Added Target Type PractitionerRole',
'Claim.provider', 'Min Cardinality changed from 0 to 1
        Type Reference: Added Target Types PractitionerRole, Organization',
'Claim.priority', 'Min Cardinality changed from 0 to 1',
'Claim.prescription', 'Type Reference: Added Target Type DeviceRequest',
'Claim.originalPrescription', 'Type Reference: Added Target Types DeviceRequest, VisionPrescription',
'Claim.payee.party', 'Type Reference: Added Target Type PractitionerRole',
'Claim.referral', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'Claim.careTeam.provider', 'Type Reference: Added Target Type PractitionerRole',
'Claim.supportingInfo', 'Renamed from information to supportingInfo',
'Claim.supportingInfo.sequence', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.category', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.code', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.timing[x]', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.supportingInfo.value[x]', 'Moved from Claim.information to Claim.supportingInfo
        Add Type boolean',
'Claim.supportingInfo.reason', 'Moved from Claim.information to Claim.supportingInfo',
'Claim.diagnosis.onAdmission', 'Added Element',
'Claim.procedure.type', 'Added Element',
'Claim.procedure.udi', 'Added Element',
'Claim.insurance', 'Min Cardinality changed from 0 to 1',
'Claim.insurance.identifier', 'Added Element',
'Claim.accident.type', 'Change binding strength from required to extensible',
'Claim.item.careTeamSequence', 'Renamed from careTeamLinkId to careTeamSequence',
'Claim.item.diagnosisSequence', 'Renamed from diagnosisLinkId to diagnosisSequence',
'Claim.item.procedureSequence', 'Renamed from procedureLinkId to procedureSequence',
'Claim.item.informationSequence', 'Renamed from informationLinkId to informationSequence',
'Claim.item.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.item.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.item.detail.subDetail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'Claim.organization', 'deleted',
'Claim.payee.resourceType', 'deleted',
'Claim.employmentImpacted', 'deleted',
'Claim.hospitalization', 'deleted',
)


df7 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Claim.status', 'A code specifying the state of the resource instance.', 'Required', 'FinancialResourceStatusCodes',
'Claim.type', 'The type or discipline-style of the claim.', 'Extensible', 'ClaimTypeCodes',
'Claim.subType', 'A more granular claim typecode.', 'Example', 'ExampleClaimSubTypeCodes',
'Claim.use', 'The purpose of the Claim: predetermination, preauthorization, claim.', 'Required', 'Use',
'Claim.priority', 'The timeliness with which processing is required: stat, normal, deferred.', 'Example', 'ProcessPriorityCodes',
'Claim.fundsReserve', 'For whom funds are to be reserved: (Patient, Provider, None).', 'Example', 'Funds Reservation Codes',
'Claim.related.relationship', 'Relationship of this claim to a related Claim.', 'Example', 'ExampleRelatedClaimRelationshipCodes',
'Claim.payee.type', 'A code for the party to be reimbursed.', 'Example', 'Claim Payee Type Codes',
'Claim.careTeam.role', 'The role codes for the care team members.', 'Example', 'ClaimCareTeamRoleCodes',
'Claim.careTeam.qualification', 'Provider professional qualifications.', 'Example', 'ExampleProviderQualificationCodes',
'Claim.supportingInfo.category', 'The valuset used for additional information category codes.', 'Example', 'ClaimInformationCategoryCodes',
'Claim.supportingInfo.code', 'The valuset used for additional information codes.', 'Example', 'ExceptionCodes',
'Claim.supportingInfo.reason', 'Reason codes for the missing teeth.', 'Example', 'MissingToothReasonCodes',
'Claim.diagnosis.diagnosis[x]', 'Example ICD10 Diagnostic codes.', 'Example', 'ICD-10Codes',
'Claim.diagnosis.type', 'The type of the diagnosis: admitting, principal, discharge.', 'Example', 'ExampleDiagnosisTypeCodes',
'Claim.diagnosis.onAdmission', 'Present on admission.', 'Example', 'ExampleDiagnosisOnAdmissionCodes',
'Claim.diagnosis.packageCode', 'The DRG codes associated with the diagnosis.', 'Example', 'ExampleDiagnosisRelatedGroupCodes',
'Claim.procedure.type', 'Example procedure type codes.', 'Example', 'ExampleProcedureTypeCodes',
'Claim.procedure.procedure[x]', 'Example ICD10 Procedure codes.', 'Example', 'ICD-10ProcedureCodes',
'Claim.accident.type', 'Type of accident: work place, auto, etc.', 'Extensible', 'v3.ActIncidentCode',
'Claim.item.revenueClaim.item.detail.revenueClaim.item.detail.subDetail.revenue', 'Codes for the revenue or cost centers supplying the service and/or products.', 'Example', 'ExampleRevenueCenterCodes',
'Claim.item.categoryClaim.item.detail.categoryClaim.item.detail.subDetail.category', 'Benefit categories such as: oral-basic, major, glasses.', 'Example', 'BenefitCategoryCodes',
'Claim.item.productOrServiceClaim.item.detail.productOrServiceClaim.item.detail.subDetail.productOrService', 'Allowable service and product codes.', 'Example', 'USCLSCodes',
'Claim.item.modifierClaim.item.detail.modifierClaim.item.detail.subDetail.modifier', 'Item type or modifiers codes, eg for Oral whether the treatment is cosmetic or associated with TMJ, or an appliance was lost or stolen.', 'Example', 'ModifierTypeCodes',
'Claim.item.programCodeClaim.item.detail.programCodeClaim.item.detail.subDetail.programCode', 'Program specific reason codes.', 'Example', 'ExampleProgramReasonCodes',
'Claim.item.location[x]', 'Place of service: pharmacy, school, prison, etc.', 'Example', 'ExampleServicePlaceCodes',
'Claim.item.bodySite', 'The code for the teeth, quadrant, sextant and arch.', 'Example', 'OralSiteCodes',
'Claim.item.subSite', 'The code for the tooth surface and surface combinations.', 'Example', 'SurfaceCodes',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'care-team', 'reference', 'Member of the CareTeam', 'Claim.careTeam.provider(Practitioner, Organization, PractitionerRole)', '',
'created', 'date', 'The creation date for the Claim', 'Claim.created', '',
'detail-udi', 'reference', 'UDI associated with a line item, detail product or service', 'Claim.item.detail.udi(Device)', '',
'encounter', 'reference', 'Encounters associated with a billed line item', 'Claim.item.encounter(Encounter)', '',
'enterer', 'reference', 'The party responsible for the entry of the Claim', 'Claim.enterer(Practitioner, PractitionerRole)', '',
'facility', 'reference', 'Facility where the products or services have been or will be provided', 'Claim.facility(Location)', '',
'identifier', 'token', 'The primary identifier of the financial resource', 'Claim.identifier', '',
'insurer', 'reference', 'The target payor/insurer for the Claim', 'Claim.insurer(Organization)', '',
'item-udi', 'reference', 'UDI associated with a line item product or service', 'Claim.item.udi(Device)', '',
'patient', 'reference', 'Patient receiving the products or services', 'Claim.patient(Patient)', '',
'payee', 'reference', 'The party receiving any payment for the Claim', 'Claim.payee.party(Practitioner, Organization, Patient, PractitionerRole, RelatedPerson)', '',
'priority', 'token', 'Processing priority requested', 'Claim.priority', '',
'procedure-udi', 'reference', 'UDI associated with a procedure', 'Claim.procedure.udi(Device)', '',
'provider', 'reference', 'Provider responsible for the Claim', 'Claim.provider(Practitioner, Organization, PractitionerRole)', '',
'status', 'token', 'The status of the Claim instance.', 'Claim.status', '',
'subdetail-udi', 'reference', 'UDI associated with a line item, detail, subdetail product or service', 'Claim.item.detail.subDetail.udi(Device)', '',
'use', 'token', 'The kind of financial resource', 'Claim.use', '',
)


