df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Financial Management  Work Group', 'Maturity Level: 1', 'Trial Use', 'Security Category: Patient', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Contract', 'TU', '', 'DomainResource', 'Legal AgreementElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Contract number',
'url', '', '0..1', 'uri', 'Basal definition',
'version', 'Σ', '0..1', 'string', 'Business edition',
'status', '?!Σ', '0..1', 'code', 'amended | appended | cancelled | disputed | entered-in-error | executable | executed | negotiable | offered | policy | rejected | renewed | revoked | resolved | terminatedContract Resource Status Codes (Required)',
'legalState', '', '0..1', 'CodeableConcept', 'Negotiation statusContract Resource Legal State codes (Extensible)',
'instantiatesCanonical', '', '0..1', 'Reference(Contract)', 'Source Contract Definition',
'instantiatesUri', '', '0..1', 'uri', 'External Contract Definition',
'contentDerivative', '', '0..1', 'CodeableConcept', 'Content derived from the basal informationContract Content Derivation Codes (Example)',
'issued', 'Σ', '0..1', 'dateTime', 'When this Contract was issued',
'applies', 'Σ', '0..1', 'Period', 'Effective time',
'expirationType', '', '0..1', 'CodeableConcept', 'Contract cessation causeContract Resource Expiration Type codes (Example)',
'subject', 'Σ', '0..*', 'Reference(Any)', 'Contract Target Entity',
'authority', '', '0..*', 'Reference(Organization)', 'Authority under which this Contract has standing',
'domain', '', '0..*', 'Reference(Location)', 'A sphere of control governed by an authoritative jurisdiction, organization, or person',
'site', '', '0..*', 'Reference(Location)', 'Specific Location',
'name', 'Σ', '0..1', 'string', 'Computer friendly designation',
'title', 'Σ', '0..1', 'string', 'Human Friendly name',
'subtitle', '', '0..1', 'string', 'Subordinate Friendly name',
'alias', '', '0..*', 'string', 'Acronym or short name',
'author', '', '0..1', 'Reference(Patient | Practitioner | PractitionerRole | Organization)', 'Source of Contract',
'scope', '', '0..1', 'CodeableConcept', 'Range of Legal ConcernsContract Resource Scope codes (Example)',
'topic[x]', '', '0..1', '', 'Focus of contract interest',
'topicCodeableConcept', '', '', 'CodeableConcept', '',
'topicReference', '', '', 'Reference(Any)', '',
'type', 'Σ', '0..1', 'CodeableConcept', 'Legal instrument categoryContract Type Codes (Example)',
'subType', 'Σ', '0..*', 'CodeableConcept', 'Subtype within the context of typeContract Subtype Codes (Example)',
'contentDefinition', '', '0..1', 'BackboneElement', 'Contract precursor content',
'type', '', '1..1', 'CodeableConcept', 'Content structure and useContract Resource Definition Type codes (Example)',
'subType', '', '0..1', 'CodeableConcept', 'Detailed Content Type DefinitionContract Resource Definition Subtype codes (Example)',
'publisher', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Publisher Entity',
'publicationDate', '', '0..1', 'dateTime', 'When published',
'publicationStatus', '', '1..1', 'code', 'amended | appended | cancelled | disputed | entered-in-error | executable | executed | negotiable | offered | policy | rejected | renewed | revoked | resolved | terminatedContract Resource Publication Status codes (Required)',
'copyright', '', '0..1', 'markdown', 'Publication Ownership',
'term', '', '0..*', 'BackboneElement', 'Contract Term List',
'identifier', 'Σ', '0..1', 'Identifier', 'Contract Term Number',
'issued', 'Σ', '0..1', 'dateTime', 'Contract Term Issue Date Time',
'applies', 'Σ', '0..1', 'Period', 'Contract Term Effective Time',
'topic[x]', '', '0..1', '', 'Term Concern',
'topicCodeableConcept', '', '', 'CodeableConcept', '',
'topicReference', '', '', 'Reference(Any)', '',
'type', '', '0..1', 'CodeableConcept', 'Contract Term Type or FormContract Term Type Codes (Example)',
'subType', '', '0..1', 'CodeableConcept', 'Contract Term Type specific classificationContract Term Subtype Codes (Example)',
'text', 'Σ', '0..1', 'string', 'Term Statement',
'securityLabel', '', '0..*', 'BackboneElement', 'Protection for the Term',
'number', '', '0..*', 'unsignedInt', 'Link to Security Labels',
'classification', '', '1..1', 'Coding', 'Confidentiality ProtectionContract Resource Scope codes (Example)',
'category', '', '0..*', 'Coding', 'Applicable PolicyContract Resource Scope codes (Example)',
'control', '', '0..*', 'Coding', 'Handling InstructionsContract Resource Security Control codes (Example)',
'offer', '', '1..1', 'BackboneElement', 'Context of the Contract term',
'identifier', '', '0..*', 'Identifier', 'Offer business ID',
'party', '', '0..*', 'BackboneElement', 'Offer Recipient',
'reference', '', '1..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Referenced entity',
'role', '', '1..1', 'CodeableConcept', 'Participant engagement typeContract Resource Party Role codes (Example)',
'topic', 'Σ', '0..1', 'Reference(Any)', 'Negotiable offer asset',
'type', '', '0..1', 'CodeableConcept', 'Contract Offer Type or FormContract Term Type Codes (Example)',
'decision', '', '0..1', 'CodeableConcept', 'Accepting party choiceV3 Value SetActConsentDirective (Extensible)',
'decisionMode', '', '0..*', 'CodeableConcept', 'How decision is conveyedContract Resource Decision Mode codes (Example)',
'answer', '', '0..*', 'BackboneElement', 'Response to offer text',
'value[x]', '', '1..1', '', 'The actual answer response',
'valueBoolean', '', '', 'boolean', '',
'valueDecimal', '', '', 'decimal', '',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueDateTime', '', '', 'dateTime', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueUri', '', '', 'uri', '',
'valueAttachment', '', '', 'Attachment', '',
'valueCoding', '', '', 'Coding', '',
'valueQuantity', '', '', 'Quantity', '',
'valueReference', '', '', 'Reference(Any)', '',
'text', '', '0..1', 'string', 'Human readable offer text',
'linkId', '', '0..*', 'string', 'Pointer to text',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Offer restriction numbers',
'asset', '', '0..*', 'BackboneElement', 'Contract Term Asset List',
'scope', '', '0..1', 'CodeableConcept', 'Range of assetContract Resource Asset Scope codes (Example)',
'type', '', '0..*', 'CodeableConcept', 'Asset categoryContract Resource Asset Type codes (Example)',
'typeReference', '', '0..*', 'Reference(Any)', 'Associated entities',
'subtype', '', '0..*', 'CodeableConcept', 'Asset sub-categoryContract Resource Asset Sub-Type codes (Example)',
'relationship', '', '0..1', 'Coding', 'Kinship of the assetConsent Content Class (Extensible)',
'context', '', '0..*', 'BackboneElement', 'Circumstance of the asset',
'reference', '', '0..1', 'Reference(Any)', 'Creator,custodian or owner',
'code', '', '0..*', 'CodeableConcept', 'Codeable asset contextContract Resource Asset Context codes (Example)',
'text', '', '0..1', 'string', 'Context description',
'condition', '', '0..1', 'string', 'Quality desctiption of asset',
'periodType', '', '0..*', 'CodeableConcept', 'Asset availability typesContract Resource Asset Availiability codes (Example)',
'period', '', '0..*', 'Period', 'Time period of the asset',
'usePeriod', '', '0..*', 'Period', 'Time period',
'text', '', '0..1', 'string', 'Asset clause or question text',
'linkId', '', '0..*', 'string', 'Pointer to asset text',
'answer', '', '0..*', 'see answer', 'Response to assets',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Asset restriction numbers',
'valuedItem', '', '0..*', 'BackboneElement', 'Contract Valued Item List',
'entity[x]', '', '0..1', '', 'Contract Valued Item Type',
'entityCodeableConcept', '', '', 'CodeableConcept', '',
'entityReference', '', '', 'Reference(Any)', '',
'identifier', '', '0..1', 'Identifier', 'Contract Valued Item Number',
'effectiveTime', '', '0..1', 'dateTime', 'Contract Valued Item Effective Tiem',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of Contract Valued Items',
'unitPrice', '', '0..1', 'Money', 'Contract Valued Item fee, charge, or cost',
'factor', '', '0..1', 'decimal', 'Contract Valued Item Price Scaling Factor',
'points', '', '0..1', 'decimal', 'Contract Valued Item Difficulty Scaling Factor',
'net', '', '0..1', 'Money', 'Total Contract Valued Item Value',
'payment', '', '0..1', 'string', 'Terms of valuation',
'paymentDate', '', '0..1', 'dateTime', 'When payment is due',
'responsible', '', '0..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Who will make payment',
'recipient', '', '0..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Who will receive payment',
'linkId', '', '0..*', 'string', 'Pointer to specific item',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Security Labels that define affected terms',
'action', '', '0..*', 'BackboneElement', 'Entity being ascribed responsibility',
'doNotPerform', '?!', '0..1', 'boolean', 'True if the term prohibits the  action',
'type', '', '1..1', 'CodeableConcept', 'Type or form of the actionContract Action Codes (Example)',
'subject', '', '0..*', 'BackboneElement', 'Entity of the action',
'reference', '', '1..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Entity of the action',
'role', '', '0..1', 'CodeableConcept', 'Role type of the agentContract Actor Role Codes (Example)',
'intent', '', '1..1', 'CodeableConcept', 'Purpose for the Contract Term ActionV3 Value SetPurposeOfUse (Example)',
'linkId', '', '0..*', 'string', 'Pointer to specific item',
'status', '', '1..1', 'CodeableConcept', 'State of the actionContract Resource Action Status codes (Example)',
'context', '', '0..1', 'Reference(Encounter | EpisodeOfCare)', 'Episode associated with action',
'contextLinkId', '', '0..*', 'string', 'Pointer to specific item',
'occurrence[x]', '', '0..1', '', 'When action happens',
'occurrenceDateTime', '', '', 'dateTime', '',
'occurrencePeriod', '', '', 'Period', '',
'occurrenceTiming', '', '', 'Timing', '',
'requester', '', '0..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Who asked for action',
'requesterLinkId', '', '0..*', 'string', 'Pointer to specific item',
'performerType', '', '0..*', 'CodeableConcept', 'Kind of service performerProvenance participant type (Example)',
'performerRole', '', '0..1', 'CodeableConcept', 'Competency of the performerProvenance participant role (Example)',
'performer', '', '0..1', 'Reference(RelatedPerson | Patient | Practitioner | PractitionerRole | CareTeam | Device | Substance | Organization | Location)', 'Actor that wil execute (or not) the action',
'performerLinkId', '', '0..*', 'string', 'Pointer to specific item',
'reasonCode', '', '0..*', 'CodeableConcept', 'Why is action (not) needed?V3 Value SetPurposeOfUse (Example)',
'reasonReference', '', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference | Questionnaire | QuestionnaireResponse)', 'Why is action (not) needed?',
'reason', '', '0..*', 'string', 'Why action is to be performed',
'reasonLinkId', '', '0..*', 'string', 'Pointer to specific item',
'note', '', '0..*', 'Annotation', 'Comments about the action',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Action restriction numbers',
'group', '', '0..*', 'see term', 'Nested Contract Term Group',
'supportingInfo', '', '0..*', 'Reference(Any)', 'Extra Information',
'relevantHistory', '', '0..*', 'Reference(Provenance)', 'Key event in Contract History',
'signer', '', '0..*', 'BackboneElement', 'Contract Signatory',
'type', '', '1..1', 'Coding', 'Contract Signatory RoleContract Signer Type Codes (Preferred)',
'party', '', '1..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Contract Signatory Party',
'signature', '', '1..*', 'Signature', 'Contract Documentation Signature',
'friendly', '', '0..*', 'BackboneElement', 'Contract Friendly Language',
'content[x]', '', '1..1', '', 'Easily comprehended representation of this Contract',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse)', '',
'legal', '', '0..*', 'BackboneElement', 'Contract Legal Language',
'content[x]', '', '1..1', '', 'Contract Legal Text',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse)', '',
'rule', '', '0..*', 'BackboneElement', 'Computable Contract Language',
'content[x]', '', '1..1', '', 'Computable Contract Rules',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(DocumentReference)', '',
'legallyBinding[x]', '', '0..1', '', 'Binding Contract',
'legallyBindingAttachment', '', '', 'Attachment', '',
'legallyBindingReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse | Contract)', '',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Contract', '',
'Contract.identifier', 'Max Cardinality changed from 1 to *',
'Contract.url', 'Added Element',
'Contract.version', 'Added Element',
'Contract.status', 'Change value set from http://hl7.org/fhir/ValueSet/contract-status to http://hl7.org/fhir/ValueSet/contract-status|4.0.1',
'Contract.legalState', 'Added Element',
'Contract.instantiatesCanonical', 'Added Element',
'Contract.instantiatesUri', 'Added Element',
'Contract.expirationType', 'Added Element',
'Contract.site', 'Added Element',
'Contract.name', 'Added Element',
'Contract.title', 'Added Element',
'Contract.subtitle', 'Added Element',
'Contract.alias', 'Added Element',
'Contract.author', 'Added Element',
'Contract.scope', 'Added Element',
'Contract.topic[x]', 'Renamed from topic to topic[x]
        Max Cardinality changed from * to 1
        Add Type CodeableConcept',
'Contract.contentDefinition', 'Added Element',
'Contract.contentDefinition.type', 'Added Mandatory Element',
'Contract.contentDefinition.subType', 'Added Element',
'Contract.contentDefinition.publisher', 'Added Element',
'Contract.contentDefinition.publicationDate', 'Added Element',
'Contract.contentDefinition.publicationStatus', 'Added Mandatory Element',
'Contract.contentDefinition.copyright', 'Added Element',
'Contract.term.topic[x]', 'Renamed from topic to topic[x]
        Max Cardinality changed from * to 1
        Add Type CodeableConcept',
'Contract.term.securityLabel', 'Type changed from Coding to BackboneElement
        
Remove Binding http://hl7.org/fhir/ValueSet/security-labels (extensible)',
'Contract.term.securityLabel.number', 'Added Element',
'Contract.term.securityLabel.classification', 'Added Mandatory Element',
'Contract.term.securityLabel.category', 'Added Element',
'Contract.term.securityLabel.control', 'Added Element',
'Contract.term.offer', 'Added Mandatory Element',
'Contract.term.offer.identifier', 'Added Element',
'Contract.term.offer.party', 'Added Element',
'Contract.term.offer.party.reference', 'Added Mandatory Element',
'Contract.term.offer.party.role', 'Added Mandatory Element',
'Contract.term.offer.topic', 'Added Element',
'Contract.term.offer.type', 'Added Element',
'Contract.term.offer.decision', 'Added Element',
'Contract.term.offer.decisionMode', 'Added Element',
'Contract.term.offer.answer', 'Added Element',
'Contract.term.offer.answer.value[x]', 'Added Mandatory Element',
'Contract.term.offer.text', 'Added Element',
'Contract.term.offer.linkId', 'Added Element',
'Contract.term.offer.securityLabelNumber', 'Added Element',
'Contract.term.asset', 'Added Element',
'Contract.term.asset.scope', 'Added Element',
'Contract.term.asset.type', 'Added Element',
'Contract.term.asset.typeReference', 'Added Element',
'Contract.term.asset.subtype', 'Added Element',
'Contract.term.asset.relationship', 'Added Element',
'Contract.term.asset.context', 'Added Element',
'Contract.term.asset.context.reference', 'Added Element',
'Contract.term.asset.context.code', 'Added Element',
'Contract.term.asset.context.text', 'Added Element',
'Contract.term.asset.condition', 'Added Element',
'Contract.term.asset.periodType', 'Added Element',
'Contract.term.asset.period', 'Added Element',
'Contract.term.asset.usePeriod', 'Added Element',
'Contract.term.asset.text', 'Added Element',
'Contract.term.asset.linkId', 'Added Element',
'Contract.term.asset.answer', 'Added Element',
'Contract.term.asset.securityLabelNumber', 'Added Element',
'Contract.term.asset.valuedItem', 'Added Element',
'Contract.term.asset.valuedItem.entity[x]', 'Added Element',
'Contract.term.asset.valuedItem.identifier', 'Added Element',
'Contract.term.asset.valuedItem.effectiveTime', 'Added Element',
'Contract.term.asset.valuedItem.quantity', 'Added Element',
'Contract.term.asset.valuedItem.unitPrice', 'Added Element',
'Contract.term.asset.valuedItem.factor', 'Added Element',
'Contract.term.asset.valuedItem.points', 'Added Element',
'Contract.term.asset.valuedItem.net', 'Added Element',
'Contract.term.asset.valuedItem.payment', 'Added Element',
'Contract.term.asset.valuedItem.paymentDate', 'Added Element',
'Contract.term.asset.valuedItem.responsible', 'Added Element',
'Contract.term.asset.valuedItem.recipient', 'Added Element',
'Contract.term.asset.valuedItem.linkId', 'Added Element',
'Contract.term.asset.valuedItem.securityLabelNumber', 'Added Element',
'Contract.term.action', 'Type changed from CodeableConcept to BackboneElement',
'Contract.term.action.doNotPerform', 'Added Element',
'Contract.term.action.type', 'Added Mandatory Element',
'Contract.term.action.subject', 'Added Element',
'Contract.term.action.subject.reference', 'Added Mandatory Element',
'Contract.term.action.subject.role', 'Added Element',
'Contract.term.action.intent', 'Added Mandatory Element',
'Contract.term.action.linkId', 'Added Element',
'Contract.term.action.status', 'Added Mandatory Element',
'Contract.term.action.context', 'Added Element',
'Contract.term.action.contextLinkId', 'Added Element',
'Contract.term.action.occurrence[x]', 'Added Element',
'Contract.term.action.requester', 'Added Element',
'Contract.term.action.requesterLinkId', 'Added Element',
'Contract.term.action.performerType', 'Added Element',
'Contract.term.action.performerRole', 'Added Element',
'Contract.term.action.performer', 'Added Element',
'Contract.term.action.performerLinkId', 'Added Element',
'Contract.term.action.reasonCode', 'Added Element',
'Contract.term.action.reasonReference', 'Added Element',
'Contract.term.action.reason', 'Added Element',
'Contract.term.action.reasonLinkId', 'Added Element',
'Contract.term.action.note', 'Added Element',
'Contract.term.action.securityLabelNumber', 'Added Element',
'Contract.supportingInfo', 'Added Element',
'Contract.relevantHistory', 'Added Element',
'Contract.signer.party', 'Type Reference: Added Target Type PractitionerRole',
'Contract.legallyBinding[x]', 'Added Element',
'Contract.action', 'deleted',
'Contract.actionReason', 'deleted',
'Contract.decisionType', 'deleted',
'Contract.securityLabel', 'deleted',
'Contract.agent', 'deleted',
'Contract.valuedItem', 'deleted',
'Contract.term.actionReason', 'deleted',
'Contract.term.agent', 'deleted',
'Contract.term.valuedItem', 'deleted',
'Contract.binding[x]', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Contract', 'TU', '', 'DomainResource', 'Legal AgreementElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Contract number',
'url', '', '0..1', 'uri', 'Basal definition',
'version', 'Σ', '0..1', 'string', 'Business edition',
'status', '?!Σ', '0..1', 'code', 'amended | appended | cancelled | disputed | entered-in-error | executable | executed | negotiable | offered | policy | rejected | renewed | revoked | resolved | terminatedContract Resource Status Codes (Required)',
'legalState', '', '0..1', 'CodeableConcept', 'Negotiation statusContract Resource Legal State codes (Extensible)',
'instantiatesCanonical', '', '0..1', 'Reference(Contract)', 'Source Contract Definition',
'instantiatesUri', '', '0..1', 'uri', 'External Contract Definition',
'contentDerivative', '', '0..1', 'CodeableConcept', 'Content derived from the basal informationContract Content Derivation Codes (Example)',
'issued', 'Σ', '0..1', 'dateTime', 'When this Contract was issued',
'applies', 'Σ', '0..1', 'Period', 'Effective time',
'expirationType', '', '0..1', 'CodeableConcept', 'Contract cessation causeContract Resource Expiration Type codes (Example)',
'subject', 'Σ', '0..*', 'Reference(Any)', 'Contract Target Entity',
'authority', '', '0..*', 'Reference(Organization)', 'Authority under which this Contract has standing',
'domain', '', '0..*', 'Reference(Location)', 'A sphere of control governed by an authoritative jurisdiction, organization, or person',
'site', '', '0..*', 'Reference(Location)', 'Specific Location',
'name', 'Σ', '0..1', 'string', 'Computer friendly designation',
'title', 'Σ', '0..1', 'string', 'Human Friendly name',
'subtitle', '', '0..1', 'string', 'Subordinate Friendly name',
'alias', '', '0..*', 'string', 'Acronym or short name',
'author', '', '0..1', 'Reference(Patient | Practitioner | PractitionerRole | Organization)', 'Source of Contract',
'scope', '', '0..1', 'CodeableConcept', 'Range of Legal ConcernsContract Resource Scope codes (Example)',
'topic[x]', '', '0..1', '', 'Focus of contract interest',
'topicCodeableConcept', '', '', 'CodeableConcept', '',
'topicReference', '', '', 'Reference(Any)', '',
'type', 'Σ', '0..1', 'CodeableConcept', 'Legal instrument categoryContract Type Codes (Example)',
'subType', 'Σ', '0..*', 'CodeableConcept', 'Subtype within the context of typeContract Subtype Codes (Example)',
'contentDefinition', '', '0..1', 'BackboneElement', 'Contract precursor content',
'type', '', '1..1', 'CodeableConcept', 'Content structure and useContract Resource Definition Type codes (Example)',
'subType', '', '0..1', 'CodeableConcept', 'Detailed Content Type DefinitionContract Resource Definition Subtype codes (Example)',
'publisher', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Publisher Entity',
'publicationDate', '', '0..1', 'dateTime', 'When published',
'publicationStatus', '', '1..1', 'code', 'amended | appended | cancelled | disputed | entered-in-error | executable | executed | negotiable | offered | policy | rejected | renewed | revoked | resolved | terminatedContract Resource Publication Status codes (Required)',
'copyright', '', '0..1', 'markdown', 'Publication Ownership',
'term', '', '0..*', 'BackboneElement', 'Contract Term List',
'identifier', 'Σ', '0..1', 'Identifier', 'Contract Term Number',
'issued', 'Σ', '0..1', 'dateTime', 'Contract Term Issue Date Time',
'applies', 'Σ', '0..1', 'Period', 'Contract Term Effective Time',
'topic[x]', '', '0..1', '', 'Term Concern',
'topicCodeableConcept', '', '', 'CodeableConcept', '',
'topicReference', '', '', 'Reference(Any)', '',
'type', '', '0..1', 'CodeableConcept', 'Contract Term Type or FormContract Term Type Codes (Example)',
'subType', '', '0..1', 'CodeableConcept', 'Contract Term Type specific classificationContract Term Subtype Codes (Example)',
'text', 'Σ', '0..1', 'string', 'Term Statement',
'securityLabel', '', '0..*', 'BackboneElement', 'Protection for the Term',
'number', '', '0..*', 'unsignedInt', 'Link to Security Labels',
'classification', '', '1..1', 'Coding', 'Confidentiality ProtectionContract Resource Scope codes (Example)',
'category', '', '0..*', 'Coding', 'Applicable PolicyContract Resource Scope codes (Example)',
'control', '', '0..*', 'Coding', 'Handling InstructionsContract Resource Security Control codes (Example)',
'offer', '', '1..1', 'BackboneElement', 'Context of the Contract term',
'identifier', '', '0..*', 'Identifier', 'Offer business ID',
'party', '', '0..*', 'BackboneElement', 'Offer Recipient',
'reference', '', '1..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Referenced entity',
'role', '', '1..1', 'CodeableConcept', 'Participant engagement typeContract Resource Party Role codes (Example)',
'topic', 'Σ', '0..1', 'Reference(Any)', 'Negotiable offer asset',
'type', '', '0..1', 'CodeableConcept', 'Contract Offer Type or FormContract Term Type Codes (Example)',
'decision', '', '0..1', 'CodeableConcept', 'Accepting party choiceV3 Value SetActConsentDirective (Extensible)',
'decisionMode', '', '0..*', 'CodeableConcept', 'How decision is conveyedContract Resource Decision Mode codes (Example)',
'answer', '', '0..*', 'BackboneElement', 'Response to offer text',
'value[x]', '', '1..1', '', 'The actual answer response',
'valueBoolean', '', '', 'boolean', '',
'valueDecimal', '', '', 'decimal', '',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueDateTime', '', '', 'dateTime', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueUri', '', '', 'uri', '',
'valueAttachment', '', '', 'Attachment', '',
'valueCoding', '', '', 'Coding', '',
'valueQuantity', '', '', 'Quantity', '',
'valueReference', '', '', 'Reference(Any)', '',
'text', '', '0..1', 'string', 'Human readable offer text',
'linkId', '', '0..*', 'string', 'Pointer to text',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Offer restriction numbers',
'asset', '', '0..*', 'BackboneElement', 'Contract Term Asset List',
'scope', '', '0..1', 'CodeableConcept', 'Range of assetContract Resource Asset Scope codes (Example)',
'type', '', '0..*', 'CodeableConcept', 'Asset categoryContract Resource Asset Type codes (Example)',
'typeReference', '', '0..*', 'Reference(Any)', 'Associated entities',
'subtype', '', '0..*', 'CodeableConcept', 'Asset sub-categoryContract Resource Asset Sub-Type codes (Example)',
'relationship', '', '0..1', 'Coding', 'Kinship of the assetConsent Content Class (Extensible)',
'context', '', '0..*', 'BackboneElement', 'Circumstance of the asset',
'reference', '', '0..1', 'Reference(Any)', 'Creator,custodian or owner',
'code', '', '0..*', 'CodeableConcept', 'Codeable asset contextContract Resource Asset Context codes (Example)',
'text', '', '0..1', 'string', 'Context description',
'condition', '', '0..1', 'string', 'Quality desctiption of asset',
'periodType', '', '0..*', 'CodeableConcept', 'Asset availability typesContract Resource Asset Availiability codes (Example)',
'period', '', '0..*', 'Period', 'Time period of the asset',
'usePeriod', '', '0..*', 'Period', 'Time period',
'text', '', '0..1', 'string', 'Asset clause or question text',
'linkId', '', '0..*', 'string', 'Pointer to asset text',
'answer', '', '0..*', 'see answer', 'Response to assets',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Asset restriction numbers',
'valuedItem', '', '0..*', 'BackboneElement', 'Contract Valued Item List',
'entity[x]', '', '0..1', '', 'Contract Valued Item Type',
'entityCodeableConcept', '', '', 'CodeableConcept', '',
'entityReference', '', '', 'Reference(Any)', '',
'identifier', '', '0..1', 'Identifier', 'Contract Valued Item Number',
'effectiveTime', '', '0..1', 'dateTime', 'Contract Valued Item Effective Tiem',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of Contract Valued Items',
'unitPrice', '', '0..1', 'Money', 'Contract Valued Item fee, charge, or cost',
'factor', '', '0..1', 'decimal', 'Contract Valued Item Price Scaling Factor',
'points', '', '0..1', 'decimal', 'Contract Valued Item Difficulty Scaling Factor',
'net', '', '0..1', 'Money', 'Total Contract Valued Item Value',
'payment', '', '0..1', 'string', 'Terms of valuation',
'paymentDate', '', '0..1', 'dateTime', 'When payment is due',
'responsible', '', '0..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Who will make payment',
'recipient', '', '0..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Who will receive payment',
'linkId', '', '0..*', 'string', 'Pointer to specific item',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Security Labels that define affected terms',
'action', '', '0..*', 'BackboneElement', 'Entity being ascribed responsibility',
'doNotPerform', '?!', '0..1', 'boolean', 'True if the term prohibits the  action',
'type', '', '1..1', 'CodeableConcept', 'Type or form of the actionContract Action Codes (Example)',
'subject', '', '0..*', 'BackboneElement', 'Entity of the action',
'reference', '', '1..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Entity of the action',
'role', '', '0..1', 'CodeableConcept', 'Role type of the agentContract Actor Role Codes (Example)',
'intent', '', '1..1', 'CodeableConcept', 'Purpose for the Contract Term ActionV3 Value SetPurposeOfUse (Example)',
'linkId', '', '0..*', 'string', 'Pointer to specific item',
'status', '', '1..1', 'CodeableConcept', 'State of the actionContract Resource Action Status codes (Example)',
'context', '', '0..1', 'Reference(Encounter | EpisodeOfCare)', 'Episode associated with action',
'contextLinkId', '', '0..*', 'string', 'Pointer to specific item',
'occurrence[x]', '', '0..1', '', 'When action happens',
'occurrenceDateTime', '', '', 'dateTime', '',
'occurrencePeriod', '', '', 'Period', '',
'occurrenceTiming', '', '', 'Timing', '',
'requester', '', '0..*', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Group | Organization)', 'Who asked for action',
'requesterLinkId', '', '0..*', 'string', 'Pointer to specific item',
'performerType', '', '0..*', 'CodeableConcept', 'Kind of service performerProvenance participant type (Example)',
'performerRole', '', '0..1', 'CodeableConcept', 'Competency of the performerProvenance participant role (Example)',
'performer', '', '0..1', 'Reference(RelatedPerson | Patient | Practitioner | PractitionerRole | CareTeam | Device | Substance | Organization | Location)', 'Actor that wil execute (or not) the action',
'performerLinkId', '', '0..*', 'string', 'Pointer to specific item',
'reasonCode', '', '0..*', 'CodeableConcept', 'Why is action (not) needed?V3 Value SetPurposeOfUse (Example)',
'reasonReference', '', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference | Questionnaire | QuestionnaireResponse)', 'Why is action (not) needed?',
'reason', '', '0..*', 'string', 'Why action is to be performed',
'reasonLinkId', '', '0..*', 'string', 'Pointer to specific item',
'note', '', '0..*', 'Annotation', 'Comments about the action',
'securityLabelNumber', '', '0..*', 'unsignedInt', 'Action restriction numbers',
'group', '', '0..*', 'see term', 'Nested Contract Term Group',
'supportingInfo', '', '0..*', 'Reference(Any)', 'Extra Information',
'relevantHistory', '', '0..*', 'Reference(Provenance)', 'Key event in Contract History',
'signer', '', '0..*', 'BackboneElement', 'Contract Signatory',
'type', '', '1..1', 'Coding', 'Contract Signatory RoleContract Signer Type Codes (Preferred)',
'party', '', '1..1', 'Reference(Organization | Patient | Practitioner | PractitionerRole | RelatedPerson)', 'Contract Signatory Party',
'signature', '', '1..*', 'Signature', 'Contract Documentation Signature',
'friendly', '', '0..*', 'BackboneElement', 'Contract Friendly Language',
'content[x]', '', '1..1', '', 'Easily comprehended representation of this Contract',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse)', '',
'legal', '', '0..*', 'BackboneElement', 'Contract Legal Language',
'content[x]', '', '1..1', '', 'Contract Legal Text',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse)', '',
'rule', '', '0..*', 'BackboneElement', 'Computable Contract Language',
'content[x]', '', '1..1', '', 'Computable Contract Rules',
'contentAttachment', '', '', 'Attachment', '',
'contentReference', '', '', 'Reference(DocumentReference)', '',
'legallyBinding[x]', '', '0..1', '', 'Binding Contract',
'legallyBindingAttachment', '', '', 'Attachment', '',
'legallyBindingReference', '', '', 'Reference(Composition | DocumentReference | QuestionnaireResponse | Contract)', '',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Contract', '',
'Contract.identifier', 'Max Cardinality changed from 1 to *',
'Contract.url', 'Added Element',
'Contract.version', 'Added Element',
'Contract.status', 'Change value set from http://hl7.org/fhir/ValueSet/contract-status to http://hl7.org/fhir/ValueSet/contract-status|4.0.1',
'Contract.legalState', 'Added Element',
'Contract.instantiatesCanonical', 'Added Element',
'Contract.instantiatesUri', 'Added Element',
'Contract.expirationType', 'Added Element',
'Contract.site', 'Added Element',
'Contract.name', 'Added Element',
'Contract.title', 'Added Element',
'Contract.subtitle', 'Added Element',
'Contract.alias', 'Added Element',
'Contract.author', 'Added Element',
'Contract.scope', 'Added Element',
'Contract.topic[x]', 'Renamed from topic to topic[x]
        Max Cardinality changed from * to 1
        Add Type CodeableConcept',
'Contract.contentDefinition', 'Added Element',
'Contract.contentDefinition.type', 'Added Mandatory Element',
'Contract.contentDefinition.subType', 'Added Element',
'Contract.contentDefinition.publisher', 'Added Element',
'Contract.contentDefinition.publicationDate', 'Added Element',
'Contract.contentDefinition.publicationStatus', 'Added Mandatory Element',
'Contract.contentDefinition.copyright', 'Added Element',
'Contract.term.topic[x]', 'Renamed from topic to topic[x]
        Max Cardinality changed from * to 1
        Add Type CodeableConcept',
'Contract.term.securityLabel', 'Type changed from Coding to BackboneElement
        
Remove Binding http://hl7.org/fhir/ValueSet/security-labels (extensible)',
'Contract.term.securityLabel.number', 'Added Element',
'Contract.term.securityLabel.classification', 'Added Mandatory Element',
'Contract.term.securityLabel.category', 'Added Element',
'Contract.term.securityLabel.control', 'Added Element',
'Contract.term.offer', 'Added Mandatory Element',
'Contract.term.offer.identifier', 'Added Element',
'Contract.term.offer.party', 'Added Element',
'Contract.term.offer.party.reference', 'Added Mandatory Element',
'Contract.term.offer.party.role', 'Added Mandatory Element',
'Contract.term.offer.topic', 'Added Element',
'Contract.term.offer.type', 'Added Element',
'Contract.term.offer.decision', 'Added Element',
'Contract.term.offer.decisionMode', 'Added Element',
'Contract.term.offer.answer', 'Added Element',
'Contract.term.offer.answer.value[x]', 'Added Mandatory Element',
'Contract.term.offer.text', 'Added Element',
'Contract.term.offer.linkId', 'Added Element',
'Contract.term.offer.securityLabelNumber', 'Added Element',
'Contract.term.asset', 'Added Element',
'Contract.term.asset.scope', 'Added Element',
'Contract.term.asset.type', 'Added Element',
'Contract.term.asset.typeReference', 'Added Element',
'Contract.term.asset.subtype', 'Added Element',
'Contract.term.asset.relationship', 'Added Element',
'Contract.term.asset.context', 'Added Element',
'Contract.term.asset.context.reference', 'Added Element',
'Contract.term.asset.context.code', 'Added Element',
'Contract.term.asset.context.text', 'Added Element',
'Contract.term.asset.condition', 'Added Element',
'Contract.term.asset.periodType', 'Added Element',
'Contract.term.asset.period', 'Added Element',
'Contract.term.asset.usePeriod', 'Added Element',
'Contract.term.asset.text', 'Added Element',
'Contract.term.asset.linkId', 'Added Element',
'Contract.term.asset.answer', 'Added Element',
'Contract.term.asset.securityLabelNumber', 'Added Element',
'Contract.term.asset.valuedItem', 'Added Element',
'Contract.term.asset.valuedItem.entity[x]', 'Added Element',
'Contract.term.asset.valuedItem.identifier', 'Added Element',
'Contract.term.asset.valuedItem.effectiveTime', 'Added Element',
'Contract.term.asset.valuedItem.quantity', 'Added Element',
'Contract.term.asset.valuedItem.unitPrice', 'Added Element',
'Contract.term.asset.valuedItem.factor', 'Added Element',
'Contract.term.asset.valuedItem.points', 'Added Element',
'Contract.term.asset.valuedItem.net', 'Added Element',
'Contract.term.asset.valuedItem.payment', 'Added Element',
'Contract.term.asset.valuedItem.paymentDate', 'Added Element',
'Contract.term.asset.valuedItem.responsible', 'Added Element',
'Contract.term.asset.valuedItem.recipient', 'Added Element',
'Contract.term.asset.valuedItem.linkId', 'Added Element',
'Contract.term.asset.valuedItem.securityLabelNumber', 'Added Element',
'Contract.term.action', 'Type changed from CodeableConcept to BackboneElement',
'Contract.term.action.doNotPerform', 'Added Element',
'Contract.term.action.type', 'Added Mandatory Element',
'Contract.term.action.subject', 'Added Element',
'Contract.term.action.subject.reference', 'Added Mandatory Element',
'Contract.term.action.subject.role', 'Added Element',
'Contract.term.action.intent', 'Added Mandatory Element',
'Contract.term.action.linkId', 'Added Element',
'Contract.term.action.status', 'Added Mandatory Element',
'Contract.term.action.context', 'Added Element',
'Contract.term.action.contextLinkId', 'Added Element',
'Contract.term.action.occurrence[x]', 'Added Element',
'Contract.term.action.requester', 'Added Element',
'Contract.term.action.requesterLinkId', 'Added Element',
'Contract.term.action.performerType', 'Added Element',
'Contract.term.action.performerRole', 'Added Element',
'Contract.term.action.performer', 'Added Element',
'Contract.term.action.performerLinkId', 'Added Element',
'Contract.term.action.reasonCode', 'Added Element',
'Contract.term.action.reasonReference', 'Added Element',
'Contract.term.action.reason', 'Added Element',
'Contract.term.action.reasonLinkId', 'Added Element',
'Contract.term.action.note', 'Added Element',
'Contract.term.action.securityLabelNumber', 'Added Element',
'Contract.supportingInfo', 'Added Element',
'Contract.relevantHistory', 'Added Element',
'Contract.signer.party', 'Type Reference: Added Target Type PractitionerRole',
'Contract.legallyBinding[x]', 'Added Element',
'Contract.action', 'deleted',
'Contract.actionReason', 'deleted',
'Contract.decisionType', 'deleted',
'Contract.securityLabel', 'deleted',
'Contract.agent', 'deleted',
'Contract.valuedItem', 'deleted',
'Contract.term.actionReason', 'deleted',
'Contract.term.agent', 'deleted',
'Contract.term.valuedItem', 'deleted',
'Contract.binding[x]', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Contract.status', 'A code specifying the state of the resource instance.', 'Required', 'ContractResourceStatusCodes',
'Contract.legalState', 'Detailed codes for the legal state of a contract.', 'Extensible', 'ContractResourceLegalStateCodes',
'Contract.contentDerivative', 'This is an example set of Content Derivative type codes, which represent the minimal content derived from the basal information source.', 'Example', 'ContractContentDerivationCodes',
'Contract.expirationType', 'Codes for the Cessation of Contracts.', 'Example', 'ContractResourceExpirationTypeCodes',
'Contract.scope', 'Codes for the range of legal concerns.', 'Example', 'ContractResourceScopeCodes',
'Contract.type', 'List of overall contract codes.', 'Example', 'ContractTypeCodes',
'Contract.subType', 'Detailed codes within the above.', 'Example', 'ContractSubtypeCodes',
'Contract.contentDefinition.type', 'Detailed codes for the definition of contracts.', 'Example', 'ContractResourceDefinitionTypeCodes',
'Contract.contentDefinition.subType', 'Detailed codes for the additional definition of contracts.', 'Example', 'ContractResourceDefinitionSubtypeCodes',
'Contract.contentDefinition.publicationStatus', 'Status of the publication of contract content.', 'Required', 'ContractResourcePublicationStatusCodes',
'Contract.term.typeContract.term.offer.type', 'Detailed codes for the types of contract provisions.', 'Example', 'ContractTermTypeCodes',
'Contract.term.subType', 'Detailed codes for the subtypes of contract provisions.', 'Example', 'ContractTermSubtypeCodes',
'Contract.term.securityLabel.classification', 'Codes for confidentiality protection.', 'Example', 'ContractResourceScopeCodes',
'Contract.term.securityLabel.category', 'Codes for policy category.', 'Example', 'ContractResourceScopeCodes',
'Contract.term.securityLabel.control', 'Codes for handling instructions.', 'Example', 'ContractResourceSecurityControlCodes',
'Contract.term.offer.party.role', 'Codes for offer participant roles.', 'Example', 'ContractResourcePartyRoleCodes',
'Contract.term.offer.decision', 'The type of decision made by a grantor with respect to an offer made by a grantee.', 'Extensible', 'v3.ActConsentDirective',
'Contract.term.offer.decisionMode', 'Codes for conveying a decision.', 'Example', 'ContractResourceDecisionModeCodes',
'Contract.term.asset.scope', 'Codes for scoping an asset.', 'Example', 'ContractResourceAssetScopeCodes',
'Contract.term.asset.type', 'Condes for the type of an asset.', 'Example', 'ContractResourceAssetTypeCodes',
'Contract.term.asset.subtype', 'Condes for the sub-type of an asset.', 'Example', 'ContractResourceAssetSub-TypeCodes',
'Contract.term.asset.relationship', 'The class (type) of information a consent rule covers.', 'Extensible', 'ConsentContentClass',
'Contract.term.asset.context.code', 'Codes for the context of the asset.', 'Example', 'ContractResourceAssetContextCodes',
'Contract.term.asset.periodType', 'Codes for asset availability.', 'Example', 'ContractResourceAssetAvailiabilityCodes',
'Contract.term.action.type', 'Detailed codes for the contract action.', 'Example', 'ContractActionCodes',
'Contract.term.action.subject.role', 'Detailed codes for the contract actor role.', 'Example', 'ContractActorRoleCodes',
'Contract.term.action.intentContract.term.action.reasonCode', 'Detailed codes for the contract action reason.', 'Example', 'v3.PurposeOfUse',
'Contract.term.action.status', 'Codes for the status of an term action.', 'Example', 'ContractResourceActionStatusCodes',
'Contract.term.action.performerType', 'Codes for the types of action perfomer.', 'Example', 'ProvenanceParticipantType',
'Contract.term.action.performerRole', 'Codes for the role of the action performer.', 'Example', 'ProvenanceParticipantRole',
'Contract.signer.type', 'List of parties who may be signing.', 'Preferred', 'ContractSignerTypeCodes',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'authority', 'reference', 'The authority of the contract', 'Contract.authority(Organization)', '',
'domain', 'reference', 'The domain of the contract', 'Contract.domain(Location)', '',
'identifier', 'token', 'The identity of the contract', 'Contract.identifier', '',
'instantiates', 'uri', 'A source definition of the contract', 'Contract.instantiatesUri', '',
'issued', 'date', 'The date/time the contract was issued', 'Contract.issued', '',
'patient', 'reference', 'The identity of the subject of the contract (if a patient)', 'Contract.subject.where(resolve() is Patient)(Patient)', '',
'signer', 'reference', 'Contract Signatory Party', 'Contract.signer.party(Practitioner, Organization, Patient, PractitionerRole, RelatedPerson)', '',
'status', 'token', 'The status of the contract', 'Contract.status', '',
'subject', 'reference', 'The identity of the subject of the contract', 'Contract.subject(Any)', '',
'url', 'uri', 'The basal contract definition', 'Contract.url', '',
)


