df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Orders and Observations  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Device', 'TU', '', 'DomainResource', 'Item used in healthcareElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Instance identifier',
'definition', '', '0..1', 'Reference(DeviceDefinition)', 'The reference to the definition for the device',
'udiCarrier', 'Σ', '0..*', 'BackboneElement', 'Unique Device Identifier (UDI) Barcode string',
'deviceIdentifier', 'Σ', '0..1', 'string', 'Mandatory fixed portion of UDI',
'issuer', '', '0..1', 'uri', 'UDI Issuing Organization',
'jurisdiction', '', '0..1', 'uri', 'Regional UDI authority',
'carrierAIDC', 'Σ', '0..1', 'base64Binary', 'UDI Machine Readable Barcode String',
'carrierHRF', 'Σ', '0..1', 'string', 'UDI Human Readable Barcode String',
'entryType', '', '0..1', 'code', 'barcode | rfid | manual +UDIEntryType (Required)',
'status', '?!Σ', '0..1', 'code', 'active | inactive | entered-in-error | unknownFHIRDeviceStatus (Required)',
'statusReason', '', '0..*', 'CodeableConcept', 'online | paused | standby | offline | not-ready | transduc-discon | hw-discon | offFHIRDeviceStatusReason (Extensible)',
'distinctIdentifier', '', '0..1', 'string', 'The distinct identification string',
'manufacturer', '', '0..1', 'string', 'Name of device manufacturer',
'manufactureDate', '', '0..1', 'dateTime', 'Date when the device was made',
'expirationDate', '', '0..1', 'dateTime', 'Date and time of expiry of this device (if applicable)',
'lotNumber', '', '0..1', 'string', 'Lot number of manufacture',
'serialNumber', '', '0..1', 'string', 'Serial number assigned by the manufacturer',
'deviceName', '', '0..*', 'BackboneElement', 'The name of the device as given by the manufacturer',
'name', '', '1..1', 'string', 'The name of the device',
'type', '', '1..1', 'code', 'udi-label-name | user-friendly-name | patient-reported-name | manufacturer-name | model-name | otherDeviceNameType (Required)',
'modelNumber', '', '0..1', 'string', 'The model number for the device',
'partNumber', '', '0..1', 'string', 'The part number of the device',
'type', '', '0..1', 'CodeableConcept', 'The kind or type of deviceDevice Type (Example)',
'specialization', '', '0..*', 'BackboneElement', 'The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication',
'systemType', '', '1..1', 'CodeableConcept', 'The standard that is used to operate and communicate',
'version', '', '0..1', 'string', 'The version of the standard that is used to operate and communicate',
'version', '', '0..*', 'BackboneElement', 'The actual design of the device or software version running on the device',
'type', '', '0..1', 'CodeableConcept', 'The type of the device version',
'component', '', '0..1', 'Identifier', 'A single component of the device version',
'value', '', '1..1', 'string', 'The version text',
'property', '', '0..*', 'BackboneElement', 'The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties',
'type', '', '1..1', 'CodeableConcept', 'Code that specifies the property DeviceDefinitionPropetyCode (Extensible)',
'valueQuantity', '', '0..*', 'Quantity', 'Property value as a quantity',
'valueCode', '', '0..*', 'CodeableConcept', 'Property value as a code, e.g., NTP4 (synced to NTP)',
'patient', '', '0..1', 'Reference(Patient)', 'Patient to whom Device is affixed',
'owner', '', '0..1', 'Reference(Organization)', 'Organization responsible for device',
'contact', '', '0..*', 'ContactPoint', 'Details for human/organization for support',
'location', '', '0..1', 'Reference(Location)', 'Where the device is found',
'url', '', '0..1', 'uri', 'Network address to contact device',
'note', '', '0..*', 'Annotation', 'Device notes and comments',
'safety', 'Σ', '0..*', 'CodeableConcept', 'Safety Characteristics of Device',
'parent', '', '0..1', 'Reference(Device)', 'The parent device',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Device', '',
'Device.definition', 'Added Element',
'Device.udiCarrier', 'Added Element',
'Device.udiCarrier.deviceIdentifier', 'Added Element',
'Device.udiCarrier.issuer', 'Added Element',
'Device.udiCarrier.jurisdiction', 'Added Element',
'Device.udiCarrier.carrierAIDC', 'Added Element',
'Device.udiCarrier.carrierHRF', 'Added Element',
'Device.udiCarrier.entryType', 'Added Element',
'Device.status', 'Change value set from http://hl7.org/fhir/ValueSet/device-status to http://hl7.org/fhir/ValueSet/device-status|4.0.1',
'Device.statusReason', 'Added Element',
'Device.distinctIdentifier', 'Added Element',
'Device.serialNumber', 'Added Element',
'Device.deviceName', 'Added Element',
'Device.deviceName.name', 'Added Mandatory Element',
'Device.deviceName.type', 'Added Mandatory Element',
'Device.modelNumber', 'Added Element',
'Device.partNumber', 'Added Element',
'Device.specialization', 'Added Element',
'Device.specialization.systemType', 'Added Mandatory Element',
'Device.specialization.version', 'Added Element',
'Device.version', 'Max Cardinality changed from 1 to *
        Type changed from string to BackboneElement',
'Device.version.type', 'Added Element',
'Device.version.component', 'Added Element',
'Device.version.value', 'Added Mandatory Element',
'Device.property', 'Added Element',
'Device.property.type', 'Added Mandatory Element',
'Device.property.valueQuantity', 'Added Element',
'Device.property.valueCode', 'Added Element',
'Device.parent', 'Added Element',
'Device.udi', 'deleted',
'Device.model', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Device', 'TU', '', 'DomainResource', 'Item used in healthcareElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Instance identifier',
'definition', '', '0..1', 'Reference(DeviceDefinition)', 'The reference to the definition for the device',
'udiCarrier', 'Σ', '0..*', 'BackboneElement', 'Unique Device Identifier (UDI) Barcode string',
'deviceIdentifier', 'Σ', '0..1', 'string', 'Mandatory fixed portion of UDI',
'issuer', '', '0..1', 'uri', 'UDI Issuing Organization',
'jurisdiction', '', '0..1', 'uri', 'Regional UDI authority',
'carrierAIDC', 'Σ', '0..1', 'base64Binary', 'UDI Machine Readable Barcode String',
'carrierHRF', 'Σ', '0..1', 'string', 'UDI Human Readable Barcode String',
'entryType', '', '0..1', 'code', 'barcode | rfid | manual +UDIEntryType (Required)',
'status', '?!Σ', '0..1', 'code', 'active | inactive | entered-in-error | unknownFHIRDeviceStatus (Required)',
'statusReason', '', '0..*', 'CodeableConcept', 'online | paused | standby | offline | not-ready | transduc-discon | hw-discon | offFHIRDeviceStatusReason (Extensible)',
'distinctIdentifier', '', '0..1', 'string', 'The distinct identification string',
'manufacturer', '', '0..1', 'string', 'Name of device manufacturer',
'manufactureDate', '', '0..1', 'dateTime', 'Date when the device was made',
'expirationDate', '', '0..1', 'dateTime', 'Date and time of expiry of this device (if applicable)',
'lotNumber', '', '0..1', 'string', 'Lot number of manufacture',
'serialNumber', '', '0..1', 'string', 'Serial number assigned by the manufacturer',
'deviceName', '', '0..*', 'BackboneElement', 'The name of the device as given by the manufacturer',
'name', '', '1..1', 'string', 'The name of the device',
'type', '', '1..1', 'code', 'udi-label-name | user-friendly-name | patient-reported-name | manufacturer-name | model-name | otherDeviceNameType (Required)',
'modelNumber', '', '0..1', 'string', 'The model number for the device',
'partNumber', '', '0..1', 'string', 'The part number of the device',
'type', '', '0..1', 'CodeableConcept', 'The kind or type of deviceDevice Type (Example)',
'specialization', '', '0..*', 'BackboneElement', 'The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication',
'systemType', '', '1..1', 'CodeableConcept', 'The standard that is used to operate and communicate',
'version', '', '0..1', 'string', 'The version of the standard that is used to operate and communicate',
'version', '', '0..*', 'BackboneElement', 'The actual design of the device or software version running on the device',
'type', '', '0..1', 'CodeableConcept', 'The type of the device version',
'component', '', '0..1', 'Identifier', 'A single component of the device version',
'value', '', '1..1', 'string', 'The version text',
'property', '', '0..*', 'BackboneElement', 'The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties',
'type', '', '1..1', 'CodeableConcept', 'Code that specifies the property DeviceDefinitionPropetyCode (Extensible)',
'valueQuantity', '', '0..*', 'Quantity', 'Property value as a quantity',
'valueCode', '', '0..*', 'CodeableConcept', 'Property value as a code, e.g., NTP4 (synced to NTP)',
'patient', '', '0..1', 'Reference(Patient)', 'Patient to whom Device is affixed',
'owner', '', '0..1', 'Reference(Organization)', 'Organization responsible for device',
'contact', '', '0..*', 'ContactPoint', 'Details for human/organization for support',
'location', '', '0..1', 'Reference(Location)', 'Where the device is found',
'url', '', '0..1', 'uri', 'Network address to contact device',
'note', '', '0..*', 'Annotation', 'Device notes and comments',
'safety', 'Σ', '0..*', 'CodeableConcept', 'Safety Characteristics of Device',
'parent', '', '0..1', 'Reference(Device)', 'The parent device',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Device', '',
'Device.definition', 'Added Element',
'Device.udiCarrier', 'Added Element',
'Device.udiCarrier.deviceIdentifier', 'Added Element',
'Device.udiCarrier.issuer', 'Added Element',
'Device.udiCarrier.jurisdiction', 'Added Element',
'Device.udiCarrier.carrierAIDC', 'Added Element',
'Device.udiCarrier.carrierHRF', 'Added Element',
'Device.udiCarrier.entryType', 'Added Element',
'Device.status', 'Change value set from http://hl7.org/fhir/ValueSet/device-status to http://hl7.org/fhir/ValueSet/device-status|4.0.1',
'Device.statusReason', 'Added Element',
'Device.distinctIdentifier', 'Added Element',
'Device.serialNumber', 'Added Element',
'Device.deviceName', 'Added Element',
'Device.deviceName.name', 'Added Mandatory Element',
'Device.deviceName.type', 'Added Mandatory Element',
'Device.modelNumber', 'Added Element',
'Device.partNumber', 'Added Element',
'Device.specialization', 'Added Element',
'Device.specialization.systemType', 'Added Mandatory Element',
'Device.specialization.version', 'Added Element',
'Device.version', 'Max Cardinality changed from 1 to *
        Type changed from string to BackboneElement',
'Device.version.type', 'Added Element',
'Device.version.component', 'Added Element',
'Device.version.value', 'Added Mandatory Element',
'Device.property', 'Added Element',
'Device.property.type', 'Added Mandatory Element',
'Device.property.valueQuantity', 'Added Element',
'Device.property.valueCode', 'Added Element',
'Device.parent', 'Added Element',
'Device.udi', 'deleted',
'Device.model', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Device.udiCarrier.entryType', 'Codes to identify how UDI data was entered.', 'Required', 'UDIEntryType',
'Device.status', 'The availability status of the device.', 'Required', 'FHIRDeviceStatus',
'Device.statusReason', 'The availability status reason of the device.', 'Extensible', 'FHIRDeviceStatusReason',
'Device.deviceName.type', 'The type of name the device is referred by.', 'Required', 'DeviceNameType',
'Device.type', 'Codes to identify medical devices.', 'Example', 'DeviceType',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'device-name', 'string', 'A server defined search that may match any of the string fields in Device.deviceName or Device.type.', 'Device.deviceName.name | Device.type.coding.display | Device.type.text', '',
'identifier', 'token', 'Instance id from manufacturer, owner, and others', 'Device.identifier', '',
'location', 'reference', 'A location, where the resource is found', 'Device.location(Location)', '',
'manufacturer', 'string', 'The manufacturer of the device', 'Device.manufacturer', '',
'model', 'string', 'The model of the device', 'Device.modelNumber', '',
'organization', 'reference', 'The organization responsible for the device', 'Device.owner(Organization)', '',
'patient', 'reference', 'Patient information, if the resource is affixed to a person', 'Device.patient(Patient)', '',
'status', 'token', 'active | inactive | entered-in-error | unknown', 'Device.status', '',
'type', 'token', 'The type of the device', 'Device.type', '',
'udi-carrier', 'string', 'UDI Barcode (RFID or other technology) string in *HRF* format.', 'Device.udiCarrier.carrierHRF', '',
'udi-di', 'string', 'The udi Device Identifier (DI)', 'Device.udiCarrier.deviceIdentifier', '',
'url', 'uri', 'Network address to contact device', 'Device.url', '',
)


