df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'EffectEvidenceSynthesis', 'ITU', '', 'DomainResource', 'A quantified estimate of effect based on a body of evidence+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this effect evidence synthesis, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the effect evidence synthesis',
'version', 'Σ', '0..1', 'string', 'Business version of the effect evidence synthesis',
'name', 'ΣI', '0..1', 'string', 'Name for this effect evidence synthesis (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this effect evidence synthesis (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the effect evidence synthesis',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for effect evidence synthesis (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the effect evidence synthesis was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the effect evidence synthesis was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the effect evidence synthesis is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the EffectEvidenceSynthesis, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'synthesisType', '', '0..1', 'CodeableConcept', 'Type of synthesisSynthesisType (Extensible)',
'studyType', '', '0..1', 'CodeableConcept', 'Type of studyStudyType (Extensible)',
'population', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What population?',
'exposure', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What exposure?',
'exposureAlternative', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What comparison exposure?',
'outcome', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What outcome?',
'sampleSize', '', '0..1', 'BackboneElement', 'What sample size was involved?',
'description', '', '0..1', 'string', 'Description of sample size',
'numberOfStudies', '', '0..1', 'integer', 'How many studies?',
'numberOfParticipants', '', '0..1', 'integer', 'How many participants?',
'resultsByExposure', '', '0..*', 'BackboneElement', 'What was the result per exposure?',
'description', '', '0..1', 'string', 'Description of results by exposure',
'exposureState', '', '0..1', 'code', 'exposure | exposure-alternativeExposureState (Required)',
'variantState', '', '0..1', 'CodeableConcept', 'Variant exposure statesEvidenceVariantState (Extensible)',
'riskEvidenceSynthesis', '', '1..1', 'Reference(RiskEvidenceSynthesis)', 'Risk evidence synthesis',
'effectEstimate', 'Σ', '0..*', 'BackboneElement', 'What was the estimated effect',
'description', '', '0..1', 'string', 'Description of effect estimate',
'type', '', '0..1', 'CodeableConcept', 'Type of efffect estimateEffectEstimateType (Extensible)',
'variantState', '', '0..1', 'CodeableConcept', 'Variant exposure statesEvidenceVariantState (Extensible)',
'value', '', '0..1', 'decimal', 'Point estimate',
'unitOfMeasure', '', '0..1', 'CodeableConcept', 'What unit is the outcome described in?UCUM Codes (Required)',
'precisionEstimate', '', '0..*', 'BackboneElement', 'How precise the estimate is',
'type', '', '0..1', 'CodeableConcept', 'Type of precision estimatePrecisionEstimateType (Extensible)',
'level', '', '0..1', 'decimal', 'Level of confidence interval',
'from', '', '0..1', 'decimal', 'Lower bound',
'to', '', '0..1', 'decimal', 'Upper bound',
'certainty', '', '0..*', 'BackboneElement', 'How certain is the effect',
'rating', '', '0..*', 'CodeableConcept', 'Certainty ratingQualityOfEvidenceRating (Extensible)',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'certaintySubcomponent', '', '0..*', 'BackboneElement', 'A component that contributes to the overall certainty',
'type', '', '0..1', 'CodeableConcept', 'Type of subcomponent of certainty ratingCertaintySubcomponentType (Extensible)',
'rating', '', '0..*', 'CodeableConcept', 'Subcomponent certainty ratingCertaintySubcomponentRating (Extensible)',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'EffectEvidenceSynthesis', 'ITU', '', 'DomainResource', 'A quantified estimate of effect based on a body of evidence+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this effect evidence synthesis, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the effect evidence synthesis',
'version', 'Σ', '0..1', 'string', 'Business version of the effect evidence synthesis',
'name', 'ΣI', '0..1', 'string', 'Name for this effect evidence synthesis (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this effect evidence synthesis (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the effect evidence synthesis',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for effect evidence synthesis (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the effect evidence synthesis was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the effect evidence synthesis was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the effect evidence synthesis is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the EffectEvidenceSynthesis, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'synthesisType', '', '0..1', 'CodeableConcept', 'Type of synthesisSynthesisType (Extensible)',
'studyType', '', '0..1', 'CodeableConcept', 'Type of studyStudyType (Extensible)',
'population', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What population?',
'exposure', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What exposure?',
'exposureAlternative', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What comparison exposure?',
'outcome', 'Σ', '1..1', 'Reference(EvidenceVariable)', 'What outcome?',
'sampleSize', '', '0..1', 'BackboneElement', 'What sample size was involved?',
'description', '', '0..1', 'string', 'Description of sample size',
'numberOfStudies', '', '0..1', 'integer', 'How many studies?',
'numberOfParticipants', '', '0..1', 'integer', 'How many participants?',
'resultsByExposure', '', '0..*', 'BackboneElement', 'What was the result per exposure?',
'description', '', '0..1', 'string', 'Description of results by exposure',
'exposureState', '', '0..1', 'code', 'exposure | exposure-alternativeExposureState (Required)',
'variantState', '', '0..1', 'CodeableConcept', 'Variant exposure statesEvidenceVariantState (Extensible)',
'riskEvidenceSynthesis', '', '1..1', 'Reference(RiskEvidenceSynthesis)', 'Risk evidence synthesis',
'effectEstimate', 'Σ', '0..*', 'BackboneElement', 'What was the estimated effect',
'description', '', '0..1', 'string', 'Description of effect estimate',
'type', '', '0..1', 'CodeableConcept', 'Type of efffect estimateEffectEstimateType (Extensible)',
'variantState', '', '0..1', 'CodeableConcept', 'Variant exposure statesEvidenceVariantState (Extensible)',
'value', '', '0..1', 'decimal', 'Point estimate',
'unitOfMeasure', '', '0..1', 'CodeableConcept', 'What unit is the outcome described in?UCUM Codes (Required)',
'precisionEstimate', '', '0..*', 'BackboneElement', 'How precise the estimate is',
'type', '', '0..1', 'CodeableConcept', 'Type of precision estimatePrecisionEstimateType (Extensible)',
'level', '', '0..1', 'decimal', 'Level of confidence interval',
'from', '', '0..1', 'decimal', 'Lower bound',
'to', '', '0..1', 'decimal', 'Upper bound',
'certainty', '', '0..*', 'BackboneElement', 'How certain is the effect',
'rating', '', '0..*', 'CodeableConcept', 'Certainty ratingQualityOfEvidenceRating (Extensible)',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'certaintySubcomponent', '', '0..*', 'BackboneElement', 'A component that contributes to the overall certainty',
'type', '', '0..1', 'CodeableConcept', 'Type of subcomponent of certainty ratingCertaintySubcomponentType (Extensible)',
'rating', '', '0..*', 'CodeableConcept', 'Subcomponent certainty ratingCertaintySubcomponentRating (Extensible)',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'EffectEvidenceSynthesis.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'EffectEvidenceSynthesis.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'EffectEvidenceSynthesis.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'EffectEvidenceSynthesis.synthesisType', 'Types of combining results from a body of evidence (eg. summary data meta-analysis).', 'Extensible', 'SynthesisType',
'EffectEvidenceSynthesis.studyType', 'Types of research studies (types of research methods).', 'Extensible', 'StudyType',
'EffectEvidenceSynthesis.resultsByExposure.exposureState', 'Whether the results by exposure is describing the results for the primary exposure of interest (exposure) or the alternative state (exposureAlternative).', 'Required', 'ExposureState',
'EffectEvidenceSynthesis.resultsByExposure.variantStateEffectEvidenceSynthesis.effectEstimate.variantState', 'Used for results by exposure in variant states such as low-risk, medium-risk and high-risk states.', 'Extensible', 'EvidenceVariantState',
'EffectEvidenceSynthesis.effectEstimate.type', 'Whether the effect estimate is an absolute effect estimate (absolute difference) or a relative effect estimate (relative difference), and the specific type of effect estimate (eg relative risk or median difference).', 'Extensible', 'EffectEstimateType',
'EffectEvidenceSynthesis.effectEstimate.unitOfMeasure', 'Unified Code for Units of Measure (UCUM).', 'Required', 'UCUMCodes',
'EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type', 'Method of reporting variability of estimates, such as confidence intervals, interquartile range or standard deviation.', 'Extensible', 'PrecisionEstimateType',
'EffectEvidenceSynthesis.certainty.rating', 'The quality of the evidence described. The code system used specifies the quality scale used to grade this evidence source while the code specifies the actual quality score (represented as a coded value) associated with the evidence.', 'Extensible', 'QualityOfEvidenceRating',
'EffectEvidenceSynthesis.certainty.certaintySubcomponent.type', 'The subcomponent classification of quality of evidence rating systems.', 'Extensible', 'CertaintySubcomponentType',
'EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating', 'The quality rating of the subcomponent of a quality of evidence rating.', 'Extensible', 'CertaintySubcomponentRating',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'ees-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the effect evidence synthesis', '(EffectEvidenceSynthesis.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the effect evidence synthesis', '(EffectEvidenceSynthesis.useContext.value as Quantity) | (EffectEvidenceSynthesis.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the effect evidence synthesis', 'EffectEvidenceSynthesis.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the effect evidence synthesis', 'On EffectEvidenceSynthesis.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the effect evidence synthesis', 'On EffectEvidenceSynthesis.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The effect evidence synthesis publication date', 'EffectEvidenceSynthesis.date', '',
'description', 'string', 'The description of the effect evidence synthesis', 'EffectEvidenceSynthesis.description', '',
'effective', 'date', 'The time during which the effect evidence synthesis is intended to be in use', 'EffectEvidenceSynthesis.effectivePeriod', '',
'identifier', 'token', 'External identifier for the effect evidence synthesis', 'EffectEvidenceSynthesis.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the effect evidence synthesis', 'EffectEvidenceSynthesis.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the effect evidence synthesis', 'EffectEvidenceSynthesis.name', '',
'publisher', 'string', 'Name of the publisher of the effect evidence synthesis', 'EffectEvidenceSynthesis.publisher', '',
'status', 'token', 'The current status of the effect evidence synthesis', 'EffectEvidenceSynthesis.status', '',
'title', 'string', 'The human-friendly name of the effect evidence synthesis', 'EffectEvidenceSynthesis.title', '',
'url', 'uri', 'The uri that identifies the effect evidence synthesis', 'EffectEvidenceSynthesis.url', '',
'version', 'token', 'The business version of the effect evidence synthesis', 'EffectEvidenceSynthesis.version', '',
)


