df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Patient Administration  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Patient', 'Compartments: Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Encounter', 'TU', '', 'DomainResource', 'An interaction during which services are provided to the patientElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifier(s) by which this encounter is known',
'status', '?!Σ', '1..1', 'code', 'planned | arrived | triaged | in-progress | onleave | finished | cancelled +EncounterStatus (Required)',
'statusHistory', '', '0..*', 'BackboneElement', 'List of past encounter statuses',
'status', '', '1..1', 'code', 'planned | arrived | triaged | in-progress | onleave | finished | cancelled +EncounterStatus (Required)',
'period', '', '1..1', 'Period', 'The time that the episode was in the specified status',
'class', 'Σ', '1..1', 'Coding', 'Classification of patient encounterV3 Value SetActEncounterCode (Extensible)',
'classHistory', '', '0..*', 'BackboneElement', 'List of past encounter classes',
'class', '', '1..1', 'Coding', 'inpatient | outpatient | ambulatory | emergency +V3 Value SetActEncounterCode (Extensible)',
'period', '', '1..1', 'Period', 'The time that the episode was in the specified class',
'type', 'Σ', '0..*', 'CodeableConcept', 'Specific type of encounterEncounter type (Example)',
'serviceType', 'Σ', '0..1', 'CodeableConcept', 'Specific type of serviceService type (Example)',
'priority', '', '0..1', 'CodeableConcept', 'Indicates the urgency of the encounterv3 Code System ActPriority (Example)',
'subject', 'Σ', '0..1', 'Reference(Patient | Group)', 'The patient or group present at the encounter',
'episodeOfCare', 'Σ', '0..*', 'Reference(EpisodeOfCare)', 'Episode(s) of care that this encounter should be recorded against',
'basedOn', '', '0..*', 'Reference(ServiceRequest)', 'The ServiceRequest that initiated this encounter',
'participant', 'Σ', '0..*', 'BackboneElement', 'List of participants involved in the encounter',
'type', 'Σ', '0..*', 'CodeableConcept', 'Role of participant in encounterParticipant type (Extensible)',
'period', '', '0..1', 'Period', 'Period of time during the encounter that the participant participated',
'individual', 'Σ', '0..1', 'Reference(Practitioner | PractitionerRole | RelatedPerson)', 'Persons involved in the encounter other than the patient',
'appointment', 'Σ', '0..*', 'Reference(Appointment)', 'The appointment that scheduled this encounter',
'period', '', '0..1', 'Period', 'The start and end time of the encounter',
'length', '', '0..1', 'Duration', 'Quantity of time the encounter lasted (less time absent)',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Coded reason the encounter takes placeEncounter Reason Codes (Preferred)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Procedure | Observation | ImmunizationRecommendation)', 'Reason the encounter takes place (reference)',
'diagnosis', 'Σ', '0..*', 'BackboneElement', 'The list of diagnosis relevant to this encounter',
'condition', 'Σ', '1..1', 'Reference(Condition | Procedure)', 'The diagnosis or procedure relevant to the encounter',
'use', '', '0..1', 'CodeableConcept', 'Role that this diagnosis has within the encounter (e.g. admission, billing, discharge …)DiagnosisRole (Preferred)',
'rank', '', '0..1', 'positiveInt', 'Ranking of the diagnosis (for each role type)',
'account', '', '0..*', 'Reference(Account)', 'The set of accounts that may be used for billing for this Encounter',
'hospitalization', '', '0..1', 'BackboneElement', 'Details about the admission to a healthcare service',
'preAdmissionIdentifier', '', '0..1', 'Identifier', 'Pre-admission identifier',
'origin', '', '0..1', 'Reference(Location | Organization)', 'The location/organization from which the patient came before admission',
'admitSource', '', '0..1', 'CodeableConcept', 'From where patient was admitted (physician referral, transfer)Admit source (Preferred)',
'reAdmission', '', '0..1', 'CodeableConcept', 'The type of hospital re-admission that has occurred (if any). If the value is absent, then this is not identified as a readmissionv2 RE-ADMISSION INDICATOR (Example)',
'dietPreference', '', '0..*', 'CodeableConcept', 'Diet preferences reported by the patientDiet (Example)',
'specialCourtesy', '', '0..*', 'CodeableConcept', 'Special courtesies (VIP, board member)Special courtesy (Preferred)',
'specialArrangement', '', '0..*', 'CodeableConcept', 'Wheelchair, translator, stretcher, etc.Special arrangements (Preferred)',
'destination', '', '0..1', 'Reference(Location | Organization)', 'Location/organization to which the patient is discharged',
'dischargeDisposition', '', '0..1', 'CodeableConcept', 'Category or kind of location after dischargeDischarge disposition (Example)',
'location', '', '0..*', 'BackboneElement', 'List of locations where the patient has been',
'location', '', '1..1', 'Reference(Location)', 'Location the encounter takes place',
'status', '', '0..1', 'code', 'planned | active | reserved | completedEncounterLocationStatus (Required)',
'physicalType', '', '0..1', 'CodeableConcept', 'The physical type of the location (usually the level in the location hierachy - bed room ward etc.)Location type (Example)',
'period', '', '0..1', 'Period', 'Time period during which the patient was present at the location',
'serviceProvider', '', '0..1', 'Reference(Organization)', 'The organization (facility) responsible for this encounter',
'partOf', '', '0..1', 'Reference(Encounter)', 'Another Encounter this encounter is part of',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Encounter', '',
'Encounter.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-status to http://hl7.org/fhir/ValueSet/encounter-status|4.0.1',
'Encounter.statusHistory.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-status to http://hl7.org/fhir/ValueSet/encounter-status|4.0.1',
'Encounter.class', 'Min Cardinality changed from 0 to 1',
'Encounter.serviceType', 'Added Element',
'Encounter.basedOn', 'Renamed from incomingReferral to basedOn
        Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'Encounter.participant.individual', 'Type Reference: Added Target Type PractitionerRole',
'Encounter.appointment', 'Max Cardinality changed from 1 to *',
'Encounter.reasonCode', 'Added Element',
'Encounter.reasonReference', 'Added Element',
'Encounter.diagnosis.use', 'Added Element',
'Encounter.hospitalization.origin', 'Type Reference: Added Target Type Organization',
'Encounter.hospitalization.destination', 'Type Reference: Added Target Type Organization',
'Encounter.location.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-location-status to http://hl7.org/fhir/ValueSet/encounter-location-status|4.0.1',
'Encounter.location.physicalType', 'Added Element',
'Encounter.reason', 'deleted',
'Encounter.diagnosis.role', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Encounter', 'TU', '', 'DomainResource', 'An interaction during which services are provided to the patientElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifier(s) by which this encounter is known',
'status', '?!Σ', '1..1', 'code', 'planned | arrived | triaged | in-progress | onleave | finished | cancelled +EncounterStatus (Required)',
'statusHistory', '', '0..*', 'BackboneElement', 'List of past encounter statuses',
'status', '', '1..1', 'code', 'planned | arrived | triaged | in-progress | onleave | finished | cancelled +EncounterStatus (Required)',
'period', '', '1..1', 'Period', 'The time that the episode was in the specified status',
'class', 'Σ', '1..1', 'Coding', 'Classification of patient encounterV3 Value SetActEncounterCode (Extensible)',
'classHistory', '', '0..*', 'BackboneElement', 'List of past encounter classes',
'class', '', '1..1', 'Coding', 'inpatient | outpatient | ambulatory | emergency +V3 Value SetActEncounterCode (Extensible)',
'period', '', '1..1', 'Period', 'The time that the episode was in the specified class',
'type', 'Σ', '0..*', 'CodeableConcept', 'Specific type of encounterEncounter type (Example)',
'serviceType', 'Σ', '0..1', 'CodeableConcept', 'Specific type of serviceService type (Example)',
'priority', '', '0..1', 'CodeableConcept', 'Indicates the urgency of the encounterv3 Code System ActPriority (Example)',
'subject', 'Σ', '0..1', 'Reference(Patient | Group)', 'The patient or group present at the encounter',
'episodeOfCare', 'Σ', '0..*', 'Reference(EpisodeOfCare)', 'Episode(s) of care that this encounter should be recorded against',
'basedOn', '', '0..*', 'Reference(ServiceRequest)', 'The ServiceRequest that initiated this encounter',
'participant', 'Σ', '0..*', 'BackboneElement', 'List of participants involved in the encounter',
'type', 'Σ', '0..*', 'CodeableConcept', 'Role of participant in encounterParticipant type (Extensible)',
'period', '', '0..1', 'Period', 'Period of time during the encounter that the participant participated',
'individual', 'Σ', '0..1', 'Reference(Practitioner | PractitionerRole | RelatedPerson)', 'Persons involved in the encounter other than the patient',
'appointment', 'Σ', '0..*', 'Reference(Appointment)', 'The appointment that scheduled this encounter',
'period', '', '0..1', 'Period', 'The start and end time of the encounter',
'length', '', '0..1', 'Duration', 'Quantity of time the encounter lasted (less time absent)',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Coded reason the encounter takes placeEncounter Reason Codes (Preferred)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Procedure | Observation | ImmunizationRecommendation)', 'Reason the encounter takes place (reference)',
'diagnosis', 'Σ', '0..*', 'BackboneElement', 'The list of diagnosis relevant to this encounter',
'condition', 'Σ', '1..1', 'Reference(Condition | Procedure)', 'The diagnosis or procedure relevant to the encounter',
'use', '', '0..1', 'CodeableConcept', 'Role that this diagnosis has within the encounter (e.g. admission, billing, discharge …)DiagnosisRole (Preferred)',
'rank', '', '0..1', 'positiveInt', 'Ranking of the diagnosis (for each role type)',
'account', '', '0..*', 'Reference(Account)', 'The set of accounts that may be used for billing for this Encounter',
'hospitalization', '', '0..1', 'BackboneElement', 'Details about the admission to a healthcare service',
'preAdmissionIdentifier', '', '0..1', 'Identifier', 'Pre-admission identifier',
'origin', '', '0..1', 'Reference(Location | Organization)', 'The location/organization from which the patient came before admission',
'admitSource', '', '0..1', 'CodeableConcept', 'From where patient was admitted (physician referral, transfer)Admit source (Preferred)',
'reAdmission', '', '0..1', 'CodeableConcept', 'The type of hospital re-admission that has occurred (if any). If the value is absent, then this is not identified as a readmissionv2 RE-ADMISSION INDICATOR (Example)',
'dietPreference', '', '0..*', 'CodeableConcept', 'Diet preferences reported by the patientDiet (Example)',
'specialCourtesy', '', '0..*', 'CodeableConcept', 'Special courtesies (VIP, board member)Special courtesy (Preferred)',
'specialArrangement', '', '0..*', 'CodeableConcept', 'Wheelchair, translator, stretcher, etc.Special arrangements (Preferred)',
'destination', '', '0..1', 'Reference(Location | Organization)', 'Location/organization to which the patient is discharged',
'dischargeDisposition', '', '0..1', 'CodeableConcept', 'Category or kind of location after dischargeDischarge disposition (Example)',
'location', '', '0..*', 'BackboneElement', 'List of locations where the patient has been',
'location', '', '1..1', 'Reference(Location)', 'Location the encounter takes place',
'status', '', '0..1', 'code', 'planned | active | reserved | completedEncounterLocationStatus (Required)',
'physicalType', '', '0..1', 'CodeableConcept', 'The physical type of the location (usually the level in the location hierachy - bed room ward etc.)Location type (Example)',
'period', '', '0..1', 'Period', 'Time period during which the patient was present at the location',
'serviceProvider', '', '0..1', 'Reference(Organization)', 'The organization (facility) responsible for this encounter',
'partOf', '', '0..1', 'Reference(Encounter)', 'Another Encounter this encounter is part of',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Encounter', '',
'Encounter.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-status to http://hl7.org/fhir/ValueSet/encounter-status|4.0.1',
'Encounter.statusHistory.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-status to http://hl7.org/fhir/ValueSet/encounter-status|4.0.1',
'Encounter.class', 'Min Cardinality changed from 0 to 1',
'Encounter.serviceType', 'Added Element',
'Encounter.basedOn', 'Renamed from incomingReferral to basedOn
        Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'Encounter.participant.individual', 'Type Reference: Added Target Type PractitionerRole',
'Encounter.appointment', 'Max Cardinality changed from 1 to *',
'Encounter.reasonCode', 'Added Element',
'Encounter.reasonReference', 'Added Element',
'Encounter.diagnosis.use', 'Added Element',
'Encounter.hospitalization.origin', 'Type Reference: Added Target Type Organization',
'Encounter.hospitalization.destination', 'Type Reference: Added Target Type Organization',
'Encounter.location.status', 'Change value set from http://hl7.org/fhir/ValueSet/encounter-location-status to http://hl7.org/fhir/ValueSet/encounter-location-status|4.0.1',
'Encounter.location.physicalType', 'Added Element',
'Encounter.reason', 'deleted',
'Encounter.diagnosis.role', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Encounter.statusEncounter.statusHistory.status', 'Current state of the encounter.', 'Required', 'EncounterStatus',
'Encounter.classEncounter.classHistory.class', 'Classification of the encounter.', 'Extensible', 'v3.ActEncounterCode',
'Encounter.type', 'The type of encounter.', 'Example', 'EncounterType',
'Encounter.serviceType', 'Broad categorization of the service that is to be provided.', 'Example', 'ServiceType',
'Encounter.priority', 'Indicates the urgency of the encounter.', 'Example', 'v3.ActPriority',
'Encounter.participant.type', 'Role of participant in encounter.', 'Extensible', 'ParticipantType',
'Encounter.reasonCode', 'Reason why the encounter takes place.', 'Preferred', 'EncounterReasonCodes',
'Encounter.diagnosis.use', 'The type of diagnosis this condition represents.', 'Preferred', 'DiagnosisRole',
'Encounter.hospitalization.admitSource', 'From where the patient was admitted.', 'Preferred', 'AdmitSource',
'Encounter.hospitalization.reAdmission', 'The reason for re-admission of this hospitalization encounter.', 'Example', 'v2.0092',
'Encounter.hospitalization.dietPreference', 'Medical, cultural or ethical food preferences to help with catering requirements.', 'Example', 'Diet',
'Encounter.hospitalization.specialCourtesy', 'Special courtesies.', 'Preferred', 'SpecialCourtesy',
'Encounter.hospitalization.specialArrangement', 'Special arrangements.', 'Preferred', 'SpecialArrangements',
'Encounter.hospitalization.dischargeDisposition', 'Discharge Disposition.', 'Example', 'DischargeDisposition',
'Encounter.location.status', 'The status of the location.', 'Required', 'EncounterLocationStatus',
'Encounter.location.physicalType', 'Physical form of the location.', 'Example', 'LocationType',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'account', 'reference', 'The set of accounts that may be used for billing for this Encounter', 'Encounter.account(Account)', '',
'appointment', 'reference', 'The appointment that scheduled this encounter', 'Encounter.appointment(Appointment)', '',
'based-on', 'reference', 'The ServiceRequest that initiated this encounter', 'Encounter.basedOn(ServiceRequest)', '',
'class', 'token', 'Classification of patient encounter', 'Encounter.class', '',
'date', 'date', 'A date within the period the Encounter lasted', 'Encounter.period', '17 Resources',
'diagnosis', 'reference', 'The diagnosis or procedure relevant to the encounter', 'Encounter.diagnosis.condition(Condition, Procedure)', '',
'episode-of-care', 'reference', 'Episode(s) of care that this encounter should be recorded against', 'Encounter.episodeOfCare(EpisodeOfCare)', '',
'identifier', 'token', 'Identifier(s) by which this encounter is known', 'Encounter.identifier', '30 Resources',
'length', 'quantity', 'Length of encounter in days', 'Encounter.length', '',
'location', 'reference', 'Location the encounter takes place', 'Encounter.location.location(Location)', '',
'location-period', 'date', 'Time period during which the patient was present at the location', 'Encounter.location.period', '',
'part-of', 'reference', 'Another Encounter this encounter is part of', 'Encounter.partOf(Encounter)', '',
'participant', 'reference', 'Persons involved in the encounter other than the patient', 'Encounter.participant.individual(Practitioner, PractitionerRole, RelatedPerson)', '',
'participant-type', 'token', 'Role of participant in encounter', 'Encounter.participant.type', '',
'patient', 'reference', 'The patient or group present at the encounter', 'Encounter.subject.where(resolve() is Patient)(Patient)', '33 Resources',
'practitioner', 'reference', 'Persons involved in the encounter other than the patient', 'Encounter.participant.individual.where(resolve() is Practitioner)(Practitioner)', '',
'reason-code', 'token', 'Coded reason the encounter takes place', 'Encounter.reasonCode', '',
'reason-reference', 'reference', 'Reason the encounter takes place (reference)', 'Encounter.reasonReference(Condition, Observation, Procedure, ImmunizationRecommendation)', '',
'service-provider', 'reference', 'The organization (facility) responsible for this encounter', 'Encounter.serviceProvider(Organization)', '',
'special-arrangement', 'token', 'Wheelchair, translator, stretcher, etc.', 'Encounter.hospitalization.specialArrangement', '',
'status', 'token', 'planned | arrived | triaged | in-progress | onleave | finished | cancelled +', 'Encounter.status', '',
'subject', 'reference', 'The patient or group present at the encounter', 'Encounter.subject(Group, Patient)', '',
'type', 'token', 'Specific type of encounter', 'Encounter.type', '5 Resources',
)


