df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'EvidenceVariable', 'ITU', '', 'DomainResource', 'A population, intervention, or exposure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this evidence variable, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the evidence variable',
'version', 'Σ', '0..1', 'string', 'Business version of the evidence variable',
'name', 'ΣI', '0..1', 'string', 'Name for this evidence variable (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this evidence variable (human friendly)',
'shortTitle', 'Σ', '0..1', 'string', 'Title for use in informal contexts',
'subtitle', '', '0..1', 'string', 'Subordinate title of the EvidenceVariable',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the evidence variable',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for evidence variable (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the evidence variable was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the evidence variable was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the evidence variable is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the EvidenceVariable, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'type', 'Σ', '0..1', 'code', 'dichotomous | continuous | descriptiveEvidenceVariableType (Required)',
'characteristic', 'Σ', '1..*', 'BackboneElement', 'What defines the members of the evidence element',
'description', '', '0..1', 'string', 'Natural language description of the characteristic',
'definition[x]', 'Σ', '1..1', '', 'What code or expression defines members?',
'definitionReference', '', '', 'Reference(Group)', '',
'definitionCanonical', '', '', 'canonical(ActivityDefinition)', '',
'definitionCodeableConcept', '', '', 'CodeableConcept', '',
'definitionExpression', '', '', 'Expression', '',
'definitionDataRequirement', '', '', 'DataRequirement', '',
'definitionTriggerDefinition', '', '', 'TriggerDefinition', '',
'usageContext', '', '0..*', 'UsageContext', 'What code/value pairs define members?',
'exclude', '', '0..1', 'boolean', 'Whether the characteristic includes or excludes members',
'participantEffective[x]', '', '0..1', '', 'What time period do participants cover',
'participantEffectiveDateTime', '', '', 'dateTime', '',
'participantEffectivePeriod', '', '', 'Period', '',
'participantEffectiveDuration', '', '', 'Duration', '',
'participantEffectiveTiming', '', '', 'Timing', '',
'timeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'groupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'EvidenceVariable', 'ITU', '', 'DomainResource', 'A population, intervention, or exposure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this evidence variable, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the evidence variable',
'version', 'Σ', '0..1', 'string', 'Business version of the evidence variable',
'name', 'ΣI', '0..1', 'string', 'Name for this evidence variable (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this evidence variable (human friendly)',
'shortTitle', 'Σ', '0..1', 'string', 'Title for use in informal contexts',
'subtitle', '', '0..1', 'string', 'Subordinate title of the EvidenceVariable',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the evidence variable',
'note', '', '0..*', 'Annotation', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for evidence variable (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the evidence variable was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the evidence variable was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the evidence variable is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the EvidenceVariable, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'type', 'Σ', '0..1', 'code', 'dichotomous | continuous | descriptiveEvidenceVariableType (Required)',
'characteristic', 'Σ', '1..*', 'BackboneElement', 'What defines the members of the evidence element',
'description', '', '0..1', 'string', 'Natural language description of the characteristic',
'definition[x]', 'Σ', '1..1', '', 'What code or expression defines members?',
'definitionReference', '', '', 'Reference(Group)', '',
'definitionCanonical', '', '', 'canonical(ActivityDefinition)', '',
'definitionCodeableConcept', '', '', 'CodeableConcept', '',
'definitionExpression', '', '', 'Expression', '',
'definitionDataRequirement', '', '', 'DataRequirement', '',
'definitionTriggerDefinition', '', '', 'TriggerDefinition', '',
'usageContext', '', '0..*', 'UsageContext', 'What code/value pairs define members?',
'exclude', '', '0..1', 'boolean', 'Whether the characteristic includes or excludes members',
'participantEffective[x]', '', '0..1', '', 'What time period do participants cover',
'participantEffectiveDateTime', '', '', 'dateTime', '',
'participantEffectivePeriod', '', '', 'Period', '',
'participantEffectiveDuration', '', '', 'Duration', '',
'participantEffectiveTiming', '', '', 'Timing', '',
'timeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'groupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'EvidenceVariable.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'EvidenceVariable.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'EvidenceVariable.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'EvidenceVariable.type', 'The possible types of variables for exposures or outcomes (E.g. Dichotomous, Continuous, Descriptive).', 'Required', 'EvidenceVariableType',
'EvidenceVariable.characteristic.groupMeasure', 'Possible group measure aggregates (E.g. Mean, Median).', 'Required', 'GroupMeasure',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'evv-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'composed-of', 'reference', 'What resource is being referenced', 'EvidenceVariable.relatedArtifact.where(type='composed-of').resource(Any)', '',
'context', 'token', 'A use context assigned to the evidence variable', '(EvidenceVariable.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the evidence variable', '(EvidenceVariable.useContext.value as Quantity) | (EvidenceVariable.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the evidence variable', 'EvidenceVariable.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the evidence variable', 'On EvidenceVariable.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the evidence variable', 'On EvidenceVariable.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The evidence variable publication date', 'EvidenceVariable.date', '',
'depends-on', 'reference', 'What resource is being referenced', 'EvidenceVariable.relatedArtifact.where(type='depends-on').resource(Any)', '',
'derived-from', 'reference', 'What resource is being referenced', 'EvidenceVariable.relatedArtifact.where(type='derived-from').resource(Any)', '',
'description', 'string', 'The description of the evidence variable', 'EvidenceVariable.description', '',
'effective', 'date', 'The time during which the evidence variable is intended to be in use', 'EvidenceVariable.effectivePeriod', '',
'identifier', 'token', 'External identifier for the evidence variable', 'EvidenceVariable.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the evidence variable', 'EvidenceVariable.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the evidence variable', 'EvidenceVariable.name', '',
'predecessor', 'reference', 'What resource is being referenced', 'EvidenceVariable.relatedArtifact.where(type='predecessor').resource(Any)', '',
'publisher', 'string', 'Name of the publisher of the evidence variable', 'EvidenceVariable.publisher', '',
'status', 'token', 'The current status of the evidence variable', 'EvidenceVariable.status', '',
'successor', 'reference', 'What resource is being referenced', 'EvidenceVariable.relatedArtifact.where(type='successor').resource(Any)', '',
'title', 'string', 'The human-friendly name of the evidence variable', 'EvidenceVariable.title', '',
'topic', 'token', 'Topics associated with the EvidenceVariable', 'EvidenceVariable.topic', '',
'url', 'uri', 'The uri that identifies the evidence variable', 'EvidenceVariable.url', '',
'version', 'token', 'The business version of the evidence variable', 'EvidenceVariable.version', '',
)


