df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ExampleScenario', 'ITU', '', 'DomainResource', 'Example of workflow instance+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this example scenario, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the example scenario',
'version', 'Σ', '0..1', 'string', 'Business version of the example scenario',
'name', 'ΣI', '0..1', 'string', 'Name for this example scenario (computer friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for example scenario (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'purpose', '', '0..1', 'markdown', 'The purpose of the example, e.g. to illustrate a scenario',
'actor', '', '0..*', 'BackboneElement', 'Actor participating in the resource',
'actorId', '', '1..1', 'string', 'ID or acronym of the actor',
'type', '', '1..1', 'code', 'person | entityExampleScenarioActorType (Required)',
'name', '', '0..1', 'string', 'The name of the actor as shown in the page',
'description', '', '0..1', 'markdown', 'The description of the actor',
'instance', '', '0..*', 'BackboneElement', 'Each resource and each version that is present in the workflow',
'resourceId', '', '1..1', 'string', 'The id of the resource for referencing',
'resourceType', '', '1..1', 'code', 'The type of the resourceResourceType (Required)',
'name', '', '0..1', 'string', 'A short name for the resource instance',
'description', '', '0..1', 'markdown', 'Human-friendly description of the resource instance',
'version', '', '0..*', 'BackboneElement', 'A specific version of the resource',
'versionId', '', '1..1', 'string', 'The identifier of a specific version of a resource',
'description', '', '1..1', 'markdown', 'The description of the resource version',
'containedInstance', '', '0..*', 'BackboneElement', 'Resources contained in the instance',
'resourceId', '', '1..1', 'string', 'Each resource contained in the instance',
'versionId', '', '0..1', 'string', 'A specific version of a resource contained in the instance',
'process', '', '0..*', 'BackboneElement', 'Each major process - a group of operations',
'title', 'Σ', '1..1', 'string', 'The diagram title of the group of operations',
'description', '', '0..1', 'markdown', 'A longer description of the group of operations',
'preConditions', '', '0..1', 'markdown', 'Description of initial status before the process starts',
'postConditions', '', '0..1', 'markdown', 'Description of final status after the process ends',
'step', '', '0..*', 'BackboneElement', 'Each step of the process',
'process', '', '0..*', 'see process', 'Nested process',
'pause', '', '0..1', 'boolean', 'If there is a pause in the flow',
'operation', '', '0..1', 'BackboneElement', 'Each interaction or action',
'number', '', '1..1', 'string', 'The sequential number of the interaction',
'type', '', '0..1', 'string', 'The type of operation - CRUD',
'name', '', '0..1', 'string', 'The human-friendly name of the interaction',
'initiator', '', '0..1', 'string', 'Who starts the transaction',
'receiver', '', '0..1', 'string', 'Who receives the transaction',
'description', '', '0..1', 'markdown', 'A comment to be inserted in the diagram',
'initiatorActive', '', '0..1', 'boolean', 'Whether the initiator is deactivated right after the transaction',
'receiverActive', '', '0..1', 'boolean', 'Whether the receiver is deactivated right after the transaction',
'request', '', '0..1', 'see containedInstance', 'Each resource instance used by the initiator',
'response', '', '0..1', 'see containedInstance', 'Each resource instance used by the responder',
'alternative', '', '0..*', 'BackboneElement', 'Alternate non-typical step action',
'title', '', '1..1', 'string', 'Label for alternative',
'description', '', '0..1', 'markdown', 'A human-readable description of each option',
'step', '', '0..*', 'see step', 'What happens in each alternative option',
'workflow', '', '0..*', 'canonical(ExampleScenario)', 'Another nested workflow',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ExampleScenario', 'ITU', '', 'DomainResource', 'Example of workflow instance+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this example scenario, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the example scenario',
'version', 'Σ', '0..1', 'string', 'Business version of the example scenario',
'name', 'ΣI', '0..1', 'string', 'Name for this example scenario (computer friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for example scenario (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'purpose', '', '0..1', 'markdown', 'The purpose of the example, e.g. to illustrate a scenario',
'actor', '', '0..*', 'BackboneElement', 'Actor participating in the resource',
'actorId', '', '1..1', 'string', 'ID or acronym of the actor',
'type', '', '1..1', 'code', 'person | entityExampleScenarioActorType (Required)',
'name', '', '0..1', 'string', 'The name of the actor as shown in the page',
'description', '', '0..1', 'markdown', 'The description of the actor',
'instance', '', '0..*', 'BackboneElement', 'Each resource and each version that is present in the workflow',
'resourceId', '', '1..1', 'string', 'The id of the resource for referencing',
'resourceType', '', '1..1', 'code', 'The type of the resourceResourceType (Required)',
'name', '', '0..1', 'string', 'A short name for the resource instance',
'description', '', '0..1', 'markdown', 'Human-friendly description of the resource instance',
'version', '', '0..*', 'BackboneElement', 'A specific version of the resource',
'versionId', '', '1..1', 'string', 'The identifier of a specific version of a resource',
'description', '', '1..1', 'markdown', 'The description of the resource version',
'containedInstance', '', '0..*', 'BackboneElement', 'Resources contained in the instance',
'resourceId', '', '1..1', 'string', 'Each resource contained in the instance',
'versionId', '', '0..1', 'string', 'A specific version of a resource contained in the instance',
'process', '', '0..*', 'BackboneElement', 'Each major process - a group of operations',
'title', 'Σ', '1..1', 'string', 'The diagram title of the group of operations',
'description', '', '0..1', 'markdown', 'A longer description of the group of operations',
'preConditions', '', '0..1', 'markdown', 'Description of initial status before the process starts',
'postConditions', '', '0..1', 'markdown', 'Description of final status after the process ends',
'step', '', '0..*', 'BackboneElement', 'Each step of the process',
'process', '', '0..*', 'see process', 'Nested process',
'pause', '', '0..1', 'boolean', 'If there is a pause in the flow',
'operation', '', '0..1', 'BackboneElement', 'Each interaction or action',
'number', '', '1..1', 'string', 'The sequential number of the interaction',
'type', '', '0..1', 'string', 'The type of operation - CRUD',
'name', '', '0..1', 'string', 'The human-friendly name of the interaction',
'initiator', '', '0..1', 'string', 'Who starts the transaction',
'receiver', '', '0..1', 'string', 'Who receives the transaction',
'description', '', '0..1', 'markdown', 'A comment to be inserted in the diagram',
'initiatorActive', '', '0..1', 'boolean', 'Whether the initiator is deactivated right after the transaction',
'receiverActive', '', '0..1', 'boolean', 'Whether the receiver is deactivated right after the transaction',
'request', '', '0..1', 'see containedInstance', 'Each resource instance used by the initiator',
'response', '', '0..1', 'see containedInstance', 'Each resource instance used by the responder',
'alternative', '', '0..*', 'BackboneElement', 'Alternate non-typical step action',
'title', '', '1..1', 'string', 'Label for alternative',
'description', '', '0..1', 'markdown', 'A human-readable description of each option',
'step', '', '0..*', 'see step', 'What happens in each alternative option',
'workflow', '', '0..*', 'canonical(ExampleScenario)', 'Another nested workflow',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ExampleScenario.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'ExampleScenario.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'ExampleScenario.actor.type', 'The type of actor - system or human.', 'Required', 'ExampleScenarioActorType',
'ExampleScenario.instance.resourceType', 'The type of resource.', 'Required', 'ResourceType',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'esc-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the example scenario', '(ExampleScenario.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the example scenario', '(ExampleScenario.useContext.value as Quantity) | (ExampleScenario.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the example scenario', 'ExampleScenario.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the example scenario', 'On ExampleScenario.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the example scenario', 'On ExampleScenario.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The example scenario publication date', 'ExampleScenario.date', '',
'identifier', 'token', 'External identifier for the example scenario', 'ExampleScenario.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the example scenario', 'ExampleScenario.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the example scenario', 'ExampleScenario.name', '',
'publisher', 'string', 'Name of the publisher of the example scenario', 'ExampleScenario.publisher', '',
'status', 'token', 'The current status of the example scenario', 'ExampleScenario.status', '',
'url', 'uri', 'The uri that identifies the example scenario', 'ExampleScenario.url', '',
'version', 'token', 'The business version of the example scenario', 'ExampleScenario.version', '',
)


