df1 <-
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Financial Management  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Patient', 'Compartments: Device, Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <-
tibble::tribble(
~`X1`,~`X2`,
'ExplanationOfBenefit', 'This resource combines the information from the Claim and the ClaimResponse, stripping out any provider or payor proprietary information, into a unified information model
					suitable for use for: patient reporting; transferring information to a Patient Health Record system; and, supporting complete claim and adjudication information exchange
					with regulatory and analytics organizations and other parts of the provider\'s organization.',
'Claim', 'A suite of goods and services and insurances coverages under which adjudication or authorization is requested.',
'ClaimResponse', 'A payor\'s adjudication and/or authorization response to the suite of services provided in a Claim. Typically the ClaimResponse references the Claim but does not duplicate
		the clinical or financial information provided in the claim.',
'CoverageEligibilityRequest', 'A request to a payor to: ascertain whether a coverage is in-force at the current or at a specified time; list the table of benefits;
				determine whether coverage is provided for specified categories or specific services; and whether preauthorization is required, and if so
				what supporting information would be required.',
)


df3 <-
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ExplanationOfBenefit', 'TU', '', 'DomainResource', 'Explanation of Benefit resourceElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for the resource',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorExplanationOfBenefitStatus (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'Category or disciplineClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'billablePeriod', 'Σ', '0..1', 'Period', 'Relevant time frame for the claim',
'created', 'Σ', '1..1', 'dateTime', 'Response creation date',
'enterer', '', '0..1', 'Reference(Practitioner | PractitionerRole)', 'Author of the claim',
'insurer', 'Σ', '1..1', 'Reference(Organization)', 'Party responsible for reimbursement',
'provider', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'priority', '', '0..1', 'CodeableConcept', 'Desired processing urgencyProcessPriority  (Example)',
'fundsReserveRequested', '', '0..1', 'CodeableConcept', 'For whom to reserve fundsFundsReserve (Example)',
'fundsReserve', '', '0..1', 'CodeableConcept', 'Funds reserved statusFundsReserve (Example)',
'related', '', '0..*', 'BackboneElement', 'Prior or corollary claims',
'claim', '', '0..1', 'Reference(Claim)', 'Reference to the related claim',
'relationship', '', '0..1', 'CodeableConcept', 'How the reference claim is relatedExample Related Claim Relationship Codes (Example)',
'reference', '', '0..1', 'Identifier', 'File or case reference',
'prescription', '', '0..1', 'Reference(MedicationRequest | VisionPrescription)', 'Prescription authorizing services or products',
'originalPrescription', '', '0..1', 'Reference(MedicationRequest)', 'Original prescription if superceded by fulfiller',
'payee', '', '0..1', 'BackboneElement', 'Recipient of benefits payable',
'type', '', '0..1', 'CodeableConcept', 'Category of recipientPayeeType (Example)',
'party', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson)', 'Recipient reference',
'referral', '', '0..1', 'Reference(ServiceRequest)', 'Treatment Referral',
'facility', '', '0..1', 'Reference(Location)', 'Servicing Facility',
'claim', '', '0..1', 'Reference(Claim)', 'Claim reference',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Claim response reference',
'outcome', 'Σ', '1..1', 'code', 'queued | complete | error | partialClaim Processing Codes (Required)',
'disposition', '', '0..1', 'string', 'Disposition Message',
'preAuthRef', '', '0..*', 'string', 'Preauthorization reference',
'preAuthRefPeriod', '', '0..*', 'Period', 'Preauthorization in-effect period',
'careTeam', '', '0..*', 'BackboneElement', 'Care Team members',
'sequence', '', '1..1', 'positiveInt', 'Order of care team',
'provider', '', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Practitioner or organization',
'responsible', '', '0..1', 'boolean', 'Indicator of the lead practitioner',
'role', '', '0..1', 'CodeableConcept', 'Function within the teamClaim Care Team Role Codes (Example)',
'qualification', '', '0..1', 'CodeableConcept', 'Practitioner credential or specializationExample Provider Qualification Codes (Example)',
'supportingInfo', '', '0..*', 'BackboneElement', 'Supporting information',
'sequence', '', '1..1', 'positiveInt', 'Information instance identifier',
'category', '', '1..1', 'CodeableConcept', 'Classification of the supplied informationClaim Information Category Codes (Example)',
'code', '', '0..1', 'CodeableConcept', 'Type of informationException Codes (Example)',
'timing[x]', '', '0..1', '', 'When it occurred',
'timingDate', '', '', 'date', '',
'timingPeriod', '', '', 'Period', '',
'value[x]', '', '0..1', '', 'Data to be provided',
'valueBoolean', '', '', 'boolean', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'Quantity', '',
'valueAttachment', '', '', 'Attachment', '',
'valueReference', '', '', 'Reference(Any)', '',
'reason', '', '0..1', 'Coding', 'Explanation for the informationMissing Tooth Reason Codes (Example)',
'diagnosis', '', '0..*', 'BackboneElement', 'Pertinent diagnosis information',
'sequence', '', '1..1', 'positiveInt', 'Diagnosis instance identifier',
'diagnosis[x]', '', '1..1', '', 'Nature of illness or problemICD-10 Codes (Example)',
'diagnosisCodeableConcept', '', '', 'CodeableConcept', '',
'diagnosisReference', '', '', 'Reference(Condition)', '',
'type', '', '0..*', 'CodeableConcept', 'Timing or nature of the diagnosisExample Diagnosis Type Codes (Example)',
'onAdmission', '', '0..1', 'CodeableConcept', 'Present on admissionExample Diagnosis on Admission Codes (Example)',
'packageCode', '', '0..1', 'CodeableConcept', 'Package billing codeExample Diagnosis Related Group Codes (Example)',
'procedure', '', '0..*', 'BackboneElement', 'Clinical procedures performed',
'sequence', '', '1..1', 'positiveInt', 'Procedure instance identifier',
'type', '', '0..*', 'CodeableConcept', 'Category of ProcedureExample Procedure Type Codes (Example)',
'date', '', '0..1', 'dateTime', 'When the procedure was performed',
'procedure[x]', '', '1..1', '', 'Specific clinical procedureICD-10 Procedure Codes (Example)',
'procedureCodeableConcept', '', '', 'CodeableConcept', '',
'procedureReference', '', '', 'Reference(Procedure)', '',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'precedence', '', '0..1', 'positiveInt', 'Precedence (primary, secondary, etc.)',
'insurance', 'Σ', '1..*', 'BackboneElement', 'Patient insurance information',
'focal', 'Σ', '1..1', 'boolean', 'Coverage to be used for adjudication',
'coverage', 'Σ', '1..1', 'Reference(Coverage)', 'Insurance information',
'preAuthRef', '', '0..*', 'string', 'Prior authorization reference number',
'accident', '', '0..1', 'BackboneElement', 'Details of the event',
'date', '', '0..1', 'date', 'When the incident occurred',
'type', '', '0..1', 'CodeableConcept', 'The nature of the accidentV3 Value SetActIncidentCode (Extensible)',
'location[x]', '', '0..1', '', 'Where the event occurred',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'item', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'careTeamSequence', '', '0..*', 'positiveInt', 'Applicable care team members',
'diagnosisSequence', '', '0..*', 'positiveInt', 'Applicable diagnoses',
'procedureSequence', '', '0..*', 'positiveInt', 'Applicable procedures',
'informationSequence', '', '0..*', 'positiveInt', 'Applicable exception and supporting information',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Product or service billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'encounter', '', '0..*', 'Reference(Encounter)', 'Encounters related to this billed item',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'BackboneElement', 'Adjudication details',
'category', '', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'reason', '', '0..1', 'CodeableConcept', 'Explanation of adjudication outcomeAdjudication Reason Codes (Example)',
'amount', '', '0..1', 'Money', 'Monetary amount',
'value', '', '0..1', 'decimal', 'Non-monitary value',
'detail', '', '0..*', 'BackboneElement', 'Additional items',
'sequence', '', '1..1', 'positiveInt', 'Product or service provided',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Detail level adjudication details',
'subDetail', '', '0..*', 'BackboneElement', 'Additional items',
'sequence', '', '1..1', 'positiveInt', 'Product or service provided',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Subdetail level adjudication details',
'addItem', '', '0..*', 'BackboneElement', 'Insurer added line items',
'itemSequence', '', '0..*', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..*', 'positiveInt', 'Detail sequence number',
'subDetailSequence', '', '0..*', 'positiveInt', 'Subdetail sequence number',
'provider', '', '0..*', 'Reference(Practitioner | PractitionerRole | Organization)', 'Authorized providers',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'detail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'subDetail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'adjudication', '', '0..*', 'see adjudication', 'Header-level adjudication',
'total', 'Σ', '0..*', 'BackboneElement', 'Adjudication totals',
'category', 'Σ', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'amount', 'Σ', '1..1', 'Money', 'Financial total for the category',
'payment', '', '0..1', 'BackboneElement', 'Payment Details',
'type', '', '0..1', 'CodeableConcept', 'Partial or complete paymentExample Payment Type Codes (Example)',
'adjustment', '', '0..1', 'Money', 'Payment adjustment for non-claim issues',
'adjustmentReason', '', '0..1', 'CodeableConcept', 'Explanation for the variancePayment Adjustment Reason Codes (Example)',
'date', '', '0..1', 'date', 'Expected date of payment',
'amount', '', '0..1', 'Money', 'Payable amount after adjustment',
'identifier', '', '0..1', 'Identifier', 'Business identifier for the payment',
'formCode', '', '0..1', 'CodeableConcept', 'Printed form identifierForms (Example)',
'form', '', '0..1', 'Attachment', 'Printed reference or actual form',
'processNote', '', '0..*', 'BackboneElement', 'Note concerning adjudication',
'number', '', '0..1', 'positiveInt', 'Note instance identifier',
'type', '', '0..1', 'code', 'display | print | printoperNoteType (Required)',
'text', '', '0..1', 'string', 'Note explanatory text',
'language', '', '0..1', 'CodeableConcept', 'Language of the textCommon Languages (Preferred but limited to AllLanguages)',
'benefitPeriod', '', '0..1', 'Period', 'When the benefits are applicable',
'benefitBalance', '', '0..*', 'BackboneElement', 'Balance by Benefit Category',
'category', '', '1..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'excluded', '', '0..1', 'boolean', 'Excluded from the plan',
'name', '', '0..1', 'string', 'Short name for the benefit',
'description', '', '0..1', 'string', 'Description of the benefit or services covered',
'network', '', '0..1', 'CodeableConcept', 'In or out of networkNetwork Type Codes (Example)',
'unit', '', '0..1', 'CodeableConcept', 'Individual or familyUnit Type Codes (Example)',
'term', '', '0..1', 'CodeableConcept', 'Annual or lifetimeBenefit Term Codes (Example)',
'financial', '', '0..*', 'BackboneElement', 'Benefit Summary',
'type', '', '1..1', 'CodeableConcept', 'Benefit classificationBenefit Type Codes (Example)',
'allowed[x]', '', '0..1', '', 'Benefits allowed',
'allowedUnsignedInt', '', '', 'unsignedInt', '',
'allowedString', '', '', 'string', '',
'allowedMoney', '', '', 'Money', '',
'used[x]', '', '0..1', '', 'Benefits used',
'usedUnsignedInt', '', '', 'unsignedInt', '',
'usedMoney', '', '', 'Money', '',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <-
tibble::tribble(
~`X1`,~`X2`,
'ExplanationOfBenefit', '',
'ExplanationOfBenefit.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/explanationofbenefit-status to http://hl7.org/fhir/ValueSet/explanationofbenefit-status|4.0.1',
'ExplanationOfBenefit.type', 'Min Cardinality changed from 0 to 1
        Change binding strength from required to extensible',
'ExplanationOfBenefit.subType', 'Max Cardinality changed from * to 1',
'ExplanationOfBenefit.use', 'Added Mandatory Element',
'ExplanationOfBenefit.patient', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.created', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.enterer', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.insurer', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.provider', 'Min Cardinality changed from 0 to 1
        Type Reference: Added Target Types PractitionerRole, Organization',
'ExplanationOfBenefit.priority', 'Added Element',
'ExplanationOfBenefit.fundsReserveRequested', 'Added Element',
'ExplanationOfBenefit.fundsReserve', 'Added Element',
'ExplanationOfBenefit.payee.party', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.referral', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'ExplanationOfBenefit.outcome', 'Min Cardinality changed from 0 to 1
        Type changed from CodeableConcept to code

Add Binding http://hl7.org/fhir/ValueSet/remittance-outcome|4.0.1 (required)',
'ExplanationOfBenefit.preAuthRef', 'Added Element',
'ExplanationOfBenefit.preAuthRefPeriod', 'Added Element',
'ExplanationOfBenefit.careTeam.provider', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.supportingInfo', 'Renamed from information to supportingInfo',
'ExplanationOfBenefit.supportingInfo.sequence', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.category', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.code', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.timing[x]', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.value[x]', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo
        Add Type boolean',
'ExplanationOfBenefit.supportingInfo.reason', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.diagnosis.onAdmission', 'Added Element',
'ExplanationOfBenefit.procedure.type', 'Added Element',
'ExplanationOfBenefit.procedure.udi', 'Added Element',
'ExplanationOfBenefit.insurance', 'Min Cardinality changed from 0 to 1
        Max Cardinality changed from 1 to *',
'ExplanationOfBenefit.insurance.focal', 'Added Mandatory Element',
'ExplanationOfBenefit.insurance.coverage', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.accident.type', 'Change binding strength from required to extensible',
'ExplanationOfBenefit.item.careTeamSequence', 'Renamed from careTeamLinkId to careTeamSequence',
'ExplanationOfBenefit.item.diagnosisSequence', 'Renamed from diagnosisLinkId to diagnosisSequence',
'ExplanationOfBenefit.item.procedureSequence', 'Renamed from procedureLinkId to procedureSequence',
'ExplanationOfBenefit.item.informationSequence', 'Renamed from informationLinkId to informationSequence',
'ExplanationOfBenefit.item.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.item.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.item.detail.subDetail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ExplanationOfBenefit.addItem.detailSequence', 'Added Element',
'ExplanationOfBenefit.addItem.subDetailSequence', 'Added Element',
'ExplanationOfBenefit.addItem.provider', 'Added Element',
'ExplanationOfBenefit.addItem.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.programCode', 'Added Element',
'ExplanationOfBenefit.addItem.serviced[x]', 'Added Element',
'ExplanationOfBenefit.addItem.location[x]', 'Added Element',
'ExplanationOfBenefit.addItem.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.factor', 'Added Element',
'ExplanationOfBenefit.addItem.net', 'Renamed from fee to net',
'ExplanationOfBenefit.addItem.bodySite', 'Added Element',
'ExplanationOfBenefit.addItem.subSite', 'Added Element',
'ExplanationOfBenefit.addItem.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.detail.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.detail.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.detail.factor', 'Added Element',
'ExplanationOfBenefit.addItem.detail.net', 'Renamed from fee to net',
'ExplanationOfBenefit.addItem.detail.subDetail', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.productOrService', 'Added Mandatory Element',
'ExplanationOfBenefit.addItem.detail.subDetail.modifier', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.factor', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.net', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.noteNumber', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.adjudication', 'Added Element',
'ExplanationOfBenefit.adjudication', 'Added Element',
'ExplanationOfBenefit.total', 'Added Element',
'ExplanationOfBenefit.total.category', 'Added Mandatory Element',
'ExplanationOfBenefit.total.amount', 'Added Mandatory Element',
'ExplanationOfBenefit.formCode', 'Added Element',
'ExplanationOfBenefit.form', 'Type changed from CodeableConcept to Attachment',
'ExplanationOfBenefit.processNote.type', 'Type changed from CodeableConcept to code
        Change value set from http://hl7.org/fhir/ValueSet/note-type to http://hl7.org/fhir/ValueSet/note-type|4.0.1',
'ExplanationOfBenefit.processNote.language', 'Change binding strength from extensible to preferred',
'ExplanationOfBenefit.benefitPeriod', 'Added Element',
'ExplanationOfBenefit.organization', 'deleted',
'ExplanationOfBenefit.payee.resourceType', 'deleted',
'ExplanationOfBenefit.employmentImpacted', 'deleted',
'ExplanationOfBenefit.hospitalization', 'deleted',
'ExplanationOfBenefit.item.detail.type', 'deleted',
'ExplanationOfBenefit.item.detail.subDetail.type', 'deleted',
'ExplanationOfBenefit.addItem.revenue', 'deleted',
'ExplanationOfBenefit.addItem.category', 'deleted',
'ExplanationOfBenefit.addItem.detail.revenue', 'deleted',
'ExplanationOfBenefit.addItem.detail.category', 'deleted',
'ExplanationOfBenefit.totalCost', 'deleted',
'ExplanationOfBenefit.unallocDeductable', 'deleted',
'ExplanationOfBenefit.totalBenefit', 'deleted',
'ExplanationOfBenefit.benefitBalance.subCategory', 'deleted',
)


df5 <-
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ExplanationOfBenefit', 'TU', '', 'DomainResource', 'Explanation of Benefit resourceElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', '', '0..*', 'Identifier', 'Business Identifier for the resource',
'status', '?!Σ', '1..1', 'code', 'active | cancelled | draft | entered-in-errorExplanationOfBenefitStatus (Required)',
'type', 'Σ', '1..1', 'CodeableConcept', 'Category or disciplineClaim Type Codes (Extensible)',
'subType', '', '0..1', 'CodeableConcept', 'More granular claim typeExample Claim SubType Codes (Example)',
'use', 'Σ', '1..1', 'code', 'claim | preauthorization | predeterminationUse (Required)',
'patient', 'Σ', '1..1', 'Reference(Patient)', 'The recipient of the products and services',
'billablePeriod', 'Σ', '0..1', 'Period', 'Relevant time frame for the claim',
'created', 'Σ', '1..1', 'dateTime', 'Response creation date',
'enterer', '', '0..1', 'Reference(Practitioner | PractitionerRole)', 'Author of the claim',
'insurer', 'Σ', '1..1', 'Reference(Organization)', 'Party responsible for reimbursement',
'provider', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Party responsible for the claim',
'priority', '', '0..1', 'CodeableConcept', 'Desired processing urgencyProcessPriority  (Example)',
'fundsReserveRequested', '', '0..1', 'CodeableConcept', 'For whom to reserve fundsFundsReserve (Example)',
'fundsReserve', '', '0..1', 'CodeableConcept', 'Funds reserved statusFundsReserve (Example)',
'related', '', '0..*', 'BackboneElement', 'Prior or corollary claims',
'claim', '', '0..1', 'Reference(Claim)', 'Reference to the related claim',
'relationship', '', '0..1', 'CodeableConcept', 'How the reference claim is relatedExample Related Claim Relationship Codes (Example)',
'reference', '', '0..1', 'Identifier', 'File or case reference',
'prescription', '', '0..1', 'Reference(MedicationRequest | VisionPrescription)', 'Prescription authorizing services or products',
'originalPrescription', '', '0..1', 'Reference(MedicationRequest)', 'Original prescription if superceded by fulfiller',
'payee', '', '0..1', 'BackboneElement', 'Recipient of benefits payable',
'type', '', '0..1', 'CodeableConcept', 'Category of recipientPayeeType (Example)',
'party', '', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson)', 'Recipient reference',
'referral', '', '0..1', 'Reference(ServiceRequest)', 'Treatment Referral',
'facility', '', '0..1', 'Reference(Location)', 'Servicing Facility',
'claim', '', '0..1', 'Reference(Claim)', 'Claim reference',
'claimResponse', '', '0..1', 'Reference(ClaimResponse)', 'Claim response reference',
'outcome', 'Σ', '1..1', 'code', 'queued | complete | error | partialClaim Processing Codes (Required)',
'disposition', '', '0..1', 'string', 'Disposition Message',
'preAuthRef', '', '0..*', 'string', 'Preauthorization reference',
'preAuthRefPeriod', '', '0..*', 'Period', 'Preauthorization in-effect period',
'careTeam', '', '0..*', 'BackboneElement', 'Care Team members',
'sequence', '', '1..1', 'positiveInt', 'Order of care team',
'provider', '', '1..1', 'Reference(Practitioner | PractitionerRole | Organization)', 'Practitioner or organization',
'responsible', '', '0..1', 'boolean', 'Indicator of the lead practitioner',
'role', '', '0..1', 'CodeableConcept', 'Function within the teamClaim Care Team Role Codes (Example)',
'qualification', '', '0..1', 'CodeableConcept', 'Practitioner credential or specializationExample Provider Qualification Codes (Example)',
'supportingInfo', '', '0..*', 'BackboneElement', 'Supporting information',
'sequence', '', '1..1', 'positiveInt', 'Information instance identifier',
'category', '', '1..1', 'CodeableConcept', 'Classification of the supplied informationClaim Information Category Codes (Example)',
'code', '', '0..1', 'CodeableConcept', 'Type of informationException Codes (Example)',
'timing[x]', '', '0..1', '', 'When it occurred',
'timingDate', '', '', 'date', '',
'timingPeriod', '', '', 'Period', '',
'value[x]', '', '0..1', '', 'Data to be provided',
'valueBoolean', '', '', 'boolean', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'Quantity', '',
'valueAttachment', '', '', 'Attachment', '',
'valueReference', '', '', 'Reference(Any)', '',
'reason', '', '0..1', 'Coding', 'Explanation for the informationMissing Tooth Reason Codes (Example)',
'diagnosis', '', '0..*', 'BackboneElement', 'Pertinent diagnosis information',
'sequence', '', '1..1', 'positiveInt', 'Diagnosis instance identifier',
'diagnosis[x]', '', '1..1', '', 'Nature of illness or problemICD-10 Codes (Example)',
'diagnosisCodeableConcept', '', '', 'CodeableConcept', '',
'diagnosisReference', '', '', 'Reference(Condition)', '',
'type', '', '0..*', 'CodeableConcept', 'Timing or nature of the diagnosisExample Diagnosis Type Codes (Example)',
'onAdmission', '', '0..1', 'CodeableConcept', 'Present on admissionExample Diagnosis on Admission Codes (Example)',
'packageCode', '', '0..1', 'CodeableConcept', 'Package billing codeExample Diagnosis Related Group Codes (Example)',
'procedure', '', '0..*', 'BackboneElement', 'Clinical procedures performed',
'sequence', '', '1..1', 'positiveInt', 'Procedure instance identifier',
'type', '', '0..*', 'CodeableConcept', 'Category of ProcedureExample Procedure Type Codes (Example)',
'date', '', '0..1', 'dateTime', 'When the procedure was performed',
'procedure[x]', '', '1..1', '', 'Specific clinical procedureICD-10 Procedure Codes (Example)',
'procedureCodeableConcept', '', '', 'CodeableConcept', '',
'procedureReference', '', '', 'Reference(Procedure)', '',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'precedence', '', '0..1', 'positiveInt', 'Precedence (primary, secondary, etc.)',
'insurance', 'Σ', '1..*', 'BackboneElement', 'Patient insurance information',
'focal', 'Σ', '1..1', 'boolean', 'Coverage to be used for adjudication',
'coverage', 'Σ', '1..1', 'Reference(Coverage)', 'Insurance information',
'preAuthRef', '', '0..*', 'string', 'Prior authorization reference number',
'accident', '', '0..1', 'BackboneElement', 'Details of the event',
'date', '', '0..1', 'date', 'When the incident occurred',
'type', '', '0..1', 'CodeableConcept', 'The nature of the accidentV3 Value SetActIncidentCode (Extensible)',
'location[x]', '', '0..1', '', 'Where the event occurred',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'item', '', '0..*', 'BackboneElement', 'Product or service provided',
'sequence', '', '1..1', 'positiveInt', 'Item instance identifier',
'careTeamSequence', '', '0..*', 'positiveInt', 'Applicable care team members',
'diagnosisSequence', '', '0..*', 'positiveInt', 'Applicable diagnoses',
'procedureSequence', '', '0..*', 'positiveInt', 'Applicable procedures',
'informationSequence', '', '0..*', 'positiveInt', 'Applicable exception and supporting information',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Product or service billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'encounter', '', '0..*', 'Reference(Encounter)', 'Encounters related to this billed item',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'BackboneElement', 'Adjudication details',
'category', '', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'reason', '', '0..1', 'CodeableConcept', 'Explanation of adjudication outcomeAdjudication Reason Codes (Example)',
'amount', '', '0..1', 'Money', 'Monetary amount',
'value', '', '0..1', 'decimal', 'Non-monitary value',
'detail', '', '0..*', 'BackboneElement', 'Additional items',
'sequence', '', '1..1', 'positiveInt', 'Product or service provided',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Detail level adjudication details',
'subDetail', '', '0..*', 'BackboneElement', 'Additional items',
'sequence', '', '1..1', 'positiveInt', 'Product or service provided',
'revenue', '', '0..1', 'CodeableConcept', 'Revenue or cost center codeExample Revenue Center Codes (Example)',
'category', '', '0..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'udi', '', '0..*', 'Reference(Device)', 'Unique device identifier',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Subdetail level adjudication details',
'addItem', '', '0..*', 'BackboneElement', 'Insurer added line items',
'itemSequence', '', '0..*', 'positiveInt', 'Item sequence number',
'detailSequence', '', '0..*', 'positiveInt', 'Detail sequence number',
'subDetailSequence', '', '0..*', 'positiveInt', 'Subdetail sequence number',
'provider', '', '0..*', 'Reference(Practitioner | PractitionerRole | Organization)', 'Authorized providers',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'programCode', '', '0..*', 'CodeableConcept', 'Program the product or service is provided underExample Program Reason Codes (Example)',
'serviced[x]', '', '0..1', '', 'Date or dates of service or product delivery',
'servicedDate', '', '', 'date', '',
'servicedPeriod', '', '', 'Period', '',
'location[x]', '', '0..1', '', 'Place of service or where product was suppliedExample Service Place Codes (Example)',
'locationCodeableConcept', '', '', 'CodeableConcept', '',
'locationAddress', '', '', 'Address', '',
'locationReference', '', '', 'Reference(Location)', '',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'bodySite', '', '0..1', 'CodeableConcept', 'Anatomical locationOral Site Codes (Example)',
'subSite', '', '0..*', 'CodeableConcept', 'Anatomical sub-locationSurface Codes (Example)',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'detail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'subDetail', '', '0..*', 'BackboneElement', 'Insurer added line items',
'productOrService', '', '1..1', 'CodeableConcept', 'Billing, service, product, or drug codeUSCLS Codes (Example)',
'modifier', '', '0..*', 'CodeableConcept', 'Service/Product billing modifiersModifier type Codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'Count of products or services',
'unitPrice', '', '0..1', 'Money', 'Fee, charge or cost per item',
'factor', '', '0..1', 'decimal', 'Price scaling factor',
'net', '', '0..1', 'Money', 'Total item cost',
'noteNumber', '', '0..*', 'positiveInt', 'Applicable note numbers',
'adjudication', '', '0..*', 'see adjudication', 'Added items adjudication',
'adjudication', '', '0..*', 'see adjudication', 'Header-level adjudication',
'total', 'Σ', '0..*', 'BackboneElement', 'Adjudication totals',
'category', 'Σ', '1..1', 'CodeableConcept', 'Type of adjudication informationAdjudication Value Codes (Example)',
'amount', 'Σ', '1..1', 'Money', 'Financial total for the category',
'payment', '', '0..1', 'BackboneElement', 'Payment Details',
'type', '', '0..1', 'CodeableConcept', 'Partial or complete paymentExample Payment Type Codes (Example)',
'adjustment', '', '0..1', 'Money', 'Payment adjustment for non-claim issues',
'adjustmentReason', '', '0..1', 'CodeableConcept', 'Explanation for the variancePayment Adjustment Reason Codes (Example)',
'date', '', '0..1', 'date', 'Expected date of payment',
'amount', '', '0..1', 'Money', 'Payable amount after adjustment',
'identifier', '', '0..1', 'Identifier', 'Business identifier for the payment',
'formCode', '', '0..1', 'CodeableConcept', 'Printed form identifierForms (Example)',
'form', '', '0..1', 'Attachment', 'Printed reference or actual form',
'processNote', '', '0..*', 'BackboneElement', 'Note concerning adjudication',
'number', '', '0..1', 'positiveInt', 'Note instance identifier',
'type', '', '0..1', 'code', 'display | print | printoperNoteType (Required)',
'text', '', '0..1', 'string', 'Note explanatory text',
'language', '', '0..1', 'CodeableConcept', 'Language of the textCommon Languages (Preferred but limited to AllLanguages)',
'benefitPeriod', '', '0..1', 'Period', 'When the benefits are applicable',
'benefitBalance', '', '0..*', 'BackboneElement', 'Balance by Benefit Category',
'category', '', '1..1', 'CodeableConcept', 'Benefit classificationBenefit Category Codes (Example)',
'excluded', '', '0..1', 'boolean', 'Excluded from the plan',
'name', '', '0..1', 'string', 'Short name for the benefit',
'description', '', '0..1', 'string', 'Description of the benefit or services covered',
'network', '', '0..1', 'CodeableConcept', 'In or out of networkNetwork Type Codes (Example)',
'unit', '', '0..1', 'CodeableConcept', 'Individual or familyUnit Type Codes (Example)',
'term', '', '0..1', 'CodeableConcept', 'Annual or lifetimeBenefit Term Codes (Example)',
'financial', '', '0..*', 'BackboneElement', 'Benefit Summary',
'type', '', '1..1', 'CodeableConcept', 'Benefit classificationBenefit Type Codes (Example)',
'allowed[x]', '', '0..1', '', 'Benefits allowed',
'allowedUnsignedInt', '', '', 'unsignedInt', '',
'allowedString', '', '', 'string', '',
'allowedMoney', '', '', 'Money', '',
'used[x]', '', '0..1', '', 'Benefits used',
'usedUnsignedInt', '', '', 'unsignedInt', '',
'usedMoney', '', '', 'Money', '',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df6 <-
tibble::tribble(
~`X1`,~`X2`,
'ExplanationOfBenefit', '',
'ExplanationOfBenefit.status', 'Min Cardinality changed from 0 to 1
        Change value set from http://hl7.org/fhir/ValueSet/explanationofbenefit-status to http://hl7.org/fhir/ValueSet/explanationofbenefit-status|4.0.1',
'ExplanationOfBenefit.type', 'Min Cardinality changed from 0 to 1
        Change binding strength from required to extensible',
'ExplanationOfBenefit.subType', 'Max Cardinality changed from * to 1',
'ExplanationOfBenefit.use', 'Added Mandatory Element',
'ExplanationOfBenefit.patient', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.created', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.enterer', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.insurer', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.provider', 'Min Cardinality changed from 0 to 1
        Type Reference: Added Target Types PractitionerRole, Organization',
'ExplanationOfBenefit.priority', 'Added Element',
'ExplanationOfBenefit.fundsReserveRequested', 'Added Element',
'ExplanationOfBenefit.fundsReserve', 'Added Element',
'ExplanationOfBenefit.payee.party', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.referral', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Type ReferralRequest',
'ExplanationOfBenefit.outcome', 'Min Cardinality changed from 0 to 1
        Type changed from CodeableConcept to code

Add Binding http://hl7.org/fhir/ValueSet/remittance-outcome|4.0.1 (required)',
'ExplanationOfBenefit.preAuthRef', 'Added Element',
'ExplanationOfBenefit.preAuthRefPeriod', 'Added Element',
'ExplanationOfBenefit.careTeam.provider', 'Type Reference: Added Target Type PractitionerRole',
'ExplanationOfBenefit.supportingInfo', 'Renamed from information to supportingInfo',
'ExplanationOfBenefit.supportingInfo.sequence', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.category', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.code', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.timing[x]', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.supportingInfo.value[x]', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo
        Add Type boolean',
'ExplanationOfBenefit.supportingInfo.reason', 'Moved from ExplanationOfBenefit.information to ExplanationOfBenefit.supportingInfo',
'ExplanationOfBenefit.diagnosis.onAdmission', 'Added Element',
'ExplanationOfBenefit.procedure.type', 'Added Element',
'ExplanationOfBenefit.procedure.udi', 'Added Element',
'ExplanationOfBenefit.insurance', 'Min Cardinality changed from 0 to 1
        Max Cardinality changed from 1 to *',
'ExplanationOfBenefit.insurance.focal', 'Added Mandatory Element',
'ExplanationOfBenefit.insurance.coverage', 'Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.accident.type', 'Change binding strength from required to extensible',
'ExplanationOfBenefit.item.careTeamSequence', 'Renamed from careTeamLinkId to careTeamSequence',
'ExplanationOfBenefit.item.diagnosisSequence', 'Renamed from diagnosisLinkId to diagnosisSequence',
'ExplanationOfBenefit.item.procedureSequence', 'Renamed from procedureLinkId to procedureSequence',
'ExplanationOfBenefit.item.informationSequence', 'Renamed from informationLinkId to informationSequence',
'ExplanationOfBenefit.item.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.item.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.item.detail.subDetail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.itemSequence', 'Renamed from sequenceLinkId to itemSequence',
'ExplanationOfBenefit.addItem.detailSequence', 'Added Element',
'ExplanationOfBenefit.addItem.subDetailSequence', 'Added Element',
'ExplanationOfBenefit.addItem.provider', 'Added Element',
'ExplanationOfBenefit.addItem.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.programCode', 'Added Element',
'ExplanationOfBenefit.addItem.serviced[x]', 'Added Element',
'ExplanationOfBenefit.addItem.location[x]', 'Added Element',
'ExplanationOfBenefit.addItem.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.factor', 'Added Element',
'ExplanationOfBenefit.addItem.net', 'Renamed from fee to net',
'ExplanationOfBenefit.addItem.bodySite', 'Added Element',
'ExplanationOfBenefit.addItem.subSite', 'Added Element',
'ExplanationOfBenefit.addItem.detail.productOrService', 'Renamed from service to productOrService
        Min Cardinality changed from 0 to 1',
'ExplanationOfBenefit.addItem.detail.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.detail.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.detail.factor', 'Added Element',
'ExplanationOfBenefit.addItem.detail.net', 'Renamed from fee to net',
'ExplanationOfBenefit.addItem.detail.subDetail', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.productOrService', 'Added Mandatory Element',
'ExplanationOfBenefit.addItem.detail.subDetail.modifier', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.quantity', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.unitPrice', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.factor', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.net', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.noteNumber', 'Added Element',
'ExplanationOfBenefit.addItem.detail.subDetail.adjudication', 'Added Element',
'ExplanationOfBenefit.adjudication', 'Added Element',
'ExplanationOfBenefit.total', 'Added Element',
'ExplanationOfBenefit.total.category', 'Added Mandatory Element',
'ExplanationOfBenefit.total.amount', 'Added Mandatory Element',
'ExplanationOfBenefit.formCode', 'Added Element',
'ExplanationOfBenefit.form', 'Type changed from CodeableConcept to Attachment',
'ExplanationOfBenefit.processNote.type', 'Type changed from CodeableConcept to code
        Change value set from http://hl7.org/fhir/ValueSet/note-type to http://hl7.org/fhir/ValueSet/note-type|4.0.1',
'ExplanationOfBenefit.processNote.language', 'Change binding strength from extensible to preferred',
'ExplanationOfBenefit.benefitPeriod', 'Added Element',
'ExplanationOfBenefit.organization', 'deleted',
'ExplanationOfBenefit.payee.resourceType', 'deleted',
'ExplanationOfBenefit.employmentImpacted', 'deleted',
'ExplanationOfBenefit.hospitalization', 'deleted',
'ExplanationOfBenefit.item.detail.type', 'deleted',
'ExplanationOfBenefit.item.detail.subDetail.type', 'deleted',
'ExplanationOfBenefit.addItem.revenue', 'deleted',
'ExplanationOfBenefit.addItem.category', 'deleted',
'ExplanationOfBenefit.addItem.detail.revenue', 'deleted',
'ExplanationOfBenefit.addItem.detail.category', 'deleted',
'ExplanationOfBenefit.totalCost', 'deleted',
'ExplanationOfBenefit.unallocDeductable', 'deleted',
'ExplanationOfBenefit.totalBenefit', 'deleted',
'ExplanationOfBenefit.benefitBalance.subCategory', 'deleted',
)


df7 <-
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ExplanationOfBenefit.status', 'A code specifying the state of the resource instance.', 'Required', 'ExplanationOfBenefitStatus',
'ExplanationOfBenefit.type', 'The type or discipline-style of the claim.', 'Extensible', 'ClaimTypeCodes',
'ExplanationOfBenefit.subType', 'A more granular claim typecode.', 'Example', 'ExampleClaimSubTypeCodes',
'ExplanationOfBenefit.use', 'Complete, proposed, exploratory, other.', 'Required', 'Use',
'ExplanationOfBenefit.priority', 'The timeliness with which processing is required: stat, normal, deferred.', 'Example', 'http://terminology.hl7.org/CodeSystem/processpriority',
'ExplanationOfBenefit.fundsReserveRequestedExplanationOfBenefit.fundsReserve', 'For whom funds are to be reserved: (Patient, Provider, None).', 'Example', 'Funds Reservation Codes',
'ExplanationOfBenefit.related.relationship', 'Relationship of this claim to a related Claim.', 'Example', 'ExampleRelatedClaimRelationshipCodes',
'ExplanationOfBenefit.payee.type', 'A code for the party to be reimbursed.', 'Example', 'Claim Payee Type Codes',
'ExplanationOfBenefit.outcome', 'The result of the claim processing.', 'Required', 'ClaimProcessingCodes',
'ExplanationOfBenefit.careTeam.role', 'The role codes for the care team members.', 'Example', 'ClaimCareTeamRoleCodes',
'ExplanationOfBenefit.careTeam.qualification', 'Provider professional qualifications.', 'Example', 'ExampleProviderQualificationCodes',
'ExplanationOfBenefit.supportingInfo.category', 'The valuset used for additional information category codes.', 'Example', 'ClaimInformationCategoryCodes',
'ExplanationOfBenefit.supportingInfo.code', 'The valuset used for additional information codes.', 'Example', 'ExceptionCodes',
'ExplanationOfBenefit.supportingInfo.reason', 'Reason codes for the missing teeth.', 'Example', 'MissingToothReasonCodes',
'ExplanationOfBenefit.diagnosis.diagnosis[x]', 'ICD10 Diagnostic codes.', 'Example', 'ICD-10Codes',
'ExplanationOfBenefit.diagnosis.type', 'The type of the diagnosis: admitting, principal, discharge.', 'Example', 'ExampleDiagnosisTypeCodes',
'ExplanationOfBenefit.diagnosis.onAdmission', 'Present on admission.', 'Example', 'ExampleDiagnosisOnAdmissionCodes',
'ExplanationOfBenefit.diagnosis.packageCode', 'The DRG codes associated with the diagnosis.', 'Example', 'ExampleDiagnosisRelatedGroupCodes',
'ExplanationOfBenefit.procedure.type', 'Example procedure type codes.', 'Example', 'ExampleProcedureTypeCodes',
'ExplanationOfBenefit.procedure.procedure[x]', 'ICD10 Procedure codes.', 'Example', 'ICD-10ProcedureCodes',
'ExplanationOfBenefit.accident.type', 'Type of accident: work place, auto, etc.', 'Extensible', 'v3.ActIncidentCode',
'ExplanationOfBenefit.item.revenueExplanationOfBenefit.item.detail.revenueExplanationOfBenefit.item.detail.subDetail.revenue', 'Codes for the revenue or cost centers supplying the service and/or products.', 'Example', 'ExampleRevenueCenterCodes',
'ExplanationOfBenefit.item.categoryExplanationOfBenefit.item.detail.categoryExplanationOfBenefit.item.detail.subDetail.categoryExplanationOfBenefit.benefitBalance.category', 'Benefit categories such as: oral, medical, vision, oral-basic etc.', 'Example', 'BenefitCategoryCodes',
'ExplanationOfBenefit.item.productOrServiceExplanationOfBenefit.item.detail.productOrServiceExplanationOfBenefit.item.detail.subDetail.productOrServiceExplanationOfBenefit.addItem.productOrServiceExplanationOfBenefit.addItem.detail.productOrServiceExplanationOfBenefit.addItem.detail.subDetail.productOrService', 'Allowable service and product codes.', 'Example', 'USCLSCodes',
'ExplanationOfBenefit.item.modifierExplanationOfBenefit.item.detail.modifierExplanationOfBenefit.item.detail.subDetail.modifierExplanationOfBenefit.addItem.modifierExplanationOfBenefit.addItem.detail.modifierExplanationOfBenefit.addItem.detail.subDetail.modifier', 'Item type or modifiers codes, eg for Oral whether the treatment is cosmetic or associated with TMJ, or an appliance was lost or stolen.', 'Example', 'ModifierTypeCodes',
'ExplanationOfBenefit.item.programCodeExplanationOfBenefit.item.detail.programCodeExplanationOfBenefit.item.detail.subDetail.programCodeExplanationOfBenefit.addItem.programCode', 'Program specific reason codes.', 'Example', 'ExampleProgramReasonCodes',
'ExplanationOfBenefit.item.location[x]ExplanationOfBenefit.addItem.location[x]', 'Place where the service is rendered.', 'Example', 'ExampleServicePlaceCodes',
'ExplanationOfBenefit.item.bodySiteExplanationOfBenefit.addItem.bodySite', 'The code for the teeth, quadrant, sextant and arch.', 'Example', 'OralSiteCodes',
'ExplanationOfBenefit.item.subSiteExplanationOfBenefit.addItem.subSite', 'The code for the tooth surface and surface combinations.', 'Example', 'SurfaceCodes',
'ExplanationOfBenefit.item.adjudication.categoryExplanationOfBenefit.total.category', 'The adjudication codes.', 'Example', 'AdjudicationValueCodes',
'ExplanationOfBenefit.item.adjudication.reason', 'Adjudication reason codes.', 'Example', 'AdjudicationReasonCodes',
'ExplanationOfBenefit.payment.type', 'The type (partial, complete) of the payment.', 'Example', 'ExamplePaymentTypeCodes',
'ExplanationOfBenefit.payment.adjustmentReason', 'Payment Adjustment reason codes.', 'Example', 'PaymentAdjustmentReasonCodes',
'ExplanationOfBenefit.formCode', 'The forms codes.', 'Example', 'Form Codes',
'ExplanationOfBenefit.processNote.type', 'The presentation types of notes.', 'Required', 'NoteType',
'ExplanationOfBenefit.processNote.language', 'A human language.', 'Preferred, but limited to AllLanguages', 'CommonLanguages',
'ExplanationOfBenefit.benefitBalance.network', 'Code to classify in or out of network services.', 'Example', 'NetworkTypeCodes',
'ExplanationOfBenefit.benefitBalance.unit', 'Unit covered/serviced - individual or family.', 'Example', 'UnitTypeCodes',
'ExplanationOfBenefit.benefitBalance.term', 'Coverage unit - annual, lifetime.', 'Example', 'BenefitTermCodes',
'ExplanationOfBenefit.benefitBalance.financial.type', 'Deductable, visits, co-pay, etc.', 'Example', 'BenefitTypeCodes',
)


df8 <-
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'care-team', 'reference', 'Member of the CareTeam', 'ExplanationOfBenefit.careTeam.provider(Practitioner, Organization, PractitionerRole)', '',
'claim', 'reference', 'The reference to the claim', 'ExplanationOfBenefit.claim(Claim)', '',
'coverage', 'reference', 'The plan under which the claim was adjudicated', 'ExplanationOfBenefit.insurance.coverage(Coverage)', '',
'created', 'date', 'The creation date for the EOB', 'ExplanationOfBenefit.created', '',
'detail-udi', 'reference', 'UDI associated with a line item detail product or service', 'ExplanationOfBenefit.item.detail.udi(Device)', '',
'disposition', 'string', 'The contents of the disposition message', 'ExplanationOfBenefit.disposition', '',
'encounter', 'reference', 'Encounters associated with a billed line item', 'ExplanationOfBenefit.item.encounter(Encounter)', '',
'enterer', 'reference', 'The party responsible for the entry of the Claim', 'ExplanationOfBenefit.enterer(Practitioner, PractitionerRole)', '',
'facility', 'reference', 'Facility responsible for the goods and services', 'ExplanationOfBenefit.facility(Location)', '',
'identifier', 'token', 'The business identifier of the Explanation of Benefit', 'ExplanationOfBenefit.identifier', '',
'item-udi', 'reference', 'UDI associated with a line item product or service', 'ExplanationOfBenefit.item.udi(Device)', '',
'patient', 'reference', 'The reference to the patient', 'ExplanationOfBenefit.patient(Patient)', '',
'payee', 'reference', 'The party receiving any payment for the Claim', 'ExplanationOfBenefit.payee.party(Practitioner, Organization, Patient, PractitionerRole, RelatedPerson)', '',
'procedure-udi', 'reference', 'UDI associated with a procedure', 'ExplanationOfBenefit.procedure.udi(Device)', '',
'provider', 'reference', 'The reference to the provider', 'ExplanationOfBenefit.provider(Practitioner, Organization, PractitionerRole)', '',
'status', 'token', 'Status of the instance', 'ExplanationOfBenefit.status', '',
'subdetail-udi', 'reference', 'UDI associated with a line item detail subdetail product or service', 'ExplanationOfBenefit.item.detail.subDetail.udi(Device)', '',
)


