df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: 1', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ImplementationGuide', 'ITU', '', 'DomainResource', 'A set of rules about how FHIR is used+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: If a resource has a fhirVersion, it must be oe of the versions defined for the Implementation GuideElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this implementation guide, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the implementation guide',
'name', 'ΣI', '1..1', 'string', 'Name for this implementation guide (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this implementation guide (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the implementation guide',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for implementation guide (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'packageId', 'Σ', '1..1', 'id', 'NPM Package name for IG',
'license', 'Σ', '0..1', 'code', 'SPDX license code for this IG (or not-open-source)SPDXLicense (Required)',
'fhirVersion', 'Σ', '1..*', 'code', 'FHIR Version(s) this Implementation Guide targetsFHIRVersion (Required)',
'dependsOn', 'Σ', '0..*', 'BackboneElement', 'Another Implementation guide this depends on',
'uri', 'Σ', '1..1', 'canonical(ImplementationGuide)', 'Identity of the IG that this depends on',
'packageId', 'Σ', '0..1', 'id', 'NPM Package name for IG this depends on',
'version', 'Σ', '0..1', 'string', 'Version of the IG',
'global', 'Σ', '0..*', 'BackboneElement', 'Profiles that apply globally',
'type', 'Σ', '1..1', 'code', 'Type this profile applies toResourceType (Required)',
'profile', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Profile that all resources must conform to',
'definition', 'I', '0..1', 'BackboneElement', 'Information needed to build the IG+ Rule: If a resource has a groupingId, it must refer to a grouping defined in the Implementation Guide',
'grouping', '', '0..*', 'BackboneElement', 'Grouping used to present related resources in the IG',
'name', '', '1..1', 'string', 'Descriptive name for the package',
'description', '', '0..1', 'string', 'Human readable text describing the package',
'resource', '', '1..*', 'BackboneElement', 'Resource in the implementation guide',
'reference', '', '1..1', 'Reference(Any)', 'Location of the resource',
'fhirVersion', '', '0..*', 'code', 'Versions this applies to (if different to IG)FHIRVersion (Required)',
'name', '', '0..1', 'string', 'Human Name for the resource',
'description', '', '0..1', 'string', 'Reason why included in guide',
'example[x]', '', '0..1', '', 'Is an example/What is this an example of?',
'exampleBoolean', '', '', 'boolean', '',
'exampleCanonical', '', '', 'canonical(StructureDefinition)', '',
'groupingId', '', '0..1', 'id', 'Grouping this is part of',
'page', '', '0..1', 'BackboneElement', 'Page/Section in the Guide',
'name[x]', '', '1..1', '', 'Where to find that page',
'nameUrl', '', '', 'url', '',
'nameReference', '', '', 'Reference(Binary)', '',
'title', '', '1..1', 'string', 'Short title shown for navigational assistance',
'generation', '', '1..1', 'code', 'html | markdown | xml | generatedGuidePageGeneration (Required)',
'page', '', '0..*', 'see page', 'Nested Pages / Sections',
'parameter', '', '0..*', 'BackboneElement', 'Defines how IG is built by tools',
'code', '', '1..1', 'code', 'apply | path-resource | path-pages | path-tx-cache | expansion-parameter | rule-broken-links | generate-xml | generate-json | generate-turtle | html-templateGuideParameterCode (Required)',
'value', '', '1..1', 'string', 'Value for named type',
'template', '', '0..*', 'BackboneElement', 'A template for building resources',
'code', '', '1..1', 'code', 'Type of template specified',
'source', '', '1..1', 'string', 'The source location for the template',
'scope', '', '0..1', 'string', 'The scope in which the template applies',
'manifest', '', '0..1', 'BackboneElement', 'Information about an assembled IG',
'rendering', 'Σ', '0..1', 'url', 'Location of rendered implementation guide',
'resource', 'Σ', '1..*', 'BackboneElement', 'Resource in the implementation guide',
'reference', 'Σ', '1..1', 'Reference(Any)', 'Location of the resource',
'example[x]', '', '0..1', '', 'Is an example/What is this an example of?',
'exampleBoolean', '', '', 'boolean', '',
'exampleCanonical', '', '', 'canonical(StructureDefinition)', '',
'relativePath', '', '0..1', 'url', 'Relative path for page in IG',
'page', '', '0..*', 'BackboneElement', 'HTML page within the parent IG',
'name', '', '1..1', 'string', 'HTML page name',
'title', '', '0..1', 'string', 'Title of the page, for references',
'anchor', '', '0..*', 'string', 'Anchor available on the page',
'image', '', '0..*', 'string', 'Image within the IG',
'other', '', '0..*', 'string', 'Additional linkable file in IG',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'ImplementationGuide', '',
'ImplementationGuide', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'ImplementationGuide.title', 'Added Element',
'ImplementationGuide.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'ImplementationGuide.experimental', 'No longer marked as Modifier',
'ImplementationGuide.packageId', 'Added Mandatory Element',
'ImplementationGuide.license', 'Added Element',
'ImplementationGuide.fhirVersion', 'Min Cardinality changed from 0 to 1
        Max Cardinality changed from 1 to *
        Type changed from id to code
        
Add Binding http://hl7.org/fhir/ValueSet/FHIR-version|4.0.1 (required)',
'ImplementationGuide.dependsOn', 'Renamed from dependency to dependsOn',
'ImplementationGuide.dependsOn.uri', 'Moved from ImplementationGuide.dependency to ImplementationGuide.dependsOn
        Type changed from uri to canonical(ImplementationGuide)',
'ImplementationGuide.dependsOn.packageId', 'Added Element',
'ImplementationGuide.dependsOn.version', 'Added Element',
'ImplementationGuide.global.type', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'ImplementationGuide.global.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'ImplementationGuide.definition', 'Added Element',
'ImplementationGuide.definition.grouping', 'Added Element',
'ImplementationGuide.definition.grouping.name', 'Added Mandatory Element',
'ImplementationGuide.definition.grouping.description', 'Added Element',
'ImplementationGuide.definition.resource', 'Moved from ImplementationGuide.package to ImplementationGuide.definition',
'ImplementationGuide.definition.resource.reference', 'Added Mandatory Element',
'ImplementationGuide.definition.resource.fhirVersion', 'Added Element',
'ImplementationGuide.definition.resource.example[x]', 'Moved from ImplementationGuide.package.resource.example to example[x]
        Min Cardinality changed from 1 to 0
        Add Type canonical(StructureDefinition)',
'ImplementationGuide.definition.resource.groupingId', 'Added Element',
'ImplementationGuide.definition.page', 'Moved from ImplementationGuide to ImplementationGuide.definition',
'ImplementationGuide.definition.page.name[x]', 'Added Mandatory Element',
'ImplementationGuide.definition.page.generation', 'Added Mandatory Element',
'ImplementationGuide.definition.parameter', 'Added Element',
'ImplementationGuide.definition.parameter.code', 'Added Mandatory Element',
'ImplementationGuide.definition.parameter.value', 'Added Mandatory Element',
'ImplementationGuide.definition.template', 'Added Element',
'ImplementationGuide.definition.template.code', 'Added Mandatory Element',
'ImplementationGuide.definition.template.source', 'Added Mandatory Element',
'ImplementationGuide.definition.template.scope', 'Added Element',
'ImplementationGuide.manifest', 'Added Element',
'ImplementationGuide.manifest.rendering', 'Added Element',
'ImplementationGuide.manifest.resource', 'Added Mandatory Element',
'ImplementationGuide.manifest.resource.reference', 'Added Mandatory Element',
'ImplementationGuide.manifest.resource.example[x]', 'Added Element',
'ImplementationGuide.manifest.resource.relativePath', 'Added Element',
'ImplementationGuide.manifest.page', 'Added Element',
'ImplementationGuide.manifest.page.name', 'Added Mandatory Element',
'ImplementationGuide.manifest.page.title', 'Added Element',
'ImplementationGuide.manifest.page.anchor', 'Added Element',
'ImplementationGuide.manifest.image', 'Added Element',
'ImplementationGuide.manifest.other', 'Added Element',
'ImplementationGuide.dependency.type', 'deleted',
'ImplementationGuide.package', 'deleted',
'ImplementationGuide.binary', 'deleted',
'ImplementationGuide.page.source', 'deleted',
'ImplementationGuide.page.kind', 'deleted',
'ImplementationGuide.page.type', 'deleted',
'ImplementationGuide.page.package', 'deleted',
'ImplementationGuide.page.format', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ImplementationGuide', 'ITU', '', 'DomainResource', 'A set of rules about how FHIR is used+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: If a resource has a fhirVersion, it must be oe of the versions defined for the Implementation GuideElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this implementation guide, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the implementation guide',
'name', 'ΣI', '1..1', 'string', 'Name for this implementation guide (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this implementation guide (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the implementation guide',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for implementation guide (if applicable)Jurisdiction (Extensible)',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'packageId', 'Σ', '1..1', 'id', 'NPM Package name for IG',
'license', 'Σ', '0..1', 'code', 'SPDX license code for this IG (or not-open-source)SPDXLicense (Required)',
'fhirVersion', 'Σ', '1..*', 'code', 'FHIR Version(s) this Implementation Guide targetsFHIRVersion (Required)',
'dependsOn', 'Σ', '0..*', 'BackboneElement', 'Another Implementation guide this depends on',
'uri', 'Σ', '1..1', 'canonical(ImplementationGuide)', 'Identity of the IG that this depends on',
'packageId', 'Σ', '0..1', 'id', 'NPM Package name for IG this depends on',
'version', 'Σ', '0..1', 'string', 'Version of the IG',
'global', 'Σ', '0..*', 'BackboneElement', 'Profiles that apply globally',
'type', 'Σ', '1..1', 'code', 'Type this profile applies toResourceType (Required)',
'profile', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Profile that all resources must conform to',
'definition', 'I', '0..1', 'BackboneElement', 'Information needed to build the IG+ Rule: If a resource has a groupingId, it must refer to a grouping defined in the Implementation Guide',
'grouping', '', '0..*', 'BackboneElement', 'Grouping used to present related resources in the IG',
'name', '', '1..1', 'string', 'Descriptive name for the package',
'description', '', '0..1', 'string', 'Human readable text describing the package',
'resource', '', '1..*', 'BackboneElement', 'Resource in the implementation guide',
'reference', '', '1..1', 'Reference(Any)', 'Location of the resource',
'fhirVersion', '', '0..*', 'code', 'Versions this applies to (if different to IG)FHIRVersion (Required)',
'name', '', '0..1', 'string', 'Human Name for the resource',
'description', '', '0..1', 'string', 'Reason why included in guide',
'example[x]', '', '0..1', '', 'Is an example/What is this an example of?',
'exampleBoolean', '', '', 'boolean', '',
'exampleCanonical', '', '', 'canonical(StructureDefinition)', '',
'groupingId', '', '0..1', 'id', 'Grouping this is part of',
'page', '', '0..1', 'BackboneElement', 'Page/Section in the Guide',
'name[x]', '', '1..1', '', 'Where to find that page',
'nameUrl', '', '', 'url', '',
'nameReference', '', '', 'Reference(Binary)', '',
'title', '', '1..1', 'string', 'Short title shown for navigational assistance',
'generation', '', '1..1', 'code', 'html | markdown | xml | generatedGuidePageGeneration (Required)',
'page', '', '0..*', 'see page', 'Nested Pages / Sections',
'parameter', '', '0..*', 'BackboneElement', 'Defines how IG is built by tools',
'code', '', '1..1', 'code', 'apply | path-resource | path-pages | path-tx-cache | expansion-parameter | rule-broken-links | generate-xml | generate-json | generate-turtle | html-templateGuideParameterCode (Required)',
'value', '', '1..1', 'string', 'Value for named type',
'template', '', '0..*', 'BackboneElement', 'A template for building resources',
'code', '', '1..1', 'code', 'Type of template specified',
'source', '', '1..1', 'string', 'The source location for the template',
'scope', '', '0..1', 'string', 'The scope in which the template applies',
'manifest', '', '0..1', 'BackboneElement', 'Information about an assembled IG',
'rendering', 'Σ', '0..1', 'url', 'Location of rendered implementation guide',
'resource', 'Σ', '1..*', 'BackboneElement', 'Resource in the implementation guide',
'reference', 'Σ', '1..1', 'Reference(Any)', 'Location of the resource',
'example[x]', '', '0..1', '', 'Is an example/What is this an example of?',
'exampleBoolean', '', '', 'boolean', '',
'exampleCanonical', '', '', 'canonical(StructureDefinition)', '',
'relativePath', '', '0..1', 'url', 'Relative path for page in IG',
'page', '', '0..*', 'BackboneElement', 'HTML page within the parent IG',
'name', '', '1..1', 'string', 'HTML page name',
'title', '', '0..1', 'string', 'Title of the page, for references',
'anchor', '', '0..*', 'string', 'Anchor available on the page',
'image', '', '0..*', 'string', 'Image within the IG',
'other', '', '0..*', 'string', 'Additional linkable file in IG',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'ImplementationGuide', '',
'ImplementationGuide', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'ImplementationGuide.title', 'Added Element',
'ImplementationGuide.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'ImplementationGuide.experimental', 'No longer marked as Modifier',
'ImplementationGuide.packageId', 'Added Mandatory Element',
'ImplementationGuide.license', 'Added Element',
'ImplementationGuide.fhirVersion', 'Min Cardinality changed from 0 to 1
        Max Cardinality changed from 1 to *
        Type changed from id to code
        
Add Binding http://hl7.org/fhir/ValueSet/FHIR-version|4.0.1 (required)',
'ImplementationGuide.dependsOn', 'Renamed from dependency to dependsOn',
'ImplementationGuide.dependsOn.uri', 'Moved from ImplementationGuide.dependency to ImplementationGuide.dependsOn
        Type changed from uri to canonical(ImplementationGuide)',
'ImplementationGuide.dependsOn.packageId', 'Added Element',
'ImplementationGuide.dependsOn.version', 'Added Element',
'ImplementationGuide.global.type', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'ImplementationGuide.global.profile', 'Type changed from Reference(StructureDefinition) to canonical(StructureDefinition)',
'ImplementationGuide.definition', 'Added Element',
'ImplementationGuide.definition.grouping', 'Added Element',
'ImplementationGuide.definition.grouping.name', 'Added Mandatory Element',
'ImplementationGuide.definition.grouping.description', 'Added Element',
'ImplementationGuide.definition.resource', 'Moved from ImplementationGuide.package to ImplementationGuide.definition',
'ImplementationGuide.definition.resource.reference', 'Added Mandatory Element',
'ImplementationGuide.definition.resource.fhirVersion', 'Added Element',
'ImplementationGuide.definition.resource.example[x]', 'Moved from ImplementationGuide.package.resource.example to example[x]
        Min Cardinality changed from 1 to 0
        Add Type canonical(StructureDefinition)',
'ImplementationGuide.definition.resource.groupingId', 'Added Element',
'ImplementationGuide.definition.page', 'Moved from ImplementationGuide to ImplementationGuide.definition',
'ImplementationGuide.definition.page.name[x]', 'Added Mandatory Element',
'ImplementationGuide.definition.page.generation', 'Added Mandatory Element',
'ImplementationGuide.definition.parameter', 'Added Element',
'ImplementationGuide.definition.parameter.code', 'Added Mandatory Element',
'ImplementationGuide.definition.parameter.value', 'Added Mandatory Element',
'ImplementationGuide.definition.template', 'Added Element',
'ImplementationGuide.definition.template.code', 'Added Mandatory Element',
'ImplementationGuide.definition.template.source', 'Added Mandatory Element',
'ImplementationGuide.definition.template.scope', 'Added Element',
'ImplementationGuide.manifest', 'Added Element',
'ImplementationGuide.manifest.rendering', 'Added Element',
'ImplementationGuide.manifest.resource', 'Added Mandatory Element',
'ImplementationGuide.manifest.resource.reference', 'Added Mandatory Element',
'ImplementationGuide.manifest.resource.example[x]', 'Added Element',
'ImplementationGuide.manifest.resource.relativePath', 'Added Element',
'ImplementationGuide.manifest.page', 'Added Element',
'ImplementationGuide.manifest.page.name', 'Added Mandatory Element',
'ImplementationGuide.manifest.page.title', 'Added Element',
'ImplementationGuide.manifest.page.anchor', 'Added Element',
'ImplementationGuide.manifest.image', 'Added Element',
'ImplementationGuide.manifest.other', 'Added Element',
'ImplementationGuide.dependency.type', 'deleted',
'ImplementationGuide.package', 'deleted',
'ImplementationGuide.binary', 'deleted',
'ImplementationGuide.page.source', 'deleted',
'ImplementationGuide.page.kind', 'deleted',
'ImplementationGuide.page.type', 'deleted',
'ImplementationGuide.page.package', 'deleted',
'ImplementationGuide.page.format', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ImplementationGuide.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'ImplementationGuide.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'ImplementationGuide.license', 'The license that applies to an Implementation Guide (using an SPDX license Identifiers, or 'not-open-source'). The binding is required but new SPDX license Identifiers are allowed to be used (https://spdx.org/licenses/).', 'Required', 'SPDXLicense',
'ImplementationGuide.fhirVersionImplementationGuide.definition.resource.fhirVersion', 'All published FHIR Versions.', 'Required', 'FHIRVersion',
'ImplementationGuide.global.type', 'One of the resource types defined as part of this version of FHIR.', 'Required', 'Resource Types',
'ImplementationGuide.definition.page.generation', 'A code that indicates how the page is generated.', 'Required', 'GuidePageGeneration',
'ImplementationGuide.definition.parameter.code', 'Code of parameter that is input to the guide.', 'Required', 'GuideParameterCode',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'ig-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'ig-1', 'Rule', 'ImplementationGuide.definition', 'If a resource has a groupingId, it must refer to a grouping defined in the Implementation Guide', 'resource.groupingId.all(%context.grouping.id contains $this)',
'ig-2', 'Rule', '(base)', 'If a resource has a fhirVersion, it must be oe of the versions defined for the Implementation Guide', 'definition.resource.fhirVersion.all(%context.fhirVersion contains $this)',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the implementation guide', '(ImplementationGuide.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the implementation guide', '(ImplementationGuide.useContext.value as Quantity) | (ImplementationGuide.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the implementation guide', 'ImplementationGuide.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the implementation guide', 'On ImplementationGuide.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the implementation guide', 'On ImplementationGuide.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The implementation guide publication date', 'ImplementationGuide.date', '',
'depends-on', 'reference', 'Identity of the IG that this depends on', 'ImplementationGuide.dependsOn.uri(ImplementationGuide)', '',
'description', 'string', 'The description of the implementation guide', 'ImplementationGuide.description', '',
'experimental', 'token', 'For testing purposes, not real usage', 'ImplementationGuide.experimental', '',
'global', 'reference', 'Profile that all resources must conform to', 'ImplementationGuide.global.profile(StructureDefinition)', '',
'jurisdiction', 'token', 'Intended jurisdiction for the implementation guide', 'ImplementationGuide.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the implementation guide', 'ImplementationGuide.name', '',
'publisher', 'string', 'Name of the publisher of the implementation guide', 'ImplementationGuide.publisher', '',
'resource', 'reference', 'Location of the resource', 'ImplementationGuide.definition.resource.reference(Any)', '',
'status', 'token', 'The current status of the implementation guide', 'ImplementationGuide.status', '',
'title', 'string', 'The human-friendly name of the implementation guide', 'ImplementationGuide.title', '',
'url', 'uri', 'The uri that identifies the implementation guide', 'ImplementationGuide.url', '',
'version', 'token', 'The business version of the implementation guide', 'ImplementationGuide.version', '',
)


