df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Quality Information  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Measure', 'ITU', '', 'DomainResource', 'A quality measure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: Stratifier SHALL be either a single criteria or a set of criteria componentsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this measure, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the measure',
'version', 'Σ', '0..1', 'string', 'Business version of the measure',
'name', 'ΣI', '0..1', 'string', 'Name for this measure (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this measure (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the measure',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'E.g. Patient, Practitioner, RelatedPerson, Organization, Location, DeviceSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the measure',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for measure (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this measure is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the measure',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the measure was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the measure was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the measure is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the measure, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the measure',
'disclaimer', 'Σ', '0..1', 'markdown', 'Disclaimer for use of the measure or its referenced content',
'scoring', 'Σ', '0..1', 'CodeableConcept', 'proportion | ratio | continuous-variable | cohortMeasureScoring (Extensible)',
'compositeScoring', 'Σ', '0..1', 'CodeableConcept', 'opportunity | all-or-nothing | linear | weightedCompositeMeasureScoring (Extensible)',
'type', 'Σ', '0..*', 'CodeableConcept', 'process | outcome | structure | patient-reported-outcome | compositeMeasureType (Extensible)',
'riskAdjustment', 'Σ', '0..1', 'string', 'How risk adjustment is applied for this measure',
'rateAggregation', 'Σ', '0..1', 'string', 'How is rate aggregation performed for this measure',
'rationale', 'Σ', '0..1', 'markdown', 'Detailed description of why the measure exists',
'clinicalRecommendationStatement', 'Σ', '0..1', 'markdown', 'Summary of clinical guidelines',
'improvementNotation', 'Σ', '0..1', 'CodeableConcept', 'increase | decreaseMeasureImprovementNotation (Required)',
'definition', 'Σ', '0..*', 'markdown', 'Defined terms used in the measure documentation',
'guidance', 'Σ', '0..1', 'markdown', 'Additional guidance for implementers',
'group', '', '0..*', 'BackboneElement', 'Population criteria group',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the group',
'description', '', '0..1', 'string', 'Summary description',
'population', '', '0..*', 'BackboneElement', 'Population criteria',
'code', '', '0..1', 'CodeableConcept', 'initial-population | numerator | numerator-exclusion | denominator | denominator-exclusion | denominator-exception | measure-population | measure-population-exclusion | measure-observationMeasurePopulationType (Extensible)',
'description', '', '0..1', 'string', 'The human readable description of this population criteria',
'criteria', '', '1..1', 'Expression', 'The criteria that defines this population',
'stratifier', '', '0..*', 'BackboneElement', 'Stratifier criteria for the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the stratifier',
'description', '', '0..1', 'string', 'The human readable description of this stratifier',
'criteria', '', '0..1', 'Expression', 'How the measure should be stratified',
'component', '', '0..*', 'BackboneElement', 'Stratifier criteria component for the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the stratifier component',
'description', '', '0..1', 'string', 'The human readable description of this stratifier component',
'criteria', '', '1..1', 'Expression', 'Component of how the measure should be stratified',
'supplementalData', '', '0..*', 'BackboneElement', 'What other data should be reported with the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the supplemental data',
'usage', '', '0..*', 'CodeableConcept', 'supplemental-data | risk-adjustment-factorMeasureDataUsage (Extensible)',
'description', '', '0..1', 'string', 'The human readable description of this supplemental data',
'criteria', '', '1..1', 'Expression', 'Expression describing additional data to be reported',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Measure', '',
'Measure.subtitle', 'Added Element',
'Measure.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'Measure.experimental', 'No longer marked as Modifier',
'Measure.subject[x]', 'Added Element',
'Measure.author', 'Added Element',
'Measure.editor', 'Added Element',
'Measure.reviewer', 'Added Element',
'Measure.endorser', 'Added Element',
'Measure.library', 'Type changed from Reference(Library) to canonical(Library)',
'Measure.scoring', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-scoring" to "http://terminology.hl7.org/CodeSystem/measure-scoring"',
'Measure.compositeScoring', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/composite-measure-scoring" to "http://terminology.hl7.org/CodeSystem/composite-measure-scoring"',
'Measure.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-type" to "http://terminology.hl7.org/CodeSystem/measure-type"',
'Measure.improvementNotation', 'Type changed from string to CodeableConcept
        
Add Binding http://hl7.org/fhir/ValueSet/measure-improvement-notation|4.0.1 (required)',
'Measure.group.code', 'Added Element',
'Measure.group.population.code', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-population" to "http://terminology.hl7.org/CodeSystem/measure-population"',
'Measure.group.population.criteria', 'Type changed from string to Expression',
'Measure.group.stratifier.code', 'Added Element',
'Measure.group.stratifier.description', 'Added Element',
'Measure.group.stratifier.criteria', 'Type changed from string to Expression',
'Measure.group.stratifier.component', 'Added Element',
'Measure.group.stratifier.component.code', 'Added Element',
'Measure.group.stratifier.component.description', 'Added Element',
'Measure.group.stratifier.component.criteria', 'Added Mandatory Element',
'Measure.supplementalData.code', 'Added Element',
'Measure.supplementalData.usage', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-data-usage" to "http://terminology.hl7.org/CodeSystem/measure-data-usage"',
'Measure.supplementalData.description', 'Added Element',
'Measure.supplementalData.criteria', 'Min Cardinality changed from 0 to 1
        Type changed from string to Expression',
'Measure.contributor', 'deleted',
'Measure.set', 'deleted',
'Measure.group.identifier', 'deleted',
'Measure.group.name', 'deleted',
'Measure.group.population.identifier', 'deleted',
'Measure.group.population.name', 'deleted',
'Measure.group.stratifier.identifier', 'deleted',
'Measure.group.stratifier.path', 'deleted',
'Measure.supplementalData.identifier', 'deleted',
'Measure.supplementalData.path', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Measure', 'ITU', '', 'DomainResource', 'A quality measure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: Stratifier SHALL be either a single criteria or a set of criteria componentsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this measure, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the measure',
'version', 'Σ', '0..1', 'string', 'Business version of the measure',
'name', 'ΣI', '0..1', 'string', 'Name for this measure (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this measure (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the measure',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'E.g. Patient, Practitioner, RelatedPerson, Organization, Location, DeviceSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the measure',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for measure (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this measure is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the measure',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the measure was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the measure was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the measure is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the measure, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the measure',
'disclaimer', 'Σ', '0..1', 'markdown', 'Disclaimer for use of the measure or its referenced content',
'scoring', 'Σ', '0..1', 'CodeableConcept', 'proportion | ratio | continuous-variable | cohortMeasureScoring (Extensible)',
'compositeScoring', 'Σ', '0..1', 'CodeableConcept', 'opportunity | all-or-nothing | linear | weightedCompositeMeasureScoring (Extensible)',
'type', 'Σ', '0..*', 'CodeableConcept', 'process | outcome | structure | patient-reported-outcome | compositeMeasureType (Extensible)',
'riskAdjustment', 'Σ', '0..1', 'string', 'How risk adjustment is applied for this measure',
'rateAggregation', 'Σ', '0..1', 'string', 'How is rate aggregation performed for this measure',
'rationale', 'Σ', '0..1', 'markdown', 'Detailed description of why the measure exists',
'clinicalRecommendationStatement', 'Σ', '0..1', 'markdown', 'Summary of clinical guidelines',
'improvementNotation', 'Σ', '0..1', 'CodeableConcept', 'increase | decreaseMeasureImprovementNotation (Required)',
'definition', 'Σ', '0..*', 'markdown', 'Defined terms used in the measure documentation',
'guidance', 'Σ', '0..1', 'markdown', 'Additional guidance for implementers',
'group', '', '0..*', 'BackboneElement', 'Population criteria group',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the group',
'description', '', '0..1', 'string', 'Summary description',
'population', '', '0..*', 'BackboneElement', 'Population criteria',
'code', '', '0..1', 'CodeableConcept', 'initial-population | numerator | numerator-exclusion | denominator | denominator-exclusion | denominator-exception | measure-population | measure-population-exclusion | measure-observationMeasurePopulationType (Extensible)',
'description', '', '0..1', 'string', 'The human readable description of this population criteria',
'criteria', '', '1..1', 'Expression', 'The criteria that defines this population',
'stratifier', '', '0..*', 'BackboneElement', 'Stratifier criteria for the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the stratifier',
'description', '', '0..1', 'string', 'The human readable description of this stratifier',
'criteria', '', '0..1', 'Expression', 'How the measure should be stratified',
'component', '', '0..*', 'BackboneElement', 'Stratifier criteria component for the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the stratifier component',
'description', '', '0..1', 'string', 'The human readable description of this stratifier component',
'criteria', '', '1..1', 'Expression', 'Component of how the measure should be stratified',
'supplementalData', '', '0..*', 'BackboneElement', 'What other data should be reported with the measure',
'code', '', '0..1', 'CodeableConcept', 'Meaning of the supplemental data',
'usage', '', '0..*', 'CodeableConcept', 'supplemental-data | risk-adjustment-factorMeasureDataUsage (Extensible)',
'description', '', '0..1', 'string', 'The human readable description of this supplemental data',
'criteria', '', '1..1', 'Expression', 'Expression describing additional data to be reported',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Measure', '',
'Measure.subtitle', 'Added Element',
'Measure.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'Measure.experimental', 'No longer marked as Modifier',
'Measure.subject[x]', 'Added Element',
'Measure.author', 'Added Element',
'Measure.editor', 'Added Element',
'Measure.reviewer', 'Added Element',
'Measure.endorser', 'Added Element',
'Measure.library', 'Type changed from Reference(Library) to canonical(Library)',
'Measure.scoring', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-scoring" to "http://terminology.hl7.org/CodeSystem/measure-scoring"',
'Measure.compositeScoring', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/composite-measure-scoring" to "http://terminology.hl7.org/CodeSystem/composite-measure-scoring"',
'Measure.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-type" to "http://terminology.hl7.org/CodeSystem/measure-type"',
'Measure.improvementNotation', 'Type changed from string to CodeableConcept
        
Add Binding http://hl7.org/fhir/ValueSet/measure-improvement-notation|4.0.1 (required)',
'Measure.group.code', 'Added Element',
'Measure.group.population.code', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-population" to "http://terminology.hl7.org/CodeSystem/measure-population"',
'Measure.group.population.criteria', 'Type changed from string to Expression',
'Measure.group.stratifier.code', 'Added Element',
'Measure.group.stratifier.description', 'Added Element',
'Measure.group.stratifier.criteria', 'Type changed from string to Expression',
'Measure.group.stratifier.component', 'Added Element',
'Measure.group.stratifier.component.code', 'Added Element',
'Measure.group.stratifier.component.description', 'Added Element',
'Measure.group.stratifier.component.criteria', 'Added Mandatory Element',
'Measure.supplementalData.code', 'Added Element',
'Measure.supplementalData.usage', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/measure-data-usage" to "http://terminology.hl7.org/CodeSystem/measure-data-usage"',
'Measure.supplementalData.description', 'Added Element',
'Measure.supplementalData.criteria', 'Min Cardinality changed from 0 to 1
        Type changed from string to Expression',
'Measure.contributor', 'deleted',
'Measure.set', 'deleted',
'Measure.group.identifier', 'deleted',
'Measure.group.name', 'deleted',
'Measure.group.population.identifier', 'deleted',
'Measure.group.population.name', 'deleted',
'Measure.group.stratifier.identifier', 'deleted',
'Measure.group.stratifier.path', 'deleted',
'Measure.supplementalData.identifier', 'deleted',
'Measure.supplementalData.path', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Measure.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'Measure.subject[x]', 'The possible types of subjects for a measure (E.g. Patient, Practitioner, Organization, Location, etc.).', 'Extensible', 'SubjectType',
'Measure.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'Measure.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'Measure.scoring', 'The scoring type of the measure.', 'Extensible', 'MeasureScoring',
'Measure.compositeScoring', 'The composite scoring method of the measure.', 'Extensible', 'CompositeMeasureScoring',
'Measure.type', 'The type of measure (includes codes from 2.16.840.1.113883.1.11.20368).', 'Extensible', 'MeasureType',
'Measure.improvementNotation', 'Observation values that indicate what change in a measurement value or score is indicative of an improvement in the measured item or scored issue.', 'Required', 'MeasureImprovementNotation',
'Measure.group.population.code', 'The type of population.', 'Extensible', 'MeasurePopulationType',
'Measure.supplementalData.usage', 'The intended usage for supplemental data elements in the measure.', 'Extensible', 'MeasureDataUsage',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'mea-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'mea-1', 'Rule', '(base)', 'Stratifier SHALL be either a single criteria or a set of criteria components', 'group.stratifier.all((code | description | criteria).exists() xor component.exists())',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'composed-of', 'reference', 'What resource is being referenced', 'Measure.relatedArtifact.where(type='composed-of').resource(Any)', '',
'context', 'token', 'A use context assigned to the measure', '(Measure.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the measure', '(Measure.useContext.value as Quantity) | (Measure.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the measure', 'Measure.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the measure', 'On Measure.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the measure', 'On Measure.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The measure publication date', 'Measure.date', '',
'depends-on', 'reference', 'What resource is being referenced', 'Measure.relatedArtifact.where(type='depends-on').resource | Measure.library(Library, Any)', '',
'derived-from', 'reference', 'What resource is being referenced', 'Measure.relatedArtifact.where(type='derived-from').resource(Any)', '',
'description', 'string', 'The description of the measure', 'Measure.description', '',
'effective', 'date', 'The time during which the measure is intended to be in use', 'Measure.effectivePeriod', '',
'identifier', 'token', 'External identifier for the measure', 'Measure.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the measure', 'Measure.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the measure', 'Measure.name', '',
'predecessor', 'reference', 'What resource is being referenced', 'Measure.relatedArtifact.where(type='predecessor').resource(Any)', '',
'publisher', 'string', 'Name of the publisher of the measure', 'Measure.publisher', '',
'status', 'token', 'The current status of the measure', 'Measure.status', '',
'successor', 'reference', 'What resource is being referenced', 'Measure.relatedArtifact.where(type='successor').resource(Any)', '',
'title', 'string', 'The human-friendly name of the measure', 'Measure.title', '',
'topic', 'token', 'Topics associated with the measure', 'Measure.topic', '',
'url', 'uri', 'The uri that identifies the measure', 'Measure.url', '',
'version', 'token', 'The business version of the measure', 'Measure.version', '',
)


