df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Pharmacy  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'MedicationKnowledge', 'TU', '', 'DomainResource', 'Definition of Medication KnowledgeElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'code', 'Σ', '0..1', 'CodeableConcept', 'Code that identifies this medicationSNOMED CT Medication Codes (Example)',
'status', '?!Σ', '0..1', 'code', 'active | inactive | entered-in-errorMedication knowledge  status  codes (Required)',
'manufacturer', 'Σ', '0..1', 'Reference(Organization)', 'Manufacturer of the item',
'doseForm', '', '0..1', 'CodeableConcept', 'powder | tablets | capsule +SNOMED CT Form Codes (Example)',
'amount', 'Σ', '0..1', 'SimpleQuantity', 'Amount of drug in package',
'synonym', 'Σ', '0..*', 'string', 'Additional names for a medication',
'relatedMedicationKnowledge', '', '0..*', 'BackboneElement', 'Associated or related medication information',
'type', '', '1..1', 'CodeableConcept', 'Category of medicationKnowledge',
'reference', '', '1..*', 'Reference(MedicationKnowledge)', 'Associated documentation about the associated medication knowledge',
'associatedMedication', '', '0..*', 'Reference(Medication)', 'A medication resource that is associated with this medication',
'productType', '', '0..*', 'CodeableConcept', 'Category of the medication or product',
'monograph', '', '0..*', 'BackboneElement', 'Associated documentation about the medication',
'type', '', '0..1', 'CodeableConcept', 'The category of medication document',
'source', '', '0..1', 'Reference(DocumentReference | Media)', 'Associated documentation about the medication',
'ingredient', '', '0..*', 'BackboneElement', 'Active or inactive ingredient',
'item[x]', '', '1..1', '', 'Medication(s) or substance(s) contained in the medication',
'itemCodeableConcept', '', '', 'CodeableConcept', '',
'itemReference', '', '', 'Reference(Substance)', '',
'isActive', '', '0..1', 'boolean', 'Active ingredient indicator',
'strength', '', '0..1', 'Ratio', 'Quantity of ingredient present',
'preparationInstruction', '', '0..1', 'markdown', 'The instructions for preparing the medication',
'intendedRoute', '', '0..*', 'CodeableConcept', 'The intended or approved route of administrationSNOMED CT Route Codes (Example)',
'cost', '', '0..*', 'BackboneElement', 'The pricing of the medication',
'type', '', '1..1', 'CodeableConcept', 'The category of the cost information',
'source', '', '0..1', 'string', 'The source or owner for the price information',
'cost', '', '1..1', 'Money', 'The price of the medication',
'monitoringProgram', '', '0..*', 'BackboneElement', 'Program under which a medication is reviewed',
'type', '', '0..1', 'CodeableConcept', 'Type of program under which the medication is monitored',
'name', '', '0..1', 'string', 'Name of the reviewing program',
'administrationGuidelines', '', '0..*', 'BackboneElement', 'Guidelines for administration of the medication',
'dosage', '', '0..*', 'BackboneElement', 'Dosage for the medication for the specific guidelines',
'type', '', '1..1', 'CodeableConcept', 'Type of dosage',
'dosage', '', '1..*', 'Dosage', 'Dosage for the medication for the specific guidelines',
'indication[x]', '', '0..1', '', 'Indication for use that apply to the specific administration guidelines',
'indicationCodeableConcept', '', '', 'CodeableConcept', '',
'indicationReference', '', '', 'Reference(ObservationDefinition)', '',
'patientCharacteristics', '', '0..*', 'BackboneElement', 'Characteristics of the patient that are relevant to the administration guidelines',
'characteristic[x]', '', '1..1', '', 'Specific characteristic that is relevant to the administration guideline',
'characteristicCodeableConcept', '', '', 'CodeableConcept', '',
'characteristicQuantity', '', '', 'SimpleQuantity', '',
'value', '', '0..*', 'string', 'The specific characteristic',
'medicineClassification', '', '0..*', 'BackboneElement', 'Categorization of the medication within a formulary or classification system',
'type', '', '1..1', 'CodeableConcept', 'The type of category for the medication (for example, therapeutic classification, therapeutic sub-classification)',
'classification', '', '0..*', 'CodeableConcept', 'Specific category assigned to the medication',
'packaging', '', '0..1', 'BackboneElement', 'Details about packaged medications',
'type', '', '0..1', 'CodeableConcept', 'A code that defines the specific type of packaging that the medication can be found inMedication knowledge  package  type  codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'The number of product units the package would contain if fully loaded',
'drugCharacteristic', '', '0..*', 'BackboneElement', 'Specifies descriptive properties of the medicine',
'type', '', '0..1', 'CodeableConcept', 'Code specifying the type of characteristic of medicationMedication knowledge  characteristic  codes (Example)',
'value[x]', '', '0..1', '', 'Description of the characteristic',
'valueCodeableConcept', '', '', 'CodeableConcept', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'SimpleQuantity', '',
'valueBase64Binary', '', '', 'base64Binary', '',
'contraindication', '', '0..*', 'Reference(DetectedIssue)', 'Potential clinical issue with or between medication(s)',
'regulatory', '', '0..*', 'BackboneElement', 'Regulatory information about a medication',
'regulatoryAuthority', '', '1..1', 'Reference(Organization)', 'Specifies the authority of the regulation',
'substitution', '', '0..*', 'BackboneElement', 'Specifies if changes are allowed when dispensing a medication from a regulatory perspective',
'type', '', '1..1', 'CodeableConcept', 'Specifies the type of substitution allowed',
'allowed', '', '1..1', 'boolean', 'Specifies if regulation allows for changes in the medication when dispensing',
'schedule', '', '0..*', 'BackboneElement', 'Specifies the schedule of a medication in jurisdiction',
'schedule', '', '1..1', 'CodeableConcept', 'Specifies the specific drug schedule',
'maxDispense', '', '0..1', 'BackboneElement', 'The maximum number of units of the medication that can be dispensed in a period',
'quantity', '', '1..1', 'SimpleQuantity', 'The maximum number of units of the medication that can be dispensed',
'period', '', '0..1', 'Duration', 'The period that applies to the maximum number of units',
'kinetics', '', '0..*', 'BackboneElement', 'The time course of drug absorption, distribution, metabolism and excretion of a medication from the body',
'areaUnderCurve', '', '0..*', 'SimpleQuantity', 'The drug concentration measured at certain discrete points in time',
'lethalDose50', '', '0..*', 'SimpleQuantity', 'The median lethal dose of a drug',
'halfLifePeriod', '', '0..1', 'Duration', 'Time required for concentration in the body to decrease by half',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'MedicationKnowledge', 'TU', '', 'DomainResource', 'Definition of Medication KnowledgeElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'code', 'Σ', '0..1', 'CodeableConcept', 'Code that identifies this medicationSNOMED CT Medication Codes (Example)',
'status', '?!Σ', '0..1', 'code', 'active | inactive | entered-in-errorMedication knowledge  status  codes (Required)',
'manufacturer', 'Σ', '0..1', 'Reference(Organization)', 'Manufacturer of the item',
'doseForm', '', '0..1', 'CodeableConcept', 'powder | tablets | capsule +SNOMED CT Form Codes (Example)',
'amount', 'Σ', '0..1', 'SimpleQuantity', 'Amount of drug in package',
'synonym', 'Σ', '0..*', 'string', 'Additional names for a medication',
'relatedMedicationKnowledge', '', '0..*', 'BackboneElement', 'Associated or related medication information',
'type', '', '1..1', 'CodeableConcept', 'Category of medicationKnowledge',
'reference', '', '1..*', 'Reference(MedicationKnowledge)', 'Associated documentation about the associated medication knowledge',
'associatedMedication', '', '0..*', 'Reference(Medication)', 'A medication resource that is associated with this medication',
'productType', '', '0..*', 'CodeableConcept', 'Category of the medication or product',
'monograph', '', '0..*', 'BackboneElement', 'Associated documentation about the medication',
'type', '', '0..1', 'CodeableConcept', 'The category of medication document',
'source', '', '0..1', 'Reference(DocumentReference | Media)', 'Associated documentation about the medication',
'ingredient', '', '0..*', 'BackboneElement', 'Active or inactive ingredient',
'item[x]', '', '1..1', '', 'Medication(s) or substance(s) contained in the medication',
'itemCodeableConcept', '', '', 'CodeableConcept', '',
'itemReference', '', '', 'Reference(Substance)', '',
'isActive', '', '0..1', 'boolean', 'Active ingredient indicator',
'strength', '', '0..1', 'Ratio', 'Quantity of ingredient present',
'preparationInstruction', '', '0..1', 'markdown', 'The instructions for preparing the medication',
'intendedRoute', '', '0..*', 'CodeableConcept', 'The intended or approved route of administrationSNOMED CT Route Codes (Example)',
'cost', '', '0..*', 'BackboneElement', 'The pricing of the medication',
'type', '', '1..1', 'CodeableConcept', 'The category of the cost information',
'source', '', '0..1', 'string', 'The source or owner for the price information',
'cost', '', '1..1', 'Money', 'The price of the medication',
'monitoringProgram', '', '0..*', 'BackboneElement', 'Program under which a medication is reviewed',
'type', '', '0..1', 'CodeableConcept', 'Type of program under which the medication is monitored',
'name', '', '0..1', 'string', 'Name of the reviewing program',
'administrationGuidelines', '', '0..*', 'BackboneElement', 'Guidelines for administration of the medication',
'dosage', '', '0..*', 'BackboneElement', 'Dosage for the medication for the specific guidelines',
'type', '', '1..1', 'CodeableConcept', 'Type of dosage',
'dosage', '', '1..*', 'Dosage', 'Dosage for the medication for the specific guidelines',
'indication[x]', '', '0..1', '', 'Indication for use that apply to the specific administration guidelines',
'indicationCodeableConcept', '', '', 'CodeableConcept', '',
'indicationReference', '', '', 'Reference(ObservationDefinition)', '',
'patientCharacteristics', '', '0..*', 'BackboneElement', 'Characteristics of the patient that are relevant to the administration guidelines',
'characteristic[x]', '', '1..1', '', 'Specific characteristic that is relevant to the administration guideline',
'characteristicCodeableConcept', '', '', 'CodeableConcept', '',
'characteristicQuantity', '', '', 'SimpleQuantity', '',
'value', '', '0..*', 'string', 'The specific characteristic',
'medicineClassification', '', '0..*', 'BackboneElement', 'Categorization of the medication within a formulary or classification system',
'type', '', '1..1', 'CodeableConcept', 'The type of category for the medication (for example, therapeutic classification, therapeutic sub-classification)',
'classification', '', '0..*', 'CodeableConcept', 'Specific category assigned to the medication',
'packaging', '', '0..1', 'BackboneElement', 'Details about packaged medications',
'type', '', '0..1', 'CodeableConcept', 'A code that defines the specific type of packaging that the medication can be found inMedication knowledge  package  type  codes (Example)',
'quantity', '', '0..1', 'SimpleQuantity', 'The number of product units the package would contain if fully loaded',
'drugCharacteristic', '', '0..*', 'BackboneElement', 'Specifies descriptive properties of the medicine',
'type', '', '0..1', 'CodeableConcept', 'Code specifying the type of characteristic of medicationMedication knowledge  characteristic  codes (Example)',
'value[x]', '', '0..1', '', 'Description of the characteristic',
'valueCodeableConcept', '', '', 'CodeableConcept', '',
'valueString', '', '', 'string', '',
'valueQuantity', '', '', 'SimpleQuantity', '',
'valueBase64Binary', '', '', 'base64Binary', '',
'contraindication', '', '0..*', 'Reference(DetectedIssue)', 'Potential clinical issue with or between medication(s)',
'regulatory', '', '0..*', 'BackboneElement', 'Regulatory information about a medication',
'regulatoryAuthority', '', '1..1', 'Reference(Organization)', 'Specifies the authority of the regulation',
'substitution', '', '0..*', 'BackboneElement', 'Specifies if changes are allowed when dispensing a medication from a regulatory perspective',
'type', '', '1..1', 'CodeableConcept', 'Specifies the type of substitution allowed',
'allowed', '', '1..1', 'boolean', 'Specifies if regulation allows for changes in the medication when dispensing',
'schedule', '', '0..*', 'BackboneElement', 'Specifies the schedule of a medication in jurisdiction',
'schedule', '', '1..1', 'CodeableConcept', 'Specifies the specific drug schedule',
'maxDispense', '', '0..1', 'BackboneElement', 'The maximum number of units of the medication that can be dispensed in a period',
'quantity', '', '1..1', 'SimpleQuantity', 'The maximum number of units of the medication that can be dispensed',
'period', '', '0..1', 'Duration', 'The period that applies to the maximum number of units',
'kinetics', '', '0..*', 'BackboneElement', 'The time course of drug absorption, distribution, metabolism and excretion of a medication from the body',
'areaUnderCurve', '', '0..*', 'SimpleQuantity', 'The drug concentration measured at certain discrete points in time',
'lethalDose50', '', '0..*', 'SimpleQuantity', 'The median lethal dose of a drug',
'halfLifePeriod', '', '0..1', 'Duration', 'Time required for concentration in the body to decrease by half',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'MedicationKnowledge.code', 'A coded concept that defines the type of a medication.', 'Example', 'SNOMEDCTMedicationCodes',
'MedicationKnowledge.status', 'A coded concept defining if the medication is in active use.', 'Required', 'MedicationKnowledge Status Codes',
'MedicationKnowledge.doseForm', 'A coded concept defining the form of a medication.', 'Example', 'SNOMEDCTFormCodes',
'MedicationKnowledge.intendedRoute', 'A coded concept defining the intended route of administration.', 'Example', 'SNOMEDCTRouteCodes',
'MedicationKnowledge.packaging.type', 'A coded concept defining the type of packaging of a medication.', 'Example', 'medicationKnowledge Package Type Codes',
'MedicationKnowledge.drugCharacteristic.type', 'A coded concept defining the characteristic types of a medication.', 'Example', 'medicationKnowledge Characteristic Codes',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'classification', 'token', 'Specific category assigned to the medication', 'MedicationKnowledge.medicineClassification.classification', '',
'classification-type', 'token', 'The type of category for the medication (for example, therapeutic classification, therapeutic sub-classification)', 'MedicationKnowledge.medicineClassification.type', '',
'code', 'token', 'Code that identifies this medication', 'MedicationKnowledge.code', '',
'doseform', 'token', 'powder | tablets | capsule +', 'MedicationKnowledge.doseForm', '',
'ingredient', 'reference', 'Medication(s) or substance(s) contained in the medication', '(MedicationKnowledge.ingredient.item as Reference)(Substance)', '',
'ingredient-code', 'token', 'Medication(s) or substance(s) contained in the medication', '(MedicationKnowledge.ingredient.item as CodeableConcept)', '',
'manufacturer', 'reference', 'Manufacturer of the item', 'MedicationKnowledge.manufacturer(Organization)', '',
'monitoring-program-name', 'token', 'Name of the reviewing program', 'MedicationKnowledge.monitoringProgram.name', '',
'monitoring-program-type', 'token', 'Type of program under which the medication is monitored', 'MedicationKnowledge.monitoringProgram.type', '',
'monograph', 'reference', 'Associated documentation about the medication', 'MedicationKnowledge.monograph.source(Media, DocumentReference)', '',
'monograph-type', 'token', 'The category of medication document', 'MedicationKnowledge.monograph.type', '',
'source-cost', 'token', 'The source or owner for the price information', 'MedicationKnowledge.cost.source', '',
'status', 'token', 'active | inactive | entered-in-error', 'MedicationKnowledge.status', '',
)


