df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Biomedical Research and Regulation  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'MedicinalProduct', 'ΣTU', '', 'DomainResource', 'Detailed definition of a medicinal product, typically for uses other than direct patient care (e.g. regulatory use)Elements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Business identifier for this product. Could be an MPID',
'type', 'Σ', '0..1', 'CodeableConcept', 'Regulatory type, e.g. Investigational or Authorized',
'domain', 'Σ', '0..1', 'Coding', 'If this medicine applies to human or veterinary uses',
'combinedPharmaceuticalDoseForm', 'Σ', '0..1', 'CodeableConcept', 'The dose form for a single part product, or combined form of a multiple part product',
'legalStatusOfSupply', 'Σ', '0..1', 'CodeableConcept', 'The legal status of supply of the medicinal product as classified by the regulator',
'additionalMonitoringIndicator', 'Σ', '0..1', 'CodeableConcept', 'Whether the Medicinal Product is subject to additional monitoring for regulatory reasons',
'specialMeasures', 'Σ', '0..*', 'string', 'Whether the Medicinal Product is subject to special measures for regulatory reasons',
'paediatricUseIndicator', 'Σ', '0..1', 'CodeableConcept', 'If authorised for use in children',
'productClassification', 'Σ', '0..*', 'CodeableConcept', 'Allows the product to be classified by various systems',
'marketingStatus', 'Σ', '0..*', 'MarketingStatus', 'Marketing status of the medicinal product, in contrast to marketing authorizaton',
'pharmaceuticalProduct', 'Σ', '0..*', 'Reference(MedicinalProductPharmaceutical)', 'Pharmaceutical aspects of product',
'packagedMedicinalProduct', 'Σ', '0..*', 'Reference(MedicinalProductPackaged)', 'Package representation for the product',
'attachedDocument', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting documentation, typically for regulatory submission',
'masterFile', 'Σ', '0..*', 'Reference(DocumentReference)', 'A master file for to the medicinal product (e.g. Pharmacovigilance System Master File)',
'contact', 'Σ', '0..*', 'Reference(Organization | PractitionerRole)', 'A product specific contact, person (in a role), or an organization',
'clinicalTrial', 'Σ', '0..*', 'Reference(ResearchStudy)', 'Clinical trials or studies that this product is involved in',
'name', 'Σ', '1..*', 'BackboneElement', 'The product's name, including full name and possibly coded parts',
'productName', 'Σ', '1..1', 'string', 'The full product name',
'namePart', 'Σ', '0..*', 'BackboneElement', 'Coding words or phrases of the name',
'part', 'Σ', '1..1', 'string', 'A fragment of a product name',
'type', 'Σ', '1..1', 'Coding', 'Idenifying type for this part of the name (e.g. strength part)',
'countryLanguage', 'Σ', '0..*', 'BackboneElement', 'Country where the name applies',
'country', 'Σ', '1..1', 'CodeableConcept', 'Country code for where this name applies',
'jurisdiction', 'Σ', '0..1', 'CodeableConcept', 'Jurisdiction code for where this name applies',
'language', 'Σ', '1..1', 'CodeableConcept', 'Language code for this name',
'crossReference', 'Σ', '0..*', 'Identifier', 'Reference to another product, e.g. for linking authorised to investigational product',
'manufacturingBusinessOperation', 'Σ', '0..*', 'BackboneElement', 'An operation applied to the product, for manufacturing or adminsitrative purpose',
'operationType', 'Σ', '0..1', 'CodeableConcept', 'The type of manufacturing operation',
'authorisationReferenceNumber', 'Σ', '0..1', 'Identifier', 'Regulatory authorization reference number',
'effectiveDate', 'Σ', '0..1', 'dateTime', 'Regulatory authorization date',
'confidentialityIndicator', 'Σ', '0..1', 'CodeableConcept', 'To indicate if this proces is commercially confidential',
'manufacturer', 'Σ', '0..*', 'Reference(Organization)', 'The manufacturer or establishment associated with the process',
'regulator', 'Σ', '0..1', 'Reference(Organization)', 'A regulator which oversees the operation',
'specialDesignation', 'Σ', '0..*', 'BackboneElement', 'Indicates if the medicinal product has an orphan designation for the treatment of a rare disease',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifier for the designation, or procedure number',
'type', 'Σ', '0..1', 'CodeableConcept', 'The type of special designation, e.g. orphan drug, minor use',
'intendedUse', 'Σ', '0..1', 'CodeableConcept', 'The intended use of the product, e.g. prevention, treatment',
'indication[x]', 'Σ', '0..1', '', 'Condition for which the medicinal use applies',
'indicationCodeableConcept', '', '', 'CodeableConcept', '',
'indicationReference', '', '', 'Reference(MedicinalProductIndication)', '',
'status', 'Σ', '0..1', 'CodeableConcept', 'For example granted, pending, expired or withdrawn',
'date', 'Σ', '0..1', 'dateTime', 'Date when the designation was granted',
'species', 'Σ', '0..1', 'CodeableConcept', 'Animal species for which this applies',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'MedicinalProduct', 'ΣTU', '', 'DomainResource', 'Detailed definition of a medicinal product, typically for uses other than direct patient care (e.g. regulatory use)Elements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Business identifier for this product. Could be an MPID',
'type', 'Σ', '0..1', 'CodeableConcept', 'Regulatory type, e.g. Investigational or Authorized',
'domain', 'Σ', '0..1', 'Coding', 'If this medicine applies to human or veterinary uses',
'combinedPharmaceuticalDoseForm', 'Σ', '0..1', 'CodeableConcept', 'The dose form for a single part product, or combined form of a multiple part product',
'legalStatusOfSupply', 'Σ', '0..1', 'CodeableConcept', 'The legal status of supply of the medicinal product as classified by the regulator',
'additionalMonitoringIndicator', 'Σ', '0..1', 'CodeableConcept', 'Whether the Medicinal Product is subject to additional monitoring for regulatory reasons',
'specialMeasures', 'Σ', '0..*', 'string', 'Whether the Medicinal Product is subject to special measures for regulatory reasons',
'paediatricUseIndicator', 'Σ', '0..1', 'CodeableConcept', 'If authorised for use in children',
'productClassification', 'Σ', '0..*', 'CodeableConcept', 'Allows the product to be classified by various systems',
'marketingStatus', 'Σ', '0..*', 'MarketingStatus', 'Marketing status of the medicinal product, in contrast to marketing authorizaton',
'pharmaceuticalProduct', 'Σ', '0..*', 'Reference(MedicinalProductPharmaceutical)', 'Pharmaceutical aspects of product',
'packagedMedicinalProduct', 'Σ', '0..*', 'Reference(MedicinalProductPackaged)', 'Package representation for the product',
'attachedDocument', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting documentation, typically for regulatory submission',
'masterFile', 'Σ', '0..*', 'Reference(DocumentReference)', 'A master file for to the medicinal product (e.g. Pharmacovigilance System Master File)',
'contact', 'Σ', '0..*', 'Reference(Organization | PractitionerRole)', 'A product specific contact, person (in a role), or an organization',
'clinicalTrial', 'Σ', '0..*', 'Reference(ResearchStudy)', 'Clinical trials or studies that this product is involved in',
'name', 'Σ', '1..*', 'BackboneElement', 'The product's name, including full name and possibly coded parts',
'productName', 'Σ', '1..1', 'string', 'The full product name',
'namePart', 'Σ', '0..*', 'BackboneElement', 'Coding words or phrases of the name',
'part', 'Σ', '1..1', 'string', 'A fragment of a product name',
'type', 'Σ', '1..1', 'Coding', 'Idenifying type for this part of the name (e.g. strength part)',
'countryLanguage', 'Σ', '0..*', 'BackboneElement', 'Country where the name applies',
'country', 'Σ', '1..1', 'CodeableConcept', 'Country code for where this name applies',
'jurisdiction', 'Σ', '0..1', 'CodeableConcept', 'Jurisdiction code for where this name applies',
'language', 'Σ', '1..1', 'CodeableConcept', 'Language code for this name',
'crossReference', 'Σ', '0..*', 'Identifier', 'Reference to another product, e.g. for linking authorised to investigational product',
'manufacturingBusinessOperation', 'Σ', '0..*', 'BackboneElement', 'An operation applied to the product, for manufacturing or adminsitrative purpose',
'operationType', 'Σ', '0..1', 'CodeableConcept', 'The type of manufacturing operation',
'authorisationReferenceNumber', 'Σ', '0..1', 'Identifier', 'Regulatory authorization reference number',
'effectiveDate', 'Σ', '0..1', 'dateTime', 'Regulatory authorization date',
'confidentialityIndicator', 'Σ', '0..1', 'CodeableConcept', 'To indicate if this proces is commercially confidential',
'manufacturer', 'Σ', '0..*', 'Reference(Organization)', 'The manufacturer or establishment associated with the process',
'regulator', 'Σ', '0..1', 'Reference(Organization)', 'A regulator which oversees the operation',
'specialDesignation', 'Σ', '0..*', 'BackboneElement', 'Indicates if the medicinal product has an orphan designation for the treatment of a rare disease',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifier for the designation, or procedure number',
'type', 'Σ', '0..1', 'CodeableConcept', 'The type of special designation, e.g. orphan drug, minor use',
'intendedUse', 'Σ', '0..1', 'CodeableConcept', 'The intended use of the product, e.g. prevention, treatment',
'indication[x]', 'Σ', '0..1', '', 'Condition for which the medicinal use applies',
'indicationCodeableConcept', '', '', 'CodeableConcept', '',
'indicationReference', '', '', 'Reference(MedicinalProductIndication)', '',
'status', 'Σ', '0..1', 'CodeableConcept', 'For example granted, pending, expired or withdrawn',
'date', 'Σ', '0..1', 'dateTime', 'Date when the designation was granted',
'species', 'Σ', '0..1', 'CodeableConcept', 'Animal species for which this applies',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'identifier', 'token', 'Business identifier for this product. Could be an MPID', 'MedicinalProduct.identifier', '',
'name', 'string', 'The full product name', 'MedicinalProduct.name.productName', '',
'name-language', 'token', 'Language code for this name', 'MedicinalProduct.name.countryLanguage.language', '',
)


