df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'PlanDefinition', 'ITU', '', 'DomainResource', 'The definition of a plan for a series of actions, independent of any specific patient or context+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this plan definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the plan definition',
'version', 'Σ', '0..1', 'string', 'Business version of the plan definition',
'name', 'ΣI', '0..1', 'string', 'Name for this plan definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this plan definition (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the plan definition',
'type', 'Σ', '0..1', 'CodeableConcept', 'order-set | clinical-protocol | eca-rule | workflow-definitionPlanDefinitionType (Extensible)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'Type of individual the plan definition is focused onSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the plan definition',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for plan definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this plan definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the plan',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the plan definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the plan definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the plan definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'E.g. Education, Treatment, AssessmentDefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the plan definition',
'goal', '', '0..*', 'BackboneElement', 'What the plan is trying to accomplish',
'category', '', '0..1', 'CodeableConcept', 'E.g. Treatment, dietary, behavioralGoal category (Example)',
'description', '', '1..1', 'CodeableConcept', 'Code or text describing the goalSNOMED CT Clinical Findings (Example)',
'priority', '', '0..1', 'CodeableConcept', 'high-priority | medium-priority | low-priorityGoal priority (Preferred)',
'start', '', '0..1', 'CodeableConcept', 'When goal pursuit beginsGoal start event (Example)',
'addresses', '', '0..*', 'CodeableConcept', 'What does the goal addressCondition/Problem/Diagnosis Codes (Example)',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the goal',
'target', '', '0..*', 'BackboneElement', 'Target outcome for the goal',
'measure', '', '0..1', 'CodeableConcept', 'The parameter whose value is to be trackedLOINC Codes (Example)',
'detail[x]', '', '0..1', '', 'The target value to be achieved',
'detailQuantity', '', '', 'Quantity', '',
'detailRange', '', '', 'Range', '',
'detailCodeableConcept', '', '', 'CodeableConcept', '',
'due', '', '0..1', 'Duration', 'Reach goal within',
'action', '', '0..*', 'BackboneElement', 'Action defined by the plan',
'prefix', '', '0..1', 'string', 'User-visible prefix for the action (e.g. 1. or A.)',
'title', '', '0..1', 'string', 'User-visible title',
'description', '', '0..1', 'string', 'Brief description of the action',
'textEquivalent', '', '0..1', 'string', 'Static text equivalent of the action, used if the dynamic aspects cannot be interpreted by the receiving system',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', '', '0..*', 'CodeableConcept', 'Code representing the meaning of the action or sub-actions',
'reason', '', '0..*', 'CodeableConcept', 'Why the action should be performed',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the intended performer of the action',
'goalId', '', '0..*', 'id', 'What goals this action supports',
'subject[x]', '', '0..1', '', 'Type of individual the action is focused onSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'trigger', '', '0..*', 'TriggerDefinition', 'When the action should be triggered',
'condition', '', '0..*', 'BackboneElement', 'Whether or not the action is applicable',
'kind', '', '1..1', 'code', 'applicability | start | stopActionConditionKind (Required)',
'expression', '', '0..1', 'Expression', 'Boolean-valued expression',
'input', '', '0..*', 'DataRequirement', 'Input data requirements',
'output', '', '0..*', 'DataRequirement', 'Output data definition',
'relatedAction', '', '0..*', 'BackboneElement', 'Relationship to another action',
'actionId', '', '1..1', 'id', 'What action is this related to',
'relationship', '', '1..1', 'code', 'before-start | before | before-end | concurrent-with-start | concurrent | concurrent-with-end | after-start | after | after-endActionRelationshipType (Required)',
'offset[x]', '', '0..1', '', 'Time offset for the relationship',
'offsetDuration', '', '', 'Duration', '',
'offsetRange', '', '', 'Range', '',
'timing[x]', '', '0..1', '', 'When the action should take place',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingDuration', '', '', 'Duration', '',
'timingRange', '', '', 'Range', '',
'timingTiming', '', '', 'Timing', '',
'participant', '', '0..*', 'BackboneElement', 'Who should participate in the action',
'type', '', '1..1', 'code', 'patient | practitioner | related-person | deviceActionParticipantType (Required)',
'role', '', '0..1', 'CodeableConcept', 'E.g. Nurse, Surgeon, ParentAction participant role (Example)',
'type', '', '0..1', 'CodeableConcept', 'create | update | remove | fire-eventActionType (Extensible)',
'groupingBehavior', '', '0..1', 'code', 'visual-group | logical-group | sentence-groupActionGroupingBehavior (Required)',
'selectionBehavior', '', '0..1', 'code', 'any | all | all-or-none | exactly-one | at-most-one | one-or-moreActionSelectionBehavior (Required)',
'requiredBehavior', '', '0..1', 'code', 'must | could | must-unless-documentedActionRequiredBehavior (Required)',
'precheckBehavior', '', '0..1', 'code', 'yes | noActionPrecheckBehavior (Required)',
'cardinalityBehavior', '', '0..1', 'code', 'single | multipleActionCardinalityBehavior (Required)',
'definition[x]', '', '0..1', '', 'Description of the activity to be performed',
'definitionCanonical', '', '', 'canonical(ActivityDefinition | PlanDefinition | Questionnaire)', '',
'definitionUri', '', '', 'uri', '',
'transform', '', '0..1', 'canonical(StructureMap)', 'Transform to apply the template',
'dynamicValue', '', '0..*', 'BackboneElement', 'Dynamic aspects of the definition',
'path', '', '0..1', 'string', 'The path to the element to be set dynamically',
'expression', '', '0..1', 'Expression', 'An expression that provides the dynamic value for the customization',
'action', '', '0..*', 'see action', 'A sub-action',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'PlanDefinition', '',
'PlanDefinition.subtitle', 'Added Element',
'PlanDefinition.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/plan-definition-type" to "http://terminology.hl7.org/CodeSystem/plan-definition-type"',
'PlanDefinition.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'PlanDefinition.experimental', 'No longer marked as Modifier',
'PlanDefinition.subject[x]', 'Added Element',
'PlanDefinition.author', 'Added Element',
'PlanDefinition.editor', 'Added Element',
'PlanDefinition.reviewer', 'Added Element',
'PlanDefinition.endorser', 'Added Element',
'PlanDefinition.library', 'Type changed from Reference(Library) to canonical(Library)',
'PlanDefinition.action.prefix', 'Added Element',
'PlanDefinition.action.priority', 'Added Element',
'PlanDefinition.action.subject[x]', 'Added Element',
'PlanDefinition.action.trigger', 'Added Element',
'PlanDefinition.action.condition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/action-condition-kind to http://hl7.org/fhir/ValueSet/action-condition-kind|4.0.1',
'PlanDefinition.action.condition.expression', 'Type changed from string to Expression',
'PlanDefinition.action.relatedAction.relationship', 'Change value set from http://hl7.org/fhir/ValueSet/action-relationship-type to http://hl7.org/fhir/ValueSet/action-relationship-type|4.0.1',
'PlanDefinition.action.timing[x]', 'Add Type Age',
'PlanDefinition.action.participant.type', 'Change value set from http://hl7.org/fhir/ValueSet/action-participant-type to http://hl7.org/fhir/ValueSet/action-participant-type|4.0.1',
'PlanDefinition.action.type', 'Type changed from Coding to CodeableConcept
        Change binding strength from required to extensible',
'PlanDefinition.action.groupingBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-grouping-behavior to http://hl7.org/fhir/ValueSet/action-grouping-behavior|4.0.1',
'PlanDefinition.action.selectionBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-selection-behavior to http://hl7.org/fhir/ValueSet/action-selection-behavior|4.0.1',
'PlanDefinition.action.requiredBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-required-behavior to http://hl7.org/fhir/ValueSet/action-required-behavior|4.0.1',
'PlanDefinition.action.precheckBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-precheck-behavior to http://hl7.org/fhir/ValueSet/action-precheck-behavior|4.0.1',
'PlanDefinition.action.cardinalityBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-cardinality-behavior to http://hl7.org/fhir/ValueSet/action-cardinality-behavior|4.0.1',
'PlanDefinition.action.definition[x]', 'Renamed from definition to definition[x]
        Add Types canonical(ActivityDefinition | PlanDefinition | Questionnaire), uri
        Remove Type Reference(ActivityDefinition | PlanDefinition)',
'PlanDefinition.action.transform', 'Type changed from Reference(StructureMap) to canonical(StructureMap)',
'PlanDefinition.action.dynamicValue.expression', 'Type changed from string to Expression',
'PlanDefinition.contributor', 'deleted',
'PlanDefinition.action.label', 'deleted',
'PlanDefinition.action.triggerDefinition', 'deleted',
'PlanDefinition.action.condition.description', 'deleted',
'PlanDefinition.action.condition.language', 'deleted',
'PlanDefinition.action.dynamicValue.description', 'deleted',
'PlanDefinition.action.dynamicValue.language', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'PlanDefinition', 'ITU', '', 'DomainResource', 'The definition of a plan for a series of actions, independent of any specific patient or context+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this plan definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the plan definition',
'version', 'Σ', '0..1', 'string', 'Business version of the plan definition',
'name', 'ΣI', '0..1', 'string', 'Name for this plan definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this plan definition (human friendly)',
'subtitle', '', '0..1', 'string', 'Subordinate title of the plan definition',
'type', 'Σ', '0..1', 'CodeableConcept', 'order-set | clinical-protocol | eca-rule | workflow-definitionPlanDefinitionType (Extensible)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'Type of individual the plan definition is focused onSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the plan definition',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for plan definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this plan definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the plan',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the plan definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the plan definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the plan definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'E.g. Education, Treatment, AssessmentDefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the plan definition',
'goal', '', '0..*', 'BackboneElement', 'What the plan is trying to accomplish',
'category', '', '0..1', 'CodeableConcept', 'E.g. Treatment, dietary, behavioralGoal category (Example)',
'description', '', '1..1', 'CodeableConcept', 'Code or text describing the goalSNOMED CT Clinical Findings (Example)',
'priority', '', '0..1', 'CodeableConcept', 'high-priority | medium-priority | low-priorityGoal priority (Preferred)',
'start', '', '0..1', 'CodeableConcept', 'When goal pursuit beginsGoal start event (Example)',
'addresses', '', '0..*', 'CodeableConcept', 'What does the goal addressCondition/Problem/Diagnosis Codes (Example)',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the goal',
'target', '', '0..*', 'BackboneElement', 'Target outcome for the goal',
'measure', '', '0..1', 'CodeableConcept', 'The parameter whose value is to be trackedLOINC Codes (Example)',
'detail[x]', '', '0..1', '', 'The target value to be achieved',
'detailQuantity', '', '', 'Quantity', '',
'detailRange', '', '', 'Range', '',
'detailCodeableConcept', '', '', 'CodeableConcept', '',
'due', '', '0..1', 'Duration', 'Reach goal within',
'action', '', '0..*', 'BackboneElement', 'Action defined by the plan',
'prefix', '', '0..1', 'string', 'User-visible prefix for the action (e.g. 1. or A.)',
'title', '', '0..1', 'string', 'User-visible title',
'description', '', '0..1', 'string', 'Brief description of the action',
'textEquivalent', '', '0..1', 'string', 'Static text equivalent of the action, used if the dynamic aspects cannot be interpreted by the receiving system',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', '', '0..*', 'CodeableConcept', 'Code representing the meaning of the action or sub-actions',
'reason', '', '0..*', 'CodeableConcept', 'Why the action should be performed',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the intended performer of the action',
'goalId', '', '0..*', 'id', 'What goals this action supports',
'subject[x]', '', '0..1', '', 'Type of individual the action is focused onSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'trigger', '', '0..*', 'TriggerDefinition', 'When the action should be triggered',
'condition', '', '0..*', 'BackboneElement', 'Whether or not the action is applicable',
'kind', '', '1..1', 'code', 'applicability | start | stopActionConditionKind (Required)',
'expression', '', '0..1', 'Expression', 'Boolean-valued expression',
'input', '', '0..*', 'DataRequirement', 'Input data requirements',
'output', '', '0..*', 'DataRequirement', 'Output data definition',
'relatedAction', '', '0..*', 'BackboneElement', 'Relationship to another action',
'actionId', '', '1..1', 'id', 'What action is this related to',
'relationship', '', '1..1', 'code', 'before-start | before | before-end | concurrent-with-start | concurrent | concurrent-with-end | after-start | after | after-endActionRelationshipType (Required)',
'offset[x]', '', '0..1', '', 'Time offset for the relationship',
'offsetDuration', '', '', 'Duration', '',
'offsetRange', '', '', 'Range', '',
'timing[x]', '', '0..1', '', 'When the action should take place',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingDuration', '', '', 'Duration', '',
'timingRange', '', '', 'Range', '',
'timingTiming', '', '', 'Timing', '',
'participant', '', '0..*', 'BackboneElement', 'Who should participate in the action',
'type', '', '1..1', 'code', 'patient | practitioner | related-person | deviceActionParticipantType (Required)',
'role', '', '0..1', 'CodeableConcept', 'E.g. Nurse, Surgeon, ParentAction participant role (Example)',
'type', '', '0..1', 'CodeableConcept', 'create | update | remove | fire-eventActionType (Extensible)',
'groupingBehavior', '', '0..1', 'code', 'visual-group | logical-group | sentence-groupActionGroupingBehavior (Required)',
'selectionBehavior', '', '0..1', 'code', 'any | all | all-or-none | exactly-one | at-most-one | one-or-moreActionSelectionBehavior (Required)',
'requiredBehavior', '', '0..1', 'code', 'must | could | must-unless-documentedActionRequiredBehavior (Required)',
'precheckBehavior', '', '0..1', 'code', 'yes | noActionPrecheckBehavior (Required)',
'cardinalityBehavior', '', '0..1', 'code', 'single | multipleActionCardinalityBehavior (Required)',
'definition[x]', '', '0..1', '', 'Description of the activity to be performed',
'definitionCanonical', '', '', 'canonical(ActivityDefinition | PlanDefinition | Questionnaire)', '',
'definitionUri', '', '', 'uri', '',
'transform', '', '0..1', 'canonical(StructureMap)', 'Transform to apply the template',
'dynamicValue', '', '0..*', 'BackboneElement', 'Dynamic aspects of the definition',
'path', '', '0..1', 'string', 'The path to the element to be set dynamically',
'expression', '', '0..1', 'Expression', 'An expression that provides the dynamic value for the customization',
'action', '', '0..*', 'see action', 'A sub-action',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'PlanDefinition', '',
'PlanDefinition.subtitle', 'Added Element',
'PlanDefinition.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/plan-definition-type" to "http://terminology.hl7.org/CodeSystem/plan-definition-type"',
'PlanDefinition.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'PlanDefinition.experimental', 'No longer marked as Modifier',
'PlanDefinition.subject[x]', 'Added Element',
'PlanDefinition.author', 'Added Element',
'PlanDefinition.editor', 'Added Element',
'PlanDefinition.reviewer', 'Added Element',
'PlanDefinition.endorser', 'Added Element',
'PlanDefinition.library', 'Type changed from Reference(Library) to canonical(Library)',
'PlanDefinition.action.prefix', 'Added Element',
'PlanDefinition.action.priority', 'Added Element',
'PlanDefinition.action.subject[x]', 'Added Element',
'PlanDefinition.action.trigger', 'Added Element',
'PlanDefinition.action.condition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/action-condition-kind to http://hl7.org/fhir/ValueSet/action-condition-kind|4.0.1',
'PlanDefinition.action.condition.expression', 'Type changed from string to Expression',
'PlanDefinition.action.relatedAction.relationship', 'Change value set from http://hl7.org/fhir/ValueSet/action-relationship-type to http://hl7.org/fhir/ValueSet/action-relationship-type|4.0.1',
'PlanDefinition.action.timing[x]', 'Add Type Age',
'PlanDefinition.action.participant.type', 'Change value set from http://hl7.org/fhir/ValueSet/action-participant-type to http://hl7.org/fhir/ValueSet/action-participant-type|4.0.1',
'PlanDefinition.action.type', 'Type changed from Coding to CodeableConcept
        Change binding strength from required to extensible',
'PlanDefinition.action.groupingBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-grouping-behavior to http://hl7.org/fhir/ValueSet/action-grouping-behavior|4.0.1',
'PlanDefinition.action.selectionBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-selection-behavior to http://hl7.org/fhir/ValueSet/action-selection-behavior|4.0.1',
'PlanDefinition.action.requiredBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-required-behavior to http://hl7.org/fhir/ValueSet/action-required-behavior|4.0.1',
'PlanDefinition.action.precheckBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-precheck-behavior to http://hl7.org/fhir/ValueSet/action-precheck-behavior|4.0.1',
'PlanDefinition.action.cardinalityBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-cardinality-behavior to http://hl7.org/fhir/ValueSet/action-cardinality-behavior|4.0.1',
'PlanDefinition.action.definition[x]', 'Renamed from definition to definition[x]
        Add Types canonical(ActivityDefinition | PlanDefinition | Questionnaire), uri
        Remove Type Reference(ActivityDefinition | PlanDefinition)',
'PlanDefinition.action.transform', 'Type changed from Reference(StructureMap) to canonical(StructureMap)',
'PlanDefinition.action.dynamicValue.expression', 'Type changed from string to Expression',
'PlanDefinition.contributor', 'deleted',
'PlanDefinition.action.label', 'deleted',
'PlanDefinition.action.triggerDefinition', 'deleted',
'PlanDefinition.action.condition.description', 'deleted',
'PlanDefinition.action.condition.language', 'deleted',
'PlanDefinition.action.dynamicValue.description', 'deleted',
'PlanDefinition.action.dynamicValue.language', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'PlanDefinition.type', 'The type of PlanDefinition.', 'Extensible', 'PlanDefinitionType',
'PlanDefinition.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'PlanDefinition.subject[x]PlanDefinition.action.subject[x]', 'The possible types of subjects for a plan definition (E.g. Patient, Practitioner, Organization, Location, etc.).', 'Extensible', 'SubjectType',
'PlanDefinition.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'PlanDefinition.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'PlanDefinition.goal.category', 'Example codes for grouping goals for filtering or presentation.', 'Example', 'GoalCategory',
'PlanDefinition.goal.description', 'Describes goals that can be achieved.', 'Example', 'SNOMEDCTClinicalFindings',
'PlanDefinition.goal.priority', 'Indicates the level of importance associated with reaching or sustaining a goal.', 'Preferred', 'GoalPriority',
'PlanDefinition.goal.start', 'Identifies the types of events that might trigger the start of a goal.', 'Example', 'GoalStartEvent',
'PlanDefinition.goal.addresses', 'Identifies problems, conditions, issues, or concerns that goals may address.', 'Example', 'Condition/Problem/DiagnosisCodes',
'PlanDefinition.goal.target.measure', 'Identifies types of parameters that can be tracked to determine goal achievement.', 'Example', 'LOINCCodes',
'PlanDefinition.action.priority', 'Identifies the level of importance to be assigned to actioning the request.', 'Required', 'RequestPriority',
'PlanDefinition.action.condition.kind', 'Defines the kinds of conditions that can appear on actions.', 'Required', 'ActionConditionKind',
'PlanDefinition.action.relatedAction.relationship', 'Defines the types of relationships between actions.', 'Required', 'ActionRelationshipType',
'PlanDefinition.action.participant.type', 'The type of participant for the action.', 'Required', 'ActionParticipantType',
'PlanDefinition.action.participant.role', 'Defines roles played by participants for the action.', 'Example', 'ActionParticipantRole',
'PlanDefinition.action.type', 'The type of action to be performed.', 'Extensible', 'ActionType',
'PlanDefinition.action.groupingBehavior', 'Defines organization behavior of a group.', 'Required', 'ActionGroupingBehavior',
'PlanDefinition.action.selectionBehavior', 'Defines selection behavior of a group.', 'Required', 'ActionSelectionBehavior',
'PlanDefinition.action.requiredBehavior', 'Defines expectations around whether an action or action group is required.', 'Required', 'ActionRequiredBehavior',
'PlanDefinition.action.precheckBehavior', 'Defines selection frequency behavior for an action or group.', 'Required', 'ActionPrecheckBehavior',
'PlanDefinition.action.cardinalityBehavior', 'Defines behavior for an action or a group for how many times that item may be repeated.', 'Required', 'ActionCardinalityBehavior',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'pdf-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
)


df8 <- 
tibble::tribble(
~`Element`,~`Behavior`,
'title', 'The title element in ActivityDefinition is the title of the activity "as defined", where the title element in PlanDefinition reflects the title in the scope of the plan.',
'description', 'The description element in ActivityDefinition is the description of the activity "as defined", where the description element in PlanDefinition reflects the description in the scope of the plan.',
'code', 'The code element in ActivityDefinition represents the meaning of the activity "as defined", where the code element in PlanDefinition represents the meaning in the scope of the plan.',
'documentation', 'The documentation element in PlanDefinition represents additional documentation for the action specific to the scope of the plan, where the relatedArtifact element in ActivityDefinition provides documentation specific to the activity itself.',
'timing', 'The timing element in ActivityDefinition represents timings associated within the activity itself, where the timing element in PlanDefinition represents the timing of the activity with respect to the plan and its other actions. When a timing is provided on both, the timing defined in the plan generally takes precedence.',
'participant', 'The participant element in ActivityDefinition represents what type of actor is expected to perform the activity generally, where the participant element in PlanDefinition represents the type of actor that is expected to perform the activity in the context of the plan.',
'transform', 'The transform element in ActivityDefinition describes the transformation of the definition to a request or event resource in general, where the transform element in PlanDefinition describes the transformation within the scope of the plan. When a transform is present in both, the transform in the plan takes precedence.',
'dynamicValue', 'The dynamicValue element in ActivityDefinition defines values for elements of the target request or event resource in general, where the dynamicValue element in PlanDefinition defines values within the scope of the plan. When dynamic values are present in both, the dynamic values from the ActivityDefinition are applied first (in the order in which they appear on the ActivityDefinition), followed by the dynamic values from the PlanDefinition (in the order in which they appear on the PlanDefinition).',
)


df9 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'composed-of', 'reference', 'What resource is being referenced', 'PlanDefinition.relatedArtifact.where(type='composed-of').resource(Any)', '',
'context', 'token', 'A use context assigned to the plan definition', '(PlanDefinition.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the plan definition', '(PlanDefinition.useContext.value as Quantity) | (PlanDefinition.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the plan definition', 'PlanDefinition.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the plan definition', 'On PlanDefinition.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the plan definition', 'On PlanDefinition.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The plan definition publication date', 'PlanDefinition.date', '',
'definition', 'reference', 'Activity or plan definitions used by plan definition', 'PlanDefinition.action.definition(Questionnaire, PlanDefinition, ActivityDefinition)', '',
'depends-on', 'reference', 'What resource is being referenced', 'PlanDefinition.relatedArtifact.where(type='depends-on').resource | PlanDefinition.library(Library, Any)', '',
'derived-from', 'reference', 'What resource is being referenced', 'PlanDefinition.relatedArtifact.where(type='derived-from').resource(Any)', '',
'description', 'string', 'The description of the plan definition', 'PlanDefinition.description', '',
'effective', 'date', 'The time during which the plan definition is intended to be in use', 'PlanDefinition.effectivePeriod', '',
'identifier', 'token', 'External identifier for the plan definition', 'PlanDefinition.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the plan definition', 'PlanDefinition.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the plan definition', 'PlanDefinition.name', '',
'predecessor', 'reference', 'What resource is being referenced', 'PlanDefinition.relatedArtifact.where(type='predecessor').resource(Any)', '',
'publisher', 'string', 'Name of the publisher of the plan definition', 'PlanDefinition.publisher', '',
'status', 'token', 'The current status of the plan definition', 'PlanDefinition.status', '',
'successor', 'reference', 'What resource is being referenced', 'PlanDefinition.relatedArtifact.where(type='successor').resource(Any)', '',
'title', 'string', 'The human-friendly name of the plan definition', 'PlanDefinition.title', '',
'topic', 'token', 'Topics associated with the module', 'PlanDefinition.topic', '',
'type', 'token', 'The type of artifact the plan (e.g. order-set, eca-rule, protocol)', 'PlanDefinition.type', '',
'url', 'uri', 'The uri that identifies the plan definition', 'PlanDefinition.url', '',
'version', 'token', 'The business version of the plan definition', 'PlanDefinition.version', '',
)


