df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Patient Care  Work Group', 'Maturity Level: 3', 'Trial Use', 'Security Category: Patient', 'Compartments: Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Procedure', 'TU', '', 'DomainResource', 'An action that is being or was performed on a patientElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'External Identifiers for this procedure',
'instantiatesCanonical', 'Σ', '0..*', 'canonical(PlanDefinition | ActivityDefinition | Measure | OperationDefinition | Questionnaire)', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', 'Σ', '0..*', 'Reference(CarePlan | ServiceRequest)', 'A request for this procedure',
'partOf', 'Σ', '0..*', 'Reference(Procedure | Observation | MedicationAdministration)', 'Part of referenced event',
'status', '?!Σ', '1..1', 'code', 'preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknownEventStatus (Required)',
'statusReason', 'Σ', '0..1', 'CodeableConcept', 'Reason for current statusProcedure Not Performed Reason (SNOMED-CT) (Example)',
'category', 'Σ', '0..1', 'CodeableConcept', 'Classification of the procedureProcedure Category Codes (SNOMED CT) (Example)',
'code', 'Σ', '0..1', 'CodeableConcept', 'Identification of the procedureProcedure Codes (SNOMED CT) (Example)',
'subject', 'Σ', '1..1', 'Reference(Patient | Group)', 'Who the procedure was performed on',
'encounter', 'Σ', '0..1', 'Reference(Encounter)', 'Encounter created as part of',
'performed[x]', 'Σ', '0..1', '', 'When the procedure was performed',
'performedDateTime', '', '', 'dateTime', '',
'performedPeriod', '', '', 'Period', '',
'performedString', '', '', 'string', '',
'performedAge', '', '', 'Age', '',
'performedRange', '', '', 'Range', '',
'recorder', 'Σ', '0..1', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole)', 'Who recorded the procedure',
'asserter', 'Σ', '0..1', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole)', 'Person who asserts this procedure',
'performer', 'Σ', '0..*', 'BackboneElement', 'The people who performed the procedure',
'function', 'Σ', '0..1', 'CodeableConcept', 'Type of performanceProcedure Performer Role Codes (Example)',
'actor', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson | Device)', 'The reference to the practitioner',
'onBehalfOf', '', '0..1', 'Reference(Organization)', 'Organization the device or practitioner was acting for',
'location', 'Σ', '0..1', 'Reference(Location)', 'Where the procedure happened',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Coded reason procedure performedProcedure Reason Codes (Example)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Observation | Procedure | DiagnosticReport | DocumentReference)', 'The justification that the procedure was performed',
'bodySite', 'Σ', '0..*', 'CodeableConcept', 'Target body sitesSNOMED CT Body Structures (Example)',
'outcome', 'Σ', '0..1', 'CodeableConcept', 'The result of procedureProcedure Outcome Codes (SNOMED CT) (Example)',
'report', '', '0..*', 'Reference(DiagnosticReport | DocumentReference | Composition)', 'Any report resulting from the procedure',
'complication', '', '0..*', 'CodeableConcept', 'Complication following the procedureCondition/Problem/Diagnosis Codes (Example)',
'complicationDetail', '', '0..*', 'Reference(Condition)', 'A condition that is a result of the procedure',
'followUp', '', '0..*', 'CodeableConcept', 'Instructions for follow upProcedure Follow up Codes (SNOMED CT) (Example)',
'note', '', '0..*', 'Annotation', 'Additional information about the procedure',
'focalDevice', '', '0..*', 'BackboneElement', 'Manipulated, implanted, or removed device',
'action', '', '0..1', 'CodeableConcept', 'Kind of change to deviceProcedure Device Action Codes (Preferred)',
'manipulated', '', '1..1', 'Reference(Device)', 'Device that was changed',
'usedReference', '', '0..*', 'Reference(Device | Medication | Substance)', 'Items used during procedure',
'usedCode', '', '0..*', 'CodeableConcept', 'Coded items used during the procedureFHIR Device Types (Example)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Procedure', '',
'Procedure.instantiatesCanonical', 'Added Element',
'Procedure.instantiatesUri', 'Added Element',
'Procedure.basedOn', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Types ProcedureRequest, ReferralRequest',
'Procedure.status', 'Change value set from http://hl7.org/fhir/ValueSet/event-status to http://hl7.org/fhir/ValueSet/event-status|4.0.1',
'Procedure.statusReason', 'Added Element',
'Procedure.encounter', 'Added Element',
'Procedure.performed[x]', 'Add Types string, Age, Range',
'Procedure.recorder', 'Added Element',
'Procedure.asserter', 'Added Element',
'Procedure.performer.function', 'Added Element',
'Procedure.performer.actor', 'Type Reference: Added Target Type PractitionerRole',
'Procedure.reasonReference', 'Type Reference: Added Target Types Procedure, DiagnosticReport, DocumentReference',
'Procedure.report', 'Type Reference: Added Target Types DocumentReference, Composition',
'Procedure.definition', 'deleted',
'Procedure.notDone', 'deleted',
'Procedure.notDoneReason', 'deleted',
'Procedure.context', 'deleted',
'Procedure.performer.role', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Procedure', 'TU', '', 'DomainResource', 'An action that is being or was performed on a patientElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'External Identifiers for this procedure',
'instantiatesCanonical', 'Σ', '0..*', 'canonical(PlanDefinition | ActivityDefinition | Measure | OperationDefinition | Questionnaire)', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', 'Σ', '0..*', 'Reference(CarePlan | ServiceRequest)', 'A request for this procedure',
'partOf', 'Σ', '0..*', 'Reference(Procedure | Observation | MedicationAdministration)', 'Part of referenced event',
'status', '?!Σ', '1..1', 'code', 'preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknownEventStatus (Required)',
'statusReason', 'Σ', '0..1', 'CodeableConcept', 'Reason for current statusProcedure Not Performed Reason (SNOMED-CT) (Example)',
'category', 'Σ', '0..1', 'CodeableConcept', 'Classification of the procedureProcedure Category Codes (SNOMED CT) (Example)',
'code', 'Σ', '0..1', 'CodeableConcept', 'Identification of the procedureProcedure Codes (SNOMED CT) (Example)',
'subject', 'Σ', '1..1', 'Reference(Patient | Group)', 'Who the procedure was performed on',
'encounter', 'Σ', '0..1', 'Reference(Encounter)', 'Encounter created as part of',
'performed[x]', 'Σ', '0..1', '', 'When the procedure was performed',
'performedDateTime', '', '', 'dateTime', '',
'performedPeriod', '', '', 'Period', '',
'performedString', '', '', 'string', '',
'performedAge', '', '', 'Age', '',
'performedRange', '', '', 'Range', '',
'recorder', 'Σ', '0..1', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole)', 'Who recorded the procedure',
'asserter', 'Σ', '0..1', 'Reference(Patient | RelatedPerson | Practitioner | PractitionerRole)', 'Person who asserts this procedure',
'performer', 'Σ', '0..*', 'BackboneElement', 'The people who performed the procedure',
'function', 'Σ', '0..1', 'CodeableConcept', 'Type of performanceProcedure Performer Role Codes (Example)',
'actor', 'Σ', '1..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson | Device)', 'The reference to the practitioner',
'onBehalfOf', '', '0..1', 'Reference(Organization)', 'Organization the device or practitioner was acting for',
'location', 'Σ', '0..1', 'Reference(Location)', 'Where the procedure happened',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Coded reason procedure performedProcedure Reason Codes (Example)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Observation | Procedure | DiagnosticReport | DocumentReference)', 'The justification that the procedure was performed',
'bodySite', 'Σ', '0..*', 'CodeableConcept', 'Target body sitesSNOMED CT Body Structures (Example)',
'outcome', 'Σ', '0..1', 'CodeableConcept', 'The result of procedureProcedure Outcome Codes (SNOMED CT) (Example)',
'report', '', '0..*', 'Reference(DiagnosticReport | DocumentReference | Composition)', 'Any report resulting from the procedure',
'complication', '', '0..*', 'CodeableConcept', 'Complication following the procedureCondition/Problem/Diagnosis Codes (Example)',
'complicationDetail', '', '0..*', 'Reference(Condition)', 'A condition that is a result of the procedure',
'followUp', '', '0..*', 'CodeableConcept', 'Instructions for follow upProcedure Follow up Codes (SNOMED CT) (Example)',
'note', '', '0..*', 'Annotation', 'Additional information about the procedure',
'focalDevice', '', '0..*', 'BackboneElement', 'Manipulated, implanted, or removed device',
'action', '', '0..1', 'CodeableConcept', 'Kind of change to deviceProcedure Device Action Codes (Preferred)',
'manipulated', '', '1..1', 'Reference(Device)', 'Device that was changed',
'usedReference', '', '0..*', 'Reference(Device | Medication | Substance)', 'Items used during procedure',
'usedCode', '', '0..*', 'CodeableConcept', 'Coded items used during the procedureFHIR Device Types (Example)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Procedure', '',
'Procedure.instantiatesCanonical', 'Added Element',
'Procedure.instantiatesUri', 'Added Element',
'Procedure.basedOn', 'Type Reference: Added Target Type ServiceRequest
        Type Reference: Removed Target Types ProcedureRequest, ReferralRequest',
'Procedure.status', 'Change value set from http://hl7.org/fhir/ValueSet/event-status to http://hl7.org/fhir/ValueSet/event-status|4.0.1',
'Procedure.statusReason', 'Added Element',
'Procedure.encounter', 'Added Element',
'Procedure.performed[x]', 'Add Types string, Age, Range',
'Procedure.recorder', 'Added Element',
'Procedure.asserter', 'Added Element',
'Procedure.performer.function', 'Added Element',
'Procedure.performer.actor', 'Type Reference: Added Target Type PractitionerRole',
'Procedure.reasonReference', 'Type Reference: Added Target Types Procedure, DiagnosticReport, DocumentReference',
'Procedure.report', 'Type Reference: Added Target Types DocumentReference, Composition',
'Procedure.definition', 'deleted',
'Procedure.notDone', 'deleted',
'Procedure.notDoneReason', 'deleted',
'Procedure.context', 'deleted',
'Procedure.performer.role', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Procedure.status', 'A code specifying the state of the procedure.', 'Required', 'EventStatus',
'Procedure.statusReason', 'A code that identifies the reason a procedure was not performed.', 'Example', 'ProcedureNotPerformedReason(SNOMED-CT)',
'Procedure.category', 'A code that classifies a procedure for searching, sorting and display purposes.', 'Example', 'ProcedureCategoryCodes(SNOMEDCT)',
'Procedure.code', 'A code to identify a specific procedure .', 'Example', 'ProcedureCodes(SNOMEDCT)',
'Procedure.performer.function', 'A code that identifies the role of a performer of the procedure.', 'Example', 'ProcedurePerformerRoleCodes',
'Procedure.reasonCode', 'A code that identifies the reason a procedure is  required.', 'Example', 'ProcedureReasonCodes',
'Procedure.bodySite', 'Codes describing anatomical locations. May include laterality.', 'Example', 'SNOMEDCTBodyStructures',
'Procedure.outcome', 'An outcome of a procedure - whether it was resolved or otherwise.', 'Example', 'ProcedureOutcomeCodes(SNOMEDCT)',
'Procedure.complication', 'Codes describing complications that resulted from a procedure.', 'Example', 'Condition/Problem/DiagnosisCodes',
'Procedure.followUp', 'Specific follow up required for a procedure e.g. removal of sutures.', 'Example', 'ProcedureFollowUpCodes(SNOMEDCT)',
'Procedure.focalDevice.action', 'A kind of change that happened to the device during the procedure.', 'Preferred', 'ProcedureDeviceActionCodes',
'Procedure.usedCode', 'Codes describing items used during a procedure.', 'Example', 'FHIRDeviceTypes',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'based-on', 'reference', 'A request for this procedure', 'Procedure.basedOn(CarePlan, ServiceRequest)', '',
'category', 'token', 'Classification of the procedure', 'Procedure.category', '',
'code', 'token', 'A code to identify a  procedure', 'Procedure.code', '13 Resources',
'date', 'date', 'When the procedure was performed', 'Procedure.performed', '17 Resources',
'encounter', 'reference', 'Encounter created as part of', 'Procedure.encounter(Encounter)', '12 Resources',
'identifier', 'token', 'A unique identifier for a procedure', 'Procedure.identifier', '30 Resources',
'instantiates-canonical', 'reference', 'Instantiates FHIR protocol or definition', 'Procedure.instantiatesCanonical(Questionnaire, Measure, PlanDefinition, OperationDefinition, ActivityDefinition)', '',
'instantiates-uri', 'uri', 'Instantiates external protocol or definition', 'Procedure.instantiatesUri', '',
'location', 'reference', 'Where the procedure happened', 'Procedure.location(Location)', '',
'part-of', 'reference', 'Part of referenced event', 'Procedure.partOf(Observation, Procedure, MedicationAdministration)', '',
'patient', 'reference', 'Search by subject - a patient', 'Procedure.subject.where(resolve() is Patient)(Patient)', '33 Resources',
'performer', 'reference', 'The reference to the practitioner', 'Procedure.performer.actor(Practitioner, Organization, Device, Patient, PractitionerRole, RelatedPerson)', '',
'reason-code', 'token', 'Coded reason procedure performed', 'Procedure.reasonCode', '',
'reason-reference', 'reference', 'The justification that the procedure was performed', 'Procedure.reasonReference(Condition, Observation, Procedure, DiagnosticReport, DocumentReference)', '',
'status', 'token', 'preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown', 'Procedure.status', '',
'subject', 'reference', 'Search by subject', 'Procedure.subject(Group, Patient)', '',
)


