df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: 3', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Questionnaire', 'ITU', '', 'DomainResource', 'A structured set of questions+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: The link ids for groups and questions must be unique within the questionnaireElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this questionnaire, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the questionnaire',
'version', 'Σ', '0..1', 'string', 'Business version of the questionnaire',
'name', 'ΣI', '0..1', 'string', 'Name for this questionnaire (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this questionnaire (human friendly)',
'derivedFrom', '', '0..*', 'canonical(Questionnaire)', 'Instantiates protocol or definition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subjectType', 'Σ', '0..*', 'code', 'Resource that can be subject of QuestionnaireResponseResourceType (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the questionnaire',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for questionnaire (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this questionnaire is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the questionnaire was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the questionnaire was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the questionnaire is expected to be used',
'code', 'Σ', '0..*', 'Coding', 'Concept that represents the overall questionnaireQuestionnaire Question Codes (Example)',
'item', 'I', '0..*', 'BackboneElement', 'Questions and sections within the Questionnaire+ Rule: Group items must have nested items, display items cannot have nested items+ Rule: Display items cannot have a "code" asserted+ Rule: A question cannot have both answerOption and answerValueSet+ Rule: Only 'choice' and 'open-choice' items can have answerValueSet+ Rule: Required and repeat aren't permitted for display items+ Rule: Initial values can't be specified for groups or display items+ Rule: Read-only can't be specified for "display" items+ Rule: Maximum length can only be declared for simple question types+ Rule: If one or more answerOption is present, initial[x] must be missing+ Rule: If there are more than one enableWhen, enableBehavior must be specified+ Rule: Can only have multiple initial values for repeating items',
'linkId', '', '1..1', 'string', 'Unique id for item in questionnaire',
'definition', '', '0..1', 'uri', 'ElementDefinition - details for the item',
'code', 'I', '0..*', 'Coding', 'Corresponding concept for this item in a terminologyQuestionnaire Question Codes (Example)',
'prefix', '', '0..1', 'string', 'E.g. "1(a)", "2.5.3"',
'text', '', '0..1', 'string', 'Primary text for the item',
'type', '', '1..1', 'code', 'group | display | boolean | decimal | integer | date | dateTime +QuestionnaireItemType (Required)',
'enableWhen', '?!I', '0..*', 'BackboneElement', 'Only allow data when+ Rule: If the operator is 'exists', the value must be a boolean',
'question', '', '1..1', 'string', 'Question that determines whether item is enabled',
'operator', '', '1..1', 'code', 'exists | = | != | > | < | >= | <=QuestionnaireItemOperator (Required)',
'answer[x]', 'I', '1..1', '', 'Value for question comparison based on operatorQuestionnaire Answer Codes (Example)',
'answerBoolean', '', '', 'boolean', '',
'answerDecimal', '', '', 'decimal', '',
'answerInteger', '', '', 'integer', '',
'answerDate', '', '', 'date', '',
'answerDateTime', '', '', 'dateTime', '',
'answerTime', '', '', 'time', '',
'answerString', '', '', 'string', '',
'answerCoding', '', '', 'Coding', '',
'answerQuantity', '', '', 'Quantity', '',
'answerReference', '', '', 'Reference(Any)', '',
'enableBehavior', 'I', '0..1', 'code', 'all | anyEnableWhenBehavior (Required)',
'required', 'I', '0..1', 'boolean', 'Whether the item must be included in data results',
'repeats', 'I', '0..1', 'boolean', 'Whether the item may repeat',
'readOnly', 'I', '0..1', 'boolean', 'Don't allow human editing',
'maxLength', 'I', '0..1', 'integer', 'No more than this many characters',
'answerValueSet', 'I', '0..1', 'canonical(ValueSet)', 'Valueset containing permitted answers',
'answerOption', 'I', '0..*', 'BackboneElement', 'Permitted answer',
'value[x]', '', '1..1', '', 'Answer valueQuestionnaire Answer Codes (Example)',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueCoding', '', '', 'Coding', '',
'valueReference', '', '', 'Reference(Any)', '',
'initialSelected', '', '0..1', 'boolean', 'Whether option is selected by default',
'initial', 'I', '0..*', 'BackboneElement', 'Initial value(s) when item is first rendered',
'value[x]', '', '1..1', '', 'Actual value for initializing the questionQuestionnaire Answer Codes (Example)',
'valueBoolean', '', '', 'boolean', '',
'valueDecimal', '', '', 'decimal', '',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueDateTime', '', '', 'dateTime', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueUri', '', '', 'uri', '',
'valueAttachment', '', '', 'Attachment', '',
'valueCoding', '', '', 'Coding', '',
'valueQuantity', '', '', 'Quantity', '',
'valueReference', '', '', 'Reference(Any)', '',
'item', 'I', '0..*', 'see item', 'Nested questionnaire items',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'Questionnaire', '',
'Questionnaire.derivedFrom', 'Added Element',
'Questionnaire.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'Questionnaire.experimental', 'No longer marked as Modifier',
'Questionnaire.subjectType', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'Questionnaire.item.type', 'Change value set from http://hl7.org/fhir/ValueSet/item-type to http://hl7.org/fhir/ValueSet/item-type|4.0.1',
'Questionnaire.item.enableWhen.operator', 'Added Mandatory Element',
'Questionnaire.item.enableWhen.answer[x]', 'Min Cardinality changed from 0 to 1
        Remove Types uri, Attachment',
'Questionnaire.item.enableBehavior', 'Added Element',
'Questionnaire.item.required', 'Default Value "false" removed',
'Questionnaire.item.repeats', 'Default Value "false" removed',
'Questionnaire.item.answerValueSet', 'Renamed from options to answerValueSet
        Type changed from Reference(ValueSet) to canonical(ValueSet)',
'Questionnaire.item.answerOption', 'Renamed from option to answerOption',
'Questionnaire.item.answerOption.value[x]', 'Moved from Questionnaire.item.option to Questionnaire.item.answerOption
        Add Type Reference(Resource)',
'Questionnaire.item.answerOption.initialSelected', 'Added Element',
'Questionnaire.item.initial', 'Renamed from initial[x] to initial
        Max Cardinality changed from 1 to *
        Remove Types boolean, decimal, integer, date, dateTime, time, string, uri, Attachment, Coding, Quantity, Reference(Resource)',
'Questionnaire.item.initial.value[x]', 'Added Mandatory Element',
'Questionnaire.item.enableWhen.hasAnswer', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'Questionnaire', 'ITU', '', 'DomainResource', 'A structured set of questions+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: The link ids for groups and questions must be unique within the questionnaireElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this questionnaire, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the questionnaire',
'version', 'Σ', '0..1', 'string', 'Business version of the questionnaire',
'name', 'ΣI', '0..1', 'string', 'Name for this questionnaire (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this questionnaire (human friendly)',
'derivedFrom', '', '0..*', 'canonical(Questionnaire)', 'Instantiates protocol or definition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subjectType', 'Σ', '0..*', 'code', 'Resource that can be subject of QuestionnaireResponseResourceType (Required)',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the questionnaire',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for questionnaire (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this questionnaire is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the questionnaire was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the questionnaire was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the questionnaire is expected to be used',
'code', 'Σ', '0..*', 'Coding', 'Concept that represents the overall questionnaireQuestionnaire Question Codes (Example)',
'item', 'I', '0..*', 'BackboneElement', 'Questions and sections within the Questionnaire+ Rule: Group items must have nested items, display items cannot have nested items+ Rule: Display items cannot have a "code" asserted+ Rule: A question cannot have both answerOption and answerValueSet+ Rule: Only 'choice' and 'open-choice' items can have answerValueSet+ Rule: Required and repeat aren't permitted for display items+ Rule: Initial values can't be specified for groups or display items+ Rule: Read-only can't be specified for "display" items+ Rule: Maximum length can only be declared for simple question types+ Rule: If one or more answerOption is present, initial[x] must be missing+ Rule: If there are more than one enableWhen, enableBehavior must be specified+ Rule: Can only have multiple initial values for repeating items',
'linkId', '', '1..1', 'string', 'Unique id for item in questionnaire',
'definition', '', '0..1', 'uri', 'ElementDefinition - details for the item',
'code', 'I', '0..*', 'Coding', 'Corresponding concept for this item in a terminologyQuestionnaire Question Codes (Example)',
'prefix', '', '0..1', 'string', 'E.g. "1(a)", "2.5.3"',
'text', '', '0..1', 'string', 'Primary text for the item',
'type', '', '1..1', 'code', 'group | display | boolean | decimal | integer | date | dateTime +QuestionnaireItemType (Required)',
'enableWhen', '?!I', '0..*', 'BackboneElement', 'Only allow data when+ Rule: If the operator is 'exists', the value must be a boolean',
'question', '', '1..1', 'string', 'Question that determines whether item is enabled',
'operator', '', '1..1', 'code', 'exists | = | != | > | < | >= | <=QuestionnaireItemOperator (Required)',
'answer[x]', 'I', '1..1', '', 'Value for question comparison based on operatorQuestionnaire Answer Codes (Example)',
'answerBoolean', '', '', 'boolean', '',
'answerDecimal', '', '', 'decimal', '',
'answerInteger', '', '', 'integer', '',
'answerDate', '', '', 'date', '',
'answerDateTime', '', '', 'dateTime', '',
'answerTime', '', '', 'time', '',
'answerString', '', '', 'string', '',
'answerCoding', '', '', 'Coding', '',
'answerQuantity', '', '', 'Quantity', '',
'answerReference', '', '', 'Reference(Any)', '',
'enableBehavior', 'I', '0..1', 'code', 'all | anyEnableWhenBehavior (Required)',
'required', 'I', '0..1', 'boolean', 'Whether the item must be included in data results',
'repeats', 'I', '0..1', 'boolean', 'Whether the item may repeat',
'readOnly', 'I', '0..1', 'boolean', 'Don't allow human editing',
'maxLength', 'I', '0..1', 'integer', 'No more than this many characters',
'answerValueSet', 'I', '0..1', 'canonical(ValueSet)', 'Valueset containing permitted answers',
'answerOption', 'I', '0..*', 'BackboneElement', 'Permitted answer',
'value[x]', '', '1..1', '', 'Answer valueQuestionnaire Answer Codes (Example)',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueCoding', '', '', 'Coding', '',
'valueReference', '', '', 'Reference(Any)', '',
'initialSelected', '', '0..1', 'boolean', 'Whether option is selected by default',
'initial', 'I', '0..*', 'BackboneElement', 'Initial value(s) when item is first rendered',
'value[x]', '', '1..1', '', 'Actual value for initializing the questionQuestionnaire Answer Codes (Example)',
'valueBoolean', '', '', 'boolean', '',
'valueDecimal', '', '', 'decimal', '',
'valueInteger', '', '', 'integer', '',
'valueDate', '', '', 'date', '',
'valueDateTime', '', '', 'dateTime', '',
'valueTime', '', '', 'time', '',
'valueString', '', '', 'string', '',
'valueUri', '', '', 'uri', '',
'valueAttachment', '', '', 'Attachment', '',
'valueCoding', '', '', 'Coding', '',
'valueQuantity', '', '', 'Quantity', '',
'valueReference', '', '', 'Reference(Any)', '',
'item', 'I', '0..*', 'see item', 'Nested questionnaire items',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'Questionnaire', '',
'Questionnaire.derivedFrom', 'Added Element',
'Questionnaire.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'Questionnaire.experimental', 'No longer marked as Modifier',
'Questionnaire.subjectType', 'Change value set from http://hl7.org/fhir/ValueSet/resource-types to http://hl7.org/fhir/ValueSet/resource-types|4.0.1',
'Questionnaire.item.type', 'Change value set from http://hl7.org/fhir/ValueSet/item-type to http://hl7.org/fhir/ValueSet/item-type|4.0.1',
'Questionnaire.item.enableWhen.operator', 'Added Mandatory Element',
'Questionnaire.item.enableWhen.answer[x]', 'Min Cardinality changed from 0 to 1
        Remove Types uri, Attachment',
'Questionnaire.item.enableBehavior', 'Added Element',
'Questionnaire.item.required', 'Default Value "false" removed',
'Questionnaire.item.repeats', 'Default Value "false" removed',
'Questionnaire.item.answerValueSet', 'Renamed from options to answerValueSet
        Type changed from Reference(ValueSet) to canonical(ValueSet)',
'Questionnaire.item.answerOption', 'Renamed from option to answerOption',
'Questionnaire.item.answerOption.value[x]', 'Moved from Questionnaire.item.option to Questionnaire.item.answerOption
        Add Type Reference(Resource)',
'Questionnaire.item.answerOption.initialSelected', 'Added Element',
'Questionnaire.item.initial', 'Renamed from initial[x] to initial
        Max Cardinality changed from 1 to *
        Remove Types boolean, decimal, integer, date, dateTime, time, string, uri, Attachment, Coding, Quantity, Reference(Resource)',
'Questionnaire.item.initial.value[x]', 'Added Mandatory Element',
'Questionnaire.item.enableWhen.hasAnswer', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'Questionnaire.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'Questionnaire.subjectType', 'One of the resource types defined as part of this version of FHIR.', 'Required', 'Resource Types',
'Questionnaire.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'Questionnaire.codeQuestionnaire.item.code', 'Codes for questionnaires, groups and individual questions.', 'Example', 'QuestionnaireQuestionCodes',
'Questionnaire.item.type', 'Distinguishes groups from questions and display text and indicates data type for questions.', 'Required', 'QuestionnaireItemType',
'Questionnaire.item.enableWhen.operator', 'The criteria by which a question is enabled.', 'Required', 'QuestionnaireItemOperator',
'Questionnaire.item.enableWhen.answer[x]', 'Allowed values to answer questions.', 'Example', 'QuestionnaireAnswerCodes',
'Questionnaire.item.enableBehavior', 'Controls how multiple enableWhen values are interpreted -  whether all or any must be true.', 'Required', 'EnableWhenBehavior',
'Questionnaire.item.answerOption.value[x]', 'Allowed values to answer questions.', 'Example', 'QuestionnaireAnswerCodes',
'Questionnaire.item.initial.value[x]', 'Allowed values to answer questions.', 'Example', 'QuestionnaireAnswerCodes',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'que-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'que-1', 'Rule', 'Questionnaire.item', 'Group items must have nested items, display items cannot have nested items', '(type='group' implies item.empty().not()) and (type.trace('type')='display' implies item.trace('item').empty())',
'que-2', 'Rule', '(base)', 'The link ids for groups and questions must be unique within the questionnaire', 'descendants().linkId.isDistinct()',
'que-3', 'Rule', 'Questionnaire.item', 'Display items cannot have a "code" asserted', 'type!='display' or code.empty()',
'que-4', 'Rule', 'Questionnaire.item', 'A question cannot have both answerOption and answerValueSet', 'answerOption.empty() or answerValueSet.empty()',
'que-5', 'Rule', 'Questionnaire.item', 'Only 'choice' and 'open-choice' items can have answerValueSet', '(type ='choice' or type = 'open-choice' or type = 'decimal' or type = 'integer' or type = 'date' or type = 'dateTime' or type = 'time' or type = 'string' or type = 'quantity') or (answerValueSet.empty() and answerOption.empty())',
'que-6', 'Rule', 'Questionnaire.item', 'Required and repeat aren't permitted for display items', 'type!='display' or (required.empty() and repeats.empty())',
'que-7', 'Rule', 'Questionnaire.item.enableWhen', 'If the operator is 'exists', the value must be a boolean', 'operator = 'exists' implies (answer is Boolean)',
'que-8', 'Rule', 'Questionnaire.item', 'Initial values can't be specified for groups or display items', '(type!='group' and type!='display') or initial.empty()',
'que-9', 'Rule', 'Questionnaire.item', 'Read-only can't be specified for "display" items', 'type!='display' or readOnly.empty()',
'que-10', 'Rule', 'Questionnaire.item', 'Maximum length can only be declared for simple question types', '(type in ('boolean' | 'decimal' | 'integer' | 'string' | 'text' | 'url' | 'open-choice')) or maxLength.empty()',
'que-11', 'Rule', 'Questionnaire.item', 'If one or more answerOption is present, initial[x] must be missing', 'answerOption.empty() or initial.empty()',
'que-12', 'Rule', 'Questionnaire.item', 'If there are more than one enableWhen, enableBehavior must be specified', 'enableWhen.count() > 2 implies enableBehavior.exists()',
'que-13', 'Rule', 'Questionnaire.item', 'Can only have multiple initial values for repeating items', 'repeats=true or initial.count() <= 1',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,
'Value of definition', 'Explanation',
'http://hl7.org/fhir/StructureDefinition/Observation#Observation.comment', 'A reference to the standard Observation element comment',
'http://example.org/definitions/xxx', 'A reference to the logical model "xxx" that represents a data element',
'http://example.org/StructureDefinition/Oedema#Observation.category:XXX', 'A reference to slice XXX on the Observation category element on an Oedema Scale profile',
'http://example.org/StructureDefinition/Oedema|2.0#Observation.category:XXX', 'A reference to slice XXX on the Observation category element on an Oedema Scale profile, specifying version 2.0',
)


df9 <- 
tibble::tribble(
~`Questionnaire AnswerFormat code`,~`QuestionnaireResponse data type`,
'text', 'string',
'url', 'uri',
'choice', 'Coding',
'open-choice', 'Coding (if choosing from one of the listed choices) or string (if a different value is provided)',
)


df10 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'code', 'token', 'A code that corresponds to one of its items in the questionnaire', 'Questionnaire.item.code', '',
'context', 'token', 'A use context assigned to the questionnaire', '(Questionnaire.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the questionnaire', '(Questionnaire.useContext.value as Quantity) | (Questionnaire.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the questionnaire', 'Questionnaire.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the questionnaire', 'On Questionnaire.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the questionnaire', 'On Questionnaire.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The questionnaire publication date', 'Questionnaire.date', '',
'definition', 'uri', 'ElementDefinition - details for the item', 'Questionnaire.item.definition', '',
'description', 'string', 'The description of the questionnaire', 'Questionnaire.description', '',
'effective', 'date', 'The time during which the questionnaire is intended to be in use', 'Questionnaire.effectivePeriod', '',
'identifier', 'token', 'External identifier for the questionnaire', 'Questionnaire.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the questionnaire', 'Questionnaire.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the questionnaire', 'Questionnaire.name', '',
'publisher', 'string', 'Name of the publisher of the questionnaire', 'Questionnaire.publisher', '',
'status', 'token', 'The current status of the questionnaire', 'Questionnaire.status', '',
'subject-type', 'token', 'Resource that can be subject of QuestionnaireResponse', 'Questionnaire.subjectType', '',
'title', 'string', 'The human-friendly name of the questionnaire', 'Questionnaire.title', '',
'url', 'uri', 'The uri that identifies the questionnaire', 'Questionnaire.url', '',
'version', 'token', 'The business version of the questionnaire', 'Questionnaire.version', '',
)


