df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Business', 'Compartments: Device, Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'RequestGroup', 'TU', '', 'DomainResource', 'A group of related requestsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Business identifier',
'instantiatesCanonical', 'Σ', '0..*', 'canonical()', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', '', '0..*', 'Reference(Any)', 'Fulfills plan, proposal, or order',
'replaces', '', '0..*', 'Reference(Any)', 'Request(s) replaced by this request',
'groupIdentifier', 'Σ', '0..1', 'Identifier', 'Composite request this is part of',
'status', '?!Σ', '1..1', 'code', 'draft | active | on-hold | revoked | completed | entered-in-error | unknownRequestStatus (Required)',
'intent', '?!Σ', '1..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'priority', 'Σ', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', 'Σ', '0..1', 'CodeableConcept', 'What's being requested/ordered',
'subject', '', '0..1', 'Reference(Patient | Group)', 'Who the request group is about',
'encounter', '', '0..1', 'Reference(Encounter)', 'Created as part of',
'authoredOn', '', '0..1', 'dateTime', 'When the request group was authored',
'author', '', '0..1', 'Reference(Device | Practitioner | PractitionerRole)', 'Device or practitioner that authored the request group',
'reasonCode', '', '0..*', 'CodeableConcept', 'Why the request group is needed',
'reasonReference', '', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference)', 'Why the request group is needed',
'note', '', '0..*', 'Annotation', 'Additional notes about the response',
'action', 'I', '0..*', 'BackboneElement', 'Proposed actions, if any+ Rule: Must have resource or action but not both',
'prefix', '', '0..1', 'string', 'User-visible prefix for the action (e.g. 1. or A.)',
'title', '', '0..1', 'string', 'User-visible title',
'description', 'Σ', '0..1', 'string', 'Short description of the action',
'textEquivalent', 'Σ', '0..1', 'string', 'Static text equivalent of the action, used if the dynamic aspects cannot be interpreted by the receiving system',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', '', '0..*', 'CodeableConcept', 'Code representing the meaning of the action or sub-actions',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the intended performer of the action',
'condition', '', '0..*', 'BackboneElement', 'Whether or not the action is applicable',
'kind', '', '1..1', 'code', 'applicability | start | stopActionConditionKind (Required)',
'expression', '', '0..1', 'Expression', 'Boolean-valued expression',
'relatedAction', '', '0..*', 'BackboneElement', 'Relationship to another action',
'actionId', '', '1..1', 'id', 'What action this is related to',
'relationship', '', '1..1', 'code', 'before-start | before | before-end | concurrent-with-start | concurrent | concurrent-with-end | after-start | after | after-endActionRelationshipType (Required)',
'offset[x]', '', '0..1', '', 'Time offset for the relationship',
'offsetDuration', '', '', 'Duration', '',
'offsetRange', '', '', 'Range', '',
'timing[x]', '', '0..1', '', 'When the action should take place',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingDuration', '', '', 'Duration', '',
'timingRange', '', '', 'Range', '',
'timingTiming', '', '', 'Timing', '',
'participant', '', '0..*', 'Reference(Patient | Practitioner | PractitionerRole | RelatedPerson | Device)', 'Who should perform the action',
'type', '', '0..1', 'CodeableConcept', 'create | update | remove | fire-eventActionType (Extensible)',
'groupingBehavior', '', '0..1', 'code', 'visual-group | logical-group | sentence-groupActionGroupingBehavior (Required)',
'selectionBehavior', '', '0..1', 'code', 'any | all | all-or-none | exactly-one | at-most-one | one-or-moreActionSelectionBehavior (Required)',
'requiredBehavior', '', '0..1', 'code', 'must | could | must-unless-documentedActionRequiredBehavior (Required)',
'precheckBehavior', '', '0..1', 'code', 'yes | noActionPrecheckBehavior (Required)',
'cardinalityBehavior', '', '0..1', 'code', 'single | multipleActionCardinalityBehavior (Required)',
'resource', 'I', '0..1', 'Reference(Any)', 'The target of the action',
'action', 'I', '0..*', 'see action', 'Sub action',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'RequestGroup', '',
'RequestGroup.instantiatesCanonical', 'Added Element',
'RequestGroup.instantiatesUri', 'Added Element',
'RequestGroup.status', 'Change value set from http://hl7.org/fhir/ValueSet/request-status to http://hl7.org/fhir/ValueSet/request-status|4.0.1',
'RequestGroup.intent', 'Change value set from http://hl7.org/fhir/ValueSet/request-intent to http://hl7.org/fhir/ValueSet/request-intent|4.0.1',
'RequestGroup.priority', 'Change value set from http://hl7.org/fhir/ValueSet/request-priority to http://hl7.org/fhir/ValueSet/request-priority|4.0.1',
'RequestGroup.code', 'Added Element',
'RequestGroup.encounter', 'Added Element',
'RequestGroup.author', 'Type Reference: Added Target Type PractitionerRole',
'RequestGroup.reasonCode', 'Added Element',
'RequestGroup.reasonReference', 'Added Element',
'RequestGroup.action.prefix', 'Added Element',
'RequestGroup.action.priority', 'Added Element',
'RequestGroup.action.condition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/action-condition-kind to http://hl7.org/fhir/ValueSet/action-condition-kind|4.0.1',
'RequestGroup.action.condition.expression', 'Type changed from string to Expression',
'RequestGroup.action.relatedAction.relationship', 'Change value set from http://hl7.org/fhir/ValueSet/action-relationship-type to http://hl7.org/fhir/ValueSet/action-relationship-type|4.0.1',
'RequestGroup.action.timing[x]', 'Add Type Age',
'RequestGroup.action.participant', 'Type Reference: Added Target Types PractitionerRole, Device
        Type Reference: Removed Target Type Person',
'RequestGroup.action.type', 'Type changed from Coding to CodeableConcept
        Change code system for extensibly bound codes from "http://hl7.org/fhir/action-type" to "http://terminology.hl7.org/CodeSystem/action-type"',
'RequestGroup.action.groupingBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-grouping-behavior to http://hl7.org/fhir/ValueSet/action-grouping-behavior|4.0.1',
'RequestGroup.action.selectionBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-selection-behavior to http://hl7.org/fhir/ValueSet/action-selection-behavior|4.0.1',
'RequestGroup.action.requiredBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-required-behavior to http://hl7.org/fhir/ValueSet/action-required-behavior|4.0.1',
'RequestGroup.action.precheckBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-precheck-behavior to http://hl7.org/fhir/ValueSet/action-precheck-behavior|4.0.1',
'RequestGroup.action.cardinalityBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-cardinality-behavior to http://hl7.org/fhir/ValueSet/action-cardinality-behavior|4.0.1',
'RequestGroup.definition', 'deleted',
'RequestGroup.context', 'deleted',
'RequestGroup.reason[x]', 'deleted',
'RequestGroup.action.label', 'deleted',
'RequestGroup.action.condition.description', 'deleted',
'RequestGroup.action.condition.language', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'RequestGroup', 'TU', '', 'DomainResource', 'A group of related requestsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Business identifier',
'instantiatesCanonical', 'Σ', '0..*', 'canonical()', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', '', '0..*', 'Reference(Any)', 'Fulfills plan, proposal, or order',
'replaces', '', '0..*', 'Reference(Any)', 'Request(s) replaced by this request',
'groupIdentifier', 'Σ', '0..1', 'Identifier', 'Composite request this is part of',
'status', '?!Σ', '1..1', 'code', 'draft | active | on-hold | revoked | completed | entered-in-error | unknownRequestStatus (Required)',
'intent', '?!Σ', '1..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'priority', 'Σ', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', 'Σ', '0..1', 'CodeableConcept', 'What's being requested/ordered',
'subject', '', '0..1', 'Reference(Patient | Group)', 'Who the request group is about',
'encounter', '', '0..1', 'Reference(Encounter)', 'Created as part of',
'authoredOn', '', '0..1', 'dateTime', 'When the request group was authored',
'author', '', '0..1', 'Reference(Device | Practitioner | PractitionerRole)', 'Device or practitioner that authored the request group',
'reasonCode', '', '0..*', 'CodeableConcept', 'Why the request group is needed',
'reasonReference', '', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference)', 'Why the request group is needed',
'note', '', '0..*', 'Annotation', 'Additional notes about the response',
'action', 'I', '0..*', 'BackboneElement', 'Proposed actions, if any+ Rule: Must have resource or action but not both',
'prefix', '', '0..1', 'string', 'User-visible prefix for the action (e.g. 1. or A.)',
'title', '', '0..1', 'string', 'User-visible title',
'description', 'Σ', '0..1', 'string', 'Short description of the action',
'textEquivalent', 'Σ', '0..1', 'string', 'Static text equivalent of the action, used if the dynamic aspects cannot be interpreted by the receiving system',
'priority', '', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'code', '', '0..*', 'CodeableConcept', 'Code representing the meaning of the action or sub-actions',
'documentation', '', '0..*', 'RelatedArtifact', 'Supporting documentation for the intended performer of the action',
'condition', '', '0..*', 'BackboneElement', 'Whether or not the action is applicable',
'kind', '', '1..1', 'code', 'applicability | start | stopActionConditionKind (Required)',
'expression', '', '0..1', 'Expression', 'Boolean-valued expression',
'relatedAction', '', '0..*', 'BackboneElement', 'Relationship to another action',
'actionId', '', '1..1', 'id', 'What action this is related to',
'relationship', '', '1..1', 'code', 'before-start | before | before-end | concurrent-with-start | concurrent | concurrent-with-end | after-start | after | after-endActionRelationshipType (Required)',
'offset[x]', '', '0..1', '', 'Time offset for the relationship',
'offsetDuration', '', '', 'Duration', '',
'offsetRange', '', '', 'Range', '',
'timing[x]', '', '0..1', '', 'When the action should take place',
'timingDateTime', '', '', 'dateTime', '',
'timingAge', '', '', 'Age', '',
'timingPeriod', '', '', 'Period', '',
'timingDuration', '', '', 'Duration', '',
'timingRange', '', '', 'Range', '',
'timingTiming', '', '', 'Timing', '',
'participant', '', '0..*', 'Reference(Patient | Practitioner | PractitionerRole | RelatedPerson | Device)', 'Who should perform the action',
'type', '', '0..1', 'CodeableConcept', 'create | update | remove | fire-eventActionType (Extensible)',
'groupingBehavior', '', '0..1', 'code', 'visual-group | logical-group | sentence-groupActionGroupingBehavior (Required)',
'selectionBehavior', '', '0..1', 'code', 'any | all | all-or-none | exactly-one | at-most-one | one-or-moreActionSelectionBehavior (Required)',
'requiredBehavior', '', '0..1', 'code', 'must | could | must-unless-documentedActionRequiredBehavior (Required)',
'precheckBehavior', '', '0..1', 'code', 'yes | noActionPrecheckBehavior (Required)',
'cardinalityBehavior', '', '0..1', 'code', 'single | multipleActionCardinalityBehavior (Required)',
'resource', 'I', '0..1', 'Reference(Any)', 'The target of the action',
'action', 'I', '0..*', 'see action', 'Sub action',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'RequestGroup', '',
'RequestGroup.instantiatesCanonical', 'Added Element',
'RequestGroup.instantiatesUri', 'Added Element',
'RequestGroup.status', 'Change value set from http://hl7.org/fhir/ValueSet/request-status to http://hl7.org/fhir/ValueSet/request-status|4.0.1',
'RequestGroup.intent', 'Change value set from http://hl7.org/fhir/ValueSet/request-intent to http://hl7.org/fhir/ValueSet/request-intent|4.0.1',
'RequestGroup.priority', 'Change value set from http://hl7.org/fhir/ValueSet/request-priority to http://hl7.org/fhir/ValueSet/request-priority|4.0.1',
'RequestGroup.code', 'Added Element',
'RequestGroup.encounter', 'Added Element',
'RequestGroup.author', 'Type Reference: Added Target Type PractitionerRole',
'RequestGroup.reasonCode', 'Added Element',
'RequestGroup.reasonReference', 'Added Element',
'RequestGroup.action.prefix', 'Added Element',
'RequestGroup.action.priority', 'Added Element',
'RequestGroup.action.condition.kind', 'Change value set from http://hl7.org/fhir/ValueSet/action-condition-kind to http://hl7.org/fhir/ValueSet/action-condition-kind|4.0.1',
'RequestGroup.action.condition.expression', 'Type changed from string to Expression',
'RequestGroup.action.relatedAction.relationship', 'Change value set from http://hl7.org/fhir/ValueSet/action-relationship-type to http://hl7.org/fhir/ValueSet/action-relationship-type|4.0.1',
'RequestGroup.action.timing[x]', 'Add Type Age',
'RequestGroup.action.participant', 'Type Reference: Added Target Types PractitionerRole, Device
        Type Reference: Removed Target Type Person',
'RequestGroup.action.type', 'Type changed from Coding to CodeableConcept
        Change code system for extensibly bound codes from "http://hl7.org/fhir/action-type" to "http://terminology.hl7.org/CodeSystem/action-type"',
'RequestGroup.action.groupingBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-grouping-behavior to http://hl7.org/fhir/ValueSet/action-grouping-behavior|4.0.1',
'RequestGroup.action.selectionBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-selection-behavior to http://hl7.org/fhir/ValueSet/action-selection-behavior|4.0.1',
'RequestGroup.action.requiredBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-required-behavior to http://hl7.org/fhir/ValueSet/action-required-behavior|4.0.1',
'RequestGroup.action.precheckBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-precheck-behavior to http://hl7.org/fhir/ValueSet/action-precheck-behavior|4.0.1',
'RequestGroup.action.cardinalityBehavior', 'Change value set from http://hl7.org/fhir/ValueSet/action-cardinality-behavior to http://hl7.org/fhir/ValueSet/action-cardinality-behavior|4.0.1',
'RequestGroup.definition', 'deleted',
'RequestGroup.context', 'deleted',
'RequestGroup.reason[x]', 'deleted',
'RequestGroup.action.label', 'deleted',
'RequestGroup.action.condition.description', 'deleted',
'RequestGroup.action.condition.language', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'RequestGroup.status', 'Codes identifying the lifecycle stage of a request.', 'Required', 'RequestStatus',
'RequestGroup.intent', 'Codes indicating the degree of authority/intentionality associated with a request.', 'Required', 'RequestIntent',
'RequestGroup.priorityRequestGroup.action.priority', 'Identifies the level of importance to be assigned to actioning the request.', 'Required', 'RequestPriority',
'RequestGroup.action.condition.kind', 'The kind of condition for the action.', 'Required', 'ActionConditionKind',
'RequestGroup.action.relatedAction.relationship', 'Defines the types of relationships between actions.', 'Required', 'ActionRelationshipType',
'RequestGroup.action.type', 'The type of action to be performed.', 'Extensible', 'ActionType',
'RequestGroup.action.groupingBehavior', 'Defines organization behavior of a group.', 'Required', 'ActionGroupingBehavior',
'RequestGroup.action.selectionBehavior', 'Defines selection behavior of a group.', 'Required', 'ActionSelectionBehavior',
'RequestGroup.action.requiredBehavior', 'Defines expectations around whether an action or action group is required.', 'Required', 'ActionRequiredBehavior',
'RequestGroup.action.precheckBehavior', 'Defines selection frequency behavior for an action or group.', 'Required', 'ActionPrecheckBehavior',
'RequestGroup.action.cardinalityBehavior', 'Defines behavior for an action or a group for how many times that item may be repeated.', 'Required', 'ActionCardinalityBehavior',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'rqg-1', 'Rule', 'RequestGroup.action', 'Must have resource or action but not both', 'resource.exists() != action.exists()',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'author', 'reference', 'The author of the request group', 'RequestGroup.author(Practitioner, Device, PractitionerRole)', '',
'authored', 'date', 'The date the request group was authored', 'RequestGroup.authoredOn', '',
'code', 'token', 'The code of the request group', 'RequestGroup.code', '',
'encounter', 'reference', 'The encounter the request group applies to', 'RequestGroup.encounter(Encounter)', '',
'group-identifier', 'token', 'The group identifier for the request group', 'RequestGroup.groupIdentifier', '',
'identifier', 'token', 'External identifiers for the request group', 'RequestGroup.identifier', '',
'instantiates-canonical', 'reference', 'The FHIR-based definition from which the request group is realized', 'RequestGroup.instantiatesCanonical', '',
'instantiates-uri', 'uri', 'The external definition from which the request group is realized', 'RequestGroup.instantiatesUri', '',
'intent', 'token', 'The intent of the request group', 'RequestGroup.intent', '',
'participant', 'reference', 'The participant in the requests in the group', 'RequestGroup.action.participant(Practitioner, Device, Patient, PractitionerRole, RelatedPerson)', '',
'patient', 'reference', 'The identity of a patient to search for request groups', 'RequestGroup.subject.where(resolve() is Patient)(Patient)', '',
'priority', 'token', 'The priority of the request group', 'RequestGroup.priority', '',
'status', 'token', 'The status of the request group', 'RequestGroup.status', '',
'subject', 'reference', 'The subject that the request group is about', 'RequestGroup.subject(Group, Patient)', '',
)


