df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Clinical Decision Support  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Business', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ResearchElementDefinition', 'ITU', '', 'DomainResource', 'A population, intervention, or exposure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this research element definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the research element definition',
'version', 'Σ', '0..1', 'string', 'Business version of the research element definition',
'name', 'ΣI', '0..1', 'string', 'Name for this research element definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this research element definition (human friendly)',
'shortTitle', 'Σ', '0..1', 'string', 'Title for use in informal contexts',
'subtitle', '', '0..1', 'string', 'Subordinate title of the ResearchElementDefinition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'E.g. Patient, Practitioner, RelatedPerson, Organization, Location, DeviceSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the research element definition',
'comment', '', '0..*', 'string', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for research element definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this research element definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the ResearchElementDefinition',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the research element definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the research element definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the research element definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the ResearchElementDefinition, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the ResearchElementDefinition',
'type', 'Σ', '1..1', 'code', 'population | exposure | outcomeResearchElementType (Required)',
'variableType', '', '0..1', 'code', 'dichotomous | continuous | descriptiveVariableType (Required)',
'characteristic', 'Σ', '1..*', 'BackboneElement', 'What defines the members of the research element',
'definition[x]', 'Σ', '1..1', '', 'What code or expression defines members?',
'definitionCodeableConcept', '', '', 'CodeableConcept', '',
'definitionCanonical', '', '', 'canonical(ValueSet)', '',
'definitionExpression', '', '', 'Expression', '',
'definitionDataRequirement', '', '', 'DataRequirement', '',
'usageContext', '', '0..*', 'UsageContext', 'What code/value pairs define members?',
'exclude', '', '0..1', 'boolean', 'Whether the characteristic includes or excludes members',
'unitOfMeasure', '', '0..1', 'CodeableConcept', 'What unit is the outcome described in?UCUM Codes (Required)',
'studyEffectiveDescription', '', '0..1', 'string', 'What time period does the study cover',
'studyEffective[x]', '', '0..1', '', 'What time period does the study cover',
'studyEffectiveDateTime', '', '', 'dateTime', '',
'studyEffectivePeriod', '', '', 'Period', '',
'studyEffectiveDuration', '', '', 'Duration', '',
'studyEffectiveTiming', '', '', 'Timing', '',
'studyEffectiveTimeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'studyEffectiveGroupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'participantEffectiveDescription', '', '0..1', 'string', 'What time period do participants cover',
'participantEffective[x]', '', '0..1', '', 'What time period do participants cover',
'participantEffectiveDateTime', '', '', 'dateTime', '',
'participantEffectivePeriod', '', '', 'Period', '',
'participantEffectiveDuration', '', '', 'Duration', '',
'participantEffectiveTiming', '', '', 'Timing', '',
'participantEffectiveTimeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'participantEffectiveGroupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ResearchElementDefinition', 'ITU', '', 'DomainResource', 'A population, intervention, or exposure definition+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this research element definition, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the research element definition',
'version', 'Σ', '0..1', 'string', 'Business version of the research element definition',
'name', 'ΣI', '0..1', 'string', 'Name for this research element definition (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this research element definition (human friendly)',
'shortTitle', 'Σ', '0..1', 'string', 'Title for use in informal contexts',
'subtitle', '', '0..1', 'string', 'Subordinate title of the ResearchElementDefinition',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'subject[x]', '', '0..1', '', 'E.g. Patient, Practitioner, RelatedPerson, Organization, Location, DeviceSubject type (Extensible)',
'subjectCodeableConcept', '', '', 'CodeableConcept', '',
'subjectReference', '', '', 'Reference(Group)', '',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', 'Σ', '0..1', 'markdown', 'Natural language description of the research element definition',
'comment', '', '0..*', 'string', 'Used for footnotes or explanatory notes',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for research element definition (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this research element definition is defined',
'usage', '', '0..1', 'string', 'Describes the clinical usage of the ResearchElementDefinition',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'approvalDate', '', '0..1', 'date', 'When the research element definition was approved by publisher',
'lastReviewDate', '', '0..1', 'date', 'When the research element definition was last reviewed',
'effectivePeriod', 'Σ', '0..1', 'Period', 'When the research element definition is expected to be used',
'topic', '', '0..*', 'CodeableConcept', 'The category of the ResearchElementDefinition, such as Education, Treatment, Assessment, etc.DefinitionTopic (Example)',
'author', '', '0..*', 'ContactDetail', 'Who authored the content',
'editor', '', '0..*', 'ContactDetail', 'Who edited the content',
'reviewer', '', '0..*', 'ContactDetail', 'Who reviewed the content',
'endorser', '', '0..*', 'ContactDetail', 'Who endorsed the content',
'relatedArtifact', '', '0..*', 'RelatedArtifact', 'Additional documentation, citations, etc.',
'library', '', '0..*', 'canonical(Library)', 'Logic used by the ResearchElementDefinition',
'type', 'Σ', '1..1', 'code', 'population | exposure | outcomeResearchElementType (Required)',
'variableType', '', '0..1', 'code', 'dichotomous | continuous | descriptiveVariableType (Required)',
'characteristic', 'Σ', '1..*', 'BackboneElement', 'What defines the members of the research element',
'definition[x]', 'Σ', '1..1', '', 'What code or expression defines members?',
'definitionCodeableConcept', '', '', 'CodeableConcept', '',
'definitionCanonical', '', '', 'canonical(ValueSet)', '',
'definitionExpression', '', '', 'Expression', '',
'definitionDataRequirement', '', '', 'DataRequirement', '',
'usageContext', '', '0..*', 'UsageContext', 'What code/value pairs define members?',
'exclude', '', '0..1', 'boolean', 'Whether the characteristic includes or excludes members',
'unitOfMeasure', '', '0..1', 'CodeableConcept', 'What unit is the outcome described in?UCUM Codes (Required)',
'studyEffectiveDescription', '', '0..1', 'string', 'What time period does the study cover',
'studyEffective[x]', '', '0..1', '', 'What time period does the study cover',
'studyEffectiveDateTime', '', '', 'dateTime', '',
'studyEffectivePeriod', '', '', 'Period', '',
'studyEffectiveDuration', '', '', 'Duration', '',
'studyEffectiveTiming', '', '', 'Timing', '',
'studyEffectiveTimeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'studyEffectiveGroupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'participantEffectiveDescription', '', '0..1', 'string', 'What time period do participants cover',
'participantEffective[x]', '', '0..1', '', 'What time period do participants cover',
'participantEffectiveDateTime', '', '', 'dateTime', '',
'participantEffectivePeriod', '', '', 'Period', '',
'participantEffectiveDuration', '', '', 'Duration', '',
'participantEffectiveTiming', '', '', 'Timing', '',
'participantEffectiveTimeFromStart', '', '0..1', 'Duration', 'Observation time from study start',
'participantEffectiveGroupMeasure', '', '0..1', 'code', 'mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-medianGroupMeasure (Required)',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ResearchElementDefinition.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'ResearchElementDefinition.subject[x]', 'The possible types of subjects for a measure (E.g. Patient, Practitioner, Organization, Location, etc.).', 'Extensible', 'SubjectType',
'ResearchElementDefinition.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'ResearchElementDefinition.topic', 'High-level categorization of the definition, used for searching, sorting, and filtering.', 'Example', 'DefinitionTopic',
'ResearchElementDefinition.type', 'The possible types of research elements (E.g. Population, Exposure, Outcome).', 'Required', 'ResearchElementType',
'ResearchElementDefinition.variableType', 'The possible types of variables for exposures or outcomes (E.g. Dichotomous, Continuous, Descriptive).', 'Required', 'VariableType',
'ResearchElementDefinition.characteristic.unitOfMeasure', 'Unified Code for Units of Measure (UCUM).', 'Required', 'UCUMCodes',
'ResearchElementDefinition.characteristic.studyEffectiveGroupMeasureResearchElementDefinition.characteristic.participantEffectiveGroupMeasure', 'Possible group measure aggregates (E.g. Mean, Median).', 'Required', 'GroupMeasure',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'red-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'composed-of', 'reference', 'What resource is being referenced', 'ResearchElementDefinition.relatedArtifact.where(type='composed-of').resource(Any)', '',
'context', 'token', 'A use context assigned to the research element definition', '(ResearchElementDefinition.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the research element definition', '(ResearchElementDefinition.useContext.value as Quantity) | (ResearchElementDefinition.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the research element definition', 'ResearchElementDefinition.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the research element definition', 'On ResearchElementDefinition.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the research element definition', 'On ResearchElementDefinition.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The research element definition publication date', 'ResearchElementDefinition.date', '',
'depends-on', 'reference', 'What resource is being referenced', 'ResearchElementDefinition.relatedArtifact.where(type='depends-on').resource | ResearchElementDefinition.library(Library, Any)', '',
'derived-from', 'reference', 'What resource is being referenced', 'ResearchElementDefinition.relatedArtifact.where(type='derived-from').resource(Any)', '',
'description', 'string', 'The description of the research element definition', 'ResearchElementDefinition.description', '',
'effective', 'date', 'The time during which the research element definition is intended to be in use', 'ResearchElementDefinition.effectivePeriod', '',
'identifier', 'token', 'External identifier for the research element definition', 'ResearchElementDefinition.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the research element definition', 'ResearchElementDefinition.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the research element definition', 'ResearchElementDefinition.name', '',
'predecessor', 'reference', 'What resource is being referenced', 'ResearchElementDefinition.relatedArtifact.where(type='predecessor').resource(Any)', '',
'publisher', 'string', 'Name of the publisher of the research element definition', 'ResearchElementDefinition.publisher', '',
'status', 'token', 'The current status of the research element definition', 'ResearchElementDefinition.status', '',
'successor', 'reference', 'What resource is being referenced', 'ResearchElementDefinition.relatedArtifact.where(type='successor').resource(Any)', '',
'title', 'string', 'The human-friendly name of the research element definition', 'ResearchElementDefinition.title', '',
'topic', 'token', 'Topics associated with the ResearchElementDefinition', 'ResearchElementDefinition.topic', '',
'url', 'uri', 'The uri that identifies the research element definition', 'ResearchElementDefinition.url', '',
'version', 'token', 'The business version of the research element definition', 'ResearchElementDefinition.version', '',
)


