df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Orders and Observations  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Patient', 'Compartments: Device, Encounter, Patient, Practitioner, RelatedPerson',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ServiceRequest', 'ITU', '', 'DomainResource', 'A request for a service to be performed+ Rule: orderDetail SHALL only be present if code is presentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifiers assigned to this order',
'instantiatesCanonical', 'Σ', '0..*', 'canonical(ActivityDefinition | PlanDefinition)', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', 'Σ', '0..*', 'Reference(CarePlan | ServiceRequest | MedicationRequest)', 'What request fulfills',
'replaces', 'Σ', '0..*', 'Reference(ServiceRequest)', 'What request replaces',
'requisition', 'Σ', '0..1', 'Identifier', 'Composite Request ID',
'status', '?!Σ', '1..1', 'code', 'draft | active | on-hold | revoked | completed | entered-in-error | unknownRequestStatus (Required)',
'intent', '?!Σ', '1..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'category', 'Σ', '0..*', 'CodeableConcept', 'Classification of serviceService Request Category Codes (Example)',
'priority', 'Σ', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'doNotPerform', '?!Σ', '0..1', 'boolean', 'True if service/procedure should not be performed',
'code', 'Σ', '0..1', 'CodeableConcept', 'What is being requested/orderedProcedure Codes (SNOMED CT) (Example)',
'orderDetail', 'ΣI', '0..*', 'CodeableConcept', 'Additional order informationService Request Order Details Codes (Example)',
'quantity[x]', 'Σ', '0..1', '', 'Service amount',
'quantityQuantity', '', '', 'Quantity', '',
'quantityRatio', '', '', 'Ratio', '',
'quantityRange', '', '', 'Range', '',
'subject', 'Σ', '1..1', 'Reference(Patient | Group | Location | Device)', 'Individual or Entity the service is ordered for',
'encounter', 'Σ', '0..1', 'Reference(Encounter)', 'Encounter in which the request was created',
'occurrence[x]', 'Σ', '0..1', '', 'When service should occur',
'occurrenceDateTime', '', '', 'dateTime', '',
'occurrencePeriod', '', '', 'Period', '',
'occurrenceTiming', '', '', 'Timing', '',
'asNeeded[x]', 'Σ', '0..1', '', 'Preconditions for serviceSNOMED CT Medication As Needed Reason Codes (Example)',
'asNeededBoolean', '', '', 'boolean', '',
'asNeededCodeableConcept', '', '', 'CodeableConcept', '',
'authoredOn', 'Σ', '0..1', 'dateTime', 'Date request signed',
'requester', 'Σ', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson | Device)', 'Who/what is requesting service',
'performerType', 'Σ', '0..1', 'CodeableConcept', 'Performer roleParticipant Roles (Example)',
'performer', 'Σ', '0..*', 'Reference(Practitioner | PractitionerRole | Organization | CareTeam | HealthcareService | Patient | Device | RelatedPerson)', 'Requested performer',
'locationCode', 'Σ', '0..*', 'CodeableConcept', 'Requested locationV3 Value SetServiceDeliveryLocationRoleType (Example)',
'locationReference', 'Σ', '0..*', 'Reference(Location)', 'Requested location',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Explanation/Justification for procedure or serviceProcedure Reason Codes (Example)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference)', 'Explanation/Justification for service or service',
'insurance', '', '0..*', 'Reference(Coverage | ClaimResponse)', 'Associated insurance coverage',
'supportingInfo', '', '0..*', 'Reference(Any)', 'Additional clinical information',
'specimen', 'Σ', '0..*', 'Reference(Specimen)', 'Procedure Samples',
'bodySite', 'Σ', '0..*', 'CodeableConcept', 'Location on BodySNOMED CT Body Structures (Example)',
'note', '', '0..*', 'Annotation', 'Comments',
'patientInstruction', 'Σ', '0..1', 'string', 'Patient or consumer-oriented instructions',
'relevantHistory', '', '0..*', 'Reference(Provenance)', 'Request provenance',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'ServiceRequest', 'ITU', '', 'DomainResource', 'A request for a service to be performed+ Rule: orderDetail SHALL only be present if code is presentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..*', 'Identifier', 'Identifiers assigned to this order',
'instantiatesCanonical', 'Σ', '0..*', 'canonical(ActivityDefinition | PlanDefinition)', 'Instantiates FHIR protocol or definition',
'instantiatesUri', 'Σ', '0..*', 'uri', 'Instantiates external protocol or definition',
'basedOn', 'Σ', '0..*', 'Reference(CarePlan | ServiceRequest | MedicationRequest)', 'What request fulfills',
'replaces', 'Σ', '0..*', 'Reference(ServiceRequest)', 'What request replaces',
'requisition', 'Σ', '0..1', 'Identifier', 'Composite Request ID',
'status', '?!Σ', '1..1', 'code', 'draft | active | on-hold | revoked | completed | entered-in-error | unknownRequestStatus (Required)',
'intent', '?!Σ', '1..1', 'code', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | optionRequestIntent (Required)',
'category', 'Σ', '0..*', 'CodeableConcept', 'Classification of serviceService Request Category Codes (Example)',
'priority', 'Σ', '0..1', 'code', 'routine | urgent | asap | statRequest priority (Required)',
'doNotPerform', '?!Σ', '0..1', 'boolean', 'True if service/procedure should not be performed',
'code', 'Σ', '0..1', 'CodeableConcept', 'What is being requested/orderedProcedure Codes (SNOMED CT) (Example)',
'orderDetail', 'ΣI', '0..*', 'CodeableConcept', 'Additional order informationService Request Order Details Codes (Example)',
'quantity[x]', 'Σ', '0..1', '', 'Service amount',
'quantityQuantity', '', '', 'Quantity', '',
'quantityRatio', '', '', 'Ratio', '',
'quantityRange', '', '', 'Range', '',
'subject', 'Σ', '1..1', 'Reference(Patient | Group | Location | Device)', 'Individual or Entity the service is ordered for',
'encounter', 'Σ', '0..1', 'Reference(Encounter)', 'Encounter in which the request was created',
'occurrence[x]', 'Σ', '0..1', '', 'When service should occur',
'occurrenceDateTime', '', '', 'dateTime', '',
'occurrencePeriod', '', '', 'Period', '',
'occurrenceTiming', '', '', 'Timing', '',
'asNeeded[x]', 'Σ', '0..1', '', 'Preconditions for serviceSNOMED CT Medication As Needed Reason Codes (Example)',
'asNeededBoolean', '', '', 'boolean', '',
'asNeededCodeableConcept', '', '', 'CodeableConcept', '',
'authoredOn', 'Σ', '0..1', 'dateTime', 'Date request signed',
'requester', 'Σ', '0..1', 'Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson | Device)', 'Who/what is requesting service',
'performerType', 'Σ', '0..1', 'CodeableConcept', 'Performer roleParticipant Roles (Example)',
'performer', 'Σ', '0..*', 'Reference(Practitioner | PractitionerRole | Organization | CareTeam | HealthcareService | Patient | Device | RelatedPerson)', 'Requested performer',
'locationCode', 'Σ', '0..*', 'CodeableConcept', 'Requested locationV3 Value SetServiceDeliveryLocationRoleType (Example)',
'locationReference', 'Σ', '0..*', 'Reference(Location)', 'Requested location',
'reasonCode', 'Σ', '0..*', 'CodeableConcept', 'Explanation/Justification for procedure or serviceProcedure Reason Codes (Example)',
'reasonReference', 'Σ', '0..*', 'Reference(Condition | Observation | DiagnosticReport | DocumentReference)', 'Explanation/Justification for service or service',
'insurance', '', '0..*', 'Reference(Coverage | ClaimResponse)', 'Associated insurance coverage',
'supportingInfo', '', '0..*', 'Reference(Any)', 'Additional clinical information',
'specimen', 'Σ', '0..*', 'Reference(Specimen)', 'Procedure Samples',
'bodySite', 'Σ', '0..*', 'CodeableConcept', 'Location on BodySNOMED CT Body Structures (Example)',
'note', '', '0..*', 'Annotation', 'Comments',
'patientInstruction', 'Σ', '0..1', 'string', 'Patient or consumer-oriented instructions',
'relevantHistory', '', '0..*', 'Reference(Provenance)', 'Request provenance',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'ServiceRequest.status', 'The status of a service order.', 'Required', 'RequestStatus',
'ServiceRequest.intent', 'The kind of service request.', 'Required', 'RequestIntent',
'ServiceRequest.category', 'Classification of the requested service.', 'Example', 'ServiceRequestCategoryCodes',
'ServiceRequest.priority', 'Identifies the level of importance to be assigned to actioning the request.', 'Required', 'RequestPriority',
'ServiceRequest.code', 'Codes for tests or services that can be carried out by a designated individual, organization or healthcare service.  For laboratory, LOINC is  (preferred)[http://build.fhir.org/terminologies.html#preferred] and a valueset using LOINC Order codes is available [here](valueset-diagnostic-requests.html).', 'Example', 'ProcedureCodes(SNOMEDCT)',
'ServiceRequest.orderDetail', 'Codified order entry details which are based on order context.', 'Example', 'ServiceRequestOrderDetailsCodes',
'ServiceRequest.asNeeded[x]', 'A coded concept identifying the pre-condition that should hold prior to performing a procedure.  For example "pain", "on flare-up", etc.', 'Example', 'SNOMEDCTMedicationAsNeededReasonCodes',
'ServiceRequest.performerType', 'Indicates specific responsibility of an individual within the care team, such as "Primary physician", "Team coordinator", "Caregiver", etc.', 'Example', 'ParticipantRoles',
'ServiceRequest.locationCode', 'A location type where services are delivered.', 'Example', 'v3.ServiceDeliveryLocationRoleType',
'ServiceRequest.reasonCode', 'Diagnosis or problem codes justifying the reason for requesting the service investigation.', 'Example', 'ProcedureReasonCodes',
'ServiceRequest.bodySite', 'Codes describing anatomical locations. May include laterality.', 'Example', 'SNOMEDCTBodyStructures',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'prr-1', 'Rule', '(base)', 'orderDetail SHALL only be present if code is present', 'orderDetail.empty() or code.exists()',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'authored', 'date', 'Date request signed', 'ServiceRequest.authoredOn', '',
'based-on', 'reference', 'What request fulfills', 'ServiceRequest.basedOn(CarePlan, MedicationRequest, ServiceRequest)', '',
'body-site', 'token', 'Where procedure is going to be done', 'ServiceRequest.bodySite', '',
'category', 'token', 'Classification of service', 'ServiceRequest.category', '',
'code', 'token', 'What is being requested/ordered', 'ServiceRequest.code', '13 Resources',
'encounter', 'reference', 'An encounter in which this request is made', 'ServiceRequest.encounter(Encounter)', '11 Resources',
'identifier', 'token', 'Identifiers assigned to this order', 'ServiceRequest.identifier', '29 Resources',
'instantiates-canonical', 'reference', 'Instantiates FHIR protocol or definition', 'ServiceRequest.instantiatesCanonical(PlanDefinition, ActivityDefinition)', '',
'instantiates-uri', 'uri', 'Instantiates external protocol or definition', 'ServiceRequest.instantiatesUri', '',
'intent', 'token', 'proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | option', 'ServiceRequest.intent', '',
'occurrence', 'date', 'When service should occur', 'ServiceRequest.occurrence', '',
'patient', 'reference', 'Search by subject - a patient', 'ServiceRequest.subject.where(resolve() is Patient)(Patient)', '32 Resources',
'performer', 'reference', 'Requested performer', 'ServiceRequest.performer(Practitioner, Organization, CareTeam, Device, Patient, HealthcareService, PractitionerRole, RelatedPerson)', '',
'performer-type', 'token', 'Performer role', 'ServiceRequest.performerType', '',
'priority', 'token', 'routine | urgent | asap | stat', 'ServiceRequest.priority', '',
'replaces', 'reference', 'What request replaces', 'ServiceRequest.replaces(ServiceRequest)', '',
'requester', 'reference', 'Who/what is requesting service', 'ServiceRequest.requester(Practitioner, Organization, Device, Patient, PractitionerRole, RelatedPerson)', '',
'requisition', 'token', 'Composite Request ID', 'ServiceRequest.requisition', '',
'specimen', 'reference', 'Specimen to be tested', 'ServiceRequest.specimen(Specimen)', '',
'status', 'token', 'draft | active | on-hold | revoked | completed | entered-in-error | unknown', 'ServiceRequest.status', '',
'subject', 'reference', 'Search by subject', 'ServiceRequest.subject(Group, Device, Patient, Location)', '',
)


