df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'StructureMap', 'ITU', '', 'DomainResource', 'A Map of relationships between 2 structures that can be used to transform data+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this structure map, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the structure map',
'version', 'Σ', '0..1', 'string', 'Business version of the structure map',
'name', 'ΣI', '1..1', 'string', 'Name for this structure map (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this structure map (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the structure map',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for structure map (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this structure map is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'structure', 'Σ', '0..*', 'BackboneElement', 'Structure Definition used by this map',
'url', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Canonical reference to structure definition',
'mode', 'Σ', '1..1', 'code', 'source | queried | target | producedStructureMapModelMode (Required)',
'alias', 'Σ', '0..1', 'string', 'Name for type in this map',
'documentation', '', '0..1', 'string', 'Documentation on use of structure',
'import', 'Σ', '0..*', 'canonical(StructureMap)', 'Other maps used by this map (canonical URLs)',
'group', 'Σ', '1..*', 'BackboneElement', 'Named sections for reader convenience',
'name', 'Σ', '1..1', 'id', 'Human-readable label',
'extends', 'Σ', '0..1', 'id', 'Another group that this group adds rules to',
'typeMode', 'Σ', '1..1', 'code', 'none | types | type-and-typesStructureMapGroupTypeMode (Required)',
'documentation', 'Σ', '0..1', 'string', 'Additional description/explanation for group',
'input', 'Σ', '1..*', 'BackboneElement', 'Named instance provided when invoking the map',
'name', 'Σ', '1..1', 'id', 'Name for this instance of data',
'type', 'Σ', '0..1', 'string', 'Type for this instance of data',
'mode', 'Σ', '1..1', 'code', 'source | targetStructureMapInputMode (Required)',
'documentation', '', '0..1', 'string', 'Documentation for this instance of data',
'rule', 'Σ', '1..*', 'BackboneElement', 'Transform Rule from source to target',
'name', 'Σ', '1..1', 'id', 'Name of the rule for internal references',
'source', 'Σ', '1..*', 'BackboneElement', 'Source inputs to the mapping',
'context', 'Σ', '1..1', 'id', 'Type or variable this rule applies to',
'min', 'Σ', '0..1', 'integer', 'Specified minimum cardinality',
'max', 'Σ', '0..1', 'string', 'Specified maximum cardinality (number or *)',
'type', 'Σ', '0..1', 'string', 'Rule only applies if source has this type',
'defaultValue[x]', 'Σ', '0..1', '*', 'Default value if no value exists',
'element', 'Σ', '0..1', 'string', 'Optional field for this source',
'listMode', 'Σ', '0..1', 'code', 'first | not_first | last | not_last | only_oneStructureMapSourceListMode (Required)',
'variable', 'Σ', '0..1', 'id', 'Named context for field, if a field is specified',
'condition', 'Σ', '0..1', 'string', 'FHIRPath expression  - must be true or the rule does not apply',
'check', 'Σ', '0..1', 'string', 'FHIRPath expression  - must be true or the mapping engine throws an error instead of completing',
'logMessage', 'Σ', '0..1', 'string', 'Message to put in log if source exists (FHIRPath)',
'target', 'ΣI', '0..*', 'BackboneElement', 'Content to create because of this mapping rule+ Rule: Can only have an element if you have a context+ Rule: Must have a contextType if you have a context',
'context', 'Σ', '0..1', 'id', 'Type or variable this rule applies to',
'contextType', 'Σ', '0..1', 'code', 'type | variableStructureMapContextType (Required)',
'element', 'Σ', '0..1', 'string', 'Field to create in the context',
'variable', 'Σ', '0..1', 'id', 'Named context for field, if desired, and a field is specified',
'listMode', 'Σ', '0..*', 'code', 'first | share | last | collateStructureMapTargetListMode (Required)',
'listRuleId', 'Σ', '0..1', 'id', 'Internal rule reference for shared list items',
'transform', 'Σ', '0..1', 'code', 'create | copy +StructureMapTransform (Required)',
'parameter', 'Σ', '0..*', 'BackboneElement', 'Parameters to the transform',
'value[x]', 'Σ', '1..1', '', 'Parameter value - variable or literal',
'valueId', '', '', 'id', '',
'valueString', '', '', 'string', '',
'valueBoolean', '', '', 'boolean', '',
'valueInteger', '', '', 'integer', '',
'valueDecimal', '', '', 'decimal', '',
'rule', 'Σ', '0..*', 'see rule', 'Rules contained in this rule',
'dependent', 'Σ', '0..*', 'BackboneElement', 'Which other rules to apply in the context of this rule',
'name', 'Σ', '1..1', 'id', 'Name of a rule or group to apply',
'variable', 'Σ', '1..*', 'string', 'Variable to pass to the rule or group',
'documentation', '', '0..1', 'string', 'Documentation for this instance of data',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'StructureMap', '',
'StructureMap', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'StructureMap.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'StructureMap.experimental', 'No longer marked as Modifier',
'StructureMap.structure.url', 'Type changed from uri to canonical(StructureDefinition)',
'StructureMap.structure.mode', 'Change value set from http://hl7.org/fhir/ValueSet/map-model-mode to http://hl7.org/fhir/ValueSet/map-model-mode|4.0.1',
'StructureMap.import', 'Type changed from uri to canonical(StructureMap)',
'StructureMap.group.typeMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-group-type-mode to http://hl7.org/fhir/ValueSet/map-group-type-mode|4.0.1',
'StructureMap.group.input.mode', 'Change value set from http://hl7.org/fhir/ValueSet/map-input-mode to http://hl7.org/fhir/ValueSet/map-input-mode|4.0.1',
'StructureMap.group.rule.source.defaultValue[x]', 'Add Types canonical, url, uuid, ContactDetail, Contributor, DataRequirement, Expression, ParameterDefinition, RelatedArtifact, TriggerDefinition, UsageContext, Dosage',
'StructureMap.group.rule.source.listMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-source-list-mode to http://hl7.org/fhir/ValueSet/map-source-list-mode|4.0.1',
'StructureMap.group.rule.source.logMessage', 'Added Element',
'StructureMap.group.rule.target.contextType', 'Change value set from http://hl7.org/fhir/ValueSet/map-context-type to http://hl7.org/fhir/ValueSet/map-context-type|4.0.1',
'StructureMap.group.rule.target.listMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-target-list-mode to http://hl7.org/fhir/ValueSet/map-target-list-mode|4.0.1',
'StructureMap.group.rule.target.transform', 'Change value set from http://hl7.org/fhir/ValueSet/map-transform to http://hl7.org/fhir/ValueSet/map-transform|4.0.1',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'StructureMap', 'ITU', '', 'DomainResource', 'A Map of relationships between 2 structures that can be used to transform data+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this structure map, represented as a URI (globally unique)',
'identifier', 'Σ', '0..*', 'Identifier', 'Additional identifier for the structure map',
'version', 'Σ', '0..1', 'string', 'Business version of the structure map',
'name', 'ΣI', '1..1', 'string', 'Name for this structure map (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this structure map (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the structure map',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for structure map (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this structure map is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'structure', 'Σ', '0..*', 'BackboneElement', 'Structure Definition used by this map',
'url', 'Σ', '1..1', 'canonical(StructureDefinition)', 'Canonical reference to structure definition',
'mode', 'Σ', '1..1', 'code', 'source | queried | target | producedStructureMapModelMode (Required)',
'alias', 'Σ', '0..1', 'string', 'Name for type in this map',
'documentation', '', '0..1', 'string', 'Documentation on use of structure',
'import', 'Σ', '0..*', 'canonical(StructureMap)', 'Other maps used by this map (canonical URLs)',
'group', 'Σ', '1..*', 'BackboneElement', 'Named sections for reader convenience',
'name', 'Σ', '1..1', 'id', 'Human-readable label',
'extends', 'Σ', '0..1', 'id', 'Another group that this group adds rules to',
'typeMode', 'Σ', '1..1', 'code', 'none | types | type-and-typesStructureMapGroupTypeMode (Required)',
'documentation', 'Σ', '0..1', 'string', 'Additional description/explanation for group',
'input', 'Σ', '1..*', 'BackboneElement', 'Named instance provided when invoking the map',
'name', 'Σ', '1..1', 'id', 'Name for this instance of data',
'type', 'Σ', '0..1', 'string', 'Type for this instance of data',
'mode', 'Σ', '1..1', 'code', 'source | targetStructureMapInputMode (Required)',
'documentation', '', '0..1', 'string', 'Documentation for this instance of data',
'rule', 'Σ', '1..*', 'BackboneElement', 'Transform Rule from source to target',
'name', 'Σ', '1..1', 'id', 'Name of the rule for internal references',
'source', 'Σ', '1..*', 'BackboneElement', 'Source inputs to the mapping',
'context', 'Σ', '1..1', 'id', 'Type or variable this rule applies to',
'min', 'Σ', '0..1', 'integer', 'Specified minimum cardinality',
'max', 'Σ', '0..1', 'string', 'Specified maximum cardinality (number or *)',
'type', 'Σ', '0..1', 'string', 'Rule only applies if source has this type',
'defaultValue[x]', 'Σ', '0..1', '*', 'Default value if no value exists',
'element', 'Σ', '0..1', 'string', 'Optional field for this source',
'listMode', 'Σ', '0..1', 'code', 'first | not_first | last | not_last | only_oneStructureMapSourceListMode (Required)',
'variable', 'Σ', '0..1', 'id', 'Named context for field, if a field is specified',
'condition', 'Σ', '0..1', 'string', 'FHIRPath expression  - must be true or the rule does not apply',
'check', 'Σ', '0..1', 'string', 'FHIRPath expression  - must be true or the mapping engine throws an error instead of completing',
'logMessage', 'Σ', '0..1', 'string', 'Message to put in log if source exists (FHIRPath)',
'target', 'ΣI', '0..*', 'BackboneElement', 'Content to create because of this mapping rule+ Rule: Can only have an element if you have a context+ Rule: Must have a contextType if you have a context',
'context', 'Σ', '0..1', 'id', 'Type or variable this rule applies to',
'contextType', 'Σ', '0..1', 'code', 'type | variableStructureMapContextType (Required)',
'element', 'Σ', '0..1', 'string', 'Field to create in the context',
'variable', 'Σ', '0..1', 'id', 'Named context for field, if desired, and a field is specified',
'listMode', 'Σ', '0..*', 'code', 'first | share | last | collateStructureMapTargetListMode (Required)',
'listRuleId', 'Σ', '0..1', 'id', 'Internal rule reference for shared list items',
'transform', 'Σ', '0..1', 'code', 'create | copy +StructureMapTransform (Required)',
'parameter', 'Σ', '0..*', 'BackboneElement', 'Parameters to the transform',
'value[x]', 'Σ', '1..1', '', 'Parameter value - variable or literal',
'valueId', '', '', 'id', '',
'valueString', '', '', 'string', '',
'valueBoolean', '', '', 'boolean', '',
'valueInteger', '', '', 'integer', '',
'valueDecimal', '', '', 'decimal', '',
'rule', 'Σ', '0..*', 'see rule', 'Rules contained in this rule',
'dependent', 'Σ', '0..*', 'BackboneElement', 'Which other rules to apply in the context of this rule',
'name', 'Σ', '1..1', 'id', 'Name of a rule or group to apply',
'variable', 'Σ', '1..*', 'string', 'Variable to pass to the rule or group',
'documentation', '', '0..1', 'string', 'Documentation for this instance of data',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'StructureMap', '',
'StructureMap', 'Min Cardinality changed from 1 to 0
        Max Cardinality changed from 1 to *',
'StructureMap.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'StructureMap.experimental', 'No longer marked as Modifier',
'StructureMap.structure.url', 'Type changed from uri to canonical(StructureDefinition)',
'StructureMap.structure.mode', 'Change value set from http://hl7.org/fhir/ValueSet/map-model-mode to http://hl7.org/fhir/ValueSet/map-model-mode|4.0.1',
'StructureMap.import', 'Type changed from uri to canonical(StructureMap)',
'StructureMap.group.typeMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-group-type-mode to http://hl7.org/fhir/ValueSet/map-group-type-mode|4.0.1',
'StructureMap.group.input.mode', 'Change value set from http://hl7.org/fhir/ValueSet/map-input-mode to http://hl7.org/fhir/ValueSet/map-input-mode|4.0.1',
'StructureMap.group.rule.source.defaultValue[x]', 'Add Types canonical, url, uuid, ContactDetail, Contributor, DataRequirement, Expression, ParameterDefinition, RelatedArtifact, TriggerDefinition, UsageContext, Dosage',
'StructureMap.group.rule.source.listMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-source-list-mode to http://hl7.org/fhir/ValueSet/map-source-list-mode|4.0.1',
'StructureMap.group.rule.source.logMessage', 'Added Element',
'StructureMap.group.rule.target.contextType', 'Change value set from http://hl7.org/fhir/ValueSet/map-context-type to http://hl7.org/fhir/ValueSet/map-context-type|4.0.1',
'StructureMap.group.rule.target.listMode', 'Change value set from http://hl7.org/fhir/ValueSet/map-target-list-mode to http://hl7.org/fhir/ValueSet/map-target-list-mode|4.0.1',
'StructureMap.group.rule.target.transform', 'Change value set from http://hl7.org/fhir/ValueSet/map-transform to http://hl7.org/fhir/ValueSet/map-transform|4.0.1',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'StructureMap.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'StructureMap.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'StructureMap.structure.mode', 'How the referenced structure is used in this mapping.', 'Required', 'StructureMapModelMode',
'StructureMap.group.typeMode', 'If this is the default rule set to apply for the source type, or this combination of types.', 'Required', 'StructureMapGroupTypeMode',
'StructureMap.group.input.mode', 'Mode for this instance of data.', 'Required', 'StructureMapInputMode',
'StructureMap.group.rule.source.listMode', 'If field is a list, how to manage the source.', 'Required', 'StructureMapSourceListMode',
'StructureMap.group.rule.target.contextType', 'How to interpret the context.', 'Required', 'StructureMapContextType',
'StructureMap.group.rule.target.listMode', 'If field is a list, how to manage the production.', 'Required', 'StructureMapTargetListMode',
'StructureMap.group.rule.target.transform', 'How data is copied/created.', 'Required', 'StructureMapTransform',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'smp-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'smp-1', 'Rule', 'StructureMap.group.rule.target', 'Can only have an element if you have a context', 'element.exists() implies context.exists()',
'smp-2', 'Rule', 'StructureMap.group.rule.target', 'Must have a contextType if you have a context', 'context.exists() implies contextType.exists()',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the structure map', '(StructureMap.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the structure map', '(StructureMap.useContext.value as Quantity) | (StructureMap.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the structure map', 'StructureMap.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the structure map', 'On StructureMap.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the structure map', 'On StructureMap.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The structure map publication date', 'StructureMap.date', '',
'description', 'string', 'The description of the structure map', 'StructureMap.description', '',
'identifier', 'token', 'External identifier for the structure map', 'StructureMap.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the structure map', 'StructureMap.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the structure map', 'StructureMap.name', '',
'publisher', 'string', 'Name of the publisher of the structure map', 'StructureMap.publisher', '',
'status', 'token', 'The current status of the structure map', 'StructureMap.status', '',
'title', 'string', 'The human-friendly name of the structure map', 'StructureMap.title', '',
'url', 'uri', 'The uri that identifies the structure map', 'StructureMap.url', '',
'version', 'token', 'The business version of the structure map', 'StructureMap.version', '',
)


