df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Biomedical Research and Regulation  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'SubstanceProtein', 'ΣTU', '', 'DomainResource', 'A SubstanceProtein is defined as a single unit of a linear amino acid sequence, or a combination of subunits that are either covalently linked or have a defined invariant stoichiometric relationship. This includes all synthetic, recombinant and purified SubstanceProteins of defined sequence, whether the use is therapeutic or prophylactic. This set of elements will be used to describe albumins, coagulation factors, cytokines, growth factors, peptide/SubstanceProtein hormones, enzymes, toxins, toxoids, recombinant vaccines, and immunomodulatorsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'sequenceType', 'Σ', '0..1', 'CodeableConcept', 'The SubstanceProtein descriptive elements will only be used when a complete or partial amino acid sequence is available or derivable from a nucleic acid sequence',
'numberOfSubunits', 'Σ', '0..1', 'integer', 'Number of linear sequences of amino acids linked through peptide bonds. The number of subunits constituting the SubstanceProtein shall be described. It is possible that the number of subunits can be variable',
'disulfideLinkage', 'Σ', '0..*', 'string', 'The disulphide bond between two cysteine residues either on the same subunit or on two different subunits shall be described. The position of the disulfide bonds in the SubstanceProtein shall be listed in increasing order of subunit number and position within subunit followed by the abbreviation of the amino acids involved. The disulfide linkage positions shall actually contain the amino acid Cysteine at the respective positions',
'subunit', 'Σ', '0..*', 'BackboneElement', 'This subclause refers to the description of each subunit constituting the SubstanceProtein. A subunit is a linear sequence of amino acids linked through peptide bonds. The Subunit information shall be provided when the finished SubstanceProtein is a complex of multiple sequences; subunits are not used to delineate domains within a single sequence. Subunits are listed in order of decreasing length; sequences of the same length will be ordered by decreasing molecular weight; subunits that have identical sequences will be repeated multiple times',
'subunit', 'Σ', '0..1', 'integer', 'Index of primary sequences of amino acids linked through peptide bonds in order of decreasing length. Sequences of the same length will be ordered by molecular weight. Subunits that have identical sequences will be repeated and have sequential subscripts',
'sequence', 'Σ', '0..1', 'string', 'The sequence information shall be provided enumerating the amino acids from N- to C-terminal end using standard single-letter amino acid codes. Uppercase shall be used for L-amino acids and lowercase for D-amino acids. Transcribed SubstanceProteins will always be described using the translated sequence; for synthetic peptide containing amino acids that are not represented with a single letter code an X should be used within the sequence. The modified amino acids will be distinguished by their position in the sequence',
'length', 'Σ', '0..1', 'integer', 'Length of linear sequences of amino acids contained in the subunit',
'sequenceAttachment', 'Σ', '0..1', 'Attachment', 'The sequence information shall be provided enumerating the amino acids from N- to C-terminal end using standard single-letter amino acid codes. Uppercase shall be used for L-amino acids and lowercase for D-amino acids. Transcribed SubstanceProteins will always be described using the translated sequence; for synthetic peptide containing amino acids that are not represented with a single letter code an X should be used within the sequence. The modified amino acids will be distinguished by their position in the sequence',
'nTerminalModificationId', 'Σ', '0..1', 'Identifier', 'Unique identifier for molecular fragment modification based on the ISO 11238 Substance ID',
'nTerminalModification', 'Σ', '0..1', 'string', 'The name of the fragment modified at the N-terminal of the SubstanceProtein shall be specified',
'cTerminalModificationId', 'Σ', '0..1', 'Identifier', 'Unique identifier for molecular fragment modification based on the ISO 11238 Substance ID',
'cTerminalModification', 'Σ', '0..1', 'string', 'The modification at the C-terminal shall be specified',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'SubstanceProtein', 'ΣTU', '', 'DomainResource', 'A SubstanceProtein is defined as a single unit of a linear amino acid sequence, or a combination of subunits that are either covalently linked or have a defined invariant stoichiometric relationship. This includes all synthetic, recombinant and purified SubstanceProteins of defined sequence, whether the use is therapeutic or prophylactic. This set of elements will be used to describe albumins, coagulation factors, cytokines, growth factors, peptide/SubstanceProtein hormones, enzymes, toxins, toxoids, recombinant vaccines, and immunomodulatorsElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'sequenceType', 'Σ', '0..1', 'CodeableConcept', 'The SubstanceProtein descriptive elements will only be used when a complete or partial amino acid sequence is available or derivable from a nucleic acid sequence',
'numberOfSubunits', 'Σ', '0..1', 'integer', 'Number of linear sequences of amino acids linked through peptide bonds. The number of subunits constituting the SubstanceProtein shall be described. It is possible that the number of subunits can be variable',
'disulfideLinkage', 'Σ', '0..*', 'string', 'The disulphide bond between two cysteine residues either on the same subunit or on two different subunits shall be described. The position of the disulfide bonds in the SubstanceProtein shall be listed in increasing order of subunit number and position within subunit followed by the abbreviation of the amino acids involved. The disulfide linkage positions shall actually contain the amino acid Cysteine at the respective positions',
'subunit', 'Σ', '0..*', 'BackboneElement', 'This subclause refers to the description of each subunit constituting the SubstanceProtein. A subunit is a linear sequence of amino acids linked through peptide bonds. The Subunit information shall be provided when the finished SubstanceProtein is a complex of multiple sequences; subunits are not used to delineate domains within a single sequence. Subunits are listed in order of decreasing length; sequences of the same length will be ordered by decreasing molecular weight; subunits that have identical sequences will be repeated multiple times',
'subunit', 'Σ', '0..1', 'integer', 'Index of primary sequences of amino acids linked through peptide bonds in order of decreasing length. Sequences of the same length will be ordered by molecular weight. Subunits that have identical sequences will be repeated and have sequential subscripts',
'sequence', 'Σ', '0..1', 'string', 'The sequence information shall be provided enumerating the amino acids from N- to C-terminal end using standard single-letter amino acid codes. Uppercase shall be used for L-amino acids and lowercase for D-amino acids. Transcribed SubstanceProteins will always be described using the translated sequence; for synthetic peptide containing amino acids that are not represented with a single letter code an X should be used within the sequence. The modified amino acids will be distinguished by their position in the sequence',
'length', 'Σ', '0..1', 'integer', 'Length of linear sequences of amino acids contained in the subunit',
'sequenceAttachment', 'Σ', '0..1', 'Attachment', 'The sequence information shall be provided enumerating the amino acids from N- to C-terminal end using standard single-letter amino acid codes. Uppercase shall be used for L-amino acids and lowercase for D-amino acids. Transcribed SubstanceProteins will always be described using the translated sequence; for synthetic peptide containing amino acids that are not represented with a single letter code an X should be used within the sequence. The modified amino acids will be distinguished by their position in the sequence',
'nTerminalModificationId', 'Σ', '0..1', 'Identifier', 'Unique identifier for molecular fragment modification based on the ISO 11238 Substance ID',
'nTerminalModification', 'Σ', '0..1', 'string', 'The name of the fragment modified at the N-terminal of the SubstanceProtein shall be specified',
'cTerminalModificationId', 'Σ', '0..1', 'Identifier', 'Unique identifier for molecular fragment modification based on the ISO 11238 Substance ID',
'cTerminalModification', 'Σ', '0..1', 'string', 'The modification at the C-terminal shall be specified',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


