df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Biomedical Research and Regulation  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'SubstanceSpecification', 'ΣTU', '', 'DomainResource', 'The detailed description of a substance, typically at a level beyond what is used for prescribingElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..1', 'Identifier', 'Identifier by which this substance is known',
'type', 'Σ', '0..1', 'CodeableConcept', 'High level categorization, e.g. polymer or nucleic acid',
'status', 'Σ', '0..1', 'CodeableConcept', 'Status of substance within the catalogue e.g. approved',
'domain', 'Σ', '0..1', 'CodeableConcept', 'If the substance applies to only human or veterinary use',
'description', 'Σ', '0..1', 'string', 'Textual description of the substance',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'comment', 'Σ', '0..1', 'string', 'Textual comment about this record of a substance',
'moiety', 'Σ', '0..*', 'BackboneElement', 'Moiety, for structural modifications',
'role', 'Σ', '0..1', 'CodeableConcept', 'Role that the moiety is playing',
'identifier', 'Σ', '0..1', 'Identifier', 'Identifier by which this moiety substance is known',
'name', 'Σ', '0..1', 'string', 'Textual name for this moiety substance',
'stereochemistry', 'Σ', '0..1', 'CodeableConcept', 'Stereochemistry type',
'opticalActivity', 'Σ', '0..1', 'CodeableConcept', 'Optical activity type',
'molecularFormula', 'Σ', '0..1', 'string', 'Molecular formula',
'amount[x]', 'Σ', '0..1', '', 'Quantitative value for this moiety',
'amountQuantity', '', '', 'Quantity', '',
'amountString', '', '', 'string', '',
'property', 'Σ', '0..*', 'BackboneElement', 'General specifications for this substance, including how it is related to other substances',
'category', 'Σ', '0..1', 'CodeableConcept', 'A category for this property, e.g. Physical, Chemical, Enzymatic',
'code', 'Σ', '0..1', 'CodeableConcept', 'Property type e.g. viscosity, pH, isoelectric point',
'parameters', 'Σ', '0..1', 'string', 'Parameters that were used in the measurement of a property (e.g. for viscosity: measured at 20C with a pH of 7.1)',
'definingSubstance[x]', 'Σ', '0..1', '', 'A substance upon which a defining property depends (e.g. for solubility: in water, in alcohol)',
'definingSubstanceReference', '', '', 'Reference(SubstanceSpecification | Substance)', '',
'definingSubstanceCodeableConcept', '', '', 'CodeableConcept', '',
'amount[x]', 'Σ', '0..1', '', 'Quantitative value for this property',
'amountQuantity', '', '', 'Quantity', '',
'amountString', '', '', 'string', '',
'referenceInformation', 'Σ', '0..1', 'Reference(SubstanceReferenceInformation)', 'General information detailing this substance',
'structure', 'Σ', '0..1', 'BackboneElement', 'Structural information',
'stereochemistry', 'Σ', '0..1', 'CodeableConcept', 'Stereochemistry type',
'opticalActivity', 'Σ', '0..1', 'CodeableConcept', 'Optical activity type',
'molecularFormula', 'Σ', '0..1', 'string', 'Molecular formula',
'molecularFormulaByMoiety', 'Σ', '0..1', 'string', 'Specified per moiety according to the Hill system, i.e. first C, then H, then alphabetical, each moiety separated by a dot',
'isotope', 'Σ', '0..*', 'BackboneElement', 'Applicable for single substances that contain a radionuclide or a non-natural isotopic ratio',
'identifier', 'Σ', '0..1', 'Identifier', 'Substance identifier for each non-natural or radioisotope',
'name', 'Σ', '0..1', 'CodeableConcept', 'Substance name for each non-natural or radioisotope',
'substitution', 'Σ', '0..1', 'CodeableConcept', 'The type of isotopic substitution present in a single substance',
'halfLife', 'Σ', '0..1', 'Quantity', 'Half life - for a non-natural nuclide',
'molecularWeight', 'Σ', '0..1', 'BackboneElement', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'method', 'Σ', '0..1', 'CodeableConcept', 'The method by which the molecular weight was determined',
'type', 'Σ', '0..1', 'CodeableConcept', 'Type of molecular weight such as exact, average (also known as. number average), weight average',
'amount', 'Σ', '0..1', 'Quantity', 'Used to capture quantitative values for a variety of elements. If only limits are given, the arithmetic mean would be the average. If only a single definite value for a given element is given, it would be captured in this field',
'molecularWeight', 'Σ', '0..1', 'see molecularWeight', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'representation', 'Σ', '0..*', 'BackboneElement', 'Molecular structural representation',
'type', 'Σ', '0..1', 'CodeableConcept', 'The type of structure (e.g. Full, Partial, Representative)',
'representation', 'Σ', '0..1', 'string', 'The structural representation as text string in a format e.g. InChI, SMILES, MOLFILE, CDX',
'attachment', 'Σ', '0..1', 'Attachment', 'An attached file with the structural representation',
'code', 'Σ', '0..*', 'BackboneElement', 'Codes associated with the substance',
'code', 'Σ', '0..1', 'CodeableConcept', 'The specific code',
'status', 'Σ', '0..1', 'CodeableConcept', 'Status of the code assignment',
'statusDate', 'Σ', '0..1', 'dateTime', 'The date at which the code status is changed as part of the terminology maintenance',
'comment', 'Σ', '0..1', 'string', 'Any comment can be provided in this field, if necessary',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'name', 'Σ', '0..*', 'BackboneElement', 'Names applicable to this substance',
'name', 'Σ', '1..1', 'string', 'The actual name',
'type', 'Σ', '0..1', 'CodeableConcept', 'Name type',
'status', 'Σ', '0..1', 'CodeableConcept', 'The status of the name',
'preferred', 'Σ', '0..1', 'boolean', 'If this is the preferred name for this substance',
'language', 'Σ', '0..*', 'CodeableConcept', 'Language of the name',
'domain', 'Σ', '0..*', 'CodeableConcept', 'The use context of this name for example if there is a different name a drug active ingredient as opposed to a food colour additive',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'The jurisdiction where this name applies',
'synonym', 'Σ', '0..*', 'see name', 'A synonym of this name',
'translation', 'Σ', '0..*', 'see name', 'A translation for this name',
'official', 'Σ', '0..*', 'BackboneElement', 'Details of the official nature of this name',
'authority', 'Σ', '0..1', 'CodeableConcept', 'Which authority uses this official name',
'status', 'Σ', '0..1', 'CodeableConcept', 'The status of the official name',
'date', 'Σ', '0..1', 'dateTime', 'Date of official name change',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'molecularWeight', 'Σ', '0..*', 'see molecularWeight', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'relationship', 'Σ', '0..*', 'BackboneElement', 'A link between this substance and another, with details of the relationship',
'substance[x]', 'Σ', '0..1', '', 'A pointer to another substance, as a resource or just a representational code',
'substanceReference', '', '', 'Reference(SubstanceSpecification)', '',
'substanceCodeableConcept', '', '', 'CodeableConcept', '',
'relationship', 'Σ', '0..1', 'CodeableConcept', 'For example "salt to parent", "active moiety", "starting material"',
'isDefining', 'Σ', '0..1', 'boolean', 'For example where an enzyme strongly bonds with a particular substance, this is a defining relationship for that enzyme, out of several possible substance relationships',
'amount[x]', 'Σ', '0..1', '', 'A numeric factor for the relationship, for instance to express that the salt of a substance has some percentage of the active substance in relation to some other',
'amountQuantity', '', '', 'Quantity', '',
'amountRange', '', '', 'Range', '',
'amountRatio', '', '', 'Ratio', '',
'amountString', '', '', 'string', '',
'amountRatioLowLimit', 'Σ', '0..1', 'Ratio', 'For use when the numeric',
'amountType', 'Σ', '0..1', 'CodeableConcept', 'An operator for the amount, for example "average", "approximately", "less than"',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'nucleicAcid', 'Σ', '0..1', 'Reference(SubstanceNucleicAcid)', 'Data items specific to nucleic acids',
'polymer', 'Σ', '0..1', 'Reference(SubstancePolymer)', 'Data items specific to polymers',
'protein', 'Σ', '0..1', 'Reference(SubstanceProtein)', 'Data items specific to proteins',
'sourceMaterial', 'Σ', '0..1', 'Reference(SubstanceSourceMaterial)', 'Material or taxonomic/anatomical source for the substance',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'SubstanceSpecification', 'ΣTU', '', 'DomainResource', 'The detailed description of a substance, typically at a level beyond what is used for prescribingElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'identifier', 'Σ', '0..1', 'Identifier', 'Identifier by which this substance is known',
'type', 'Σ', '0..1', 'CodeableConcept', 'High level categorization, e.g. polymer or nucleic acid',
'status', 'Σ', '0..1', 'CodeableConcept', 'Status of substance within the catalogue e.g. approved',
'domain', 'Σ', '0..1', 'CodeableConcept', 'If the substance applies to only human or veterinary use',
'description', 'Σ', '0..1', 'string', 'Textual description of the substance',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'comment', 'Σ', '0..1', 'string', 'Textual comment about this record of a substance',
'moiety', 'Σ', '0..*', 'BackboneElement', 'Moiety, for structural modifications',
'role', 'Σ', '0..1', 'CodeableConcept', 'Role that the moiety is playing',
'identifier', 'Σ', '0..1', 'Identifier', 'Identifier by which this moiety substance is known',
'name', 'Σ', '0..1', 'string', 'Textual name for this moiety substance',
'stereochemistry', 'Σ', '0..1', 'CodeableConcept', 'Stereochemistry type',
'opticalActivity', 'Σ', '0..1', 'CodeableConcept', 'Optical activity type',
'molecularFormula', 'Σ', '0..1', 'string', 'Molecular formula',
'amount[x]', 'Σ', '0..1', '', 'Quantitative value for this moiety',
'amountQuantity', '', '', 'Quantity', '',
'amountString', '', '', 'string', '',
'property', 'Σ', '0..*', 'BackboneElement', 'General specifications for this substance, including how it is related to other substances',
'category', 'Σ', '0..1', 'CodeableConcept', 'A category for this property, e.g. Physical, Chemical, Enzymatic',
'code', 'Σ', '0..1', 'CodeableConcept', 'Property type e.g. viscosity, pH, isoelectric point',
'parameters', 'Σ', '0..1', 'string', 'Parameters that were used in the measurement of a property (e.g. for viscosity: measured at 20C with a pH of 7.1)',
'definingSubstance[x]', 'Σ', '0..1', '', 'A substance upon which a defining property depends (e.g. for solubility: in water, in alcohol)',
'definingSubstanceReference', '', '', 'Reference(SubstanceSpecification | Substance)', '',
'definingSubstanceCodeableConcept', '', '', 'CodeableConcept', '',
'amount[x]', 'Σ', '0..1', '', 'Quantitative value for this property',
'amountQuantity', '', '', 'Quantity', '',
'amountString', '', '', 'string', '',
'referenceInformation', 'Σ', '0..1', 'Reference(SubstanceReferenceInformation)', 'General information detailing this substance',
'structure', 'Σ', '0..1', 'BackboneElement', 'Structural information',
'stereochemistry', 'Σ', '0..1', 'CodeableConcept', 'Stereochemistry type',
'opticalActivity', 'Σ', '0..1', 'CodeableConcept', 'Optical activity type',
'molecularFormula', 'Σ', '0..1', 'string', 'Molecular formula',
'molecularFormulaByMoiety', 'Σ', '0..1', 'string', 'Specified per moiety according to the Hill system, i.e. first C, then H, then alphabetical, each moiety separated by a dot',
'isotope', 'Σ', '0..*', 'BackboneElement', 'Applicable for single substances that contain a radionuclide or a non-natural isotopic ratio',
'identifier', 'Σ', '0..1', 'Identifier', 'Substance identifier for each non-natural or radioisotope',
'name', 'Σ', '0..1', 'CodeableConcept', 'Substance name for each non-natural or radioisotope',
'substitution', 'Σ', '0..1', 'CodeableConcept', 'The type of isotopic substitution present in a single substance',
'halfLife', 'Σ', '0..1', 'Quantity', 'Half life - for a non-natural nuclide',
'molecularWeight', 'Σ', '0..1', 'BackboneElement', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'method', 'Σ', '0..1', 'CodeableConcept', 'The method by which the molecular weight was determined',
'type', 'Σ', '0..1', 'CodeableConcept', 'Type of molecular weight such as exact, average (also known as. number average), weight average',
'amount', 'Σ', '0..1', 'Quantity', 'Used to capture quantitative values for a variety of elements. If only limits are given, the arithmetic mean would be the average. If only a single definite value for a given element is given, it would be captured in this field',
'molecularWeight', 'Σ', '0..1', 'see molecularWeight', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'representation', 'Σ', '0..*', 'BackboneElement', 'Molecular structural representation',
'type', 'Σ', '0..1', 'CodeableConcept', 'The type of structure (e.g. Full, Partial, Representative)',
'representation', 'Σ', '0..1', 'string', 'The structural representation as text string in a format e.g. InChI, SMILES, MOLFILE, CDX',
'attachment', 'Σ', '0..1', 'Attachment', 'An attached file with the structural representation',
'code', 'Σ', '0..*', 'BackboneElement', 'Codes associated with the substance',
'code', 'Σ', '0..1', 'CodeableConcept', 'The specific code',
'status', 'Σ', '0..1', 'CodeableConcept', 'Status of the code assignment',
'statusDate', 'Σ', '0..1', 'dateTime', 'The date at which the code status is changed as part of the terminology maintenance',
'comment', 'Σ', '0..1', 'string', 'Any comment can be provided in this field, if necessary',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'name', 'Σ', '0..*', 'BackboneElement', 'Names applicable to this substance',
'name', 'Σ', '1..1', 'string', 'The actual name',
'type', 'Σ', '0..1', 'CodeableConcept', 'Name type',
'status', 'Σ', '0..1', 'CodeableConcept', 'The status of the name',
'preferred', 'Σ', '0..1', 'boolean', 'If this is the preferred name for this substance',
'language', 'Σ', '0..*', 'CodeableConcept', 'Language of the name',
'domain', 'Σ', '0..*', 'CodeableConcept', 'The use context of this name for example if there is a different name a drug active ingredient as opposed to a food colour additive',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'The jurisdiction where this name applies',
'synonym', 'Σ', '0..*', 'see name', 'A synonym of this name',
'translation', 'Σ', '0..*', 'see name', 'A translation for this name',
'official', 'Σ', '0..*', 'BackboneElement', 'Details of the official nature of this name',
'authority', 'Σ', '0..1', 'CodeableConcept', 'Which authority uses this official name',
'status', 'Σ', '0..1', 'CodeableConcept', 'The status of the official name',
'date', 'Σ', '0..1', 'dateTime', 'Date of official name change',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'molecularWeight', 'Σ', '0..*', 'see molecularWeight', 'The molecular weight or weight range (for proteins, polymers or nucleic acids)',
'relationship', 'Σ', '0..*', 'BackboneElement', 'A link between this substance and another, with details of the relationship',
'substance[x]', 'Σ', '0..1', '', 'A pointer to another substance, as a resource or just a representational code',
'substanceReference', '', '', 'Reference(SubstanceSpecification)', '',
'substanceCodeableConcept', '', '', 'CodeableConcept', '',
'relationship', 'Σ', '0..1', 'CodeableConcept', 'For example "salt to parent", "active moiety", "starting material"',
'isDefining', 'Σ', '0..1', 'boolean', 'For example where an enzyme strongly bonds with a particular substance, this is a defining relationship for that enzyme, out of several possible substance relationships',
'amount[x]', 'Σ', '0..1', '', 'A numeric factor for the relationship, for instance to express that the salt of a substance has some percentage of the active substance in relation to some other',
'amountQuantity', '', '', 'Quantity', '',
'amountRange', '', '', 'Range', '',
'amountRatio', '', '', 'Ratio', '',
'amountString', '', '', 'string', '',
'amountRatioLowLimit', 'Σ', '0..1', 'Ratio', 'For use when the numeric',
'amountType', 'Σ', '0..1', 'CodeableConcept', 'An operator for the amount, for example "average", "approximately", "less than"',
'source', 'Σ', '0..*', 'Reference(DocumentReference)', 'Supporting literature',
'nucleicAcid', 'Σ', '0..1', 'Reference(SubstanceNucleicAcid)', 'Data items specific to nucleic acids',
'polymer', 'Σ', '0..1', 'Reference(SubstancePolymer)', 'Data items specific to polymers',
'protein', 'Σ', '0..1', 'Reference(SubstanceProtein)', 'Data items specific to proteins',
'sourceMaterial', 'Σ', '0..1', 'Reference(SubstanceSourceMaterial)', 'Material or taxonomic/anatomical source for the substance',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'code', 'token', 'The specific code', 'SubstanceSpecification.code.code', '',
)


