df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Vocabulary  Work Group', 'Maturity Level: 0', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'TerminologyCapabilities', 'ITU', '', 'DomainResource', 'A statement of system capabilities+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: A Capability Statement SHALL have at least one of description, software, or implementation element.+ Rule: If kind = instance, implementation must be present and software may be present+ Rule: If kind = capability, implementation must be absent, software must be present+ Rule: If kind = requirements, implementation and software must be absentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this terminology capabilities, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the terminology capabilities',
'name', 'ΣI', '0..1', 'string', 'Name for this terminology capabilities (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this terminology capabilities (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '1..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the terminology capabilities',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for terminology capabilities (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this terminology capabilities is defined',
'copyright', 'Σ', '0..1', 'markdown', 'Use and/or publishing restrictions',
'kind', 'ΣI', '1..1', 'code', 'instance | capability | requirementsCapabilityStatementKind (Required)',
'software', 'ΣI', '0..1', 'BackboneElement', 'Software that is covered by this terminology capability statement',
'name', 'Σ', '1..1', 'string', 'A name the software is known by',
'version', 'Σ', '0..1', 'string', 'Version covered by this statement',
'implementation', 'ΣI', '0..1', 'BackboneElement', 'If this describes a specific instance',
'description', 'Σ', '1..1', 'string', 'Describes this specific instance',
'url', 'Σ', '0..1', 'url', 'Base URL for the implementation',
'lockedDate', 'Σ', '0..1', 'boolean', 'Whether lockedDate is supported',
'codeSystem', 'I', '0..*', 'BackboneElement', 'A code system supported by the server+ Rule: If there is more than one version, a version code must be defined',
'uri', '', '0..1', 'canonical(CodeSystem)', 'URI for the Code System',
'version', '', '0..*', 'BackboneElement', 'Version of Code System supported',
'code', 'ΣI', '0..1', 'string', 'Version identifier for this version',
'isDefault', 'Σ', '0..1', 'boolean', 'If this is the default version for this code system',
'compositional', '', '0..1', 'boolean', 'If compositional grammar is supported',
'language', '', '0..*', 'code', 'Language Displays supported',
'filter', '', '0..*', 'BackboneElement', 'Filter Properties supported',
'code', '', '1..1', 'code', 'Code of the property supported',
'op', '', '1..*', 'code', 'Operations supported for the property',
'property', '', '0..*', 'code', 'Properties supported for $lookup',
'subsumption', '', '0..1', 'boolean', 'Whether subsumption is supported',
'expansion', '', '0..1', 'BackboneElement', 'Information about the [ValueSet/$expand](valueset-operation-expand.html) operation',
'hierarchical', '', '0..1', 'boolean', 'Whether the server can return nested value sets',
'paging', '', '0..1', 'boolean', 'Whether the server supports paging on expansion',
'incomplete', '', '0..1', 'boolean', 'Allow request for incomplete expansions?',
'parameter', '', '0..*', 'BackboneElement', 'Supported expansion parameter',
'name', '', '1..1', 'code', 'Expansion Parameter name',
'documentation', '', '0..1', 'string', 'Description of support for parameter',
'textFilter', '', '0..1', 'markdown', 'Documentation about text searching works',
'codeSearch', '', '0..1', 'code', 'explicit | allCodeSearchSupport (Required)',
'validateCode', '', '0..1', 'BackboneElement', 'Information about the [ValueSet/$validate-code](valueset-operation-validate-code.html) operation',
'translations', '', '1..1', 'boolean', 'Whether translations are validated',
'translation', '', '0..1', 'BackboneElement', 'Information about the [ConceptMap/$translate](conceptmap-operation-translate.html) operation',
'needsMap', '', '1..1', 'boolean', 'Whether the client must identify the map',
'closure', '', '0..1', 'BackboneElement', 'Information about the [ConceptMap/$closure](conceptmap-operation-closure.html) operation',
'translation', '', '0..1', 'boolean', 'If cross-system closure is supported',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'TerminologyCapabilities', 'ITU', '', 'DomainResource', 'A statement of system capabilities+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generation+ Rule: A Capability Statement SHALL have at least one of description, software, or implementation element.+ Rule: If kind = instance, implementation must be present and software may be present+ Rule: If kind = capability, implementation must be absent, software must be present+ Rule: If kind = requirements, implementation and software must be absentElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '0..1', 'uri', 'Canonical identifier for this terminology capabilities, represented as a URI (globally unique)',
'version', 'Σ', '0..1', 'string', 'Business version of the terminology capabilities',
'name', 'ΣI', '0..1', 'string', 'Name for this terminology capabilities (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this terminology capabilities (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '1..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the terminology capabilities',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for terminology capabilities (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this terminology capabilities is defined',
'copyright', 'Σ', '0..1', 'markdown', 'Use and/or publishing restrictions',
'kind', 'ΣI', '1..1', 'code', 'instance | capability | requirementsCapabilityStatementKind (Required)',
'software', 'ΣI', '0..1', 'BackboneElement', 'Software that is covered by this terminology capability statement',
'name', 'Σ', '1..1', 'string', 'A name the software is known by',
'version', 'Σ', '0..1', 'string', 'Version covered by this statement',
'implementation', 'ΣI', '0..1', 'BackboneElement', 'If this describes a specific instance',
'description', 'Σ', '1..1', 'string', 'Describes this specific instance',
'url', 'Σ', '0..1', 'url', 'Base URL for the implementation',
'lockedDate', 'Σ', '0..1', 'boolean', 'Whether lockedDate is supported',
'codeSystem', 'I', '0..*', 'BackboneElement', 'A code system supported by the server+ Rule: If there is more than one version, a version code must be defined',
'uri', '', '0..1', 'canonical(CodeSystem)', 'URI for the Code System',
'version', '', '0..*', 'BackboneElement', 'Version of Code System supported',
'code', 'ΣI', '0..1', 'string', 'Version identifier for this version',
'isDefault', 'Σ', '0..1', 'boolean', 'If this is the default version for this code system',
'compositional', '', '0..1', 'boolean', 'If compositional grammar is supported',
'language', '', '0..*', 'code', 'Language Displays supported',
'filter', '', '0..*', 'BackboneElement', 'Filter Properties supported',
'code', '', '1..1', 'code', 'Code of the property supported',
'op', '', '1..*', 'code', 'Operations supported for the property',
'property', '', '0..*', 'code', 'Properties supported for $lookup',
'subsumption', '', '0..1', 'boolean', 'Whether subsumption is supported',
'expansion', '', '0..1', 'BackboneElement', 'Information about the [ValueSet/$expand](valueset-operation-expand.html) operation',
'hierarchical', '', '0..1', 'boolean', 'Whether the server can return nested value sets',
'paging', '', '0..1', 'boolean', 'Whether the server supports paging on expansion',
'incomplete', '', '0..1', 'boolean', 'Allow request for incomplete expansions?',
'parameter', '', '0..*', 'BackboneElement', 'Supported expansion parameter',
'name', '', '1..1', 'code', 'Expansion Parameter name',
'documentation', '', '0..1', 'string', 'Description of support for parameter',
'textFilter', '', '0..1', 'markdown', 'Documentation about text searching works',
'codeSearch', '', '0..1', 'code', 'explicit | allCodeSearchSupport (Required)',
'validateCode', '', '0..1', 'BackboneElement', 'Information about the [ValueSet/$validate-code](valueset-operation-validate-code.html) operation',
'translations', '', '1..1', 'boolean', 'Whether translations are validated',
'translation', '', '0..1', 'BackboneElement', 'Information about the [ConceptMap/$translate](conceptmap-operation-translate.html) operation',
'needsMap', '', '1..1', 'boolean', 'Whether the client must identify the map',
'closure', '', '0..1', 'BackboneElement', 'Information about the [ConceptMap/$closure](conceptmap-operation-closure.html) operation',
'translation', '', '0..1', 'boolean', 'If cross-system closure is supported',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df4 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'TerminologyCapabilities.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'TerminologyCapabilities.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'TerminologyCapabilities.kind', 'How a capability statement is intended to be used.', 'Required', 'CapabilityStatementKind',
'TerminologyCapabilities.codeSearch', 'The degree to which the server supports the code search parameter on ValueSet, if it is supported.', 'Required', 'CodeSearchSupport',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'tcp-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'tcp-1', 'Rule', 'TerminologyCapabilities.codeSystem', 'If there is more than one version, a version code must be defined', 'version.count() > 1 implies version.all(code.exists())',
'tcp-2', 'Rule', '(base)', 'A Capability Statement SHALL have at least one of description, software, or implementation element.', '(description.count() + software.count() + implementation.count()) > 0',
'tcp-3', 'Rule', '(base)', 'If kind = instance, implementation must be present and software may be present', '(kind != 'instance') or implementation.exists()',
'tcp-4', 'Rule', '(base)', 'If kind = capability, implementation must be absent, software must be present', '(kind != 'capability') or (implementation.exists().not() and software.exists())',
'tcp-5', 'Rule', '(base)', 'If kind = requirements, implementation and software must be absent', '(kind!='requirements') or (implementation.exists().not() and software.exists().not())',
)


df6 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the terminology capabilities', '(TerminologyCapabilities.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the terminology capabilities', '(TerminologyCapabilities.useContext.value as Quantity) | (TerminologyCapabilities.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the terminology capabilities', 'TerminologyCapabilities.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the terminology capabilities', 'On TerminologyCapabilities.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the terminology capabilities', 'On TerminologyCapabilities.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The terminology capabilities publication date', 'TerminologyCapabilities.date', '',
'description', 'string', 'The description of the terminology capabilities', 'TerminologyCapabilities.description', '',
'jurisdiction', 'token', 'Intended jurisdiction for the terminology capabilities', 'TerminologyCapabilities.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the terminology capabilities', 'TerminologyCapabilities.name', '',
'publisher', 'string', 'Name of the publisher of the terminology capabilities', 'TerminologyCapabilities.publisher', '',
'status', 'token', 'The current status of the terminology capabilities', 'TerminologyCapabilities.status', '',
'title', 'string', 'The human-friendly name of the terminology capabilities', 'TerminologyCapabilities.title', '',
'url', 'uri', 'The uri that identifies the terminology capabilities', 'TerminologyCapabilities.url', '',
'version', 'token', 'The business version of the terminology capabilities', 'TerminologyCapabilities.version', '',
)


