df1 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'FHIR Infrastructure  Work Group', 'Maturity Level: 2', 'Trial Use', 'Security Category: Anonymous', 'Compartments: Not linked to any defined compartments',
)


df2 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'TestScript', 'ITU', '', 'DomainResource', 'Describes a set of tests+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this test script, represented as a URI (globally unique)',
'identifier', 'Σ', '0..1', 'Identifier', 'Additional identifier for the test script',
'version', 'Σ', '0..1', 'string', 'Business version of the test script',
'name', 'ΣI', '1..1', 'string', 'Name for this test script (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this test script (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the test script',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for test script (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this test script is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'origin', '', '0..*', 'BackboneElement', 'An abstract server representing a client or sender in a message exchange',
'index', '', '1..1', 'integer', 'The index of the abstract origin server starting at 1',
'profile', '', '1..1', 'Coding', 'FHIR-Client | FHIR-SDC-FormFillerTest script profile origin type (Extensible)',
'destination', '', '0..*', 'BackboneElement', 'An abstract server representing a destination or receiver in a message exchange',
'index', '', '1..1', 'integer', 'The index of the abstract destination server starting at 1',
'profile', '', '1..1', 'Coding', 'FHIR-Server | FHIR-SDC-FormManager | FHIR-SDC-FormReceiver | FHIR-SDC-FormProcessorTest script profile destination type (Extensible)',
'metadata', 'I', '0..1', 'BackboneElement', 'Required capability that is assumed to function correctly on the FHIR server being tested+ Rule: TestScript metadata capability SHALL contain required or validated or both.',
'link', '', '0..*', 'BackboneElement', 'Links to the FHIR specification',
'url', '', '1..1', 'uri', 'URL to the specification',
'description', '', '0..1', 'string', 'Short description',
'capability', '', '1..*', 'BackboneElement', 'Capabilities  that are assumed to function correctly on the FHIR server being tested',
'required', '', '1..1', 'boolean', 'Are the capabilities required?',
'validated', '', '1..1', 'boolean', 'Are the capabilities validated?',
'description', '', '0..1', 'string', 'The expected capabilities of the server',
'origin', '', '0..*', 'integer', 'Which origin server these requirements apply to',
'destination', '', '0..1', 'integer', 'Which server these requirements apply to',
'link', '', '0..*', 'uri', 'Links to the FHIR specification',
'capabilities', '', '1..1', 'canonical(CapabilityStatement)', 'Required Capability Statement',
'fixture', '', '0..*', 'BackboneElement', 'Fixture in the test script - by reference (uri)',
'autocreate', '', '1..1', 'boolean', 'Whether or not to implicitly create the fixture during setup',
'autodelete', '', '1..1', 'boolean', 'Whether or not to implicitly delete the fixture during teardown',
'resource', '', '0..1', 'Reference(Any)', 'Reference of the resource',
'profile', '', '0..*', 'Reference(Any)', 'Reference of the validation profile',
'variable', 'I', '0..*', 'BackboneElement', 'Placeholder for evaluated elements+ Rule: Variable can only contain one of expression, headerField or path.',
'name', '', '1..1', 'string', 'Descriptive name for this variable',
'defaultValue', '', '0..1', 'string', 'Default, hard-coded, or user-defined value for this variable',
'description', '', '0..1', 'string', 'Natural language description of the variable',
'expression', '', '0..1', 'string', 'The FHIRPath expression against the fixture body',
'headerField', '', '0..1', 'string', 'HTTP header field name for source',
'hint', '', '0..1', 'string', 'Hint help text for default value to enter',
'path', '', '0..1', 'string', 'XPath or JSONPath against the fixture body',
'sourceId', '', '0..1', 'id', 'Fixture Id of source expression or headerField within this variable',
'setup', '', '0..1', 'BackboneElement', 'A series of required setup operations before tests are executed',
'action', 'I', '1..*', 'BackboneElement', 'A setup operation or assert to perform+ Rule: Setup action SHALL contain either an operation or assert but not both.',
'operation', 'I', '0..1', 'BackboneElement', 'The setup operation to perform+ Rule: Setup operation SHALL contain either sourceId or targetId or params or url.',
'type', '', '0..1', 'Coding', 'The operation code type that will be executedTest script operation code (Extensible)',
'resource', '', '0..1', 'code', 'Resource typeFHIRDefinedType (Required)',
'label', '', '0..1', 'string', 'Tracking/logging operation label',
'description', '', '0..1', 'string', 'Tracking/reporting operation description',
'accept', '', '0..1', 'code', 'Mime type to accept in the payload of the response, with charset etc.MimeType (Required)',
'contentType', '', '0..1', 'code', 'Mime type of the request payload contents, with charset etc.MimeType (Required)',
'destination', '', '0..1', 'integer', 'Server responding to the request',
'encodeRequestUrl', '', '1..1', 'boolean', 'Whether or not to send the request url in encoded format',
'method', '', '0..1', 'code', 'delete | get | options | patch | post | put | headTestScriptRequestMethodCode (Required)',
'origin', '', '0..1', 'integer', 'Server initiating the request',
'params', '', '0..1', 'string', 'Explicitly defined path parameters',
'requestHeader', '', '0..*', 'BackboneElement', 'Each operation can have one or more header elements',
'field', '', '1..1', 'string', 'HTTP header field name',
'value', '', '1..1', 'string', 'HTTP headerfield value',
'requestId', '', '0..1', 'id', 'Fixture Id of mapped request',
'responseId', '', '0..1', 'id', 'Fixture Id of mapped response',
'sourceId', '', '0..1', 'id', 'Fixture Id of body for PUT and POST requests',
'targetId', '', '0..1', 'id', 'Id of fixture used for extracting the [id],  [type], and [vid] for GET requests',
'url', '', '0..1', 'string', 'Request URL',
'assert', 'I', '0..1', 'BackboneElement', 'The assertion to perform+ Rule: Only a single assertion SHALL be present within setup action assert element.+ Rule: Setup action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.+ Rule: Setup action assert response and responseCode SHALL be empty when direction equals request',
'label', '', '0..1', 'string', 'Tracking/logging assertion label',
'description', '', '0..1', 'string', 'Tracking/reporting assertion description',
'direction', '', '0..1', 'code', 'response | requestAssertionDirectionType (Required)',
'compareToSourceId', '', '0..1', 'string', 'Id of the source fixture to be evaluated',
'compareToSourceExpression', '', '0..1', 'string', 'The FHIRPath expression to evaluate against the source fixture',
'compareToSourcePath', '', '0..1', 'string', 'XPath or JSONPath expression to evaluate against the source fixture',
'contentType', '', '0..1', 'code', 'Mime type to compare against the 'Content-Type' headerMimeType (Required)',
'expression', '', '0..1', 'string', 'The FHIRPath expression to be evaluated',
'headerField', '', '0..1', 'string', 'HTTP header field name',
'minimumId', '', '0..1', 'string', 'Fixture Id of minimum content resource',
'navigationLinks', '', '0..1', 'boolean', 'Perform validation on navigation links?',
'operator', '', '0..1', 'code', 'equals | notEquals | in | notIn | greaterThan | lessThan | empty | notEmpty | contains | notContains | evalAssertionOperatorType (Required)',
'path', '', '0..1', 'string', 'XPath or JSONPath expression',
'requestMethod', '', '0..1', 'code', 'delete | get | options | patch | post | put | headTestScriptRequestMethodCode (Required)',
'requestURL', '', '0..1', 'string', 'Request URL comparison value',
'resource', '', '0..1', 'code', 'Resource typeFHIRDefinedType (Required)',
'response', '', '0..1', 'code', 'okay | created | noContent | notModified | bad | forbidden | notFound | methodNotAllowed | conflict | gone | preconditionFailed | unprocessableAssertionResponseTypes (Required)',
'responseCode', '', '0..1', 'string', 'HTTP response code to test',
'sourceId', '', '0..1', 'id', 'Fixture Id of source expression or headerField',
'validateProfileId', '', '0..1', 'id', 'Profile Id of validation profile reference',
'value', '', '0..1', 'string', 'The value to compare to',
'warningOnly', '', '1..1', 'boolean', 'Will this assert produce a warning only on error?',
'test', '', '0..*', 'BackboneElement', 'A test in this script',
'name', '', '0..1', 'string', 'Tracking/logging name of this test',
'description', '', '0..1', 'string', 'Tracking/reporting short description of the test',
'action', 'I', '1..*', 'BackboneElement', 'A test operation or assert to perform+ Rule: Test action SHALL contain either an operation or assert but not both.',
'operation', 'I', '0..1', 'see operation', 'The setup operation to perform+ Rule: Test operation SHALL contain either sourceId or targetId or params or url.',
'assert', 'I', '0..1', 'see assert', 'The setup assertion to perform+ Rule: Only a single assertion SHALL be present within test action assert element.+ Rule: Test action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.+ Rule: Test action assert response and response and responseCode SHALL be empty when direction equals request',
'teardown', '', '0..1', 'BackboneElement', 'A series of required clean up steps',
'action', '', '1..*', 'BackboneElement', 'One or more teardown operations to perform',
'operation', 'I', '1..1', 'see operation', 'The teardown operation to perform+ Rule: Teardown operation SHALL contain either sourceId or targetId or params or url.',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df3 <- 
tibble::tribble(
~`X1`,~`X2`,
'TestScript', '',
'TestScript.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'TestScript.experimental', 'No longer marked as Modifier',
'TestScript.origin.profile', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-profile-origin-types" to "http://terminology.hl7.org/CodeSystem/testscript-profile-origin-types"',
'TestScript.destination.profile', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-profile-destination-types" to "http://terminology.hl7.org/CodeSystem/testscript-profile-destination-types"',
'TestScript.metadata.capability.required', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.metadata.capability.validated', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.metadata.capability.capabilities', 'Type changed from Reference(CapabilityStatement) to canonical(CapabilityStatement)',
'TestScript.fixture.autocreate', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.fixture.autodelete', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.setup.action.operation.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-operation-codes" to "http://terminology.hl7.org/CodeSystem/testscript-operation-codes"',
'TestScript.setup.action.operation.resource', 'Change value set from http://hl7.org/fhir/ValueSet/defined-types to http://hl7.org/fhir/ValueSet/defined-types|4.0.1',
'TestScript.setup.action.operation.accept', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.operation.contentType', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.operation.encodeRequestUrl', 'Min Cardinality changed from 0 to 1
        Default Value "true" removed',
'TestScript.setup.action.operation.method', 'Added Element',
'TestScript.setup.action.assert.direction', 'Change value set from http://hl7.org/fhir/ValueSet/assert-direction-codes to http://hl7.org/fhir/ValueSet/assert-direction-codes|4.0.1',
'TestScript.setup.action.assert.contentType', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.assert.operator', 'Change value set from http://hl7.org/fhir/ValueSet/assert-operator-codes to http://hl7.org/fhir/ValueSet/assert-operator-codes|4.0.1',
'TestScript.setup.action.assert.requestMethod', 'Change value set from http://hl7.org/fhir/ValueSet/http-operations to http://hl7.org/fhir/ValueSet/http-operations|4.0.1',
'TestScript.setup.action.assert.resource', 'Change value set from http://hl7.org/fhir/ValueSet/defined-types to http://hl7.org/fhir/ValueSet/defined-types|4.0.1',
'TestScript.setup.action.assert.response', 'Change value set from http://hl7.org/fhir/ValueSet/assert-response-code-types to http://hl7.org/fhir/ValueSet/assert-response-code-types|4.0.1',
'TestScript.setup.action.assert.warningOnly', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.rule', 'deleted',
'TestScript.ruleset', 'deleted',
'TestScript.setup.action.assert.rule', 'deleted',
'TestScript.setup.action.assert.ruleset', 'deleted',
)


df4 <- 
tibble::tribble(
~`Name`,~`Flags`,~`Card.`,~`Type`,~`Description & Constraints`,
'TestScript', 'ITU', '', 'DomainResource', 'Describes a set of tests+ Warning: Name should be usable as an identifier for the module by machine processing applications such as code generationElements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension',
'url', 'Σ', '1..1', 'uri', 'Canonical identifier for this test script, represented as a URI (globally unique)',
'identifier', 'Σ', '0..1', 'Identifier', 'Additional identifier for the test script',
'version', 'Σ', '0..1', 'string', 'Business version of the test script',
'name', 'ΣI', '1..1', 'string', 'Name for this test script (computer friendly)',
'title', 'Σ', '0..1', 'string', 'Name for this test script (human friendly)',
'status', '?!Σ', '1..1', 'code', 'draft | active | retired | unknownPublicationStatus (Required)',
'experimental', 'Σ', '0..1', 'boolean', 'For testing purposes, not real usage',
'date', 'Σ', '0..1', 'dateTime', 'Date last changed',
'publisher', 'Σ', '0..1', 'string', 'Name of the publisher (organization or individual)',
'contact', 'Σ', '0..*', 'ContactDetail', 'Contact details for the publisher',
'description', '', '0..1', 'markdown', 'Natural language description of the test script',
'useContext', 'Σ', '0..*', 'UsageContext', 'The context that the content is intended to support',
'jurisdiction', 'Σ', '0..*', 'CodeableConcept', 'Intended jurisdiction for test script (if applicable)Jurisdiction (Extensible)',
'purpose', '', '0..1', 'markdown', 'Why this test script is defined',
'copyright', '', '0..1', 'markdown', 'Use and/or publishing restrictions',
'origin', '', '0..*', 'BackboneElement', 'An abstract server representing a client or sender in a message exchange',
'index', '', '1..1', 'integer', 'The index of the abstract origin server starting at 1',
'profile', '', '1..1', 'Coding', 'FHIR-Client | FHIR-SDC-FormFillerTest script profile origin type (Extensible)',
'destination', '', '0..*', 'BackboneElement', 'An abstract server representing a destination or receiver in a message exchange',
'index', '', '1..1', 'integer', 'The index of the abstract destination server starting at 1',
'profile', '', '1..1', 'Coding', 'FHIR-Server | FHIR-SDC-FormManager | FHIR-SDC-FormReceiver | FHIR-SDC-FormProcessorTest script profile destination type (Extensible)',
'metadata', 'I', '0..1', 'BackboneElement', 'Required capability that is assumed to function correctly on the FHIR server being tested+ Rule: TestScript metadata capability SHALL contain required or validated or both.',
'link', '', '0..*', 'BackboneElement', 'Links to the FHIR specification',
'url', '', '1..1', 'uri', 'URL to the specification',
'description', '', '0..1', 'string', 'Short description',
'capability', '', '1..*', 'BackboneElement', 'Capabilities  that are assumed to function correctly on the FHIR server being tested',
'required', '', '1..1', 'boolean', 'Are the capabilities required?',
'validated', '', '1..1', 'boolean', 'Are the capabilities validated?',
'description', '', '0..1', 'string', 'The expected capabilities of the server',
'origin', '', '0..*', 'integer', 'Which origin server these requirements apply to',
'destination', '', '0..1', 'integer', 'Which server these requirements apply to',
'link', '', '0..*', 'uri', 'Links to the FHIR specification',
'capabilities', '', '1..1', 'canonical(CapabilityStatement)', 'Required Capability Statement',
'fixture', '', '0..*', 'BackboneElement', 'Fixture in the test script - by reference (uri)',
'autocreate', '', '1..1', 'boolean', 'Whether or not to implicitly create the fixture during setup',
'autodelete', '', '1..1', 'boolean', 'Whether or not to implicitly delete the fixture during teardown',
'resource', '', '0..1', 'Reference(Any)', 'Reference of the resource',
'profile', '', '0..*', 'Reference(Any)', 'Reference of the validation profile',
'variable', 'I', '0..*', 'BackboneElement', 'Placeholder for evaluated elements+ Rule: Variable can only contain one of expression, headerField or path.',
'name', '', '1..1', 'string', 'Descriptive name for this variable',
'defaultValue', '', '0..1', 'string', 'Default, hard-coded, or user-defined value for this variable',
'description', '', '0..1', 'string', 'Natural language description of the variable',
'expression', '', '0..1', 'string', 'The FHIRPath expression against the fixture body',
'headerField', '', '0..1', 'string', 'HTTP header field name for source',
'hint', '', '0..1', 'string', 'Hint help text for default value to enter',
'path', '', '0..1', 'string', 'XPath or JSONPath against the fixture body',
'sourceId', '', '0..1', 'id', 'Fixture Id of source expression or headerField within this variable',
'setup', '', '0..1', 'BackboneElement', 'A series of required setup operations before tests are executed',
'action', 'I', '1..*', 'BackboneElement', 'A setup operation or assert to perform+ Rule: Setup action SHALL contain either an operation or assert but not both.',
'operation', 'I', '0..1', 'BackboneElement', 'The setup operation to perform+ Rule: Setup operation SHALL contain either sourceId or targetId or params or url.',
'type', '', '0..1', 'Coding', 'The operation code type that will be executedTest script operation code (Extensible)',
'resource', '', '0..1', 'code', 'Resource typeFHIRDefinedType (Required)',
'label', '', '0..1', 'string', 'Tracking/logging operation label',
'description', '', '0..1', 'string', 'Tracking/reporting operation description',
'accept', '', '0..1', 'code', 'Mime type to accept in the payload of the response, with charset etc.MimeType (Required)',
'contentType', '', '0..1', 'code', 'Mime type of the request payload contents, with charset etc.MimeType (Required)',
'destination', '', '0..1', 'integer', 'Server responding to the request',
'encodeRequestUrl', '', '1..1', 'boolean', 'Whether or not to send the request url in encoded format',
'method', '', '0..1', 'code', 'delete | get | options | patch | post | put | headTestScriptRequestMethodCode (Required)',
'origin', '', '0..1', 'integer', 'Server initiating the request',
'params', '', '0..1', 'string', 'Explicitly defined path parameters',
'requestHeader', '', '0..*', 'BackboneElement', 'Each operation can have one or more header elements',
'field', '', '1..1', 'string', 'HTTP header field name',
'value', '', '1..1', 'string', 'HTTP headerfield value',
'requestId', '', '0..1', 'id', 'Fixture Id of mapped request',
'responseId', '', '0..1', 'id', 'Fixture Id of mapped response',
'sourceId', '', '0..1', 'id', 'Fixture Id of body for PUT and POST requests',
'targetId', '', '0..1', 'id', 'Id of fixture used for extracting the [id],  [type], and [vid] for GET requests',
'url', '', '0..1', 'string', 'Request URL',
'assert', 'I', '0..1', 'BackboneElement', 'The assertion to perform+ Rule: Only a single assertion SHALL be present within setup action assert element.+ Rule: Setup action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.+ Rule: Setup action assert response and responseCode SHALL be empty when direction equals request',
'label', '', '0..1', 'string', 'Tracking/logging assertion label',
'description', '', '0..1', 'string', 'Tracking/reporting assertion description',
'direction', '', '0..1', 'code', 'response | requestAssertionDirectionType (Required)',
'compareToSourceId', '', '0..1', 'string', 'Id of the source fixture to be evaluated',
'compareToSourceExpression', '', '0..1', 'string', 'The FHIRPath expression to evaluate against the source fixture',
'compareToSourcePath', '', '0..1', 'string', 'XPath or JSONPath expression to evaluate against the source fixture',
'contentType', '', '0..1', 'code', 'Mime type to compare against the 'Content-Type' headerMimeType (Required)',
'expression', '', '0..1', 'string', 'The FHIRPath expression to be evaluated',
'headerField', '', '0..1', 'string', 'HTTP header field name',
'minimumId', '', '0..1', 'string', 'Fixture Id of minimum content resource',
'navigationLinks', '', '0..1', 'boolean', 'Perform validation on navigation links?',
'operator', '', '0..1', 'code', 'equals | notEquals | in | notIn | greaterThan | lessThan | empty | notEmpty | contains | notContains | evalAssertionOperatorType (Required)',
'path', '', '0..1', 'string', 'XPath or JSONPath expression',
'requestMethod', '', '0..1', 'code', 'delete | get | options | patch | post | put | headTestScriptRequestMethodCode (Required)',
'requestURL', '', '0..1', 'string', 'Request URL comparison value',
'resource', '', '0..1', 'code', 'Resource typeFHIRDefinedType (Required)',
'response', '', '0..1', 'code', 'okay | created | noContent | notModified | bad | forbidden | notFound | methodNotAllowed | conflict | gone | preconditionFailed | unprocessableAssertionResponseTypes (Required)',
'responseCode', '', '0..1', 'string', 'HTTP response code to test',
'sourceId', '', '0..1', 'id', 'Fixture Id of source expression or headerField',
'validateProfileId', '', '0..1', 'id', 'Profile Id of validation profile reference',
'value', '', '0..1', 'string', 'The value to compare to',
'warningOnly', '', '1..1', 'boolean', 'Will this assert produce a warning only on error?',
'test', '', '0..*', 'BackboneElement', 'A test in this script',
'name', '', '0..1', 'string', 'Tracking/logging name of this test',
'description', '', '0..1', 'string', 'Tracking/reporting short description of the test',
'action', 'I', '1..*', 'BackboneElement', 'A test operation or assert to perform+ Rule: Test action SHALL contain either an operation or assert but not both.',
'operation', 'I', '0..1', 'see operation', 'The setup operation to perform+ Rule: Test operation SHALL contain either sourceId or targetId or params or url.',
'assert', 'I', '0..1', 'see assert', 'The setup assertion to perform+ Rule: Only a single assertion SHALL be present within test action assert element.+ Rule: Test action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.+ Rule: Test action assert response and response and responseCode SHALL be empty when direction equals request',
'teardown', '', '0..1', 'BackboneElement', 'A series of required clean up steps',
'action', '', '1..*', 'BackboneElement', 'One or more teardown operations to perform',
'operation', 'I', '1..1', 'see operation', 'The teardown operation to perform+ Rule: Teardown operation SHALL contain either sourceId or targetId or params or url.',
'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format', 'Documentation for this format',
)


df5 <- 
tibble::tribble(
~`X1`,~`X2`,
'TestScript', '',
'TestScript.status', 'Change value set from http://hl7.org/fhir/ValueSet/publication-status to http://hl7.org/fhir/ValueSet/publication-status|4.0.1',
'TestScript.experimental', 'No longer marked as Modifier',
'TestScript.origin.profile', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-profile-origin-types" to "http://terminology.hl7.org/CodeSystem/testscript-profile-origin-types"',
'TestScript.destination.profile', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-profile-destination-types" to "http://terminology.hl7.org/CodeSystem/testscript-profile-destination-types"',
'TestScript.metadata.capability.required', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.metadata.capability.validated', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.metadata.capability.capabilities', 'Type changed from Reference(CapabilityStatement) to canonical(CapabilityStatement)',
'TestScript.fixture.autocreate', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.fixture.autodelete', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.setup.action.operation.type', 'Change code system for extensibly bound codes from "http://hl7.org/fhir/testscript-operation-codes" to "http://terminology.hl7.org/CodeSystem/testscript-operation-codes"',
'TestScript.setup.action.operation.resource', 'Change value set from http://hl7.org/fhir/ValueSet/defined-types to http://hl7.org/fhir/ValueSet/defined-types|4.0.1',
'TestScript.setup.action.operation.accept', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.operation.contentType', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.operation.encodeRequestUrl', 'Min Cardinality changed from 0 to 1
        Default Value "true" removed',
'TestScript.setup.action.operation.method', 'Added Element',
'TestScript.setup.action.assert.direction', 'Change value set from http://hl7.org/fhir/ValueSet/assert-direction-codes to http://hl7.org/fhir/ValueSet/assert-direction-codes|4.0.1',
'TestScript.setup.action.assert.contentType', 'Change value set from http://hl7.org/fhir/ValueSet/content-type to http://hl7.org/fhir/ValueSet/mimetypes|4.0.1',
'TestScript.setup.action.assert.operator', 'Change value set from http://hl7.org/fhir/ValueSet/assert-operator-codes to http://hl7.org/fhir/ValueSet/assert-operator-codes|4.0.1',
'TestScript.setup.action.assert.requestMethod', 'Change value set from http://hl7.org/fhir/ValueSet/http-operations to http://hl7.org/fhir/ValueSet/http-operations|4.0.1',
'TestScript.setup.action.assert.resource', 'Change value set from http://hl7.org/fhir/ValueSet/defined-types to http://hl7.org/fhir/ValueSet/defined-types|4.0.1',
'TestScript.setup.action.assert.response', 'Change value set from http://hl7.org/fhir/ValueSet/assert-response-code-types to http://hl7.org/fhir/ValueSet/assert-response-code-types|4.0.1',
'TestScript.setup.action.assert.warningOnly', 'Min Cardinality changed from 0 to 1
        Default Value "false" removed',
'TestScript.rule', 'deleted',
'TestScript.ruleset', 'deleted',
'TestScript.setup.action.assert.rule', 'deleted',
'TestScript.setup.action.assert.ruleset', 'deleted',
)


df6 <- 
tibble::tribble(
~`Path`,~`Definition`,~`Type`,~`Reference`,
'TestScript.status', 'The lifecycle status of an artifact.', 'Required', 'PublicationStatus',
'TestScript.jurisdiction', 'Countries and regions within which this artifact is targeted for use.', 'Extensible', 'Jurisdiction ValueSet',
'TestScript.origin.profile', 'The type of origin profile the test system supports.', 'Extensible', 'TestScriptProfileOriginType',
'TestScript.destination.profile', 'The type of destination profile the test system supports.', 'Extensible', 'TestScriptProfileDestinationType',
'TestScript.setup.action.operation.type', 'The allowable operation code types.', 'Extensible', 'TestScriptOperationCode',
'TestScript.setup.action.operation.resourceTestScript.setup.action.assert.resource', 'A list of all the concrete types defined in this version of the FHIR specification - Data Types and Resource Types.', 'Required', 'Defined Types',
'TestScript.setup.action.operation.acceptTestScript.setup.action.operation.contentTypeTestScript.setup.action.assert.contentType', 'The mime type of an attachment. Any valid mime type is allowed.', 'Required', 'Mime Types',
'TestScript.setup.action.operation.methodTestScript.setup.action.assert.requestMethod', 'The allowable request method or HTTP operation codes.', 'Required', 'TestScriptRequestMethodCode',
'TestScript.setup.action.assert.direction', 'The type of direction to use for assertion.', 'Required', 'AssertionDirectionType',
'TestScript.setup.action.assert.operator', 'The type of operator to use for assertion.', 'Required', 'AssertionOperatorType',
'TestScript.setup.action.assert.response', 'The type of response code to use for assertion.', 'Required', 'AssertionResponseTypes',
)


df7 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'id', 'Level', 'Location', 'Description', 'Expression',
'tst-0', 'Warning', '(base)', 'Name should be usable as an identifier for the module by machine processing applications such as code generation', 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')',
'tst-1', 'Rule', 'TestScript.setup.action', 'Setup action SHALL contain either an operation or assert but not both.', 'operation.exists() xor assert.exists()',
'tst-2', 'Rule', 'TestScript.test.action', 'Test action SHALL contain either an operation or assert but not both.', 'operation.exists() xor assert.exists()',
'tst-3', 'Rule', 'TestScript.variable', 'Variable can only contain one of expression, headerField or path.', 'expression.empty() or headerField.empty() or path.empty()',
'tst-4', 'Rule', 'TestScript.metadata', 'TestScript metadata capability SHALL contain required or validated or both.', 'capability.required.exists() or capability.validated.exists()',
'tst-5', 'Rule', 'TestScript.setup.action.assert', 'Only a single assertion SHALL be present within setup action assert element.', 'extension.exists() or (contentType.count() + expression.count() + headerField.count() + minimumId.count() + navigationLinks.count() + path.count() + requestMethod.count() + resource.count() + responseCode.count() + response.count()  + validateProfileId.count() <=1)',
'tst-6', 'Rule', 'TestScript.test.action.assert', 'Only a single assertion SHALL be present within test action assert element.', 'extension.exists() or (contentType.count() + expression.count() + headerField.count() + minimumId.count() + navigationLinks.count() + path.count() + requestMethod.count() + resource.count() + responseCode.count() + response.count() + validateProfileId.count() <=1)',
'tst-7', 'Rule', 'TestScript.setup.action.operation', 'Setup operation SHALL contain either sourceId or targetId or params or url.', 'sourceId.exists() or (targetId.count() + url.count() + params.count() = 1) or (type.code in ('capabilities' |'search' | 'transaction' | 'history'))',
'tst-8', 'Rule', 'TestScript.test.action.operation', 'Test operation SHALL contain either sourceId or targetId or params or url.', 'sourceId.exists() or (targetId.count() + url.count() + params.count() = 1) or (type.code in ('capabilities' | 'search' | 'transaction' | 'history'))',
'tst-9', 'Rule', 'TestScript.teardown.action.operation', 'Teardown operation SHALL contain either sourceId or targetId or params or url.', 'sourceId.exists() or (targetId.count() + url.count() + params.count() = 1) or (type.code in ('capabilities' | 'search' | 'transaction' | 'history'))',
'tst-10', 'Rule', 'TestScript.setup.action.assert', 'Setup action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.', 'compareToSourceId.empty() xor (compareToSourceExpression.exists() or compareToSourcePath.exists())',
'tst-11', 'Rule', 'TestScript.test.action.assert', 'Test action assert SHALL contain either compareToSourceId and compareToSourceExpression, compareToSourceId and compareToSourcePath or neither.', 'compareToSourceId.empty() xor (compareToSourceExpression.exists() or compareToSourcePath.exists())',
'tst-12', 'Rule', 'TestScript.setup.action.assert', 'Setup action assert response and responseCode SHALL be empty when direction equals request', '(response.empty() and responseCode.empty() and direction = 'request') or direction.empty() or direction = 'response'',
'tst-13', 'Rule', 'TestScript.test.action.assert', 'Test action assert response and response and responseCode SHALL be empty when direction equals request', '(response.empty() and responseCode.empty() and direction = 'request') or direction.empty() or direction = 'response'',
)


df8 <- 
tibble::tribble(
~`X1`,~`X2`,~`X3`,~`X4`,~`X5`,
'Name', 'Type', 'Description', 'Expression', 'In Common',
'context', 'token', 'A use context assigned to the test script', '(TestScript.useContext.value as CodeableConcept)', '',
'context-quantity', 'quantity', 'A quantity- or range-valued use context assigned to the test script', '(TestScript.useContext.value as Quantity) | (TestScript.useContext.value as Range)', '',
'context-type', 'token', 'A type of use context assigned to the test script', 'TestScript.useContext.code', '',
'context-type-quantity', 'composite', 'A use context type and quantity- or range-based value assigned to the test script', 'On TestScript.useContext:  context-type: code  context-quantity: value.as(Quantity) | value.as(Range)', '',
'context-type-value', 'composite', 'A use context type and value assigned to the test script', 'On TestScript.useContext:  context-type: code  context: value.as(CodeableConcept)', '',
'date', 'date', 'The test script publication date', 'TestScript.date', '',
'description', 'string', 'The description of the test script', 'TestScript.description', '',
'identifier', 'token', 'External identifier for the test script', 'TestScript.identifier', '',
'jurisdiction', 'token', 'Intended jurisdiction for the test script', 'TestScript.jurisdiction', '',
'name', 'string', 'Computationally friendly name of the test script', 'TestScript.name', '',
'publisher', 'string', 'Name of the publisher of the test script', 'TestScript.publisher', '',
'status', 'token', 'The current status of the test script', 'TestScript.status', '',
'testscript-capability', 'string', 'TestScript required and validated capability', 'TestScript.metadata.capability.description', '',
'title', 'string', 'The human-friendly name of the test script', 'TestScript.title', '',
'url', 'uri', 'The uri that identifies the test script', 'TestScript.url', '',
'version', 'token', 'The business version of the test script', 'TestScript.version', '',
)


